#!/usr/bin/env python

# Demonstrate vtkAppendLocationAttributes by adding point locations and
# cell center arrays to an unstructured grid generated by vtkCellTypeSource,
# then visualizing the cell centers as colored glyphs.

# Factory overrides
import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingFreeType  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401

from vtkmodules.vtkFiltersGeneral import vtkAppendLocationAttributes
from vtkmodules.vtkFiltersGeometry import vtkDataSetSurfaceFilter
from vtkmodules.vtkFiltersSources import (
    vtkCellTypeSource,
    vtkSphereSource,
)
from vtkmodules.vtkFiltersCore import (
    vtkCellCenters,
    vtkGlyph3D,
)
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkPolyDataMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
)

# Create a cell type source as input
cell_source = vtkCellTypeSource()
cell_source.SetBlocksDimensions(5, 5, 5)
cell_source.Update()

# Append location attributes
location_attrs = vtkAppendLocationAttributes()
location_attrs.SetInputConnection(cell_source.GetOutputPort())
location_attrs.Update()

# Extract surface for the grid
surface = vtkDataSetSurfaceFilter()
surface.SetInputConnection(location_attrs.GetOutputPort())

grid_mapper = vtkPolyDataMapper()
grid_mapper.SetInputConnection(surface.GetOutputPort())
grid_mapper.ScalarVisibilityOff()

grid_actor = vtkActor()
grid_actor.SetMapper(grid_mapper)
grid_actor.GetProperty().SetOpacity(0.3)
grid_actor.GetProperty().SetColor(0.8, 0.8, 0.8)

# Use cell centers to place small sphere glyphs
centers = vtkCellCenters()
centers.SetInputConnection(location_attrs.GetOutputPort())

glyph_source = vtkSphereSource()
glyph_source.SetRadius(0.1)

glyph = vtkGlyph3D()
glyph.SetInputConnection(centers.GetOutputPort())
glyph.SetSourceConnection(glyph_source.GetOutputPort())

glyph_mapper = vtkPolyDataMapper()
glyph_mapper.SetInputConnection(glyph.GetOutputPort())
glyph_mapper.ScalarVisibilityOff()

glyph_actor = vtkActor()
glyph_actor.SetMapper(glyph_mapper)
glyph_actor.GetProperty().SetColor(1.0, 0.2, 0.2)

# Renderer
renderer = vtkRenderer()
renderer.AddActor(grid_actor)
renderer.AddActor(glyph_actor)
renderer.SetBackground(0.1, 0.2, 0.4)

# Window
render_window = vtkRenderWindow()
render_window.AddRenderer(renderer)
render_window.SetSize(400, 400)
render_window.SetWindowName("append location attributes")

# Interactor
interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)

# Scene
renderer.ResetCamera()

interactor.Initialize()
interactor.Start()
