#!/usr/bin/env python

# Contour every standard cell type (voxel, hexahedron, tetra, wedge,
# pyramid, pixel, quad, triangle, polygon, triangle strip, line,
# polyline, vertex, polyvertex, pentagonal prism, hexagonal prism)
# with wireframe and contour actors on a backdrop.

# Factory overrides
import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401

from vtkmodules.vtkCommonCore import (
    vtkFloatArray,
    vtkPoints,
)
from vtkmodules.vtkCommonDataModel import (
    vtkHexagonalPrism,
    vtkHexahedron,
    vtkLine,
    vtkPentagonalPrism,
    vtkPixel,
    vtkPolyLine,
    vtkPolyVertex,
    vtkPolygon,
    vtkPyramid,
    vtkQuad,
    vtkTetra,
    vtkTriangle,
    vtkTriangleStrip,
    vtkUnstructuredGrid,
    vtkVertex,
    vtkVoxel,
    vtkWedge,
)
from vtkmodules.vtkFiltersCore import vtkContourFilter
from vtkmodules.vtkFiltersSources import vtkCubeSource
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkDataSetMapper,
    vtkPolyDataMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
)

# Remove all cullers so single vertex actors will render
renderer = vtkRenderer()
renderer.GetCullers().RemoveAllItems()

# --- Voxel ---
voxel_points = vtkPoints()
voxel_points.SetNumberOfPoints(8)
voxel_points.InsertPoint(0, 0, 0, 0)
voxel_points.InsertPoint(1, 1, 0, 0)
voxel_points.InsertPoint(2, 0, 1, 0)
voxel_points.InsertPoint(3, 1, 1, 0)
voxel_points.InsertPoint(4, 0, 0, 1)
voxel_points.InsertPoint(5, 1, 0, 1)
voxel_points.InsertPoint(6, 0, 1, 1)
voxel_points.InsertPoint(7, 1, 1, 1)
voxel_scalars = vtkFloatArray()
voxel_scalars.SetNumberOfTuples(8)
for i, v in enumerate([0, 1, 0, 0, 0, 0, 0, 0]):
    voxel_scalars.InsertValue(i, v)
a_voxel = vtkVoxel()
for i in range(8):
    a_voxel.GetPointIds().SetId(i, i)
a_voxel_grid = vtkUnstructuredGrid()
a_voxel_grid.Allocate(1, 1)
a_voxel_grid.InsertNextCell(a_voxel.GetCellType(), a_voxel.GetPointIds())
a_voxel_grid.SetPoints(voxel_points)
a_voxel_grid.GetPointData().SetScalars(voxel_scalars)
voxel_contours = vtkContourFilter()
voxel_contours.SetInputData(a_voxel_grid)
voxel_contours.SetValue(0, 0.5)
a_voxel_contour_mapper = vtkDataSetMapper()
a_voxel_contour_mapper.SetInputConnection(voxel_contours.GetOutputPort())
a_voxel_contour_mapper.ScalarVisibilityOff()
a_voxel_mapper = vtkDataSetMapper()
a_voxel_mapper.SetInputData(a_voxel_grid)
a_voxel_mapper.ScalarVisibilityOff()
a_voxel_actor = vtkActor()
a_voxel_actor.SetMapper(a_voxel_mapper)
a_voxel_actor.GetProperty().SetRepresentationToWireframe()
a_voxel_contour_actor = vtkActor()
a_voxel_contour_actor.SetMapper(a_voxel_contour_mapper)
a_voxel_contour_actor.GetProperty().BackfaceCullingOn()

# --- Hexahedron ---
hex_points = vtkPoints()
hex_points.SetNumberOfPoints(8)
hex_points.InsertPoint(0, 0, 0, 0)
hex_points.InsertPoint(1, 1, 0, 0)
hex_points.InsertPoint(2, 1, 1, 0)
hex_points.InsertPoint(3, 0, 1, 0)
hex_points.InsertPoint(4, 0, 0, 1)
hex_points.InsertPoint(5, 1, 0, 1)
hex_points.InsertPoint(6, 1, 1, 1)
hex_points.InsertPoint(7, 0, 1, 1)
hex_scalars = vtkFloatArray()
hex_scalars.SetNumberOfTuples(8)
for i, v in enumerate([0, 1, 0, 0, 0, 0, 0, 0]):
    hex_scalars.InsertValue(i, v)
a_hex = vtkHexahedron()
for i in range(8):
    a_hex.GetPointIds().SetId(i, i)
a_hex_grid = vtkUnstructuredGrid()
a_hex_grid.Allocate(1, 1)
a_hex_grid.InsertNextCell(a_hex.GetCellType(), a_hex.GetPointIds())
a_hex_grid.SetPoints(hex_points)
a_hex_grid.GetPointData().SetScalars(hex_scalars)
hex_contours = vtkContourFilter()
hex_contours.SetInputData(a_hex_grid)
hex_contours.SetValue(0, 0.5)
a_hex_contour_mapper = vtkDataSetMapper()
a_hex_contour_mapper.SetInputConnection(hex_contours.GetOutputPort())
a_hex_contour_mapper.ScalarVisibilityOff()
a_hex_mapper = vtkDataSetMapper()
a_hex_mapper.SetInputData(a_hex_grid)
a_hex_mapper.ScalarVisibilityOff()
a_hex_actor = vtkActor()
a_hex_actor.SetMapper(a_hex_mapper)
a_hex_actor.GetProperty().BackfaceCullingOn()
a_hex_actor.GetProperty().SetRepresentationToWireframe()
a_hex_contour_actor = vtkActor()
a_hex_contour_actor.SetMapper(a_hex_contour_mapper)
a_hex_contour_actor.GetProperty().BackfaceCullingOn()

# --- Tetra ---
tetra_points = vtkPoints()
tetra_points.SetNumberOfPoints(4)
tetra_points.InsertPoint(0, 0, 0, 0)
tetra_points.InsertPoint(1, 1, 0, 0)
tetra_points.InsertPoint(2, 0.5, 1, 0)
tetra_points.InsertPoint(3, 0.5, 0.5, 1)
tetra_scalars = vtkFloatArray()
tetra_scalars.SetNumberOfTuples(4)
for i, v in enumerate([1, 0, 0, 0]):
    tetra_scalars.InsertValue(i, v)
a_tetra = vtkTetra()
for i in range(4):
    a_tetra.GetPointIds().SetId(i, i)
a_tetra_grid = vtkUnstructuredGrid()
a_tetra_grid.Allocate(1, 1)
a_tetra_grid.InsertNextCell(a_tetra.GetCellType(), a_tetra.GetPointIds())
a_tetra_grid.SetPoints(tetra_points)
a_tetra_grid.GetPointData().SetScalars(tetra_scalars)
tetra_contours = vtkContourFilter()
tetra_contours.SetInputData(a_tetra_grid)
tetra_contours.SetValue(0, 0.5)
a_tetra_contour_mapper = vtkDataSetMapper()
a_tetra_contour_mapper.SetInputConnection(tetra_contours.GetOutputPort())
a_tetra_contour_mapper.ScalarVisibilityOff()
a_tetra_mapper = vtkDataSetMapper()
a_tetra_mapper.SetInputData(a_tetra_grid)
a_tetra_mapper.ScalarVisibilityOff()
a_tetra_contour_actor = vtkActor()
a_tetra_contour_actor.SetMapper(a_tetra_contour_mapper)
a_tetra_actor = vtkActor()
a_tetra_actor.SetMapper(a_tetra_mapper)
a_tetra_actor.GetProperty().SetRepresentationToWireframe()

# --- Wedge ---
wedge_points = vtkPoints()
wedge_points.SetNumberOfPoints(6)
wedge_points.InsertPoint(0, 0, 1, 0)
wedge_points.InsertPoint(1, 0, 0, 0)
wedge_points.InsertPoint(2, 0, 0.5, 0.5)
wedge_points.InsertPoint(3, 1, 1, 0)
wedge_points.InsertPoint(4, 1, 0, 0)
wedge_points.InsertPoint(5, 1, 0.5, 0.5)
wedge_scalars = vtkFloatArray()
wedge_scalars.SetNumberOfTuples(6)
for i, v in enumerate([1, 1, 0, 1, 1, 0]):
    wedge_scalars.InsertValue(i, v)
a_wedge = vtkWedge()
for i in range(6):
    a_wedge.GetPointIds().SetId(i, i)
a_wedge_grid = vtkUnstructuredGrid()
a_wedge_grid.Allocate(1, 1)
a_wedge_grid.InsertNextCell(a_wedge.GetCellType(), a_wedge.GetPointIds())
a_wedge_grid.SetPoints(wedge_points)
a_wedge_grid.GetPointData().SetScalars(wedge_scalars)
wedge_contours = vtkContourFilter()
wedge_contours.SetInputData(a_wedge_grid)
wedge_contours.SetValue(0, 0.5)
a_wedge_contour_mapper = vtkDataSetMapper()
a_wedge_contour_mapper.SetInputConnection(wedge_contours.GetOutputPort())
a_wedge_contour_mapper.ScalarVisibilityOff()
a_wedge_mapper = vtkDataSetMapper()
a_wedge_mapper.SetInputData(a_wedge_grid)
a_wedge_mapper.ScalarVisibilityOff()
a_wedge_contour_actor = vtkActor()
a_wedge_contour_actor.SetMapper(a_wedge_contour_mapper)
a_wedge_actor = vtkActor()
a_wedge_actor.SetMapper(a_wedge_mapper)
a_wedge_actor.GetProperty().SetRepresentationToWireframe()

# --- Pyramid ---
pyramid_points = vtkPoints()
pyramid_points.SetNumberOfPoints(5)
pyramid_points.InsertPoint(0, 0, 0, 0)
pyramid_points.InsertPoint(1, 1, 0, 0)
pyramid_points.InsertPoint(2, 1, 1, 0)
pyramid_points.InsertPoint(3, 0, 1, 0)
pyramid_points.InsertPoint(4, 0.5, 0.5, 1)
pyramid_scalars = vtkFloatArray()
pyramid_scalars.SetNumberOfTuples(5)
for i, v in enumerate([1, 1, 1, 1, 0]):
    pyramid_scalars.InsertValue(i, v)
a_pyramid = vtkPyramid()
for i in range(5):
    a_pyramid.GetPointIds().SetId(i, i)
a_pyramid_grid = vtkUnstructuredGrid()
a_pyramid_grid.Allocate(1, 1)
a_pyramid_grid.InsertNextCell(a_pyramid.GetCellType(), a_pyramid.GetPointIds())
a_pyramid_grid.SetPoints(pyramid_points)
a_pyramid_grid.GetPointData().SetScalars(pyramid_scalars)
pyramid_contours = vtkContourFilter()
pyramid_contours.SetInputData(a_pyramid_grid)
pyramid_contours.SetValue(0, 0.5)
a_pyramid_contour_mapper = vtkDataSetMapper()
a_pyramid_contour_mapper.SetInputConnection(pyramid_contours.GetOutputPort())
a_pyramid_contour_mapper.ScalarVisibilityOff()
a_pyramid_mapper = vtkDataSetMapper()
a_pyramid_mapper.SetInputData(a_pyramid_grid)
a_pyramid_mapper.ScalarVisibilityOff()
a_pyramid_contour_actor = vtkActor()
a_pyramid_contour_actor.SetMapper(a_pyramid_contour_mapper)
a_pyramid_actor = vtkActor()
a_pyramid_actor.SetMapper(a_pyramid_mapper)
a_pyramid_actor.GetProperty().SetRepresentationToWireframe()

# --- Pixel ---
pixel_points = vtkPoints()
pixel_points.SetNumberOfPoints(4)
pixel_points.InsertPoint(0, 0, 0, 0)
pixel_points.InsertPoint(1, 1, 0, 0)
pixel_points.InsertPoint(2, 0, 1, 0)
pixel_points.InsertPoint(3, 1, 1, 0)
pixel_scalars = vtkFloatArray()
pixel_scalars.SetNumberOfTuples(4)
for i, v in enumerate([1, 0, 0, 0]):
    pixel_scalars.InsertValue(i, v)
a_pixel = vtkPixel()
for i in range(4):
    a_pixel.GetPointIds().SetId(i, i)
a_pixel_grid = vtkUnstructuredGrid()
a_pixel_grid.Allocate(1, 1)
a_pixel_grid.InsertNextCell(a_pixel.GetCellType(), a_pixel.GetPointIds())
a_pixel_grid.SetPoints(pixel_points)
a_pixel_grid.GetPointData().SetScalars(pixel_scalars)
pixel_contours = vtkContourFilter()
pixel_contours.SetInputData(a_pixel_grid)
pixel_contours.SetValue(0, 0.5)
a_pixel_contour_mapper = vtkDataSetMapper()
a_pixel_contour_mapper.SetInputConnection(pixel_contours.GetOutputPort())
a_pixel_contour_mapper.ScalarVisibilityOff()
a_pixel_mapper = vtkDataSetMapper()
a_pixel_mapper.SetInputData(a_pixel_grid)
a_pixel_mapper.ScalarVisibilityOff()
a_pixel_contour_actor = vtkActor()
a_pixel_contour_actor.SetMapper(a_pixel_contour_mapper)
a_pixel_actor = vtkActor()
a_pixel_actor.SetMapper(a_pixel_mapper)
a_pixel_actor.GetProperty().BackfaceCullingOn()
a_pixel_actor.GetProperty().SetRepresentationToWireframe()

# --- Quad ---
quad_points = vtkPoints()
quad_points.SetNumberOfPoints(4)
quad_points.InsertPoint(0, 0, 0, 0)
quad_points.InsertPoint(1, 1, 0, 0)
quad_points.InsertPoint(2, 1, 1, 0)
quad_points.InsertPoint(3, 0, 1, 0)
quad_scalars = vtkFloatArray()
quad_scalars.SetNumberOfTuples(4)
for i, v in enumerate([1, 0, 0, 0]):
    quad_scalars.InsertValue(i, v)
a_quad = vtkQuad()
for i in range(4):
    a_quad.GetPointIds().SetId(i, i)
a_quad_grid = vtkUnstructuredGrid()
a_quad_grid.Allocate(1, 1)
a_quad_grid.InsertNextCell(a_quad.GetCellType(), a_quad.GetPointIds())
a_quad_grid.SetPoints(quad_points)
a_quad_grid.GetPointData().SetScalars(quad_scalars)
quad_contours = vtkContourFilter()
quad_contours.SetInputData(a_quad_grid)
quad_contours.SetValue(0, 0.5)
a_quad_contour_mapper = vtkDataSetMapper()
a_quad_contour_mapper.SetInputConnection(quad_contours.GetOutputPort())
a_quad_contour_mapper.ScalarVisibilityOff()
a_quad_mapper = vtkDataSetMapper()
a_quad_mapper.SetInputData(a_quad_grid)
a_quad_mapper.ScalarVisibilityOff()
a_quad_contour_actor = vtkActor()
a_quad_contour_actor.SetMapper(a_quad_contour_mapper)
a_quad_actor = vtkActor()
a_quad_actor.SetMapper(a_quad_mapper)
a_quad_actor.GetProperty().BackfaceCullingOn()
a_quad_actor.GetProperty().SetRepresentationToWireframe()

# --- Triangle ---
triangle_points = vtkPoints()
triangle_points.SetNumberOfPoints(3)
triangle_points.InsertPoint(0, 0, 0, 0)
triangle_points.InsertPoint(1, 1, 0, 0)
triangle_points.InsertPoint(2, 0.5, 0.5, 0)
triangle_scalars = vtkFloatArray()
triangle_scalars.SetNumberOfTuples(3)
for i, v in enumerate([1, 0, 0]):
    triangle_scalars.InsertValue(i, v)
a_triangle = vtkTriangle()
for i in range(3):
    a_triangle.GetPointIds().SetId(i, i)
a_triangle_grid = vtkUnstructuredGrid()
a_triangle_grid.Allocate(1, 1)
a_triangle_grid.InsertNextCell(a_triangle.GetCellType(), a_triangle.GetPointIds())
a_triangle_grid.SetPoints(triangle_points)
a_triangle_grid.GetPointData().SetScalars(triangle_scalars)
triangle_contours = vtkContourFilter()
triangle_contours.SetInputData(a_triangle_grid)
triangle_contours.SetValue(0, 0.5)
a_triangle_contour_mapper = vtkDataSetMapper()
a_triangle_contour_mapper.SetInputConnection(triangle_contours.GetOutputPort())
a_triangle_contour_mapper.ScalarVisibilityOff()
a_triangle_contour_actor = vtkActor()
a_triangle_contour_actor.SetMapper(a_triangle_contour_mapper)
a_triangle_mapper = vtkDataSetMapper()
a_triangle_mapper.SetInputData(a_triangle_grid)
a_triangle_mapper.ScalarVisibilityOff()
a_triangle_actor = vtkActor()
a_triangle_actor.SetMapper(a_triangle_mapper)
a_triangle_actor.GetProperty().BackfaceCullingOn()
a_triangle_actor.GetProperty().SetRepresentationToWireframe()

# --- Polygon ---
polygon_points = vtkPoints()
polygon_points.SetNumberOfPoints(4)
polygon_points.InsertPoint(0, 0, 0, 0)
polygon_points.InsertPoint(1, 1, 0, 0)
polygon_points.InsertPoint(2, 1, 1, 0)
polygon_points.InsertPoint(3, 0, 1, 0)
polygon_scalars = vtkFloatArray()
polygon_scalars.SetNumberOfTuples(4)
for i, v in enumerate([1, 0, 0, 0]):
    polygon_scalars.InsertValue(i, v)
a_polygon = vtkPolygon()
a_polygon.GetPointIds().SetNumberOfIds(4)
for i in range(4):
    a_polygon.GetPointIds().SetId(i, i)
a_polygon_grid = vtkUnstructuredGrid()
a_polygon_grid.Allocate(1, 1)
a_polygon_grid.InsertNextCell(a_polygon.GetCellType(), a_polygon.GetPointIds())
a_polygon_grid.SetPoints(polygon_points)
a_polygon_grid.GetPointData().SetScalars(polygon_scalars)
polygon_contours = vtkContourFilter()
polygon_contours.SetInputData(a_polygon_grid)
polygon_contours.SetValue(0, 0.5)
a_polygon_contour_mapper = vtkDataSetMapper()
a_polygon_contour_mapper.SetInputConnection(polygon_contours.GetOutputPort())
a_polygon_contour_mapper.ScalarVisibilityOff()
a_polygon_mapper = vtkDataSetMapper()
a_polygon_mapper.SetInputData(a_polygon_grid)
a_polygon_mapper.ScalarVisibilityOff()
a_polygon_contour_actor = vtkActor()
a_polygon_contour_actor.SetMapper(a_polygon_contour_mapper)
a_polygon_actor = vtkActor()
a_polygon_actor.SetMapper(a_polygon_mapper)
a_polygon_actor.GetProperty().BackfaceCullingOn()
a_polygon_actor.GetProperty().SetRepresentationToWireframe()

# --- Triangle Strip ---
tri_strip_points = vtkPoints()
tri_strip_points.SetNumberOfPoints(5)
tri_strip_points.InsertPoint(0, 0, 1, 0)
tri_strip_points.InsertPoint(1, 0, 0, 0)
tri_strip_points.InsertPoint(2, 1, 1, 0)
tri_strip_points.InsertPoint(3, 1, 0, 0)
tri_strip_points.InsertPoint(4, 2, 1, 0)
tri_strip_scalars = vtkFloatArray()
tri_strip_scalars.SetNumberOfTuples(5)
for i, v in enumerate([1, 0, 0, 0, 0]):
    tri_strip_scalars.InsertValue(i, v)
a_tri_strip = vtkTriangleStrip()
a_tri_strip.GetPointIds().SetNumberOfIds(5)
for i in range(5):
    a_tri_strip.GetPointIds().SetId(i, i)
a_tri_strip_grid = vtkUnstructuredGrid()
a_tri_strip_grid.Allocate(1, 1)
a_tri_strip_grid.InsertNextCell(a_tri_strip.GetCellType(), a_tri_strip.GetPointIds())
a_tri_strip_grid.SetPoints(tri_strip_points)
a_tri_strip_grid.GetPointData().SetScalars(tri_strip_scalars)
tri_strip_contours = vtkContourFilter()
tri_strip_contours.SetInputData(a_tri_strip_grid)
tri_strip_contours.SetValue(0, 0.5)
a_tri_strip_mapper = vtkDataSetMapper()
a_tri_strip_mapper.SetInputData(a_tri_strip_grid)
a_tri_strip_mapper.ScalarVisibilityOff()
a_tri_strip_contour_mapper = vtkDataSetMapper()
a_tri_strip_contour_mapper.SetInputConnection(tri_strip_contours.GetOutputPort())
a_tri_strip_contour_mapper.ScalarVisibilityOff()
a_tri_strip_contour_actor = vtkActor()
a_tri_strip_contour_actor.SetMapper(a_tri_strip_contour_mapper)
a_tri_strip_actor = vtkActor()
a_tri_strip_actor.SetMapper(a_tri_strip_mapper)
a_tri_strip_actor.GetProperty().BackfaceCullingOn()
a_tri_strip_actor.GetProperty().SetRepresentationToWireframe()

# --- Line ---
line_points = vtkPoints()
line_points.SetNumberOfPoints(2)
line_points.InsertPoint(0, 0, 0, 0)
line_points.InsertPoint(1, 1, 1, 0)
line_scalars = vtkFloatArray()
line_scalars.SetNumberOfTuples(2)
line_scalars.InsertValue(0, 1)
line_scalars.InsertValue(1, 0)
a_line = vtkLine()
a_line.GetPointIds().SetId(0, 0)
a_line.GetPointIds().SetId(1, 1)
a_line_grid = vtkUnstructuredGrid()
a_line_grid.Allocate(1, 1)
a_line_grid.InsertNextCell(a_line.GetCellType(), a_line.GetPointIds())
a_line_grid.SetPoints(line_points)
a_line_grid.GetPointData().SetScalars(line_scalars)
line_contours = vtkContourFilter()
line_contours.SetInputData(a_line_grid)
line_contours.SetValue(0, 0.5)
a_line_contour_mapper = vtkDataSetMapper()
a_line_contour_mapper.SetInputConnection(line_contours.GetOutputPort())
a_line_contour_mapper.ScalarVisibilityOff()
a_line_contour_actor = vtkActor()
a_line_contour_actor.SetMapper(a_line_contour_mapper)
a_line_mapper = vtkDataSetMapper()
a_line_mapper.SetInputData(a_line_grid)
a_line_mapper.ScalarVisibilityOff()
a_line_actor = vtkActor()
a_line_actor.SetMapper(a_line_mapper)
a_line_actor.GetProperty().BackfaceCullingOn()
a_line_actor.GetProperty().SetRepresentationToWireframe()

# --- Polyline ---
poly_line_points = vtkPoints()
poly_line_points.SetNumberOfPoints(3)
poly_line_points.InsertPoint(0, 0, 0, 0)
poly_line_points.InsertPoint(1, 1, 1, 0)
poly_line_points.InsertPoint(2, 1, 0, 0)
poly_line_scalars = vtkFloatArray()
poly_line_scalars.SetNumberOfTuples(3)
for i, v in enumerate([1, 0, 0]):
    poly_line_scalars.InsertValue(i, v)
a_poly_line = vtkPolyLine()
a_poly_line.GetPointIds().SetNumberOfIds(3)
for i in range(3):
    a_poly_line.GetPointIds().SetId(i, i)
a_poly_line_grid = vtkUnstructuredGrid()
a_poly_line_grid.Allocate(1, 1)
a_poly_line_grid.InsertNextCell(a_poly_line.GetCellType(), a_poly_line.GetPointIds())
a_poly_line_grid.SetPoints(poly_line_points)
a_poly_line_grid.GetPointData().SetScalars(poly_line_scalars)
poly_line_contours = vtkContourFilter()
poly_line_contours.SetInputData(a_poly_line_grid)
poly_line_contours.SetValue(0, 0.5)
a_poly_line_contour_mapper = vtkDataSetMapper()
a_poly_line_contour_mapper.SetInputConnection(poly_line_contours.GetOutputPort())
a_poly_line_contour_mapper.ScalarVisibilityOff()
a_poly_line_contour_actor = vtkActor()
a_poly_line_contour_actor.SetMapper(a_poly_line_contour_mapper)
a_poly_line_mapper = vtkDataSetMapper()
a_poly_line_mapper.SetInputData(a_poly_line_grid)
a_poly_line_mapper.ScalarVisibilityOff()
a_poly_line_actor = vtkActor()
a_poly_line_actor.SetMapper(a_poly_line_mapper)
a_poly_line_actor.GetProperty().BackfaceCullingOn()
a_poly_line_actor.GetProperty().SetRepresentationToWireframe()

# --- Vertex ---
vertex_points = vtkPoints()
vertex_points.SetNumberOfPoints(1)
vertex_points.InsertPoint(0, 0, 0, 0)
vertex_scalars = vtkFloatArray()
vertex_scalars.SetNumberOfTuples(1)
vertex_scalars.InsertValue(0, 1)
a_vertex = vtkVertex()
a_vertex.GetPointIds().SetId(0, 0)
a_vertex_grid = vtkUnstructuredGrid()
a_vertex_grid.Allocate(1, 1)
a_vertex_grid.InsertNextCell(a_vertex.GetCellType(), a_vertex.GetPointIds())
a_vertex_grid.SetPoints(vertex_points)
a_vertex_grid.GetPointData().SetScalars(vertex_scalars)
vertex_contours = vtkContourFilter()
vertex_contours.SetInputData(a_vertex_grid)
vertex_contours.SetValue(0, 1)
a_vertex_contour_mapper = vtkDataSetMapper()
a_vertex_contour_mapper.SetInputConnection(vertex_contours.GetOutputPort())
a_vertex_contour_mapper.ScalarVisibilityOff()
a_vertex_contour_actor = vtkActor()
a_vertex_contour_actor.SetMapper(a_vertex_contour_mapper)
a_vertex_contour_actor.GetProperty().SetRepresentationToWireframe()
a_vertex_mapper = vtkDataSetMapper()
a_vertex_mapper.SetInputData(a_vertex_grid)
a_vertex_mapper.ScalarVisibilityOff()
a_vertex_actor = vtkActor()
a_vertex_actor.SetMapper(a_vertex_mapper)
a_vertex_actor.GetProperty().BackfaceCullingOn()

# --- Poly Vertex ---
poly_vertex_points = vtkPoints()
poly_vertex_points.SetNumberOfPoints(3)
poly_vertex_points.InsertPoint(0, 0, 0, 0)
poly_vertex_points.InsertPoint(1, 1, 0, 0)
poly_vertex_points.InsertPoint(2, 1, 1, 0)
poly_vertex_scalars = vtkFloatArray()
poly_vertex_scalars.SetNumberOfTuples(3)
for i, v in enumerate([1, 0, 0]):
    poly_vertex_scalars.InsertValue(i, v)
a_poly_vertex = vtkPolyVertex()
a_poly_vertex.GetPointIds().SetNumberOfIds(3)
for i in range(3):
    a_poly_vertex.GetPointIds().SetId(i, i)
a_poly_vertex_grid = vtkUnstructuredGrid()
a_poly_vertex_grid.Allocate(1, 1)
a_poly_vertex_grid.InsertNextCell(a_poly_vertex.GetCellType(), a_poly_vertex.GetPointIds())
a_poly_vertex_grid.SetPoints(poly_vertex_points)
a_poly_vertex_grid.GetPointData().SetScalars(poly_vertex_scalars)
poly_vertex_contours = vtkContourFilter()
poly_vertex_contours.SetInputData(a_poly_vertex_grid)
poly_vertex_contours.SetValue(0, 0)
a_poly_vertex_contour_mapper = vtkDataSetMapper()
a_poly_vertex_contour_mapper.SetInputConnection(poly_vertex_contours.GetOutputPort())
a_poly_vertex_contour_mapper.ScalarVisibilityOff()
a_poly_vertex_contour_actor = vtkActor()
a_poly_vertex_contour_actor.SetMapper(a_poly_vertex_contour_mapper)
a_poly_vertex_contour_actor.GetProperty().SetRepresentationToWireframe()
a_poly_vertex_mapper = vtkDataSetMapper()
a_poly_vertex_mapper.SetInputData(a_poly_vertex_grid)
a_poly_vertex_mapper.ScalarVisibilityOff()
a_poly_vertex_actor = vtkActor()
a_poly_vertex_actor.SetMapper(a_poly_vertex_mapper)

# --- Pentagonal Prism ---
penta_points = vtkPoints()
penta_points.SetNumberOfPoints(10)
penta_points.InsertPoint(0, 0.25, 0.0, 0.0)
penta_points.InsertPoint(1, 0.75, 0.0, 0.0)
penta_points.InsertPoint(2, 1.0, 0.5, 0.0)
penta_points.InsertPoint(3, 0.5, 1.0, 0.0)
penta_points.InsertPoint(4, 0.0, 0.5, 0.0)
penta_points.InsertPoint(5, 0.25, 0.0, 1.0)
penta_points.InsertPoint(6, 0.75, 0.0, 1.0)
penta_points.InsertPoint(7, 1.0, 0.5, 1.0)
penta_points.InsertPoint(8, 0.5, 1.0, 1.0)
penta_points.InsertPoint(9, 0.0, 0.5, 1.0)
penta_scalars = vtkFloatArray()
penta_scalars.SetNumberOfTuples(10)
for i, v in enumerate([1, 1, 1, 1, 1, 0, 0, 0, 0, 0]):
    penta_scalars.InsertValue(i, v)
a_penta = vtkPentagonalPrism()
for i in range(10):
    a_penta.GetPointIds().SetId(i, i)
a_penta_grid = vtkUnstructuredGrid()
a_penta_grid.Allocate(1, 1)
a_penta_grid.InsertNextCell(a_penta.GetCellType(), a_penta.GetPointIds())
a_penta_grid.SetPoints(penta_points)
a_penta_grid.GetPointData().SetScalars(penta_scalars)
penta_contours = vtkContourFilter()
penta_contours.SetInputData(a_penta_grid)
penta_contours.SetValue(0, 0.5)
a_penta_contour_mapper = vtkDataSetMapper()
a_penta_contour_mapper.SetInputConnection(penta_contours.GetOutputPort())
a_penta_contour_mapper.ScalarVisibilityOff()
a_penta_mapper = vtkDataSetMapper()
a_penta_mapper.SetInputData(a_penta_grid)
a_penta_mapper.ScalarVisibilityOff()
a_penta_actor = vtkActor()
a_penta_actor.SetMapper(a_penta_mapper)
a_penta_actor.GetProperty().BackfaceCullingOn()
a_penta_actor.GetProperty().SetRepresentationToWireframe()
a_penta_contour_actor = vtkActor()
a_penta_contour_actor.SetMapper(a_penta_contour_mapper)
a_penta_contour_actor.GetProperty().BackfaceCullingOn()

# --- Hexagonal Prism ---
hexa_points = vtkPoints()
hexa_points.SetNumberOfPoints(12)
hexa_points.InsertPoint(0, 0.0, 0.0, 0.0)
hexa_points.InsertPoint(1, 0.5, 0.0, 0.0)
hexa_points.InsertPoint(2, 1.0, 0.5, 0.0)
hexa_points.InsertPoint(3, 1.0, 1.0, 0.0)
hexa_points.InsertPoint(4, 0.5, 1.0, 0.0)
hexa_points.InsertPoint(5, 0.0, 0.5, 0.0)
hexa_points.InsertPoint(6, 0.0, 0.0, 1.0)
hexa_points.InsertPoint(7, 0.5, 0.0, 1.0)
hexa_points.InsertPoint(8, 1.0, 0.5, 1.0)
hexa_points.InsertPoint(9, 1.0, 1.0, 1.0)
hexa_points.InsertPoint(10, 0.5, 1.0, 1.0)
hexa_points.InsertPoint(11, 0.0, 0.5, 1.0)
hexa_scalars = vtkFloatArray()
hexa_scalars.SetNumberOfTuples(12)
for i, v in enumerate([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]):
    hexa_scalars.InsertValue(i, v)
a_hexa = vtkHexagonalPrism()
for i in range(12):
    a_hexa.GetPointIds().SetId(i, i)
a_hexa_grid = vtkUnstructuredGrid()
a_hexa_grid.Allocate(1, 1)
a_hexa_grid.InsertNextCell(a_hexa.GetCellType(), a_hexa.GetPointIds())
a_hexa_grid.SetPoints(hexa_points)
a_hexa_grid.GetPointData().SetScalars(hexa_scalars)
hexa_contours = vtkContourFilter()
hexa_contours.SetInputData(a_hexa_grid)
hexa_contours.SetValue(0, 0.5)
a_hexa_contour_mapper = vtkDataSetMapper()
a_hexa_contour_mapper.SetInputConnection(hexa_contours.GetOutputPort())
a_hexa_contour_mapper.ScalarVisibilityOff()
a_hexa_mapper = vtkDataSetMapper()
a_hexa_mapper.SetInputData(a_hexa_grid)
a_hexa_mapper.ScalarVisibilityOff()
a_hexa_actor = vtkActor()
a_hexa_actor.SetMapper(a_hexa_mapper)
a_hexa_actor.GetProperty().BackfaceCullingOn()
a_hexa_actor.GetProperty().SetRepresentationToWireframe()
a_hexa_contour_actor = vtkActor()
a_hexa_contour_actor.SetMapper(a_hexa_contour_mapper)
a_hexa_contour_actor.GetProperty().BackfaceCullingOn()

# Set colors and add to renderer
renderer.SetBackground(0.1, 0.2, 0.3)

# Row 0: 3D cells
renderer.AddActor(a_voxel_actor)
a_voxel_actor.GetProperty().SetDiffuseColor(1, 0, 0)
renderer.AddActor(a_voxel_contour_actor)
a_voxel_contour_actor.GetProperty().SetDiffuseColor(1, 0, 0)

renderer.AddActor(a_hex_actor)
a_hex_actor.GetProperty().SetDiffuseColor(1, 1, 0)
renderer.AddActor(a_hex_contour_actor)
a_hex_contour_actor.GetProperty().SetDiffuseColor(1, 1, 0)

renderer.AddActor(a_tetra_actor)
a_tetra_actor.GetProperty().SetDiffuseColor(0, 1, 0)
renderer.AddActor(a_tetra_contour_actor)
a_tetra_contour_actor.GetProperty().SetDiffuseColor(0, 1, 0)

renderer.AddActor(a_wedge_actor)
a_wedge_actor.GetProperty().SetDiffuseColor(0, 1, 1)
renderer.AddActor(a_wedge_contour_actor)
a_wedge_contour_actor.GetProperty().SetDiffuseColor(0, 1, 1)

renderer.AddActor(a_pyramid_actor)
a_pyramid_actor.GetProperty().SetDiffuseColor(1, 0, 1)
renderer.AddActor(a_pyramid_contour_actor)
a_pyramid_contour_actor.GetProperty().SetDiffuseColor(1, 0, 1)

# Row 1: 2D cells
renderer.AddActor(a_pixel_actor)
a_pixel_actor.GetProperty().SetDiffuseColor(0, 1, 1)
renderer.AddActor(a_pixel_contour_actor)
a_pixel_contour_actor.GetProperty().SetDiffuseColor(0, 1, 1)

renderer.AddActor(a_quad_actor)
a_quad_actor.GetProperty().SetDiffuseColor(1, 0, 1)
renderer.AddActor(a_quad_contour_actor)
a_quad_contour_actor.GetProperty().SetDiffuseColor(1, 0, 1)

renderer.AddActor(a_triangle_actor)
a_triangle_actor.GetProperty().SetDiffuseColor(0.3, 1, 0.5)
renderer.AddActor(a_triangle_contour_actor)
a_triangle_contour_actor.GetProperty().SetDiffuseColor(0.3, 1, 0.5)

renderer.AddActor(a_polygon_actor)
a_polygon_actor.GetProperty().SetDiffuseColor(1, 0.4, 0.5)
renderer.AddActor(a_polygon_contour_actor)
a_polygon_contour_actor.GetProperty().SetDiffuseColor(1, 0.4, 0.5)

renderer.AddActor(a_tri_strip_actor)
a_tri_strip_actor.GetProperty().SetDiffuseColor(0.3, 0.7, 1)
renderer.AddActor(a_tri_strip_contour_actor)
a_tri_strip_contour_actor.GetProperty().SetDiffuseColor(0.3, 0.7, 1)

# Row 2: 1D cells
renderer.AddActor(a_line_actor)
a_line_actor.GetProperty().SetDiffuseColor(0.2, 1, 1)
renderer.AddActor(a_line_contour_actor)
a_line_contour_actor.GetProperty().SetDiffuseColor(0.2, 1, 1)

renderer.AddActor(a_poly_line_actor)
a_poly_line_actor.GetProperty().SetDiffuseColor(1, 1, 1)
renderer.AddActor(a_poly_line_contour_actor)
a_poly_line_contour_actor.GetProperty().SetDiffuseColor(1, 1, 1)

# Row 3: 0D cells
renderer.AddActor(a_vertex_actor)
a_vertex_actor.GetProperty().SetDiffuseColor(1, 1, 1)
renderer.AddActor(a_vertex_contour_actor)
a_vertex_contour_actor.GetProperty().SetDiffuseColor(1, 1, 1)

renderer.AddActor(a_poly_vertex_actor)
a_poly_vertex_actor.GetProperty().SetDiffuseColor(1, 1, 1)
renderer.AddActor(a_poly_vertex_contour_actor)
a_poly_vertex_contour_actor.GetProperty().SetDiffuseColor(1, 1, 1)

# Row 2 continued: prisms
renderer.AddActor(a_penta_actor)
a_penta_actor.GetProperty().SetDiffuseColor(0.2, 0.4, 0.7)
renderer.AddActor(a_penta_contour_actor)
a_penta_contour_actor.GetProperty().SetDiffuseColor(0.2, 0.4, 0.7)

renderer.AddActor(a_hexa_actor)
a_hexa_actor.GetProperty().SetDiffuseColor(0.7, 0.5, 1)
renderer.AddActor(a_hexa_contour_actor)
a_hexa_contour_actor.GetProperty().SetDiffuseColor(0.7, 0.5, 1)

# Position actors in grid layout
a_voxel_contour_actor.AddPosition(0, 0, 0)
a_voxel_contour_actor.AddPosition(0, 2, 0)
a_hex_contour_actor.AddPosition(2, 0, 0)
a_hex_contour_actor.AddPosition(0, 2, 0)
a_hex_actor.AddPosition(2, 0, 0)
a_tetra_contour_actor.AddPosition(4, 0, 0)
a_tetra_contour_actor.AddPosition(0, 2, 0)
a_tetra_actor.AddPosition(4, 0, 0)
a_wedge_contour_actor.AddPosition(6, 0, 0)
a_wedge_contour_actor.AddPosition(0, 2, 0)
a_wedge_actor.AddPosition(6, 0, 0)
a_pyramid_contour_actor.AddPosition(8, 0, 0)
a_pyramid_contour_actor.AddPosition(0, 2, 0)
a_pyramid_actor.AddPosition(8, 0, 0)

a_pixel_contour_actor.AddPosition(0, 4, 0)
a_pixel_contour_actor.AddPosition(0, 2, 0)
a_pixel_actor.AddPosition(0, 4, 0)
a_quad_contour_actor.AddPosition(2, 4, 0)
a_quad_contour_actor.AddPosition(0, 2, 0)
a_quad_actor.AddPosition(2, 4, 0)
a_triangle_contour_actor.AddPosition(4, 4, 0)
a_triangle_contour_actor.AddPosition(0, 2, 0)
a_triangle_actor.AddPosition(4, 4, 0)
a_polygon_contour_actor.AddPosition(6, 4, 0)
a_polygon_contour_actor.AddPosition(0, 2, 0)
a_polygon_actor.AddPosition(6, 4, 0)
a_tri_strip_contour_actor.AddPosition(8, 4, 0)
a_tri_strip_contour_actor.AddPosition(0, 2, 0)
a_tri_strip_actor.AddPosition(8, 4, 0)

a_line_contour_actor.AddPosition(0, 8, 0)
a_line_contour_actor.AddPosition(0, 2, 0)
a_line_actor.AddPosition(0, 8, 0)
a_poly_line_contour_actor.AddPosition(2, 8, 0)
a_poly_line_contour_actor.AddPosition(0, 2, 0)
a_poly_line_actor.AddPosition(2, 8, 0)

a_vertex_contour_actor.AddPosition(0, 12, 0)
a_vertex_contour_actor.AddPosition(0, 2, 0)
a_vertex_actor.AddPosition(0, 12, 0)
a_poly_vertex_contour_actor.AddPosition(2, 12, 0)
a_poly_vertex_contour_actor.AddPosition(0, 2, 0)
a_poly_vertex_actor.AddPosition(2, 12, 0)

a_penta_contour_actor.AddPosition(4, 8, 0)
a_penta_contour_actor.AddPosition(0, 2, 0)
a_penta_actor.AddPosition(4, 8, 0)
a_hexa_contour_actor.AddPosition(6, 8, 0)
a_hexa_contour_actor.AddPosition(0, 2, 0)
a_hexa_actor.AddPosition(6, 8, 0)

# Backdrop: base plane
base_plane = vtkCubeSource()
base_plane.SetCenter(5.0, -1, 0.5)
base_plane.SetXLength(12)
base_plane.SetYLength(0.1)
base_plane.SetZLength(3)
base_mapper = vtkPolyDataMapper()
base_mapper.SetInputConnection(base_plane.GetOutputPort())
base_actor = vtkActor()
base_actor.SetMapper(base_mapper)
base_actor.GetProperty().SetDiffuseColor(0.2, 0.2, 0.2)
renderer.AddActor(base_actor)

# Backdrop: back plane
back_plane = vtkCubeSource()
back_plane.SetCenter(5.0, 7.5, -1)
back_plane.SetXLength(12)
back_plane.SetYLength(17)
back_plane.SetZLength(0.1)
back_mapper = vtkPolyDataMapper()
back_mapper.SetInputConnection(back_plane.GetOutputPort())
back_actor = vtkActor()
back_actor.SetMapper(back_mapper)
back_actor.GetProperty().SetDiffuseColor(0.2, 0.2, 0.2)
renderer.AddActor(back_actor)

# Backdrop: left plane
left_plane = vtkCubeSource()
left_plane.SetCenter(-1, 7.5, 0.5)
left_plane.SetXLength(0.1)
left_plane.SetYLength(17)
left_plane.SetZLength(3)
left_mapper = vtkPolyDataMapper()
left_mapper.SetInputConnection(left_plane.GetOutputPort())
left_actor = vtkActor()
left_actor.SetMapper(left_mapper)
left_actor.GetProperty().SetDiffuseColor(0.2, 0.2, 0.2)
renderer.AddActor(left_actor)

# Window
render_window = vtkRenderWindow()
render_window.AddRenderer(renderer)
render_window.SetSize(400, 400)
render_window.SetWindowName("contour cells")

# Scene
renderer.ResetCamera()
renderer.GetActiveCamera().Dolly(1.5)
renderer.ResetCameraClippingRange()

# Interactor
interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)

interactor.Initialize()
interactor.Start()
