#!/usr/bin/env python

# Generate labeled blob isosurfaces using vtkDiscreteMarchingCubes with
# a rotated direction matrix, random color lookup table, and an outline.

from math import cos, sin, pi

# Factory overrides
import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401

from vtkmodules.vtkCommonCore import (
    vtkLookupTable,
    vtkMath,
)
from vtkmodules.vtkCommonDataModel import (
    vtkImageData,
    vtkSphere,
)
from vtkmodules.vtkFiltersGeneral import vtkDiscreteMarchingCubes
from vtkmodules.vtkFiltersModeling import vtkImageDataOutlineFilter
from vtkmodules.vtkImagingCore import vtkImageThreshold
from vtkmodules.vtkImagingHybrid import vtkSampleFunction
from vtkmodules.vtkImagingMath import vtkImageMathematics
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkPolyDataMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
)

vtk_math = vtkMath()

# Build a random color lookup table
lut = vtkLookupTable()
n_blobs = 20
lut.SetNumberOfColors(256)
lut.SetTableRange(0, 255)
lut.SetScaleToLinear()
lut.Build()
lut.SetTableValue(0, 0, 0, 0, 1)
vtk_math.RandomSeed(5071)
for i in range(1, 256):
    lut.SetTableValue(i, vtk_math.Random(0.2, 1),
                      vtk_math.Random(0.2, 1), vtk_math.Random(0.2, 1), 1)

radius = 10
blob_image = vtkImageData()

# Generate labeled blobs by sampling spheres
sphere_0 = vtkSphere()
sphere_0.SetRadius(radius)
sphere_0.SetCenter(6, -17, 38)
sampler_0 = vtkSampleFunction()
sampler_0.SetImplicitFunction(sphere_0)
sampler_0.SetOutputScalarTypeToFloat()
sampler_0.SetSampleDimensions(51, 51, 51)
sampler_0.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_0 = vtkImageThreshold()
thres_0.SetInputConnection(sampler_0.GetOutputPort())
thres_0.ThresholdByLower(radius * radius)
thres_0.ReplaceInOn()
thres_0.ReplaceOutOn()
thres_0.SetInValue(1)
thres_0.SetOutValue(0)
thres_0.Update()
blob_image.DeepCopy(thres_0.GetOutput())
max_value_0 = vtkImageMathematics()
max_value_0.SetInputData(0, blob_image)
max_value_0.SetInputData(1, thres_0.GetOutput())
max_value_0.SetOperationToMax()
max_value_0.Modified()
max_value_0.Update()
blob_image.DeepCopy(max_value_0.GetOutput())

sphere_1 = vtkSphere()
sphere_1.SetRadius(radius)
sphere_1.SetCenter(8, 30, 22)
sampler_1 = vtkSampleFunction()
sampler_1.SetImplicitFunction(sphere_1)
sampler_1.SetOutputScalarTypeToFloat()
sampler_1.SetSampleDimensions(51, 51, 51)
sampler_1.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_1 = vtkImageThreshold()
thres_1.SetInputConnection(sampler_1.GetOutputPort())
thres_1.ThresholdByLower(radius * radius)
thres_1.ReplaceInOn()
thres_1.ReplaceOutOn()
thres_1.SetInValue(2)
thres_1.SetOutValue(0)
thres_1.Update()
max_value_1 = vtkImageMathematics()
max_value_1.SetInputData(0, blob_image)
max_value_1.SetInputData(1, thres_1.GetOutput())
max_value_1.SetOperationToMax()
max_value_1.Modified()
max_value_1.Update()
blob_image.DeepCopy(max_value_1.GetOutput())

sphere_2 = vtkSphere()
sphere_2.SetRadius(radius)
sphere_2.SetCenter(0, 33, -5)
sampler_2 = vtkSampleFunction()
sampler_2.SetImplicitFunction(sphere_2)
sampler_2.SetOutputScalarTypeToFloat()
sampler_2.SetSampleDimensions(51, 51, 51)
sampler_2.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_2 = vtkImageThreshold()
thres_2.SetInputConnection(sampler_2.GetOutputPort())
thres_2.ThresholdByLower(radius * radius)
thres_2.ReplaceInOn()
thres_2.ReplaceOutOn()
thres_2.SetInValue(3)
thres_2.SetOutValue(0)
thres_2.Update()
max_value_2 = vtkImageMathematics()
max_value_2.SetInputData(0, blob_image)
max_value_2.SetInputData(1, thres_2.GetOutput())
max_value_2.SetOperationToMax()
max_value_2.Modified()
max_value_2.Update()
blob_image.DeepCopy(max_value_2.GetOutput())

sphere_3 = vtkSphere()
sphere_3.SetRadius(radius)
sphere_3.SetCenter(-30, -35, 16)
sampler_3 = vtkSampleFunction()
sampler_3.SetImplicitFunction(sphere_3)
sampler_3.SetOutputScalarTypeToFloat()
sampler_3.SetSampleDimensions(51, 51, 51)
sampler_3.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_3 = vtkImageThreshold()
thres_3.SetInputConnection(sampler_3.GetOutputPort())
thres_3.ThresholdByLower(radius * radius)
thres_3.ReplaceInOn()
thres_3.ReplaceOutOn()
thres_3.SetInValue(4)
thres_3.SetOutValue(0)
thres_3.Update()
max_value_3 = vtkImageMathematics()
max_value_3.SetInputData(0, blob_image)
max_value_3.SetInputData(1, thres_3.GetOutput())
max_value_3.SetOperationToMax()
max_value_3.Modified()
max_value_3.Update()
blob_image.DeepCopy(max_value_3.GetOutput())

sphere_4 = vtkSphere()
sphere_4.SetRadius(radius)
sphere_4.SetCenter(2, -21, 17)
sampler_4 = vtkSampleFunction()
sampler_4.SetImplicitFunction(sphere_4)
sampler_4.SetOutputScalarTypeToFloat()
sampler_4.SetSampleDimensions(51, 51, 51)
sampler_4.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_4 = vtkImageThreshold()
thres_4.SetInputConnection(sampler_4.GetOutputPort())
thres_4.ThresholdByLower(radius * radius)
thres_4.ReplaceInOn()
thres_4.ReplaceOutOn()
thres_4.SetInValue(5)
thres_4.SetOutValue(0)
thres_4.Update()
max_value_4 = vtkImageMathematics()
max_value_4.SetInputData(0, blob_image)
max_value_4.SetInputData(1, thres_4.GetOutput())
max_value_4.SetOperationToMax()
max_value_4.Modified()
max_value_4.Update()
blob_image.DeepCopy(max_value_4.GetOutput())

sphere_5 = vtkSphere()
sphere_5.SetRadius(radius)
sphere_5.SetCenter(28, 19, -34)
sampler_5 = vtkSampleFunction()
sampler_5.SetImplicitFunction(sphere_5)
sampler_5.SetOutputScalarTypeToFloat()
sampler_5.SetSampleDimensions(51, 51, 51)
sampler_5.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_5 = vtkImageThreshold()
thres_5.SetInputConnection(sampler_5.GetOutputPort())
thres_5.ThresholdByLower(radius * radius)
thres_5.ReplaceInOn()
thres_5.ReplaceOutOn()
thres_5.SetInValue(6)
thres_5.SetOutValue(0)
thres_5.Update()
max_value_5 = vtkImageMathematics()
max_value_5.SetInputData(0, blob_image)
max_value_5.SetInputData(1, thres_5.GetOutput())
max_value_5.SetOperationToMax()
max_value_5.Modified()
max_value_5.Update()
blob_image.DeepCopy(max_value_5.GetOutput())

sphere_6 = vtkSphere()
sphere_6.SetRadius(radius)
sphere_6.SetCenter(-18, 22, 0)
sampler_6 = vtkSampleFunction()
sampler_6.SetImplicitFunction(sphere_6)
sampler_6.SetOutputScalarTypeToFloat()
sampler_6.SetSampleDimensions(51, 51, 51)
sampler_6.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_6 = vtkImageThreshold()
thres_6.SetInputConnection(sampler_6.GetOutputPort())
thres_6.ThresholdByLower(radius * radius)
thres_6.ReplaceInOn()
thres_6.ReplaceOutOn()
thres_6.SetInValue(7)
thres_6.SetOutValue(0)
thres_6.Update()
max_value_6 = vtkImageMathematics()
max_value_6.SetInputData(0, blob_image)
max_value_6.SetInputData(1, thres_6.GetOutput())
max_value_6.SetOperationToMax()
max_value_6.Modified()
max_value_6.Update()
blob_image.DeepCopy(max_value_6.GetOutput())

sphere_7 = vtkSphere()
sphere_7.SetRadius(radius)
sphere_7.SetCenter(17, 2, 38)
sampler_7 = vtkSampleFunction()
sampler_7.SetImplicitFunction(sphere_7)
sampler_7.SetOutputScalarTypeToFloat()
sampler_7.SetSampleDimensions(51, 51, 51)
sampler_7.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_7 = vtkImageThreshold()
thres_7.SetInputConnection(sampler_7.GetOutputPort())
thres_7.ThresholdByLower(radius * radius)
thres_7.ReplaceInOn()
thres_7.ReplaceOutOn()
thres_7.SetInValue(8)
thres_7.SetOutValue(0)
thres_7.Update()
max_value_7 = vtkImageMathematics()
max_value_7.SetInputData(0, blob_image)
max_value_7.SetInputData(1, thres_7.GetOutput())
max_value_7.SetOperationToMax()
max_value_7.Modified()
max_value_7.Update()
blob_image.DeepCopy(max_value_7.GetOutput())

sphere_8 = vtkSphere()
sphere_8.SetRadius(radius)
sphere_8.SetCenter(32, -38, 19)
sampler_8 = vtkSampleFunction()
sampler_8.SetImplicitFunction(sphere_8)
sampler_8.SetOutputScalarTypeToFloat()
sampler_8.SetSampleDimensions(51, 51, 51)
sampler_8.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_8 = vtkImageThreshold()
thres_8.SetInputConnection(sampler_8.GetOutputPort())
thres_8.ThresholdByLower(radius * radius)
thres_8.ReplaceInOn()
thres_8.ReplaceOutOn()
thres_8.SetInValue(9)
thres_8.SetOutValue(0)
thres_8.Update()
max_value_8 = vtkImageMathematics()
max_value_8.SetInputData(0, blob_image)
max_value_8.SetInputData(1, thres_8.GetOutput())
max_value_8.SetOperationToMax()
max_value_8.Modified()
max_value_8.Update()
blob_image.DeepCopy(max_value_8.GetOutput())

sphere_9 = vtkSphere()
sphere_9.SetRadius(radius)
sphere_9.SetCenter(-33, 32, -31)
sampler_9 = vtkSampleFunction()
sampler_9.SetImplicitFunction(sphere_9)
sampler_9.SetOutputScalarTypeToFloat()
sampler_9.SetSampleDimensions(51, 51, 51)
sampler_9.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_9 = vtkImageThreshold()
thres_9.SetInputConnection(sampler_9.GetOutputPort())
thres_9.ThresholdByLower(radius * radius)
thres_9.ReplaceInOn()
thres_9.ReplaceOutOn()
thres_9.SetInValue(10)
thres_9.SetOutValue(0)
thres_9.Update()
max_value_9 = vtkImageMathematics()
max_value_9.SetInputData(0, blob_image)
max_value_9.SetInputData(1, thres_9.GetOutput())
max_value_9.SetOperationToMax()
max_value_9.Modified()
max_value_9.Update()
blob_image.DeepCopy(max_value_9.GetOutput())

sphere_10 = vtkSphere()
sphere_10.SetRadius(radius)
sphere_10.SetCenter(28, -20, -10)
sampler_10 = vtkSampleFunction()
sampler_10.SetImplicitFunction(sphere_10)
sampler_10.SetOutputScalarTypeToFloat()
sampler_10.SetSampleDimensions(51, 51, 51)
sampler_10.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_10 = vtkImageThreshold()
thres_10.SetInputConnection(sampler_10.GetOutputPort())
thres_10.ThresholdByLower(radius * radius)
thres_10.ReplaceInOn()
thres_10.ReplaceOutOn()
thres_10.SetInValue(11)
thres_10.SetOutValue(0)
thres_10.Update()
max_value_10 = vtkImageMathematics()
max_value_10.SetInputData(0, blob_image)
max_value_10.SetInputData(1, thres_10.GetOutput())
max_value_10.SetOperationToMax()
max_value_10.Modified()
max_value_10.Update()
blob_image.DeepCopy(max_value_10.GetOutput())

sphere_11 = vtkSphere()
sphere_11.SetRadius(radius)
sphere_11.SetCenter(-27, -17, 13)
sampler_11 = vtkSampleFunction()
sampler_11.SetImplicitFunction(sphere_11)
sampler_11.SetOutputScalarTypeToFloat()
sampler_11.SetSampleDimensions(51, 51, 51)
sampler_11.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_11 = vtkImageThreshold()
thres_11.SetInputConnection(sampler_11.GetOutputPort())
thres_11.ThresholdByLower(radius * radius)
thres_11.ReplaceInOn()
thres_11.ReplaceOutOn()
thres_11.SetInValue(12)
thres_11.SetOutValue(0)
thres_11.Update()
max_value_11 = vtkImageMathematics()
max_value_11.SetInputData(0, blob_image)
max_value_11.SetInputData(1, thres_11.GetOutput())
max_value_11.SetOperationToMax()
max_value_11.Modified()
max_value_11.Update()
blob_image.DeepCopy(max_value_11.GetOutput())

sphere_12 = vtkSphere()
sphere_12.SetRadius(radius)
sphere_12.SetCenter(-23, 38, 0)
sampler_12 = vtkSampleFunction()
sampler_12.SetImplicitFunction(sphere_12)
sampler_12.SetOutputScalarTypeToFloat()
sampler_12.SetSampleDimensions(51, 51, 51)
sampler_12.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_12 = vtkImageThreshold()
thres_12.SetInputConnection(sampler_12.GetOutputPort())
thres_12.ThresholdByLower(radius * radius)
thres_12.ReplaceInOn()
thres_12.ReplaceOutOn()
thres_12.SetInValue(13)
thres_12.SetOutValue(0)
thres_12.Update()
max_value_12 = vtkImageMathematics()
max_value_12.SetInputData(0, blob_image)
max_value_12.SetInputData(1, thres_12.GetOutput())
max_value_12.SetOperationToMax()
max_value_12.Modified()
max_value_12.Update()
blob_image.DeepCopy(max_value_12.GetOutput())

sphere_13 = vtkSphere()
sphere_13.SetRadius(radius)
sphere_13.SetCenter(-30, 13, -32)
sampler_13 = vtkSampleFunction()
sampler_13.SetImplicitFunction(sphere_13)
sampler_13.SetOutputScalarTypeToFloat()
sampler_13.SetSampleDimensions(51, 51, 51)
sampler_13.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_13 = vtkImageThreshold()
thres_13.SetInputConnection(sampler_13.GetOutputPort())
thres_13.ThresholdByLower(radius * radius)
thres_13.ReplaceInOn()
thres_13.ReplaceOutOn()
thres_13.SetInValue(14)
thres_13.SetOutValue(0)
thres_13.Update()
max_value_13 = vtkImageMathematics()
max_value_13.SetInputData(0, blob_image)
max_value_13.SetInputData(1, thres_13.GetOutput())
max_value_13.SetOperationToMax()
max_value_13.Modified()
max_value_13.Update()
blob_image.DeepCopy(max_value_13.GetOutput())

sphere_14 = vtkSphere()
sphere_14.SetRadius(radius)
sphere_14.SetCenter(-38, -1, 33)
sampler_14 = vtkSampleFunction()
sampler_14.SetImplicitFunction(sphere_14)
sampler_14.SetOutputScalarTypeToFloat()
sampler_14.SetSampleDimensions(51, 51, 51)
sampler_14.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_14 = vtkImageThreshold()
thres_14.SetInputConnection(sampler_14.GetOutputPort())
thres_14.ThresholdByLower(radius * radius)
thres_14.ReplaceInOn()
thres_14.ReplaceOutOn()
thres_14.SetInValue(15)
thres_14.SetOutValue(0)
thres_14.Update()
max_value_14 = vtkImageMathematics()
max_value_14.SetInputData(0, blob_image)
max_value_14.SetInputData(1, thres_14.GetOutput())
max_value_14.SetOperationToMax()
max_value_14.Modified()
max_value_14.Update()
blob_image.DeepCopy(max_value_14.GetOutput())

sphere_15 = vtkSphere()
sphere_15.SetRadius(radius)
sphere_15.SetCenter(-3, -5, -23)
sampler_15 = vtkSampleFunction()
sampler_15.SetImplicitFunction(sphere_15)
sampler_15.SetOutputScalarTypeToFloat()
sampler_15.SetSampleDimensions(51, 51, 51)
sampler_15.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_15 = vtkImageThreshold()
thres_15.SetInputConnection(sampler_15.GetOutputPort())
thres_15.ThresholdByLower(radius * radius)
thres_15.ReplaceInOn()
thres_15.ReplaceOutOn()
thres_15.SetInValue(16)
thres_15.SetOutValue(0)
thres_15.Update()
max_value_15 = vtkImageMathematics()
max_value_15.SetInputData(0, blob_image)
max_value_15.SetInputData(1, thres_15.GetOutput())
max_value_15.SetOperationToMax()
max_value_15.Modified()
max_value_15.Update()
blob_image.DeepCopy(max_value_15.GetOutput())

sphere_16 = vtkSphere()
sphere_16.SetRadius(radius)
sphere_16.SetCenter(-8, 11, -21)
sampler_16 = vtkSampleFunction()
sampler_16.SetImplicitFunction(sphere_16)
sampler_16.SetOutputScalarTypeToFloat()
sampler_16.SetSampleDimensions(51, 51, 51)
sampler_16.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_16 = vtkImageThreshold()
thres_16.SetInputConnection(sampler_16.GetOutputPort())
thres_16.ThresholdByLower(radius * radius)
thres_16.ReplaceInOn()
thres_16.ReplaceOutOn()
thres_16.SetInValue(17)
thres_16.SetOutValue(0)
thres_16.Update()
max_value_16 = vtkImageMathematics()
max_value_16.SetInputData(0, blob_image)
max_value_16.SetInputData(1, thres_16.GetOutput())
max_value_16.SetOperationToMax()
max_value_16.Modified()
max_value_16.Update()
blob_image.DeepCopy(max_value_16.GetOutput())

sphere_17 = vtkSphere()
sphere_17.SetRadius(radius)
sphere_17.SetCenter(1, 38, 17)
sampler_17 = vtkSampleFunction()
sampler_17.SetImplicitFunction(sphere_17)
sampler_17.SetOutputScalarTypeToFloat()
sampler_17.SetSampleDimensions(51, 51, 51)
sampler_17.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_17 = vtkImageThreshold()
thres_17.SetInputConnection(sampler_17.GetOutputPort())
thres_17.ThresholdByLower(radius * radius)
thres_17.ReplaceInOn()
thres_17.ReplaceOutOn()
thres_17.SetInValue(18)
thres_17.SetOutValue(0)
thres_17.Update()
max_value_17 = vtkImageMathematics()
max_value_17.SetInputData(0, blob_image)
max_value_17.SetInputData(1, thres_17.GetOutput())
max_value_17.SetOperationToMax()
max_value_17.Modified()
max_value_17.Update()
blob_image.DeepCopy(max_value_17.GetOutput())

sphere_18 = vtkSphere()
sphere_18.SetRadius(radius)
sphere_18.SetCenter(-6, 11, 6)
sampler_18 = vtkSampleFunction()
sampler_18.SetImplicitFunction(sphere_18)
sampler_18.SetOutputScalarTypeToFloat()
sampler_18.SetSampleDimensions(51, 51, 51)
sampler_18.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_18 = vtkImageThreshold()
thres_18.SetInputConnection(sampler_18.GetOutputPort())
thres_18.ThresholdByLower(radius * radius)
thres_18.ReplaceInOn()
thres_18.ReplaceOutOn()
thres_18.SetInValue(19)
thres_18.SetOutValue(0)
thres_18.Update()
max_value_18 = vtkImageMathematics()
max_value_18.SetInputData(0, blob_image)
max_value_18.SetInputData(1, thres_18.GetOutput())
max_value_18.SetOperationToMax()
max_value_18.Modified()
max_value_18.Update()
blob_image.DeepCopy(max_value_18.GetOutput())

sphere_19 = vtkSphere()
sphere_19.SetRadius(radius)
sphere_19.SetCenter(5, 39, -10)
sampler_19 = vtkSampleFunction()
sampler_19.SetImplicitFunction(sphere_19)
sampler_19.SetOutputScalarTypeToFloat()
sampler_19.SetSampleDimensions(51, 51, 51)
sampler_19.SetModelBounds(-50, 50, -50, 50, -50, 50)
thres_19 = vtkImageThreshold()
thres_19.SetInputConnection(sampler_19.GetOutputPort())
thres_19.ThresholdByLower(radius * radius)
thres_19.ReplaceInOn()
thres_19.ReplaceOutOn()
thres_19.SetInValue(20)
thres_19.SetOutValue(0)
thres_19.Update()
max_value_19 = vtkImageMathematics()
max_value_19.SetInputData(0, blob_image)
max_value_19.SetInputData(1, thres_19.GetOutput())
max_value_19.SetOperationToMax()
max_value_19.Modified()
max_value_19.Update()
blob_image.DeepCopy(max_value_19.GetOutput())

# Set a rotated direction matrix
angle = pi / 6
orientation = [
    -cos(angle), 0, sin(angle),
    0, 1, 0,
    sin(angle), 0, cos(angle),
]
blob_image.SetDirectionMatrix(orientation)

# Extract labeled blobs
discrete = vtkDiscreteMarchingCubes()
discrete.SetInputData(blob_image)
discrete.GenerateValues(n_blobs, 1, n_blobs)

mapper = vtkPolyDataMapper()
mapper.SetInputConnection(discrete.GetOutputPort())
mapper.SetLookupTable(lut)
mapper.SetScalarRange(0, lut.GetNumberOfColors())

actor = vtkActor()
actor.SetMapper(mapper)

# Outline around the image data
outline = vtkImageDataOutlineFilter()
outline.SetInputData(blob_image)

outline_mapper = vtkPolyDataMapper()
outline_mapper.SetInputConnection(outline.GetOutputPort())

outline_actor = vtkActor()
outline_actor.SetMapper(outline_mapper)
outline_actor.GetProperty().SetColor(1, 1, 1)

# Renderer
renderer = vtkRenderer()
renderer.AddActor(actor)
renderer.AddActor(outline_actor)
renderer.SetBackground(0.1, 0.2, 0.4)

# Window
render_window = vtkRenderWindow()
render_window.AddRenderer(renderer)
render_window.SetSize(400, 400)
render_window.SetWindowName("discrete marching cubes")

# Interactor
interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)

# Scene
renderer.ResetCamera()

interactor.Initialize()
interactor.Start()
