#!/usr/bin/env python

# Plane cut an oriented volume of random blob spheres using
# vtkFlyingEdgesPlaneCutter with a rotated direction matrix.

from math import cos, sin, pi

# Factory overrides
import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401

from vtkmodules.vtkCommonCore import (
    vtkLookupTable,
    vtkMath,
)
from vtkmodules.vtkCommonDataModel import (
    vtkImageData,
    vtkPlane,
    vtkSphere,
)
from vtkmodules.vtkFiltersCore import vtkFlyingEdgesPlaneCutter
from vtkmodules.vtkFiltersModeling import vtkImageDataOutlineFilter
from vtkmodules.vtkImagingCore import vtkImageThreshold
from vtkmodules.vtkImagingHybrid import vtkSampleFunction
from vtkmodules.vtkImagingMath import vtkImageMathematics
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkPolyDataMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
)

vtk_math = vtkMath()

# Generate random colors for lookup table
lookup_table = vtkLookupTable()
num_colors = 256
lookup_table.SetNumberOfColors(num_colors)
lookup_table.SetTableRange(0, num_colors - 1)
lookup_table.SetScaleToLinear()
lookup_table.Build()
lookup_table.SetTableValue(0, 0, 0, 0, 1)
vtk_math.RandomSeed(5071)
for i in range(1, num_colors):
    lookup_table.SetTableValue(i, vtk_math.Random(0.2, 1),
                      vtk_math.Random(0.2, 1), vtk_math.Random(0.2, 1), 1)

# Build a composite blob image from random spheres
num_blobs = 20
radius = 10
blob_image = vtkImageData()

sphere_0 = vtkSphere()
sphere_0.SetRadius(radius)
sphere_0.SetCenter(6, -17, 38)
sampler_0 = vtkSampleFunction()
sampler_0.SetImplicitFunction(sphere_0)
sampler_0.SetOutputScalarTypeToFloat()
sampler_0.SetSampleDimensions(51, 51, 51)
sampler_0.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_0 = vtkImageThreshold()
threshold_0.SetInputConnection(sampler_0.GetOutputPort())
threshold_0.ThresholdByLower(radius * radius)
threshold_0.ReplaceInOn()
threshold_0.ReplaceOutOn()
threshold_0.SetInValue(1)
threshold_0.SetOutValue(0)
threshold_0.Update()
blob_image.DeepCopy(threshold_0.GetOutput())
max_value_0 = vtkImageMathematics()
max_value_0.SetInputData(0, blob_image)
max_value_0.SetInputData(1, threshold_0.GetOutput())
max_value_0.SetOperationToMax()
max_value_0.Modified()
max_value_0.Update()
blob_image.DeepCopy(max_value_0.GetOutput())

sphere_1 = vtkSphere()
sphere_1.SetRadius(radius)
sphere_1.SetCenter(8, 30, 22)
sampler_1 = vtkSampleFunction()
sampler_1.SetImplicitFunction(sphere_1)
sampler_1.SetOutputScalarTypeToFloat()
sampler_1.SetSampleDimensions(51, 51, 51)
sampler_1.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_1 = vtkImageThreshold()
threshold_1.SetInputConnection(sampler_1.GetOutputPort())
threshold_1.ThresholdByLower(radius * radius)
threshold_1.ReplaceInOn()
threshold_1.ReplaceOutOn()
threshold_1.SetInValue(2)
threshold_1.SetOutValue(0)
threshold_1.Update()
max_value_1 = vtkImageMathematics()
max_value_1.SetInputData(0, blob_image)
max_value_1.SetInputData(1, threshold_1.GetOutput())
max_value_1.SetOperationToMax()
max_value_1.Modified()
max_value_1.Update()
blob_image.DeepCopy(max_value_1.GetOutput())

sphere_2 = vtkSphere()
sphere_2.SetRadius(radius)
sphere_2.SetCenter(0, 33, -5)
sampler_2 = vtkSampleFunction()
sampler_2.SetImplicitFunction(sphere_2)
sampler_2.SetOutputScalarTypeToFloat()
sampler_2.SetSampleDimensions(51, 51, 51)
sampler_2.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_2 = vtkImageThreshold()
threshold_2.SetInputConnection(sampler_2.GetOutputPort())
threshold_2.ThresholdByLower(radius * radius)
threshold_2.ReplaceInOn()
threshold_2.ReplaceOutOn()
threshold_2.SetInValue(3)
threshold_2.SetOutValue(0)
threshold_2.Update()
max_value_2 = vtkImageMathematics()
max_value_2.SetInputData(0, blob_image)
max_value_2.SetInputData(1, threshold_2.GetOutput())
max_value_2.SetOperationToMax()
max_value_2.Modified()
max_value_2.Update()
blob_image.DeepCopy(max_value_2.GetOutput())

sphere_3 = vtkSphere()
sphere_3.SetRadius(radius)
sphere_3.SetCenter(-30, -35, 16)
sampler_3 = vtkSampleFunction()
sampler_3.SetImplicitFunction(sphere_3)
sampler_3.SetOutputScalarTypeToFloat()
sampler_3.SetSampleDimensions(51, 51, 51)
sampler_3.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_3 = vtkImageThreshold()
threshold_3.SetInputConnection(sampler_3.GetOutputPort())
threshold_3.ThresholdByLower(radius * radius)
threshold_3.ReplaceInOn()
threshold_3.ReplaceOutOn()
threshold_3.SetInValue(4)
threshold_3.SetOutValue(0)
threshold_3.Update()
max_value_3 = vtkImageMathematics()
max_value_3.SetInputData(0, blob_image)
max_value_3.SetInputData(1, threshold_3.GetOutput())
max_value_3.SetOperationToMax()
max_value_3.Modified()
max_value_3.Update()
blob_image.DeepCopy(max_value_3.GetOutput())

sphere_4 = vtkSphere()
sphere_4.SetRadius(radius)
sphere_4.SetCenter(2, -21, 17)
sampler_4 = vtkSampleFunction()
sampler_4.SetImplicitFunction(sphere_4)
sampler_4.SetOutputScalarTypeToFloat()
sampler_4.SetSampleDimensions(51, 51, 51)
sampler_4.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_4 = vtkImageThreshold()
threshold_4.SetInputConnection(sampler_4.GetOutputPort())
threshold_4.ThresholdByLower(radius * radius)
threshold_4.ReplaceInOn()
threshold_4.ReplaceOutOn()
threshold_4.SetInValue(5)
threshold_4.SetOutValue(0)
threshold_4.Update()
max_value_4 = vtkImageMathematics()
max_value_4.SetInputData(0, blob_image)
max_value_4.SetInputData(1, threshold_4.GetOutput())
max_value_4.SetOperationToMax()
max_value_4.Modified()
max_value_4.Update()
blob_image.DeepCopy(max_value_4.GetOutput())

sphere_5 = vtkSphere()
sphere_5.SetRadius(radius)
sphere_5.SetCenter(28, 19, -34)
sampler_5 = vtkSampleFunction()
sampler_5.SetImplicitFunction(sphere_5)
sampler_5.SetOutputScalarTypeToFloat()
sampler_5.SetSampleDimensions(51, 51, 51)
sampler_5.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_5 = vtkImageThreshold()
threshold_5.SetInputConnection(sampler_5.GetOutputPort())
threshold_5.ThresholdByLower(radius * radius)
threshold_5.ReplaceInOn()
threshold_5.ReplaceOutOn()
threshold_5.SetInValue(6)
threshold_5.SetOutValue(0)
threshold_5.Update()
max_value_5 = vtkImageMathematics()
max_value_5.SetInputData(0, blob_image)
max_value_5.SetInputData(1, threshold_5.GetOutput())
max_value_5.SetOperationToMax()
max_value_5.Modified()
max_value_5.Update()
blob_image.DeepCopy(max_value_5.GetOutput())

sphere_6 = vtkSphere()
sphere_6.SetRadius(radius)
sphere_6.SetCenter(-18, 22, 0)
sampler_6 = vtkSampleFunction()
sampler_6.SetImplicitFunction(sphere_6)
sampler_6.SetOutputScalarTypeToFloat()
sampler_6.SetSampleDimensions(51, 51, 51)
sampler_6.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_6 = vtkImageThreshold()
threshold_6.SetInputConnection(sampler_6.GetOutputPort())
threshold_6.ThresholdByLower(radius * radius)
threshold_6.ReplaceInOn()
threshold_6.ReplaceOutOn()
threshold_6.SetInValue(7)
threshold_6.SetOutValue(0)
threshold_6.Update()
max_value_6 = vtkImageMathematics()
max_value_6.SetInputData(0, blob_image)
max_value_6.SetInputData(1, threshold_6.GetOutput())
max_value_6.SetOperationToMax()
max_value_6.Modified()
max_value_6.Update()
blob_image.DeepCopy(max_value_6.GetOutput())

sphere_7 = vtkSphere()
sphere_7.SetRadius(radius)
sphere_7.SetCenter(17, 2, 38)
sampler_7 = vtkSampleFunction()
sampler_7.SetImplicitFunction(sphere_7)
sampler_7.SetOutputScalarTypeToFloat()
sampler_7.SetSampleDimensions(51, 51, 51)
sampler_7.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_7 = vtkImageThreshold()
threshold_7.SetInputConnection(sampler_7.GetOutputPort())
threshold_7.ThresholdByLower(radius * radius)
threshold_7.ReplaceInOn()
threshold_7.ReplaceOutOn()
threshold_7.SetInValue(8)
threshold_7.SetOutValue(0)
threshold_7.Update()
max_value_7 = vtkImageMathematics()
max_value_7.SetInputData(0, blob_image)
max_value_7.SetInputData(1, threshold_7.GetOutput())
max_value_7.SetOperationToMax()
max_value_7.Modified()
max_value_7.Update()
blob_image.DeepCopy(max_value_7.GetOutput())

sphere_8 = vtkSphere()
sphere_8.SetRadius(radius)
sphere_8.SetCenter(32, -38, 19)
sampler_8 = vtkSampleFunction()
sampler_8.SetImplicitFunction(sphere_8)
sampler_8.SetOutputScalarTypeToFloat()
sampler_8.SetSampleDimensions(51, 51, 51)
sampler_8.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_8 = vtkImageThreshold()
threshold_8.SetInputConnection(sampler_8.GetOutputPort())
threshold_8.ThresholdByLower(radius * radius)
threshold_8.ReplaceInOn()
threshold_8.ReplaceOutOn()
threshold_8.SetInValue(9)
threshold_8.SetOutValue(0)
threshold_8.Update()
max_value_8 = vtkImageMathematics()
max_value_8.SetInputData(0, blob_image)
max_value_8.SetInputData(1, threshold_8.GetOutput())
max_value_8.SetOperationToMax()
max_value_8.Modified()
max_value_8.Update()
blob_image.DeepCopy(max_value_8.GetOutput())

sphere_9 = vtkSphere()
sphere_9.SetRadius(radius)
sphere_9.SetCenter(-33, 32, -31)
sampler_9 = vtkSampleFunction()
sampler_9.SetImplicitFunction(sphere_9)
sampler_9.SetOutputScalarTypeToFloat()
sampler_9.SetSampleDimensions(51, 51, 51)
sampler_9.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_9 = vtkImageThreshold()
threshold_9.SetInputConnection(sampler_9.GetOutputPort())
threshold_9.ThresholdByLower(radius * radius)
threshold_9.ReplaceInOn()
threshold_9.ReplaceOutOn()
threshold_9.SetInValue(10)
threshold_9.SetOutValue(0)
threshold_9.Update()
max_value_9 = vtkImageMathematics()
max_value_9.SetInputData(0, blob_image)
max_value_9.SetInputData(1, threshold_9.GetOutput())
max_value_9.SetOperationToMax()
max_value_9.Modified()
max_value_9.Update()
blob_image.DeepCopy(max_value_9.GetOutput())

sphere_10 = vtkSphere()
sphere_10.SetRadius(radius)
sphere_10.SetCenter(28, -20, -10)
sampler_10 = vtkSampleFunction()
sampler_10.SetImplicitFunction(sphere_10)
sampler_10.SetOutputScalarTypeToFloat()
sampler_10.SetSampleDimensions(51, 51, 51)
sampler_10.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_10 = vtkImageThreshold()
threshold_10.SetInputConnection(sampler_10.GetOutputPort())
threshold_10.ThresholdByLower(radius * radius)
threshold_10.ReplaceInOn()
threshold_10.ReplaceOutOn()
threshold_10.SetInValue(11)
threshold_10.SetOutValue(0)
threshold_10.Update()
max_value_10 = vtkImageMathematics()
max_value_10.SetInputData(0, blob_image)
max_value_10.SetInputData(1, threshold_10.GetOutput())
max_value_10.SetOperationToMax()
max_value_10.Modified()
max_value_10.Update()
blob_image.DeepCopy(max_value_10.GetOutput())

sphere_11 = vtkSphere()
sphere_11.SetRadius(radius)
sphere_11.SetCenter(-27, -17, 13)
sampler_11 = vtkSampleFunction()
sampler_11.SetImplicitFunction(sphere_11)
sampler_11.SetOutputScalarTypeToFloat()
sampler_11.SetSampleDimensions(51, 51, 51)
sampler_11.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_11 = vtkImageThreshold()
threshold_11.SetInputConnection(sampler_11.GetOutputPort())
threshold_11.ThresholdByLower(radius * radius)
threshold_11.ReplaceInOn()
threshold_11.ReplaceOutOn()
threshold_11.SetInValue(12)
threshold_11.SetOutValue(0)
threshold_11.Update()
max_value_11 = vtkImageMathematics()
max_value_11.SetInputData(0, blob_image)
max_value_11.SetInputData(1, threshold_11.GetOutput())
max_value_11.SetOperationToMax()
max_value_11.Modified()
max_value_11.Update()
blob_image.DeepCopy(max_value_11.GetOutput())

sphere_12 = vtkSphere()
sphere_12.SetRadius(radius)
sphere_12.SetCenter(-23, 38, 0)
sampler_12 = vtkSampleFunction()
sampler_12.SetImplicitFunction(sphere_12)
sampler_12.SetOutputScalarTypeToFloat()
sampler_12.SetSampleDimensions(51, 51, 51)
sampler_12.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_12 = vtkImageThreshold()
threshold_12.SetInputConnection(sampler_12.GetOutputPort())
threshold_12.ThresholdByLower(radius * radius)
threshold_12.ReplaceInOn()
threshold_12.ReplaceOutOn()
threshold_12.SetInValue(13)
threshold_12.SetOutValue(0)
threshold_12.Update()
max_value_12 = vtkImageMathematics()
max_value_12.SetInputData(0, blob_image)
max_value_12.SetInputData(1, threshold_12.GetOutput())
max_value_12.SetOperationToMax()
max_value_12.Modified()
max_value_12.Update()
blob_image.DeepCopy(max_value_12.GetOutput())

sphere_13 = vtkSphere()
sphere_13.SetRadius(radius)
sphere_13.SetCenter(-30, 13, -32)
sampler_13 = vtkSampleFunction()
sampler_13.SetImplicitFunction(sphere_13)
sampler_13.SetOutputScalarTypeToFloat()
sampler_13.SetSampleDimensions(51, 51, 51)
sampler_13.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_13 = vtkImageThreshold()
threshold_13.SetInputConnection(sampler_13.GetOutputPort())
threshold_13.ThresholdByLower(radius * radius)
threshold_13.ReplaceInOn()
threshold_13.ReplaceOutOn()
threshold_13.SetInValue(14)
threshold_13.SetOutValue(0)
threshold_13.Update()
max_value_13 = vtkImageMathematics()
max_value_13.SetInputData(0, blob_image)
max_value_13.SetInputData(1, threshold_13.GetOutput())
max_value_13.SetOperationToMax()
max_value_13.Modified()
max_value_13.Update()
blob_image.DeepCopy(max_value_13.GetOutput())

sphere_14 = vtkSphere()
sphere_14.SetRadius(radius)
sphere_14.SetCenter(-38, -1, 33)
sampler_14 = vtkSampleFunction()
sampler_14.SetImplicitFunction(sphere_14)
sampler_14.SetOutputScalarTypeToFloat()
sampler_14.SetSampleDimensions(51, 51, 51)
sampler_14.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_14 = vtkImageThreshold()
threshold_14.SetInputConnection(sampler_14.GetOutputPort())
threshold_14.ThresholdByLower(radius * radius)
threshold_14.ReplaceInOn()
threshold_14.ReplaceOutOn()
threshold_14.SetInValue(15)
threshold_14.SetOutValue(0)
threshold_14.Update()
max_value_14 = vtkImageMathematics()
max_value_14.SetInputData(0, blob_image)
max_value_14.SetInputData(1, threshold_14.GetOutput())
max_value_14.SetOperationToMax()
max_value_14.Modified()
max_value_14.Update()
blob_image.DeepCopy(max_value_14.GetOutput())

sphere_15 = vtkSphere()
sphere_15.SetRadius(radius)
sphere_15.SetCenter(-3, -5, -23)
sampler_15 = vtkSampleFunction()
sampler_15.SetImplicitFunction(sphere_15)
sampler_15.SetOutputScalarTypeToFloat()
sampler_15.SetSampleDimensions(51, 51, 51)
sampler_15.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_15 = vtkImageThreshold()
threshold_15.SetInputConnection(sampler_15.GetOutputPort())
threshold_15.ThresholdByLower(radius * radius)
threshold_15.ReplaceInOn()
threshold_15.ReplaceOutOn()
threshold_15.SetInValue(16)
threshold_15.SetOutValue(0)
threshold_15.Update()
max_value_15 = vtkImageMathematics()
max_value_15.SetInputData(0, blob_image)
max_value_15.SetInputData(1, threshold_15.GetOutput())
max_value_15.SetOperationToMax()
max_value_15.Modified()
max_value_15.Update()
blob_image.DeepCopy(max_value_15.GetOutput())

sphere_16 = vtkSphere()
sphere_16.SetRadius(radius)
sphere_16.SetCenter(-8, 11, -21)
sampler_16 = vtkSampleFunction()
sampler_16.SetImplicitFunction(sphere_16)
sampler_16.SetOutputScalarTypeToFloat()
sampler_16.SetSampleDimensions(51, 51, 51)
sampler_16.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_16 = vtkImageThreshold()
threshold_16.SetInputConnection(sampler_16.GetOutputPort())
threshold_16.ThresholdByLower(radius * radius)
threshold_16.ReplaceInOn()
threshold_16.ReplaceOutOn()
threshold_16.SetInValue(17)
threshold_16.SetOutValue(0)
threshold_16.Update()
max_value_16 = vtkImageMathematics()
max_value_16.SetInputData(0, blob_image)
max_value_16.SetInputData(1, threshold_16.GetOutput())
max_value_16.SetOperationToMax()
max_value_16.Modified()
max_value_16.Update()
blob_image.DeepCopy(max_value_16.GetOutput())

sphere_17 = vtkSphere()
sphere_17.SetRadius(radius)
sphere_17.SetCenter(1, 38, 17)
sampler_17 = vtkSampleFunction()
sampler_17.SetImplicitFunction(sphere_17)
sampler_17.SetOutputScalarTypeToFloat()
sampler_17.SetSampleDimensions(51, 51, 51)
sampler_17.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_17 = vtkImageThreshold()
threshold_17.SetInputConnection(sampler_17.GetOutputPort())
threshold_17.ThresholdByLower(radius * radius)
threshold_17.ReplaceInOn()
threshold_17.ReplaceOutOn()
threshold_17.SetInValue(18)
threshold_17.SetOutValue(0)
threshold_17.Update()
max_value_17 = vtkImageMathematics()
max_value_17.SetInputData(0, blob_image)
max_value_17.SetInputData(1, threshold_17.GetOutput())
max_value_17.SetOperationToMax()
max_value_17.Modified()
max_value_17.Update()
blob_image.DeepCopy(max_value_17.GetOutput())

sphere_18 = vtkSphere()
sphere_18.SetRadius(radius)
sphere_18.SetCenter(-6, 11, 6)
sampler_18 = vtkSampleFunction()
sampler_18.SetImplicitFunction(sphere_18)
sampler_18.SetOutputScalarTypeToFloat()
sampler_18.SetSampleDimensions(51, 51, 51)
sampler_18.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_18 = vtkImageThreshold()
threshold_18.SetInputConnection(sampler_18.GetOutputPort())
threshold_18.ThresholdByLower(radius * radius)
threshold_18.ReplaceInOn()
threshold_18.ReplaceOutOn()
threshold_18.SetInValue(19)
threshold_18.SetOutValue(0)
threshold_18.Update()
max_value_18 = vtkImageMathematics()
max_value_18.SetInputData(0, blob_image)
max_value_18.SetInputData(1, threshold_18.GetOutput())
max_value_18.SetOperationToMax()
max_value_18.Modified()
max_value_18.Update()
blob_image.DeepCopy(max_value_18.GetOutput())

sphere_19 = vtkSphere()
sphere_19.SetRadius(radius)
sphere_19.SetCenter(5, 39, -10)
sampler_19 = vtkSampleFunction()
sampler_19.SetImplicitFunction(sphere_19)
sampler_19.SetOutputScalarTypeToFloat()
sampler_19.SetSampleDimensions(51, 51, 51)
sampler_19.SetModelBounds(-50, 50, -50, 50, -50, 50)
threshold_19 = vtkImageThreshold()
threshold_19.SetInputConnection(sampler_19.GetOutputPort())
threshold_19.ThresholdByLower(radius * radius)
threshold_19.ReplaceInOn()
threshold_19.ReplaceOutOn()
threshold_19.SetInValue(20)
threshold_19.SetOutValue(0)
threshold_19.Update()
max_value_19 = vtkImageMathematics()
max_value_19.SetInputData(0, blob_image)
max_value_19.SetInputData(1, threshold_19.GetOutput())
max_value_19.SetOperationToMax()
max_value_19.Modified()
max_value_19.Update()
blob_image.DeepCopy(max_value_19.GetOutput())

# Apply orientation (rotation about Y axis)
angle = pi / 6
orientation = [
    -cos(angle), 0, sin(angle),
    0, 1, 0,
    sin(angle), 0, cos(angle),
]
blob_image.SetDirectionMatrix(orientation)

# Outline around the oriented image
outline = vtkImageDataOutlineFilter()
outline.SetInputData(blob_image)
outline.GenerateFacesOn()

outline_mapper = vtkPolyDataMapper()
outline_mapper.SetInputConnection(outline.GetOutputPort())

outline_actor = vtkActor()
outline_actor.SetMapper(outline_mapper)
outline_actor.GetProperty().SetOpacity(0.25)

# Cut the oriented volume with a plane
plane = vtkPlane()
plane.SetOrigin(1, 1, 1)
plane.SetNormal(1, 1, 1)

cutter = vtkFlyingEdgesPlaneCutter()
cutter.SetInputData(blob_image)
cutter.SetPlane(plane)

cutter_mapper = vtkPolyDataMapper()
cutter_mapper.SetInputConnection(cutter.GetOutputPort())

cutter_actor = vtkActor()
cutter_actor.SetMapper(cutter_mapper)

# Renderer
renderer = vtkRenderer()
renderer.AddActor(outline_actor)
renderer.AddActor(cutter_actor)

# Window
render_window = vtkRenderWindow()
render_window.AddRenderer(renderer)
render_window.SetSize(300, 300)
render_window.SetWindowName("oriented flying edges plane cutter")

# Scene
renderer.ResetCamera()

# Interactor
interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)

interactor.Initialize()
interactor.Start()
