#!/usr/bin/env python

# Test vtkPolyDataMapper with all polygon types and various data array combinations.

import os

import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingFreeType  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401

from vtkmodules.vtkCommonCore import (
    vtkFloatArray,
    vtkLookupTable,
    vtkPoints,
)
from vtkmodules.vtkCommonDataModel import (
    vtkTriangleStrip,
    vtkUnstructuredGrid,
)
from vtkmodules.vtkFiltersCore import vtkTriangleFilter
from vtkmodules.vtkFiltersGeometry import vtkGeometryFilter
from vtkmodules.vtkIOImage import vtkBMPReader
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkPolyDataMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
    vtkTexture,
)

# Texture
bmp_reader = vtkBMPReader()
data_dir = os.environ.get("VPE_DATA_DIR", os.path.dirname(os.path.abspath(__file__)))

bmp_reader.SetFileName(os.path.join(data_dir, "masonry.bmp"))

texture = vtkTexture()
texture.SetInputConnection(bmp_reader.GetOutputPort())

# Triangle strip points
triangle_strip_points = vtkPoints()
triangle_strip_points.SetNumberOfPoints(5)
triangle_strip_points.InsertPoint(0, 0, 1, 0)
triangle_strip_points.InsertPoint(1, 0, 0, 0.5)
triangle_strip_points.InsertPoint(2, 1, 1, 0.3)
triangle_strip_points.InsertPoint(3, 1, 0, 0.6)
triangle_strip_points.InsertPoint(4, 2, 1, 0.1)

# Texture coordinates
triangle_strip_tcoords = vtkFloatArray()
triangle_strip_tcoords.SetNumberOfComponents(2)
triangle_strip_tcoords.SetNumberOfTuples(5)
triangle_strip_tcoords.InsertTuple2(0, 0, 1)
triangle_strip_tcoords.InsertTuple2(1, 0, 0)
triangle_strip_tcoords.InsertTuple2(2, 0.5, 1)
triangle_strip_tcoords.InsertTuple2(3, 0.5, 0)
triangle_strip_tcoords.InsertTuple2(4, 1, 1)

# Point scalars
triangle_strip_point_scalars = vtkFloatArray()
triangle_strip_point_scalars.SetNumberOfTuples(5)
triangle_strip_point_scalars.InsertValue(0, 1)
triangle_strip_point_scalars.InsertValue(1, 0)
triangle_strip_point_scalars.InsertValue(2, 0)
triangle_strip_point_scalars.InsertValue(3, 0)
triangle_strip_point_scalars.InsertValue(4, 0)

# Cell scalars
triangle_strip_cell_scalars = vtkFloatArray()
triangle_strip_cell_scalars.SetNumberOfTuples(1)
triangle_strip_cell_scalars.InsertValue(0, 1)

# Point normals
triangle_strip_point_normals = vtkFloatArray()
triangle_strip_point_normals.SetNumberOfComponents(3)
triangle_strip_point_normals.SetNumberOfTuples(5)
triangle_strip_point_normals.InsertTuple3(0, 0, 0, 1)
triangle_strip_point_normals.InsertTuple3(1, 0, 1, 0)
triangle_strip_point_normals.InsertTuple3(2, 0, 1, 1)
triangle_strip_point_normals.InsertTuple3(3, 1, 0, 0)
triangle_strip_point_normals.InsertTuple3(4, 1, 0, 1)

# Cell normals
triangle_strip_cell_normals = vtkFloatArray()
triangle_strip_cell_normals.SetNumberOfComponents(3)
triangle_strip_cell_normals.SetNumberOfTuples(1)
triangle_strip_cell_normals.InsertTuple3(0, 0, 0, 1)

# Triangle strip cell
a_triangle_strip = vtkTriangleStrip()
a_triangle_strip.GetPointIds().SetNumberOfIds(5)
a_triangle_strip.GetPointIds().SetId(0, 0)
a_triangle_strip.GetPointIds().SetId(1, 1)
a_triangle_strip.GetPointIds().SetId(2, 2)
a_triangle_strip.GetPointIds().SetId(3, 3)
a_triangle_strip.GetPointIds().SetId(4, 4)

# Lookup table
lut = vtkLookupTable()
lut.SetNumberOfColors(5)
lut.SetTableValue(0, 0, 0, 1, 1)
lut.SetTableValue(1, 0, 1, 0, 1)
lut.SetTableValue(2, 0, 1, 1, 1)
lut.SetTableValue(3, 1, 0, 0, 1)
lut.SetTableValue(4, 1, 0, 1, 1)

# Strip type, mask=0, position=(0, 0)
grid_0 = vtkUnstructuredGrid()
grid_0.Allocate(1, 1)
grid_0.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_0.SetPoints(triangle_strip_points)
geometry_0 = vtkGeometryFilter()
geometry_0.SetInputData(grid_0)
tri_filter_0 = vtkTriangleFilter()
tri_filter_0.SetInputConnection(geometry_0.GetOutputPort())
mapper_0 = vtkPolyDataMapper()
mapper_0.SetInputConnection(geometry_0.GetOutputPort())
mapper_0.SetLookupTable(lut)
mapper_0.SetScalarRange(0, 4)
actor_0 = vtkActor()
actor_0.SetMapper(mapper_0)
actor_0.AddPosition(0, 0, 0)

# Strip type, mask=1, position=(2, 0)
grid_1 = vtkUnstructuredGrid()
grid_1.Allocate(1, 1)
grid_1.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_1.SetPoints(triangle_strip_points)
geometry_1 = vtkGeometryFilter()
geometry_1.SetInputData(grid_1)
tri_filter_1 = vtkTriangleFilter()
tri_filter_1.SetInputConnection(geometry_1.GetOutputPort())
mapper_1 = vtkPolyDataMapper()
mapper_1.SetInputConnection(geometry_1.GetOutputPort())
mapper_1.SetLookupTable(lut)
mapper_1.SetScalarRange(0, 4)
actor_1 = vtkActor()
actor_1.SetMapper(mapper_1)
grid_1.GetPointData().SetNormals(triangle_strip_point_normals)
actor_1.AddPosition(2, 0, 0)

# Strip type, mask=2, position=(4, 0)
grid_2 = vtkUnstructuredGrid()
grid_2.Allocate(1, 1)
grid_2.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_2.SetPoints(triangle_strip_points)
geometry_2 = vtkGeometryFilter()
geometry_2.SetInputData(grid_2)
tri_filter_2 = vtkTriangleFilter()
tri_filter_2.SetInputConnection(geometry_2.GetOutputPort())
mapper_2 = vtkPolyDataMapper()
mapper_2.SetInputConnection(geometry_2.GetOutputPort())
mapper_2.SetLookupTable(lut)
mapper_2.SetScalarRange(0, 4)
actor_2 = vtkActor()
actor_2.SetMapper(mapper_2)
grid_2.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_2.SetScalarModeToUsePointData()
actor_2.AddPosition(4, 0, 0)

# Strip type, mask=3, position=(6, 0)
grid_3 = vtkUnstructuredGrid()
grid_3.Allocate(1, 1)
grid_3.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_3.SetPoints(triangle_strip_points)
geometry_3 = vtkGeometryFilter()
geometry_3.SetInputData(grid_3)
tri_filter_3 = vtkTriangleFilter()
tri_filter_3.SetInputConnection(geometry_3.GetOutputPort())
mapper_3 = vtkPolyDataMapper()
mapper_3.SetInputConnection(geometry_3.GetOutputPort())
mapper_3.SetLookupTable(lut)
mapper_3.SetScalarRange(0, 4)
actor_3 = vtkActor()
actor_3.SetMapper(mapper_3)
grid_3.GetPointData().SetNormals(triangle_strip_point_normals)
grid_3.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_3.SetScalarModeToUsePointData()
actor_3.AddPosition(6, 0, 0)

# Strip type, mask=4, position=(8, 0)
grid_4 = vtkUnstructuredGrid()
grid_4.Allocate(1, 1)
grid_4.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_4.SetPoints(triangle_strip_points)
geometry_4 = vtkGeometryFilter()
geometry_4.SetInputData(grid_4)
tri_filter_4 = vtkTriangleFilter()
tri_filter_4.SetInputConnection(geometry_4.GetOutputPort())
mapper_4 = vtkPolyDataMapper()
mapper_4.SetInputConnection(geometry_4.GetOutputPort())
mapper_4.SetLookupTable(lut)
mapper_4.SetScalarRange(0, 4)
actor_4 = vtkActor()
actor_4.SetMapper(mapper_4)
grid_4.GetPointData().SetTCoords(triangle_strip_tcoords)
actor_4.SetTexture(texture)
actor_4.AddPosition(8, 0, 0)

# Strip type, mask=5, position=(10, 0)
grid_5 = vtkUnstructuredGrid()
grid_5.Allocate(1, 1)
grid_5.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_5.SetPoints(triangle_strip_points)
geometry_5 = vtkGeometryFilter()
geometry_5.SetInputData(grid_5)
tri_filter_5 = vtkTriangleFilter()
tri_filter_5.SetInputConnection(geometry_5.GetOutputPort())
mapper_5 = vtkPolyDataMapper()
mapper_5.SetInputConnection(geometry_5.GetOutputPort())
mapper_5.SetLookupTable(lut)
mapper_5.SetScalarRange(0, 4)
actor_5 = vtkActor()
actor_5.SetMapper(mapper_5)
grid_5.GetPointData().SetNormals(triangle_strip_point_normals)
grid_5.GetPointData().SetTCoords(triangle_strip_tcoords)
actor_5.SetTexture(texture)
actor_5.AddPosition(10, 0, 0)

# Strip type, mask=6, position=(0, 2)
grid_6 = vtkUnstructuredGrid()
grid_6.Allocate(1, 1)
grid_6.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_6.SetPoints(triangle_strip_points)
geometry_6 = vtkGeometryFilter()
geometry_6.SetInputData(grid_6)
tri_filter_6 = vtkTriangleFilter()
tri_filter_6.SetInputConnection(geometry_6.GetOutputPort())
mapper_6 = vtkPolyDataMapper()
mapper_6.SetInputConnection(geometry_6.GetOutputPort())
mapper_6.SetLookupTable(lut)
mapper_6.SetScalarRange(0, 4)
actor_6 = vtkActor()
actor_6.SetMapper(mapper_6)
grid_6.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_6.SetScalarModeToUsePointData()
grid_6.GetPointData().SetTCoords(triangle_strip_tcoords)
actor_6.SetTexture(texture)
actor_6.AddPosition(0, 2, 0)

# Strip type, mask=7, position=(2, 2)
grid_7 = vtkUnstructuredGrid()
grid_7.Allocate(1, 1)
grid_7.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_7.SetPoints(triangle_strip_points)
geometry_7 = vtkGeometryFilter()
geometry_7.SetInputData(grid_7)
tri_filter_7 = vtkTriangleFilter()
tri_filter_7.SetInputConnection(geometry_7.GetOutputPort())
mapper_7 = vtkPolyDataMapper()
mapper_7.SetInputConnection(geometry_7.GetOutputPort())
mapper_7.SetLookupTable(lut)
mapper_7.SetScalarRange(0, 4)
actor_7 = vtkActor()
actor_7.SetMapper(mapper_7)
grid_7.GetPointData().SetNormals(triangle_strip_point_normals)
grid_7.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_7.SetScalarModeToUsePointData()
grid_7.GetPointData().SetTCoords(triangle_strip_tcoords)
actor_7.SetTexture(texture)
actor_7.AddPosition(2, 2, 0)

# Strip type, mask=10, position=(4, 2)
grid_8 = vtkUnstructuredGrid()
grid_8.Allocate(1, 1)
grid_8.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_8.SetPoints(triangle_strip_points)
geometry_8 = vtkGeometryFilter()
geometry_8.SetInputData(grid_8)
tri_filter_8 = vtkTriangleFilter()
tri_filter_8.SetInputConnection(geometry_8.GetOutputPort())
mapper_8 = vtkPolyDataMapper()
mapper_8.SetInputConnection(geometry_8.GetOutputPort())
mapper_8.SetLookupTable(lut)
mapper_8.SetScalarRange(0, 4)
actor_8 = vtkActor()
actor_8.SetMapper(mapper_8)
grid_8.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_8.SetScalarModeToUsePointData()
grid_8.GetCellData().SetScalars(triangle_strip_cell_scalars)
mapper_8.SetScalarModeToUseCellData()
actor_8.AddPosition(4, 2, 0)

# Strip type, mask=11, position=(6, 2)
grid_9 = vtkUnstructuredGrid()
grid_9.Allocate(1, 1)
grid_9.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_9.SetPoints(triangle_strip_points)
geometry_9 = vtkGeometryFilter()
geometry_9.SetInputData(grid_9)
tri_filter_9 = vtkTriangleFilter()
tri_filter_9.SetInputConnection(geometry_9.GetOutputPort())
mapper_9 = vtkPolyDataMapper()
mapper_9.SetInputConnection(geometry_9.GetOutputPort())
mapper_9.SetLookupTable(lut)
mapper_9.SetScalarRange(0, 4)
actor_9 = vtkActor()
actor_9.SetMapper(mapper_9)
grid_9.GetPointData().SetNormals(triangle_strip_point_normals)
grid_9.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_9.SetScalarModeToUsePointData()
grid_9.GetCellData().SetScalars(triangle_strip_cell_scalars)
mapper_9.SetScalarModeToUseCellData()
actor_9.AddPosition(6, 2, 0)

# Strip type, mask=14, position=(8, 2)
grid_10 = vtkUnstructuredGrid()
grid_10.Allocate(1, 1)
grid_10.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_10.SetPoints(triangle_strip_points)
geometry_10 = vtkGeometryFilter()
geometry_10.SetInputData(grid_10)
tri_filter_10 = vtkTriangleFilter()
tri_filter_10.SetInputConnection(geometry_10.GetOutputPort())
mapper_10 = vtkPolyDataMapper()
mapper_10.SetInputConnection(geometry_10.GetOutputPort())
mapper_10.SetLookupTable(lut)
mapper_10.SetScalarRange(0, 4)
actor_10 = vtkActor()
actor_10.SetMapper(mapper_10)
grid_10.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_10.SetScalarModeToUsePointData()
grid_10.GetPointData().SetTCoords(triangle_strip_tcoords)
actor_10.SetTexture(texture)
grid_10.GetCellData().SetScalars(triangle_strip_cell_scalars)
mapper_10.SetScalarModeToUseCellData()
actor_10.AddPosition(8, 2, 0)

# Strip type, mask=15, position=(10, 2)
grid_11 = vtkUnstructuredGrid()
grid_11.Allocate(1, 1)
grid_11.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_11.SetPoints(triangle_strip_points)
geometry_11 = vtkGeometryFilter()
geometry_11.SetInputData(grid_11)
tri_filter_11 = vtkTriangleFilter()
tri_filter_11.SetInputConnection(geometry_11.GetOutputPort())
mapper_11 = vtkPolyDataMapper()
mapper_11.SetInputConnection(geometry_11.GetOutputPort())
mapper_11.SetLookupTable(lut)
mapper_11.SetScalarRange(0, 4)
actor_11 = vtkActor()
actor_11.SetMapper(mapper_11)
grid_11.GetPointData().SetNormals(triangle_strip_point_normals)
grid_11.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_11.SetScalarModeToUsePointData()
grid_11.GetPointData().SetTCoords(triangle_strip_tcoords)
actor_11.SetTexture(texture)
grid_11.GetCellData().SetScalars(triangle_strip_cell_scalars)
mapper_11.SetScalarModeToUseCellData()
actor_11.AddPosition(10, 2, 0)

# Strip type, mask=16, position=(0, 4)
grid_12 = vtkUnstructuredGrid()
grid_12.Allocate(1, 1)
grid_12.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_12.SetPoints(triangle_strip_points)
geometry_12 = vtkGeometryFilter()
geometry_12.SetInputData(grid_12)
tri_filter_12 = vtkTriangleFilter()
tri_filter_12.SetInputConnection(geometry_12.GetOutputPort())
mapper_12 = vtkPolyDataMapper()
mapper_12.SetInputConnection(geometry_12.GetOutputPort())
mapper_12.SetLookupTable(lut)
mapper_12.SetScalarRange(0, 4)
actor_12 = vtkActor()
actor_12.SetMapper(mapper_12)
grid_12.GetCellData().SetNormals(triangle_strip_cell_normals)
actor_12.AddPosition(0, 4, 0)

# Strip type, mask=18, position=(2, 4)
grid_13 = vtkUnstructuredGrid()
grid_13.Allocate(1, 1)
grid_13.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_13.SetPoints(triangle_strip_points)
geometry_13 = vtkGeometryFilter()
geometry_13.SetInputData(grid_13)
tri_filter_13 = vtkTriangleFilter()
tri_filter_13.SetInputConnection(geometry_13.GetOutputPort())
mapper_13 = vtkPolyDataMapper()
mapper_13.SetInputConnection(geometry_13.GetOutputPort())
mapper_13.SetLookupTable(lut)
mapper_13.SetScalarRange(0, 4)
actor_13 = vtkActor()
actor_13.SetMapper(mapper_13)
grid_13.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_13.SetScalarModeToUsePointData()
grid_13.GetCellData().SetNormals(triangle_strip_cell_normals)
actor_13.AddPosition(2, 4, 0)

# Strip type, mask=20, position=(4, 4)
grid_14 = vtkUnstructuredGrid()
grid_14.Allocate(1, 1)
grid_14.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_14.SetPoints(triangle_strip_points)
geometry_14 = vtkGeometryFilter()
geometry_14.SetInputData(grid_14)
tri_filter_14 = vtkTriangleFilter()
tri_filter_14.SetInputConnection(geometry_14.GetOutputPort())
mapper_14 = vtkPolyDataMapper()
mapper_14.SetInputConnection(geometry_14.GetOutputPort())
mapper_14.SetLookupTable(lut)
mapper_14.SetScalarRange(0, 4)
actor_14 = vtkActor()
actor_14.SetMapper(mapper_14)
grid_14.GetPointData().SetTCoords(triangle_strip_tcoords)
actor_14.SetTexture(texture)
grid_14.GetCellData().SetNormals(triangle_strip_cell_normals)
actor_14.AddPosition(4, 4, 0)

# Strip type, mask=22, position=(6, 4)
grid_15 = vtkUnstructuredGrid()
grid_15.Allocate(1, 1)
grid_15.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_15.SetPoints(triangle_strip_points)
geometry_15 = vtkGeometryFilter()
geometry_15.SetInputData(grid_15)
tri_filter_15 = vtkTriangleFilter()
tri_filter_15.SetInputConnection(geometry_15.GetOutputPort())
mapper_15 = vtkPolyDataMapper()
mapper_15.SetInputConnection(geometry_15.GetOutputPort())
mapper_15.SetLookupTable(lut)
mapper_15.SetScalarRange(0, 4)
actor_15 = vtkActor()
actor_15.SetMapper(mapper_15)
grid_15.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_15.SetScalarModeToUsePointData()
grid_15.GetPointData().SetTCoords(triangle_strip_tcoords)
actor_15.SetTexture(texture)
grid_15.GetCellData().SetNormals(triangle_strip_cell_normals)
actor_15.AddPosition(6, 4, 0)

# Strip type, mask=26, position=(8, 4)
grid_16 = vtkUnstructuredGrid()
grid_16.Allocate(1, 1)
grid_16.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_16.SetPoints(triangle_strip_points)
geometry_16 = vtkGeometryFilter()
geometry_16.SetInputData(grid_16)
tri_filter_16 = vtkTriangleFilter()
tri_filter_16.SetInputConnection(geometry_16.GetOutputPort())
mapper_16 = vtkPolyDataMapper()
mapper_16.SetInputConnection(geometry_16.GetOutputPort())
mapper_16.SetLookupTable(lut)
mapper_16.SetScalarRange(0, 4)
actor_16 = vtkActor()
actor_16.SetMapper(mapper_16)
grid_16.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_16.SetScalarModeToUsePointData()
grid_16.GetCellData().SetScalars(triangle_strip_cell_scalars)
mapper_16.SetScalarModeToUseCellData()
grid_16.GetCellData().SetNormals(triangle_strip_cell_normals)
actor_16.AddPosition(8, 4, 0)

# Strip type, mask=30, position=(10, 4)
grid_17 = vtkUnstructuredGrid()
grid_17.Allocate(1, 1)
grid_17.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_17.SetPoints(triangle_strip_points)
geometry_17 = vtkGeometryFilter()
geometry_17.SetInputData(grid_17)
tri_filter_17 = vtkTriangleFilter()
tri_filter_17.SetInputConnection(geometry_17.GetOutputPort())
mapper_17 = vtkPolyDataMapper()
mapper_17.SetInputConnection(geometry_17.GetOutputPort())
mapper_17.SetLookupTable(lut)
mapper_17.SetScalarRange(0, 4)
actor_17 = vtkActor()
actor_17.SetMapper(mapper_17)
grid_17.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_17.SetScalarModeToUsePointData()
grid_17.GetPointData().SetTCoords(triangle_strip_tcoords)
actor_17.SetTexture(texture)
grid_17.GetCellData().SetScalars(triangle_strip_cell_scalars)
mapper_17.SetScalarModeToUseCellData()
grid_17.GetCellData().SetNormals(triangle_strip_cell_normals)
actor_17.AddPosition(10, 4, 0)

# Triangle type, mask=0, position=(0, 6)
grid_18 = vtkUnstructuredGrid()
grid_18.Allocate(1, 1)
grid_18.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_18.SetPoints(triangle_strip_points)
geometry_18 = vtkGeometryFilter()
geometry_18.SetInputData(grid_18)
tri_filter_18 = vtkTriangleFilter()
tri_filter_18.SetInputConnection(geometry_18.GetOutputPort())
mapper_18 = vtkPolyDataMapper()
mapper_18.SetInputConnection(tri_filter_18.GetOutputPort())
mapper_18.SetLookupTable(lut)
mapper_18.SetScalarRange(0, 4)
actor_18 = vtkActor()
actor_18.SetMapper(mapper_18)
actor_18.AddPosition(0, 6, 0)

# Triangle type, mask=1, position=(2, 6)
grid_19 = vtkUnstructuredGrid()
grid_19.Allocate(1, 1)
grid_19.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_19.SetPoints(triangle_strip_points)
geometry_19 = vtkGeometryFilter()
geometry_19.SetInputData(grid_19)
tri_filter_19 = vtkTriangleFilter()
tri_filter_19.SetInputConnection(geometry_19.GetOutputPort())
mapper_19 = vtkPolyDataMapper()
mapper_19.SetInputConnection(tri_filter_19.GetOutputPort())
mapper_19.SetLookupTable(lut)
mapper_19.SetScalarRange(0, 4)
actor_19 = vtkActor()
actor_19.SetMapper(mapper_19)
grid_19.GetPointData().SetNormals(triangle_strip_point_normals)
actor_19.AddPosition(2, 6, 0)

# Triangle type, mask=2, position=(4, 6)
grid_20 = vtkUnstructuredGrid()
grid_20.Allocate(1, 1)
grid_20.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_20.SetPoints(triangle_strip_points)
geometry_20 = vtkGeometryFilter()
geometry_20.SetInputData(grid_20)
tri_filter_20 = vtkTriangleFilter()
tri_filter_20.SetInputConnection(geometry_20.GetOutputPort())
mapper_20 = vtkPolyDataMapper()
mapper_20.SetInputConnection(tri_filter_20.GetOutputPort())
mapper_20.SetLookupTable(lut)
mapper_20.SetScalarRange(0, 4)
actor_20 = vtkActor()
actor_20.SetMapper(mapper_20)
grid_20.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_20.SetScalarModeToUsePointData()
actor_20.AddPosition(4, 6, 0)

# Triangle type, mask=3, position=(6, 6)
grid_21 = vtkUnstructuredGrid()
grid_21.Allocate(1, 1)
grid_21.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_21.SetPoints(triangle_strip_points)
geometry_21 = vtkGeometryFilter()
geometry_21.SetInputData(grid_21)
tri_filter_21 = vtkTriangleFilter()
tri_filter_21.SetInputConnection(geometry_21.GetOutputPort())
mapper_21 = vtkPolyDataMapper()
mapper_21.SetInputConnection(tri_filter_21.GetOutputPort())
mapper_21.SetLookupTable(lut)
mapper_21.SetScalarRange(0, 4)
actor_21 = vtkActor()
actor_21.SetMapper(mapper_21)
grid_21.GetPointData().SetNormals(triangle_strip_point_normals)
grid_21.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_21.SetScalarModeToUsePointData()
actor_21.AddPosition(6, 6, 0)

# Triangle type, mask=4, position=(8, 6)
grid_22 = vtkUnstructuredGrid()
grid_22.Allocate(1, 1)
grid_22.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_22.SetPoints(triangle_strip_points)
geometry_22 = vtkGeometryFilter()
geometry_22.SetInputData(grid_22)
tri_filter_22 = vtkTriangleFilter()
tri_filter_22.SetInputConnection(geometry_22.GetOutputPort())
mapper_22 = vtkPolyDataMapper()
mapper_22.SetInputConnection(tri_filter_22.GetOutputPort())
mapper_22.SetLookupTable(lut)
mapper_22.SetScalarRange(0, 4)
actor_22 = vtkActor()
actor_22.SetMapper(mapper_22)
grid_22.GetPointData().SetTCoords(triangle_strip_tcoords)
actor_22.SetTexture(texture)
actor_22.AddPosition(8, 6, 0)

# Triangle type, mask=5, position=(10, 6)
grid_23 = vtkUnstructuredGrid()
grid_23.Allocate(1, 1)
grid_23.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_23.SetPoints(triangle_strip_points)
geometry_23 = vtkGeometryFilter()
geometry_23.SetInputData(grid_23)
tri_filter_23 = vtkTriangleFilter()
tri_filter_23.SetInputConnection(geometry_23.GetOutputPort())
mapper_23 = vtkPolyDataMapper()
mapper_23.SetInputConnection(tri_filter_23.GetOutputPort())
mapper_23.SetLookupTable(lut)
mapper_23.SetScalarRange(0, 4)
actor_23 = vtkActor()
actor_23.SetMapper(mapper_23)
grid_23.GetPointData().SetNormals(triangle_strip_point_normals)
grid_23.GetPointData().SetTCoords(triangle_strip_tcoords)
actor_23.SetTexture(texture)
actor_23.AddPosition(10, 6, 0)

# Triangle type, mask=6, position=(0, 8)
grid_24 = vtkUnstructuredGrid()
grid_24.Allocate(1, 1)
grid_24.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_24.SetPoints(triangle_strip_points)
geometry_24 = vtkGeometryFilter()
geometry_24.SetInputData(grid_24)
tri_filter_24 = vtkTriangleFilter()
tri_filter_24.SetInputConnection(geometry_24.GetOutputPort())
mapper_24 = vtkPolyDataMapper()
mapper_24.SetInputConnection(tri_filter_24.GetOutputPort())
mapper_24.SetLookupTable(lut)
mapper_24.SetScalarRange(0, 4)
actor_24 = vtkActor()
actor_24.SetMapper(mapper_24)
grid_24.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_24.SetScalarModeToUsePointData()
grid_24.GetPointData().SetTCoords(triangle_strip_tcoords)
actor_24.SetTexture(texture)
actor_24.AddPosition(0, 8, 0)

# Triangle type, mask=7, position=(2, 8)
grid_25 = vtkUnstructuredGrid()
grid_25.Allocate(1, 1)
grid_25.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_25.SetPoints(triangle_strip_points)
geometry_25 = vtkGeometryFilter()
geometry_25.SetInputData(grid_25)
tri_filter_25 = vtkTriangleFilter()
tri_filter_25.SetInputConnection(geometry_25.GetOutputPort())
mapper_25 = vtkPolyDataMapper()
mapper_25.SetInputConnection(tri_filter_25.GetOutputPort())
mapper_25.SetLookupTable(lut)
mapper_25.SetScalarRange(0, 4)
actor_25 = vtkActor()
actor_25.SetMapper(mapper_25)
grid_25.GetPointData().SetNormals(triangle_strip_point_normals)
grid_25.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_25.SetScalarModeToUsePointData()
grid_25.GetPointData().SetTCoords(triangle_strip_tcoords)
actor_25.SetTexture(texture)
actor_25.AddPosition(2, 8, 0)

# Triangle type, mask=10, position=(4, 8)
grid_26 = vtkUnstructuredGrid()
grid_26.Allocate(1, 1)
grid_26.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_26.SetPoints(triangle_strip_points)
geometry_26 = vtkGeometryFilter()
geometry_26.SetInputData(grid_26)
tri_filter_26 = vtkTriangleFilter()
tri_filter_26.SetInputConnection(geometry_26.GetOutputPort())
mapper_26 = vtkPolyDataMapper()
mapper_26.SetInputConnection(tri_filter_26.GetOutputPort())
mapper_26.SetLookupTable(lut)
mapper_26.SetScalarRange(0, 4)
actor_26 = vtkActor()
actor_26.SetMapper(mapper_26)
grid_26.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_26.SetScalarModeToUsePointData()
grid_26.GetCellData().SetScalars(triangle_strip_cell_scalars)
mapper_26.SetScalarModeToUseCellData()
actor_26.AddPosition(4, 8, 0)

# Triangle type, mask=11, position=(6, 8)
grid_27 = vtkUnstructuredGrid()
grid_27.Allocate(1, 1)
grid_27.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_27.SetPoints(triangle_strip_points)
geometry_27 = vtkGeometryFilter()
geometry_27.SetInputData(grid_27)
tri_filter_27 = vtkTriangleFilter()
tri_filter_27.SetInputConnection(geometry_27.GetOutputPort())
mapper_27 = vtkPolyDataMapper()
mapper_27.SetInputConnection(tri_filter_27.GetOutputPort())
mapper_27.SetLookupTable(lut)
mapper_27.SetScalarRange(0, 4)
actor_27 = vtkActor()
actor_27.SetMapper(mapper_27)
grid_27.GetPointData().SetNormals(triangle_strip_point_normals)
grid_27.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_27.SetScalarModeToUsePointData()
grid_27.GetCellData().SetScalars(triangle_strip_cell_scalars)
mapper_27.SetScalarModeToUseCellData()
actor_27.AddPosition(6, 8, 0)

# Triangle type, mask=14, position=(8, 8)
grid_28 = vtkUnstructuredGrid()
grid_28.Allocate(1, 1)
grid_28.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_28.SetPoints(triangle_strip_points)
geometry_28 = vtkGeometryFilter()
geometry_28.SetInputData(grid_28)
tri_filter_28 = vtkTriangleFilter()
tri_filter_28.SetInputConnection(geometry_28.GetOutputPort())
mapper_28 = vtkPolyDataMapper()
mapper_28.SetInputConnection(tri_filter_28.GetOutputPort())
mapper_28.SetLookupTable(lut)
mapper_28.SetScalarRange(0, 4)
actor_28 = vtkActor()
actor_28.SetMapper(mapper_28)
grid_28.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_28.SetScalarModeToUsePointData()
grid_28.GetPointData().SetTCoords(triangle_strip_tcoords)
actor_28.SetTexture(texture)
grid_28.GetCellData().SetScalars(triangle_strip_cell_scalars)
mapper_28.SetScalarModeToUseCellData()
actor_28.AddPosition(8, 8, 0)

# Triangle type, mask=15, position=(10, 8)
grid_29 = vtkUnstructuredGrid()
grid_29.Allocate(1, 1)
grid_29.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_29.SetPoints(triangle_strip_points)
geometry_29 = vtkGeometryFilter()
geometry_29.SetInputData(grid_29)
tri_filter_29 = vtkTriangleFilter()
tri_filter_29.SetInputConnection(geometry_29.GetOutputPort())
mapper_29 = vtkPolyDataMapper()
mapper_29.SetInputConnection(tri_filter_29.GetOutputPort())
mapper_29.SetLookupTable(lut)
mapper_29.SetScalarRange(0, 4)
actor_29 = vtkActor()
actor_29.SetMapper(mapper_29)
grid_29.GetPointData().SetNormals(triangle_strip_point_normals)
grid_29.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_29.SetScalarModeToUsePointData()
grid_29.GetPointData().SetTCoords(triangle_strip_tcoords)
actor_29.SetTexture(texture)
grid_29.GetCellData().SetScalars(triangle_strip_cell_scalars)
mapper_29.SetScalarModeToUseCellData()
actor_29.AddPosition(10, 8, 0)

# Triangle type, mask=16, position=(0, 10)
grid_30 = vtkUnstructuredGrid()
grid_30.Allocate(1, 1)
grid_30.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_30.SetPoints(triangle_strip_points)
geometry_30 = vtkGeometryFilter()
geometry_30.SetInputData(grid_30)
tri_filter_30 = vtkTriangleFilter()
tri_filter_30.SetInputConnection(geometry_30.GetOutputPort())
mapper_30 = vtkPolyDataMapper()
mapper_30.SetInputConnection(tri_filter_30.GetOutputPort())
mapper_30.SetLookupTable(lut)
mapper_30.SetScalarRange(0, 4)
actor_30 = vtkActor()
actor_30.SetMapper(mapper_30)
grid_30.GetCellData().SetNormals(triangle_strip_cell_normals)
actor_30.AddPosition(0, 10, 0)

# Triangle type, mask=18, position=(2, 10)
grid_31 = vtkUnstructuredGrid()
grid_31.Allocate(1, 1)
grid_31.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_31.SetPoints(triangle_strip_points)
geometry_31 = vtkGeometryFilter()
geometry_31.SetInputData(grid_31)
tri_filter_31 = vtkTriangleFilter()
tri_filter_31.SetInputConnection(geometry_31.GetOutputPort())
mapper_31 = vtkPolyDataMapper()
mapper_31.SetInputConnection(tri_filter_31.GetOutputPort())
mapper_31.SetLookupTable(lut)
mapper_31.SetScalarRange(0, 4)
actor_31 = vtkActor()
actor_31.SetMapper(mapper_31)
grid_31.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_31.SetScalarModeToUsePointData()
grid_31.GetCellData().SetNormals(triangle_strip_cell_normals)
actor_31.AddPosition(2, 10, 0)

# Triangle type, mask=20, position=(4, 10)
grid_32 = vtkUnstructuredGrid()
grid_32.Allocate(1, 1)
grid_32.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_32.SetPoints(triangle_strip_points)
geometry_32 = vtkGeometryFilter()
geometry_32.SetInputData(grid_32)
tri_filter_32 = vtkTriangleFilter()
tri_filter_32.SetInputConnection(geometry_32.GetOutputPort())
mapper_32 = vtkPolyDataMapper()
mapper_32.SetInputConnection(tri_filter_32.GetOutputPort())
mapper_32.SetLookupTable(lut)
mapper_32.SetScalarRange(0, 4)
actor_32 = vtkActor()
actor_32.SetMapper(mapper_32)
grid_32.GetPointData().SetTCoords(triangle_strip_tcoords)
actor_32.SetTexture(texture)
grid_32.GetCellData().SetNormals(triangle_strip_cell_normals)
actor_32.AddPosition(4, 10, 0)

# Triangle type, mask=22, position=(6, 10)
grid_33 = vtkUnstructuredGrid()
grid_33.Allocate(1, 1)
grid_33.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_33.SetPoints(triangle_strip_points)
geometry_33 = vtkGeometryFilter()
geometry_33.SetInputData(grid_33)
tri_filter_33 = vtkTriangleFilter()
tri_filter_33.SetInputConnection(geometry_33.GetOutputPort())
mapper_33 = vtkPolyDataMapper()
mapper_33.SetInputConnection(tri_filter_33.GetOutputPort())
mapper_33.SetLookupTable(lut)
mapper_33.SetScalarRange(0, 4)
actor_33 = vtkActor()
actor_33.SetMapper(mapper_33)
grid_33.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_33.SetScalarModeToUsePointData()
grid_33.GetPointData().SetTCoords(triangle_strip_tcoords)
actor_33.SetTexture(texture)
grid_33.GetCellData().SetNormals(triangle_strip_cell_normals)
actor_33.AddPosition(6, 10, 0)

# Triangle type, mask=26, position=(8, 10)
grid_34 = vtkUnstructuredGrid()
grid_34.Allocate(1, 1)
grid_34.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_34.SetPoints(triangle_strip_points)
geometry_34 = vtkGeometryFilter()
geometry_34.SetInputData(grid_34)
tri_filter_34 = vtkTriangleFilter()
tri_filter_34.SetInputConnection(geometry_34.GetOutputPort())
mapper_34 = vtkPolyDataMapper()
mapper_34.SetInputConnection(tri_filter_34.GetOutputPort())
mapper_34.SetLookupTable(lut)
mapper_34.SetScalarRange(0, 4)
actor_34 = vtkActor()
actor_34.SetMapper(mapper_34)
grid_34.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_34.SetScalarModeToUsePointData()
grid_34.GetCellData().SetScalars(triangle_strip_cell_scalars)
mapper_34.SetScalarModeToUseCellData()
grid_34.GetCellData().SetNormals(triangle_strip_cell_normals)
actor_34.AddPosition(8, 10, 0)

# Triangle type, mask=30, position=(10, 10)
grid_35 = vtkUnstructuredGrid()
grid_35.Allocate(1, 1)
grid_35.InsertNextCell(a_triangle_strip.GetCellType(), a_triangle_strip.GetPointIds())
grid_35.SetPoints(triangle_strip_points)
geometry_35 = vtkGeometryFilter()
geometry_35.SetInputData(grid_35)
tri_filter_35 = vtkTriangleFilter()
tri_filter_35.SetInputConnection(geometry_35.GetOutputPort())
mapper_35 = vtkPolyDataMapper()
mapper_35.SetInputConnection(tri_filter_35.GetOutputPort())
mapper_35.SetLookupTable(lut)
mapper_35.SetScalarRange(0, 4)
actor_35 = vtkActor()
actor_35.SetMapper(mapper_35)
grid_35.GetPointData().SetScalars(triangle_strip_point_scalars)
mapper_35.SetScalarModeToUsePointData()
grid_35.GetPointData().SetTCoords(triangle_strip_tcoords)
actor_35.SetTexture(texture)
grid_35.GetCellData().SetScalars(triangle_strip_cell_scalars)
mapper_35.SetScalarModeToUseCellData()
grid_35.GetCellData().SetNormals(triangle_strip_cell_normals)
actor_35.AddPosition(10, 10, 0)

# Renderer
renderer = vtkRenderer()
renderer.AddActor(actor_0)
renderer.AddActor(actor_1)
renderer.AddActor(actor_2)
renderer.AddActor(actor_3)
renderer.AddActor(actor_4)
renderer.AddActor(actor_5)
renderer.AddActor(actor_6)
renderer.AddActor(actor_7)
renderer.AddActor(actor_8)
renderer.AddActor(actor_9)
renderer.AddActor(actor_10)
renderer.AddActor(actor_11)
renderer.AddActor(actor_12)
renderer.AddActor(actor_13)
renderer.AddActor(actor_14)
renderer.AddActor(actor_15)
renderer.AddActor(actor_16)
renderer.AddActor(actor_17)
renderer.AddActor(actor_18)
renderer.AddActor(actor_19)
renderer.AddActor(actor_20)
renderer.AddActor(actor_21)
renderer.AddActor(actor_22)
renderer.AddActor(actor_23)
renderer.AddActor(actor_24)
renderer.AddActor(actor_25)
renderer.AddActor(actor_26)
renderer.AddActor(actor_27)
renderer.AddActor(actor_28)
renderer.AddActor(actor_29)
renderer.AddActor(actor_30)
renderer.AddActor(actor_31)
renderer.AddActor(actor_32)
renderer.AddActor(actor_33)
renderer.AddActor(actor_34)
renderer.AddActor(actor_35)
renderer.SetBackground(0.7, 0.3, 0.1)

render_window = vtkRenderWindow()
render_window.AddRenderer(renderer)
render_window.SetWindowName("polydata mapper all polygons")
render_window.SetMultiSamples(0)
render_window.SetSize(480, 480)

interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)

# Scene
renderer.ResetCameraClippingRange()

interactor.Initialize()
interactor.Start()
