#!/usr/bin/env python

# Read a CityGML file via stream and render buildings with textures.

import os

import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingFreeType  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401

from vtkmodules.vtkIOCityGML import vtkCityGMLReader
from vtkmodules.vtkIOCore import vtkFileResourceStream
from vtkmodules.vtkIOImage import vtkJPEGReader
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkPolyDataMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
    vtkTexture,
)

# Source
data_dir = os.environ.get("VPE_DATA_DIR", os.path.dirname(os.path.abspath(__file__)))
gml_file = os.path.join(data_dir, "Part-4-Buildings-V4-one.gml")
gml_dir = os.path.dirname(gml_file)

# Read CityGML file via stream
file_stream = vtkFileResourceStream()
file_stream.Open(gml_file)

citygml_reader = vtkCityGMLReader()
citygml_reader.SetStream(file_stream)
citygml_reader.Update()
multi_block = citygml_reader.GetOutput()

building = multi_block.GetBlock(0)
nested_block = building.GetBlock(1)

# Leaf 0: building.GetBlock(0) — textured
mapper_0 = vtkPolyDataMapper()
mapper_0.SetInputDataObject(building.GetBlock(0))
actor_0 = vtkActor()
actor_0.SetMapper(mapper_0)
jpeg_reader_0 = vtkJPEGReader()
jpeg_reader_0.SetFileName(os.path.join(gml_dir, "textures/Wood_Cherry_Chapel.jpg"))
jpeg_reader_0.Update()
texture_0 = vtkTexture()
texture_0.SetInputConnection(jpeg_reader_0.GetOutputPort())
texture_0.InterpolateOn()
actor_0.SetTexture(texture_0)

# Leaf 1: nested_block.GetBlock(0) — no texture
mapper_1 = vtkPolyDataMapper()
mapper_1.SetInputDataObject(nested_block.GetBlock(0))
actor_1 = vtkActor()
actor_1.SetMapper(mapper_1)

# Leaf 2: nested_block.GetBlock(1) — textured
mapper_2 = vtkPolyDataMapper()
mapper_2.SetInputDataObject(nested_block.GetBlock(1))
actor_2 = vtkActor()
actor_2.SetMapper(mapper_2)
jpeg_reader_2 = vtkJPEGReader()
jpeg_reader_2.SetFileName(os.path.join(gml_dir, "textures/Roofing_Slate_Rounded.jpg"))
jpeg_reader_2.Update()
texture_2 = vtkTexture()
texture_2.SetInputConnection(jpeg_reader_2.GetOutputPort())
texture_2.InterpolateOn()
actor_2.SetTexture(texture_2)

# Leaf 3: nested_block.GetBlock(2) — textured
mapper_3 = vtkPolyDataMapper()
mapper_3.SetInputDataObject(nested_block.GetBlock(2))
actor_3 = vtkActor()
actor_3.SetMapper(mapper_3)
jpeg_reader_3 = vtkJPEGReader()
jpeg_reader_3.SetFileName(os.path.join(gml_dir, "textures/Stone_Sandstone_Ashlar_Light.jpg"))
jpeg_reader_3.Update()
texture_3 = vtkTexture()
texture_3.SetInputConnection(jpeg_reader_3.GetOutputPort())
texture_3.InterpolateOn()
actor_3.SetTexture(texture_3)

# Leaf 4: building.GetBlock(2) — textured
mapper_4 = vtkPolyDataMapper()
mapper_4.SetInputDataObject(building.GetBlock(2))
actor_4 = vtkActor()
actor_4.SetMapper(mapper_4)
jpeg_reader_4 = vtkJPEGReader()
jpeg_reader_4.SetFileName(os.path.join(gml_dir, "textures/Roofing_Slate_Dark.jpg"))
jpeg_reader_4.Update()
texture_4 = vtkTexture()
texture_4.SetInputConnection(jpeg_reader_4.GetOutputPort())
texture_4.InterpolateOn()
actor_4.SetTexture(texture_4)

# Leaf 5: building.GetBlock(3) — textured
mapper_5 = vtkPolyDataMapper()
mapper_5.SetInputDataObject(building.GetBlock(3))
actor_5 = vtkActor()
actor_5.SetMapper(mapper_5)
jpeg_reader_5 = vtkJPEGReader()
jpeg_reader_5.SetFileName(os.path.join(gml_dir, "textures/Roofing_Slate_Dark.jpg"))
jpeg_reader_5.Update()
texture_5 = vtkTexture()
texture_5.SetInputConnection(jpeg_reader_5.GetOutputPort())
texture_5.InterpolateOn()
actor_5.SetTexture(texture_5)

# Leaf 6: building.GetBlock(4) — textured
mapper_6 = vtkPolyDataMapper()
mapper_6.SetInputDataObject(building.GetBlock(4))
actor_6 = vtkActor()
actor_6.SetMapper(mapper_6)
jpeg_reader_6 = vtkJPEGReader()
jpeg_reader_6.SetFileName(os.path.join(gml_dir, "textures/Stone_Sandstone_Ashlar_Light.jpg"))
jpeg_reader_6.Update()
texture_6 = vtkTexture()
texture_6.SetInputConnection(jpeg_reader_6.GetOutputPort())
texture_6.InterpolateOn()
actor_6.SetTexture(texture_6)

# Leaf 7: building.GetBlock(5) — textured
mapper_7 = vtkPolyDataMapper()
mapper_7.SetInputDataObject(building.GetBlock(5))
actor_7 = vtkActor()
actor_7.SetMapper(mapper_7)
jpeg_reader_7 = vtkJPEGReader()
jpeg_reader_7.SetFileName(os.path.join(gml_dir, "textures/Kirchenfenster-V2.jpg"))
jpeg_reader_7.Update()
texture_7 = vtkTexture()
texture_7.SetInputConnection(jpeg_reader_7.GetOutputPort())
texture_7.InterpolateOn()
actor_7.SetTexture(texture_7)

# Leaf 8: building.GetBlock(6) — textured
mapper_8 = vtkPolyDataMapper()
mapper_8.SetInputDataObject(building.GetBlock(6))
actor_8 = vtkActor()
actor_8.SetMapper(mapper_8)
jpeg_reader_8 = vtkJPEGReader()
jpeg_reader_8.SetFileName(os.path.join(gml_dir, "textures/Kirchenfenster-V2.jpg"))
jpeg_reader_8.Update()
texture_8 = vtkTexture()
texture_8.SetInputConnection(jpeg_reader_8.GetOutputPort())
texture_8.InterpolateOn()
actor_8.SetTexture(texture_8)

# Leaf 9: building.GetBlock(7) — textured
mapper_9 = vtkPolyDataMapper()
mapper_9.SetInputDataObject(building.GetBlock(7))
actor_9 = vtkActor()
actor_9.SetMapper(mapper_9)
jpeg_reader_9 = vtkJPEGReader()
jpeg_reader_9.SetFileName(os.path.join(gml_dir, "textures/Kirchenfenster-V2.jpg"))
jpeg_reader_9.Update()
texture_9 = vtkTexture()
texture_9.SetInputConnection(jpeg_reader_9.GetOutputPort())
texture_9.InterpolateOn()
actor_9.SetTexture(texture_9)

# Leaf 10: building.GetBlock(8) — textured
mapper_10 = vtkPolyDataMapper()
mapper_10.SetInputDataObject(building.GetBlock(8))
actor_10 = vtkActor()
actor_10.SetMapper(mapper_10)
jpeg_reader_10 = vtkJPEGReader()
jpeg_reader_10.SetFileName(os.path.join(gml_dir, "textures/Kirchenfenster-V2.jpg"))
jpeg_reader_10.Update()
texture_10 = vtkTexture()
texture_10.SetInputConnection(jpeg_reader_10.GetOutputPort())
texture_10.InterpolateOn()
actor_10.SetTexture(texture_10)

# Leaf 11: building.GetBlock(9) — textured
mapper_11 = vtkPolyDataMapper()
mapper_11.SetInputDataObject(building.GetBlock(9))
actor_11 = vtkActor()
actor_11.SetMapper(mapper_11)
jpeg_reader_11 = vtkJPEGReader()
jpeg_reader_11.SetFileName(os.path.join(gml_dir, "textures/Kirchenfenster-V2.jpg"))
jpeg_reader_11.Update()
texture_11 = vtkTexture()
texture_11.SetInputConnection(jpeg_reader_11.GetOutputPort())
texture_11.InterpolateOn()
actor_11.SetTexture(texture_11)

# Leaf 12: building.GetBlock(10) — textured
mapper_12 = vtkPolyDataMapper()
mapper_12.SetInputDataObject(building.GetBlock(10))
actor_12 = vtkActor()
actor_12.SetMapper(mapper_12)
jpeg_reader_12 = vtkJPEGReader()
jpeg_reader_12.SetFileName(os.path.join(gml_dir, "textures/Kirchenfenster-V2.jpg"))
jpeg_reader_12.Update()
texture_12 = vtkTexture()
texture_12.SetInputConnection(jpeg_reader_12.GetOutputPort())
texture_12.InterpolateOn()
actor_12.SetTexture(texture_12)

# Leaf 13: building.GetBlock(11) — textured
mapper_13 = vtkPolyDataMapper()
mapper_13.SetInputDataObject(building.GetBlock(11))
actor_13 = vtkActor()
actor_13.SetMapper(mapper_13)
jpeg_reader_13 = vtkJPEGReader()
jpeg_reader_13.SetFileName(os.path.join(gml_dir, "textures/Stone_Sandstone_Ashlar_Light.jpg"))
jpeg_reader_13.Update()
texture_13 = vtkTexture()
texture_13.SetInputConnection(jpeg_reader_13.GetOutputPort())
texture_13.InterpolateOn()
actor_13.SetTexture(texture_13)

# Leaf 14: building.GetBlock(12) — textured
mapper_14 = vtkPolyDataMapper()
mapper_14.SetInputDataObject(building.GetBlock(12))
actor_14 = vtkActor()
actor_14.SetMapper(mapper_14)
jpeg_reader_14 = vtkJPEGReader()
jpeg_reader_14.SetFileName(os.path.join(gml_dir, "textures/Kirchenfenster-V2.jpg"))
jpeg_reader_14.Update()
texture_14 = vtkTexture()
texture_14.SetInputConnection(jpeg_reader_14.GetOutputPort())
texture_14.InterpolateOn()
actor_14.SetTexture(texture_14)

# Leaf 15: building.GetBlock(13) — textured
mapper_15 = vtkPolyDataMapper()
mapper_15.SetInputDataObject(building.GetBlock(13))
actor_15 = vtkActor()
actor_15.SetMapper(mapper_15)
jpeg_reader_15 = vtkJPEGReader()
jpeg_reader_15.SetFileName(os.path.join(gml_dir, "textures/Kirchenfenster-V2.jpg"))
jpeg_reader_15.Update()
texture_15 = vtkTexture()
texture_15.SetInputConnection(jpeg_reader_15.GetOutputPort())
texture_15.InterpolateOn()
actor_15.SetTexture(texture_15)

# Leaf 16: building.GetBlock(14) — textured
mapper_16 = vtkPolyDataMapper()
mapper_16.SetInputDataObject(building.GetBlock(14))
actor_16 = vtkActor()
actor_16.SetMapper(mapper_16)
jpeg_reader_16 = vtkJPEGReader()
jpeg_reader_16.SetFileName(os.path.join(gml_dir, "textures/Stone_Sandstone_Ashlar_Light.jpg"))
jpeg_reader_16.Update()
texture_16 = vtkTexture()
texture_16.SetInputConnection(jpeg_reader_16.GetOutputPort())
texture_16.InterpolateOn()
actor_16.SetTexture(texture_16)

# Leaf 17: building.GetBlock(15) — textured
mapper_17 = vtkPolyDataMapper()
mapper_17.SetInputDataObject(building.GetBlock(15))
actor_17 = vtkActor()
actor_17.SetMapper(mapper_17)
jpeg_reader_17 = vtkJPEGReader()
jpeg_reader_17.SetFileName(os.path.join(gml_dir, "textures/Kirchenfenster-V2.jpg"))
jpeg_reader_17.Update()
texture_17 = vtkTexture()
texture_17.SetInputConnection(jpeg_reader_17.GetOutputPort())
texture_17.InterpolateOn()
actor_17.SetTexture(texture_17)

# Leaf 18: building.GetBlock(16) — textured
mapper_18 = vtkPolyDataMapper()
mapper_18.SetInputDataObject(building.GetBlock(16))
actor_18 = vtkActor()
actor_18.SetMapper(mapper_18)
jpeg_reader_18 = vtkJPEGReader()
jpeg_reader_18.SetFileName(os.path.join(gml_dir, "textures/Kirchenfenster-V2.jpg"))
jpeg_reader_18.Update()
texture_18 = vtkTexture()
texture_18.SetInputConnection(jpeg_reader_18.GetOutputPort())
texture_18.InterpolateOn()
actor_18.SetTexture(texture_18)

# Leaf 19: building.GetBlock(17) — textured
mapper_19 = vtkPolyDataMapper()
mapper_19.SetInputDataObject(building.GetBlock(17))
actor_19 = vtkActor()
actor_19.SetMapper(mapper_19)
jpeg_reader_19 = vtkJPEGReader()
jpeg_reader_19.SetFileName(os.path.join(gml_dir, "textures/Kirchenfenster-V2.jpg"))
jpeg_reader_19.Update()
texture_19 = vtkTexture()
texture_19.SetInputConnection(jpeg_reader_19.GetOutputPort())
texture_19.InterpolateOn()
actor_19.SetTexture(texture_19)

# Leaf 20: building.GetBlock(18) — textured
mapper_20 = vtkPolyDataMapper()
mapper_20.SetInputDataObject(building.GetBlock(18))
actor_20 = vtkActor()
actor_20.SetMapper(mapper_20)
jpeg_reader_20 = vtkJPEGReader()
jpeg_reader_20.SetFileName(os.path.join(gml_dir, "textures/Kirchenfenster-V2.jpg"))
jpeg_reader_20.Update()
texture_20 = vtkTexture()
texture_20.SetInputConnection(jpeg_reader_20.GetOutputPort())
texture_20.InterpolateOn()
actor_20.SetTexture(texture_20)

# Leaf 21: building.GetBlock(19) — textured
mapper_21 = vtkPolyDataMapper()
mapper_21.SetInputDataObject(building.GetBlock(19))
actor_21 = vtkActor()
actor_21.SetMapper(mapper_21)
jpeg_reader_21 = vtkJPEGReader()
jpeg_reader_21.SetFileName(os.path.join(gml_dir, "textures/Kirchenfenster-V2.jpg"))
jpeg_reader_21.Update()
texture_21 = vtkTexture()
texture_21.SetInputConnection(jpeg_reader_21.GetOutputPort())
texture_21.InterpolateOn()
actor_21.SetTexture(texture_21)

# Leaf 22: building.GetBlock(20) — textured
mapper_22 = vtkPolyDataMapper()
mapper_22.SetInputDataObject(building.GetBlock(20))
actor_22 = vtkActor()
actor_22.SetMapper(mapper_22)
jpeg_reader_22 = vtkJPEGReader()
jpeg_reader_22.SetFileName(os.path.join(gml_dir, "textures/Kirchenfenster-V2.jpg"))
jpeg_reader_22.Update()
texture_22 = vtkTexture()
texture_22.SetInputConnection(jpeg_reader_22.GetOutputPort())
texture_22.InterpolateOn()
actor_22.SetTexture(texture_22)

# Leaf 23: building.GetBlock(21) — no texture
mapper_23 = vtkPolyDataMapper()
mapper_23.SetInputDataObject(building.GetBlock(21))
actor_23 = vtkActor()
actor_23.SetMapper(mapper_23)

# Leaf 24: building.GetBlock(22) — textured
mapper_24 = vtkPolyDataMapper()
mapper_24.SetInputDataObject(building.GetBlock(22))
actor_24 = vtkActor()
actor_24.SetMapper(mapper_24)
jpeg_reader_24 = vtkJPEGReader()
jpeg_reader_24.SetFileName(os.path.join(gml_dir, "textures/Stone_Sandstone_Ashlar_Light.jpg"))
jpeg_reader_24.Update()
texture_24 = vtkTexture()
texture_24.SetInputConnection(jpeg_reader_24.GetOutputPort())
texture_24.InterpolateOn()
actor_24.SetTexture(texture_24)

# Leaf 25: building.GetBlock(23) — textured
mapper_25 = vtkPolyDataMapper()
mapper_25.SetInputDataObject(building.GetBlock(23))
actor_25 = vtkActor()
actor_25.SetMapper(mapper_25)
jpeg_reader_25 = vtkJPEGReader()
jpeg_reader_25.SetFileName(os.path.join(gml_dir, "textures/Kirchenfenster-V2.jpg"))
jpeg_reader_25.Update()
texture_25 = vtkTexture()
texture_25.SetInputConnection(jpeg_reader_25.GetOutputPort())
texture_25.InterpolateOn()
actor_25.SetTexture(texture_25)

# Leaf 26: building.GetBlock(24) — textured
mapper_26 = vtkPolyDataMapper()
mapper_26.SetInputDataObject(building.GetBlock(24))
actor_26 = vtkActor()
actor_26.SetMapper(mapper_26)
jpeg_reader_26 = vtkJPEGReader()
jpeg_reader_26.SetFileName(os.path.join(gml_dir, "textures/Roofing_Slate_Dark.jpg"))
jpeg_reader_26.Update()
texture_26 = vtkTexture()
texture_26.SetInputConnection(jpeg_reader_26.GetOutputPort())
texture_26.InterpolateOn()
actor_26.SetTexture(texture_26)

# Leaf 27: building.GetBlock(25) — textured
mapper_27 = vtkPolyDataMapper()
mapper_27.SetInputDataObject(building.GetBlock(25))
actor_27 = vtkActor()
actor_27.SetMapper(mapper_27)
jpeg_reader_27 = vtkJPEGReader()
jpeg_reader_27.SetFileName(os.path.join(gml_dir, "textures/Stone_Sandstone_Ashlar_Light.jpg"))
jpeg_reader_27.Update()
texture_27 = vtkTexture()
texture_27.SetInputConnection(jpeg_reader_27.GetOutputPort())
texture_27.InterpolateOn()
actor_27.SetTexture(texture_27)

# Leaf 28: building.GetBlock(26) — textured
mapper_28 = vtkPolyDataMapper()
mapper_28.SetInputDataObject(building.GetBlock(26))
actor_28 = vtkActor()
actor_28.SetMapper(mapper_28)
jpeg_reader_28 = vtkJPEGReader()
jpeg_reader_28.SetFileName(os.path.join(gml_dir, "textures/Stone_Sandstone_Ashlar_Light.jpg"))
jpeg_reader_28.Update()
texture_28 = vtkTexture()
texture_28.SetInputConnection(jpeg_reader_28.GetOutputPort())
texture_28.InterpolateOn()
actor_28.SetTexture(texture_28)

# Leaf 29: building.GetBlock(27) — textured
mapper_29 = vtkPolyDataMapper()
mapper_29.SetInputDataObject(building.GetBlock(27))
actor_29 = vtkActor()
actor_29.SetMapper(mapper_29)
jpeg_reader_29 = vtkJPEGReader()
jpeg_reader_29.SetFileName(os.path.join(gml_dir, "textures/Roofing_Slate_Dark.jpg"))
jpeg_reader_29.Update()
texture_29 = vtkTexture()
texture_29.SetInputConnection(jpeg_reader_29.GetOutputPort())
texture_29.InterpolateOn()
actor_29.SetTexture(texture_29)

# Leaf 30: building.GetBlock(28) — textured
mapper_30 = vtkPolyDataMapper()
mapper_30.SetInputDataObject(building.GetBlock(28))
actor_30 = vtkActor()
actor_30.SetMapper(mapper_30)
jpeg_reader_30 = vtkJPEGReader()
jpeg_reader_30.SetFileName(os.path.join(gml_dir, "textures/Stone_Sandstone_Ashlar_Light.jpg"))
jpeg_reader_30.Update()
texture_30 = vtkTexture()
texture_30.SetInputConnection(jpeg_reader_30.GetOutputPort())
texture_30.InterpolateOn()
actor_30.SetTexture(texture_30)

# Leaf 31: building.GetBlock(29) — textured
mapper_31 = vtkPolyDataMapper()
mapper_31.SetInputDataObject(building.GetBlock(29))
actor_31 = vtkActor()
actor_31.SetMapper(mapper_31)
jpeg_reader_31 = vtkJPEGReader()
jpeg_reader_31.SetFileName(os.path.join(gml_dir, "textures/Kirchenfenster-V2.jpg"))
jpeg_reader_31.Update()
texture_31 = vtkTexture()
texture_31.SetInputConnection(jpeg_reader_31.GetOutputPort())
texture_31.InterpolateOn()
actor_31.SetTexture(texture_31)

# Leaf 32: building.GetBlock(30) — textured
mapper_32 = vtkPolyDataMapper()
mapper_32.SetInputDataObject(building.GetBlock(30))
actor_32 = vtkActor()
actor_32.SetMapper(mapper_32)
jpeg_reader_32 = vtkJPEGReader()
jpeg_reader_32.SetFileName(os.path.join(gml_dir, "textures/Stone_Sandstone_Ashlar_Light.jpg"))
jpeg_reader_32.Update()
texture_32 = vtkTexture()
texture_32.SetInputConnection(jpeg_reader_32.GetOutputPort())
texture_32.InterpolateOn()
actor_32.SetTexture(texture_32)

# Leaf 33: building.GetBlock(31) — textured
mapper_33 = vtkPolyDataMapper()
mapper_33.SetInputDataObject(building.GetBlock(31))
actor_33 = vtkActor()
actor_33.SetMapper(mapper_33)
jpeg_reader_33 = vtkJPEGReader()
jpeg_reader_33.SetFileName(os.path.join(gml_dir, "textures/Stone_Sandstone_Ashlar_Light.jpg"))
jpeg_reader_33.Update()
texture_33 = vtkTexture()
texture_33.SetInputConnection(jpeg_reader_33.GetOutputPort())
texture_33.InterpolateOn()
actor_33.SetTexture(texture_33)

# Leaf 34: building.GetBlock(32) — textured
mapper_34 = vtkPolyDataMapper()
mapper_34.SetInputDataObject(building.GetBlock(32))
actor_34 = vtkActor()
actor_34.SetMapper(mapper_34)
jpeg_reader_34 = vtkJPEGReader()
jpeg_reader_34.SetFileName(os.path.join(gml_dir, "textures/Roofing_Slate_Rounded.jpg"))
jpeg_reader_34.Update()
texture_34 = vtkTexture()
texture_34.SetInputConnection(jpeg_reader_34.GetOutputPort())
texture_34.InterpolateOn()
actor_34.SetTexture(texture_34)

# Leaf 35: building.GetBlock(33) — textured
mapper_35 = vtkPolyDataMapper()
mapper_35.SetInputDataObject(building.GetBlock(33))
actor_35 = vtkActor()
actor_35.SetMapper(mapper_35)
jpeg_reader_35 = vtkJPEGReader()
jpeg_reader_35.SetFileName(os.path.join(gml_dir, "textures/Stone_Sandstone_Ashlar_Light.jpg"))
jpeg_reader_35.Update()
texture_35 = vtkTexture()
texture_35.SetInputConnection(jpeg_reader_35.GetOutputPort())
texture_35.InterpolateOn()
actor_35.SetTexture(texture_35)

# Leaf 36: building.GetBlock(34) — textured
mapper_36 = vtkPolyDataMapper()
mapper_36.SetInputDataObject(building.GetBlock(34))
actor_36 = vtkActor()
actor_36.SetMapper(mapper_36)
jpeg_reader_36 = vtkJPEGReader()
jpeg_reader_36.SetFileName(os.path.join(gml_dir, "textures/Wood_Cherry_Chapel.jpg"))
jpeg_reader_36.Update()
texture_36 = vtkTexture()
texture_36.SetInputConnection(jpeg_reader_36.GetOutputPort())
texture_36.InterpolateOn()
actor_36.SetTexture(texture_36)

# Leaf 37: building.GetBlock(35) — textured
mapper_37 = vtkPolyDataMapper()
mapper_37.SetInputDataObject(building.GetBlock(35))
actor_37 = vtkActor()
actor_37.SetMapper(mapper_37)
jpeg_reader_37 = vtkJPEGReader()
jpeg_reader_37.SetFileName(os.path.join(gml_dir, "textures/Roofing_Slate_Rounded.jpg"))
jpeg_reader_37.Update()
texture_37 = vtkTexture()
texture_37.SetInputConnection(jpeg_reader_37.GetOutputPort())
texture_37.InterpolateOn()
actor_37.SetTexture(texture_37)

# Leaf 38: building.GetBlock(36) — textured
mapper_38 = vtkPolyDataMapper()
mapper_38.SetInputDataObject(building.GetBlock(36))
actor_38 = vtkActor()
actor_38.SetMapper(mapper_38)
jpeg_reader_38 = vtkJPEGReader()
jpeg_reader_38.SetFileName(os.path.join(gml_dir, "textures/Stone_Sandstone_Ashlar_Light1.jpg"))
jpeg_reader_38.Update()
texture_38 = vtkTexture()
texture_38.SetInputConnection(jpeg_reader_38.GetOutputPort())
texture_38.InterpolateOn()
actor_38.SetTexture(texture_38)

# Leaf 39: building.GetBlock(37) — textured
mapper_39 = vtkPolyDataMapper()
mapper_39.SetInputDataObject(building.GetBlock(37))
actor_39 = vtkActor()
actor_39.SetMapper(mapper_39)
jpeg_reader_39 = vtkJPEGReader()
jpeg_reader_39.SetFileName(os.path.join(gml_dir, "textures/Roofing_Slate_Rounded.jpg"))
jpeg_reader_39.Update()
texture_39 = vtkTexture()
texture_39.SetInputConnection(jpeg_reader_39.GetOutputPort())
texture_39.InterpolateOn()
actor_39.SetTexture(texture_39)

# Renderer
renderer = vtkRenderer()
renderer.AddActor(actor_0)
renderer.AddActor(actor_1)
renderer.AddActor(actor_2)
renderer.AddActor(actor_3)
renderer.AddActor(actor_4)
renderer.AddActor(actor_5)
renderer.AddActor(actor_6)
renderer.AddActor(actor_7)
renderer.AddActor(actor_8)
renderer.AddActor(actor_9)
renderer.AddActor(actor_10)
renderer.AddActor(actor_11)
renderer.AddActor(actor_12)
renderer.AddActor(actor_13)
renderer.AddActor(actor_14)
renderer.AddActor(actor_15)
renderer.AddActor(actor_16)
renderer.AddActor(actor_17)
renderer.AddActor(actor_18)
renderer.AddActor(actor_19)
renderer.AddActor(actor_20)
renderer.AddActor(actor_21)
renderer.AddActor(actor_22)
renderer.AddActor(actor_23)
renderer.AddActor(actor_24)
renderer.AddActor(actor_25)
renderer.AddActor(actor_26)
renderer.AddActor(actor_27)
renderer.AddActor(actor_28)
renderer.AddActor(actor_29)
renderer.AddActor(actor_30)
renderer.AddActor(actor_31)
renderer.AddActor(actor_32)
renderer.AddActor(actor_33)
renderer.AddActor(actor_34)
renderer.AddActor(actor_35)
renderer.AddActor(actor_36)
renderer.AddActor(actor_37)
renderer.AddActor(actor_38)
renderer.AddActor(actor_39)
renderer.SetBackground(0.5, 0.7, 0.7)

# Render window
render_window = vtkRenderWindow()
render_window.AddRenderer(renderer)
render_window.SetWindowName("city gml reader stream")
render_window.SetMultiSamples(0)
render_window.SetSize(400, 400)

# Interactor
interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)

# Scene
renderer.ResetCamera()
renderer.GetActiveCamera().Azimuth(90)
renderer.GetActiveCamera().Roll(-90)
renderer.GetActiveCamera().Zoom(1.5)

interactor.Initialize()
interactor.Start()
