#!/usr/bin/env python

# Demonstrate fixed-point volume ray casting with nearest interpolation and cropping across a 5x5 grid.

import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401
import vtkmodules.vtkRenderingVolumeOpenGL2  # noqa: F401

from vtkmodules.vtkCommonDataModel import vtkPiecewiseFunction
from vtkmodules.vtkImagingCore import (
    vtkImageAppendComponents,
    vtkImageThreshold,
    vtkImageShiftScale,
)
from vtkmodules.vtkImagingMorphological import vtkImageContinuousDilate3D
from vtkmodules.vtkImagingSources import (
    vtkImageGaussianSource,
    vtkImageGridSource,
)
from vtkmodules.vtkRenderingCore import (
    vtkColorTransferFunction,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
    vtkVolume,
    vtkVolumeProperty,
)
from vtkmodules.vtkRenderingVolume import vtkFixedPointVolumeRayCastMapper

# Create a gaussian source
gaussian_source = vtkImageGaussianSource()
gaussian_source.SetWholeExtent(0, 30, 0, 30, 0, 30)
gaussian_source.SetMaximum(255.0)
gaussian_source.SetStandardDeviation(5)
gaussian_source.SetCenter(15, 15, 15)

threshold = vtkImageThreshold()
threshold.SetInputConnection(gaussian_source.GetOutputPort())
threshold.ReplaceInOn()
threshold.SetInValue(0)
threshold.ThresholdBetween(150, 200)

shift_scale = vtkImageShiftScale()
shift_scale.SetInputConnection(threshold.GetOutputPort())
shift_scale.SetOutputScalarTypeToUnsignedChar()

grid0 = vtkImageGridSource()
grid0.SetDataScalarTypeToUnsignedChar()
grid0.SetGridSpacing(10, 10, 10)
grid0.SetLineValue(200)
grid0.SetFillValue(10)
grid0.SetDataExtent(0, 30, 0, 30, 0, 30)

dilate = vtkImageContinuousDilate3D()
dilate.SetInputConnection(grid0.GetOutputPort())
dilate.SetKernelSize(3, 3, 3)

iac = vtkImageAppendComponents()
iac.AddInputConnection(dilate.GetOutputPort())
iac.AddInputConnection(shift_scale.GetOutputPort())

gs1 = vtkImageGaussianSource()
gs1.SetWholeExtent(0, 30, 0, 30, 0, 30)
gs1.SetMaximum(255.0)
gs1.SetStandardDeviation(4)
gs1.SetCenter(5, 5, 5)

t1 = vtkImageThreshold()
t1.SetInputConnection(gs1.GetOutputPort())
t1.ReplaceInOn()
t1.SetInValue(0)
t1.ThresholdBetween(150, 256)

gs2 = vtkImageGaussianSource()
gs2.SetWholeExtent(0, 30, 0, 30, 0, 30)
gs2.SetMaximum(255.0)
gs2.SetStandardDeviation(4)
gs2.SetCenter(12, 12, 12)

gs3 = vtkImageGaussianSource()
gs3.SetWholeExtent(0, 30, 0, 30, 0, 30)
gs3.SetMaximum(255.0)
gs3.SetStandardDeviation(4)
gs3.SetCenter(19, 19, 19)

t3 = vtkImageThreshold()
t3.SetInputConnection(gs3.GetOutputPort())
t3.ReplaceInOn()
t3.SetInValue(0)
t3.ThresholdBetween(150, 256)

gs4 = vtkImageGaussianSource()
gs4.SetWholeExtent(0, 30, 0, 30, 0, 30)
gs4.SetMaximum(255.0)
gs4.SetStandardDeviation(4)
gs4.SetCenter(26, 26, 26)

iac1 = vtkImageAppendComponents()
iac1.AddInputConnection(t1.GetOutputPort())
iac1.AddInputConnection(gs2.GetOutputPort())

iac2 = vtkImageAppendComponents()
iac2.AddInputConnection(iac1.GetOutputPort())
iac2.AddInputConnection(t3.GetOutputPort())

iac3 = vtkImageAppendComponents()
iac3.AddInputConnection(iac2.GetOutputPort())
iac3.AddInputConnection(gs4.GetOutputPort())

grid_r = vtkImageGridSource()
grid_r.SetDataScalarTypeToUnsignedChar()
grid_r.SetGridSpacing(10, 100, 100)
grid_r.SetLineValue(250)
grid_r.SetFillValue(100)
grid_r.SetDataExtent(0, 30, 0, 30, 0, 30)

d_r = vtkImageContinuousDilate3D()
d_r.SetInputConnection(grid_r.GetOutputPort())
d_r.SetKernelSize(2, 2, 2)

grid_g = vtkImageGridSource()
grid_g.SetDataScalarTypeToUnsignedChar()
grid_g.SetGridSpacing(100, 10, 100)
grid_g.SetLineValue(250)
grid_g.SetFillValue(100)
grid_g.SetDataExtent(0, 30, 0, 30, 0, 30)

d_g = vtkImageContinuousDilate3D()
d_g.SetInputConnection(grid_g.GetOutputPort())
d_g.SetKernelSize(2, 2, 2)

grid_b = vtkImageGridSource()
grid_b.SetDataScalarTypeToUnsignedChar()
grid_b.SetGridSpacing(100, 100, 10)
grid_b.SetLineValue(0)
grid_b.SetFillValue(250)
grid_b.SetDataExtent(0, 30, 0, 30, 0, 30)

d_b = vtkImageContinuousDilate3D()
d_b.SetInputConnection(grid_b.GetOutputPort())
d_b.SetKernelSize(2, 2, 2)

iac_rg = vtkImageAppendComponents()
iac_rg.AddInputConnection(d_r.GetOutputPort())
iac_rg.AddInputConnection(d_g.GetOutputPort())

iac_rgb = vtkImageAppendComponents()
iac_rgb.AddInputConnection(iac_rg.GetOutputPort())
iac_rgb.AddInputConnection(d_b.GetOutputPort())

iac_rgba = vtkImageAppendComponents()
iac_rgba.AddInputConnection(iac_rgb.GetOutputPort())
iac_rgba.AddInputConnection(shift_scale.GetOutputPort())

# Transfer functions
ramp_point_2 = vtkPiecewiseFunction()
ramp_point_2.AddPoint(0, 0.0)
ramp_point_2.AddPoint(255, 0.2)

ramp_1 = vtkPiecewiseFunction()
ramp_1.AddPoint(0, 0.0)
ramp_1.AddPoint(255, 1.0)

surface = vtkPiecewiseFunction()
surface.AddPoint(0, 0.0)
surface.AddPoint(10, 0.0)
surface.AddPoint(50, 1.0)
surface.AddPoint(255, 1.0)

constant_1 = vtkPiecewiseFunction()
constant_1.AddPoint(0, 1.0)
constant_1.AddPoint(255, 1.0)

gop = vtkPiecewiseFunction()
gop.AddPoint(0, 0.0)
gop.AddPoint(20, 0.0)
gop.AddPoint(60, 1.0)
gop.AddPoint(255, 1.0)

rainbow = vtkColorTransferFunction()
rainbow.SetColorSpaceToHSV()
rainbow.HSVWrapOff()
rainbow.AddHSVPoint(0, 0.1, 1.0, 1.0)
rainbow.AddHSVPoint(255, 0.9, 1.0, 1.0)

red = vtkColorTransferFunction()
red.AddRGBPoint(0, 1, 0, 0)
red.AddRGBPoint(255, 1, 0, 0)

green = vtkColorTransferFunction()
green.AddRGBPoint(0, 0, 1, 0)
green.AddRGBPoint(255, 0, 1, 0)

blue = vtkColorTransferFunction()
blue.AddRGBPoint(0, 0, 0, 1)
blue.AddRGBPoint(255, 0, 0, 1)

yellow = vtkColorTransferFunction()
yellow.AddRGBPoint(0, 1, 1, 0)
yellow.AddRGBPoint(255, 1, 1, 0)

# Rendering setup
renderer = vtkRenderer()

render_window = vtkRenderWindow()
render_window.SetSize(500, 500)
render_window.AddRenderer(renderer)
render_window.SetWindowName("fixed point ray caster nearest cropped")

interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)

# 5x5 grid with cropping enabled (nearest interpolation)

# Row 0: float threshold data, independent components
# [0][0] — MIP
volume_property_0_0 = vtkVolumeProperty()
volume_property_0_0.IndependentComponentsOn()
volume_property_0_0.SetColor(rainbow)
volume_property_0_0.SetScalarOpacity(ramp_1)
volume_property_0_0.SetGradientOpacity(constant_1)
volume_mapper_0_0 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_0_0.SetSampleDistance(0.25)
volume_mapper_0_0.SetNumberOfThreads(1)
volume_mapper_0_0.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_0_0.SetCroppingRegionFlags(253440)
volume_mapper_0_0.CroppingOn()
volume_mapper_0_0.SetInputConnection(threshold.GetOutputPort())
volume_mapper_0_0.SetBlendModeToMaximumIntensity()
volume_0_0 = vtkVolume()
volume_0_0.SetMapper(volume_mapper_0_0)
volume_0_0.SetProperty(volume_property_0_0)
volume_0_0.AddPosition(0, 0, 0)

# [0][1] — Composite
volume_property_0_1 = vtkVolumeProperty()
volume_property_0_1.IndependentComponentsOn()
volume_property_0_1.SetColor(rainbow)
volume_property_0_1.SetScalarOpacity(ramp_point_2)
volume_property_0_1.SetGradientOpacity(constant_1)
volume_mapper_0_1 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_0_1.SetSampleDistance(0.25)
volume_mapper_0_1.SetNumberOfThreads(1)
volume_mapper_0_1.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_0_1.SetCroppingRegionFlags(253440)
volume_mapper_0_1.CroppingOn()
volume_mapper_0_1.SetInputConnection(threshold.GetOutputPort())
volume_mapper_0_1.SetBlendModeToComposite()
volume_0_1 = vtkVolume()
volume_0_1.SetMapper(volume_mapper_0_1)
volume_0_1.SetProperty(volume_property_0_1)
volume_0_1.AddPosition(0, 30, 0)

# [0][2] — Composite + Shade
volume_property_0_2 = vtkVolumeProperty()
volume_property_0_2.IndependentComponentsOn()
volume_property_0_2.SetColor(rainbow)
volume_property_0_2.SetScalarOpacity(surface)
volume_property_0_2.SetGradientOpacity(constant_1)
volume_property_0_2.ShadeOn()
volume_mapper_0_2 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_0_2.SetSampleDistance(0.25)
volume_mapper_0_2.SetNumberOfThreads(1)
volume_mapper_0_2.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_0_2.SetCroppingRegionFlags(253440)
volume_mapper_0_2.CroppingOn()
volume_mapper_0_2.SetInputConnection(threshold.GetOutputPort())
volume_mapper_0_2.SetBlendModeToComposite()
volume_0_2 = vtkVolume()
volume_0_2.SetMapper(volume_mapper_0_2)
volume_0_2.SetProperty(volume_property_0_2)
volume_0_2.AddPosition(0, 60, 0)

# [0][3] — Composite + GO
volume_property_0_3 = vtkVolumeProperty()
volume_property_0_3.IndependentComponentsOn()
volume_property_0_3.SetColor(rainbow)
volume_property_0_3.SetScalarOpacity(ramp_point_2)
volume_property_0_3.SetGradientOpacity(gop)
volume_mapper_0_3 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_0_3.SetSampleDistance(0.25)
volume_mapper_0_3.SetNumberOfThreads(1)
volume_mapper_0_3.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_0_3.SetCroppingRegionFlags(253440)
volume_mapper_0_3.CroppingOn()
volume_mapper_0_3.SetInputConnection(threshold.GetOutputPort())
volume_mapper_0_3.SetBlendModeToComposite()
volume_0_3 = vtkVolume()
volume_0_3.SetMapper(volume_mapper_0_3)
volume_0_3.SetProperty(volume_property_0_3)
volume_0_3.AddPosition(0, 90, 0)

# [0][4] — Composite + GO + Shade
volume_property_0_4 = vtkVolumeProperty()
volume_property_0_4.IndependentComponentsOn()
volume_property_0_4.SetColor(rainbow)
volume_property_0_4.SetScalarOpacity(surface)
volume_property_0_4.SetGradientOpacity(gop)
volume_property_0_4.ShadeOn(0)
volume_property_0_4.ShadeOn(1)
volume_property_0_4.ShadeOn(2)
volume_property_0_4.ShadeOn(3)
volume_mapper_0_4 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_0_4.SetSampleDistance(0.25)
volume_mapper_0_4.SetNumberOfThreads(1)
volume_mapper_0_4.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_0_4.SetCroppingRegionFlags(253440)
volume_mapper_0_4.CroppingOn()
volume_mapper_0_4.SetInputConnection(threshold.GetOutputPort())
volume_mapper_0_4.SetBlendModeToComposite()
volume_0_4 = vtkVolume()
volume_0_4.SetMapper(volume_mapper_0_4)
volume_0_4.SetProperty(volume_property_0_4)
volume_0_4.AddPosition(0, 120, 0)

# Row 1: unsigned char data, independent components
# [1][0] — MIP
volume_property_1_0 = vtkVolumeProperty()
volume_property_1_0.IndependentComponentsOn()
volume_property_1_0.SetColor(rainbow)
volume_property_1_0.SetScalarOpacity(ramp_1)
volume_property_1_0.SetGradientOpacity(constant_1)
volume_mapper_1_0 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_1_0.SetSampleDistance(0.25)
volume_mapper_1_0.SetNumberOfThreads(1)
volume_mapper_1_0.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_1_0.SetCroppingRegionFlags(253440)
volume_mapper_1_0.CroppingOn()
volume_mapper_1_0.SetInputConnection(shift_scale.GetOutputPort())
volume_mapper_1_0.SetBlendModeToMaximumIntensity()
volume_1_0 = vtkVolume()
volume_1_0.SetMapper(volume_mapper_1_0)
volume_1_0.SetProperty(volume_property_1_0)
volume_1_0.AddPosition(30, 0, 0)

# [1][1] — Composite
volume_property_1_1 = vtkVolumeProperty()
volume_property_1_1.IndependentComponentsOn()
volume_property_1_1.SetColor(rainbow)
volume_property_1_1.SetScalarOpacity(ramp_point_2)
volume_property_1_1.SetGradientOpacity(constant_1)
volume_mapper_1_1 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_1_1.SetSampleDistance(0.25)
volume_mapper_1_1.SetNumberOfThreads(1)
volume_mapper_1_1.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_1_1.SetCroppingRegionFlags(253440)
volume_mapper_1_1.CroppingOn()
volume_mapper_1_1.SetInputConnection(shift_scale.GetOutputPort())
volume_mapper_1_1.SetBlendModeToComposite()
volume_1_1 = vtkVolume()
volume_1_1.SetMapper(volume_mapper_1_1)
volume_1_1.SetProperty(volume_property_1_1)
volume_1_1.AddPosition(30, 30, 0)

# [1][2] — Composite + Shade
volume_property_1_2 = vtkVolumeProperty()
volume_property_1_2.IndependentComponentsOn()
volume_property_1_2.SetColor(rainbow)
volume_property_1_2.SetScalarOpacity(surface)
volume_property_1_2.SetGradientOpacity(constant_1)
volume_property_1_2.ShadeOn()
volume_mapper_1_2 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_1_2.SetSampleDistance(0.25)
volume_mapper_1_2.SetNumberOfThreads(1)
volume_mapper_1_2.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_1_2.SetCroppingRegionFlags(253440)
volume_mapper_1_2.CroppingOn()
volume_mapper_1_2.SetInputConnection(shift_scale.GetOutputPort())
volume_mapper_1_2.SetBlendModeToComposite()
volume_1_2 = vtkVolume()
volume_1_2.SetMapper(volume_mapper_1_2)
volume_1_2.SetProperty(volume_property_1_2)
volume_1_2.AddPosition(30, 60, 0)

# [1][3] — Composite + GO
volume_property_1_3 = vtkVolumeProperty()
volume_property_1_3.IndependentComponentsOn()
volume_property_1_3.SetColor(rainbow)
volume_property_1_3.SetScalarOpacity(ramp_point_2)
volume_property_1_3.SetGradientOpacity(gop)
volume_mapper_1_3 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_1_3.SetSampleDistance(0.25)
volume_mapper_1_3.SetNumberOfThreads(1)
volume_mapper_1_3.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_1_3.SetCroppingRegionFlags(253440)
volume_mapper_1_3.CroppingOn()
volume_mapper_1_3.SetInputConnection(shift_scale.GetOutputPort())
volume_mapper_1_3.SetBlendModeToComposite()
volume_1_3 = vtkVolume()
volume_1_3.SetMapper(volume_mapper_1_3)
volume_1_3.SetProperty(volume_property_1_3)
volume_1_3.AddPosition(30, 90, 0)

# [1][4] — Composite + GO + Shade
volume_property_1_4 = vtkVolumeProperty()
volume_property_1_4.IndependentComponentsOn()
volume_property_1_4.SetColor(rainbow)
volume_property_1_4.SetScalarOpacity(surface)
volume_property_1_4.SetGradientOpacity(gop)
volume_property_1_4.ShadeOn(0)
volume_property_1_4.ShadeOn(1)
volume_property_1_4.ShadeOn(2)
volume_property_1_4.ShadeOn(3)
volume_mapper_1_4 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_1_4.SetSampleDistance(0.25)
volume_mapper_1_4.SetNumberOfThreads(1)
volume_mapper_1_4.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_1_4.SetCroppingRegionFlags(253440)
volume_mapper_1_4.CroppingOn()
volume_mapper_1_4.SetInputConnection(shift_scale.GetOutputPort())
volume_mapper_1_4.SetBlendModeToComposite()
volume_1_4 = vtkVolume()
volume_1_4.SetMapper(volume_mapper_1_4)
volume_1_4.SetProperty(volume_property_1_4)
volume_1_4.AddPosition(30, 120, 0)

# Row 2: two-component dependent data
# [2][0] — MIP
volume_property_2_0 = vtkVolumeProperty()
volume_property_2_0.IndependentComponentsOff()
volume_property_2_0.SetColor(rainbow)
volume_property_2_0.SetScalarOpacity(ramp_1)
volume_property_2_0.SetGradientOpacity(constant_1)
volume_mapper_2_0 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_2_0.SetSampleDistance(0.25)
volume_mapper_2_0.SetNumberOfThreads(1)
volume_mapper_2_0.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_2_0.SetCroppingRegionFlags(253440)
volume_mapper_2_0.CroppingOn()
volume_mapper_2_0.SetInputConnection(iac.GetOutputPort())
volume_mapper_2_0.SetBlendModeToMaximumIntensity()
volume_2_0 = vtkVolume()
volume_2_0.SetMapper(volume_mapper_2_0)
volume_2_0.SetProperty(volume_property_2_0)
volume_2_0.AddPosition(60, 0, 0)

# [2][1] — Composite
volume_property_2_1 = vtkVolumeProperty()
volume_property_2_1.IndependentComponentsOff()
volume_property_2_1.SetColor(rainbow)
volume_property_2_1.SetScalarOpacity(ramp_point_2)
volume_property_2_1.SetGradientOpacity(constant_1)
volume_mapper_2_1 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_2_1.SetSampleDistance(0.25)
volume_mapper_2_1.SetNumberOfThreads(1)
volume_mapper_2_1.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_2_1.SetCroppingRegionFlags(253440)
volume_mapper_2_1.CroppingOn()
volume_mapper_2_1.SetInputConnection(iac.GetOutputPort())
volume_mapper_2_1.SetBlendModeToComposite()
volume_2_1 = vtkVolume()
volume_2_1.SetMapper(volume_mapper_2_1)
volume_2_1.SetProperty(volume_property_2_1)
volume_2_1.AddPosition(60, 30, 0)

# [2][2] — Composite + Shade
volume_property_2_2 = vtkVolumeProperty()
volume_property_2_2.IndependentComponentsOff()
volume_property_2_2.SetColor(rainbow)
volume_property_2_2.SetScalarOpacity(surface)
volume_property_2_2.SetGradientOpacity(constant_1)
volume_property_2_2.ShadeOn()
volume_mapper_2_2 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_2_2.SetSampleDistance(0.25)
volume_mapper_2_2.SetNumberOfThreads(1)
volume_mapper_2_2.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_2_2.SetCroppingRegionFlags(253440)
volume_mapper_2_2.CroppingOn()
volume_mapper_2_2.SetInputConnection(iac.GetOutputPort())
volume_mapper_2_2.SetBlendModeToComposite()
volume_2_2 = vtkVolume()
volume_2_2.SetMapper(volume_mapper_2_2)
volume_2_2.SetProperty(volume_property_2_2)
volume_2_2.AddPosition(60, 60, 0)

# [2][3] — Composite + GO
volume_property_2_3 = vtkVolumeProperty()
volume_property_2_3.IndependentComponentsOff()
volume_property_2_3.SetColor(rainbow)
volume_property_2_3.SetScalarOpacity(ramp_point_2)
volume_property_2_3.SetGradientOpacity(gop)
volume_mapper_2_3 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_2_3.SetSampleDistance(0.25)
volume_mapper_2_3.SetNumberOfThreads(1)
volume_mapper_2_3.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_2_3.SetCroppingRegionFlags(253440)
volume_mapper_2_3.CroppingOn()
volume_mapper_2_3.SetInputConnection(iac.GetOutputPort())
volume_mapper_2_3.SetBlendModeToComposite()
volume_2_3 = vtkVolume()
volume_2_3.SetMapper(volume_mapper_2_3)
volume_2_3.SetProperty(volume_property_2_3)
volume_2_3.AddPosition(60, 90, 0)

# [2][4] — Composite + GO + Shade
volume_property_2_4 = vtkVolumeProperty()
volume_property_2_4.IndependentComponentsOff()
volume_property_2_4.SetColor(rainbow)
volume_property_2_4.SetScalarOpacity(surface)
volume_property_2_4.SetGradientOpacity(gop)
volume_property_2_4.ShadeOn(0)
volume_property_2_4.ShadeOn(1)
volume_property_2_4.ShadeOn(2)
volume_property_2_4.ShadeOn(3)
volume_mapper_2_4 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_2_4.SetSampleDistance(0.25)
volume_mapper_2_4.SetNumberOfThreads(1)
volume_mapper_2_4.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_2_4.SetCroppingRegionFlags(253440)
volume_mapper_2_4.CroppingOn()
volume_mapper_2_4.SetInputConnection(iac.GetOutputPort())
volume_mapper_2_4.SetBlendModeToComposite()
volume_2_4 = vtkVolume()
volume_2_4.SetMapper(volume_mapper_2_4)
volume_2_4.SetProperty(volume_property_2_4)
volume_2_4.AddPosition(60, 120, 0)

# Row 3: four-component independent data
# [3][0] — MIP
volume_property_3_0 = vtkVolumeProperty()
volume_property_3_0.IndependentComponentsOn()
volume_property_3_0.SetColor(0, red)
volume_property_3_0.SetColor(1, green)
volume_property_3_0.SetColor(2, blue)
volume_property_3_0.SetColor(3, yellow)
volume_property_3_0.SetScalarOpacity(0, surface)
volume_property_3_0.SetScalarOpacity(1, surface)
volume_property_3_0.SetScalarOpacity(2, surface)
volume_property_3_0.SetScalarOpacity(3, surface)
volume_property_3_0.SetGradientOpacity(0, constant_1)
volume_property_3_0.SetGradientOpacity(1, constant_1)
volume_property_3_0.SetGradientOpacity(2, constant_1)
volume_property_3_0.SetGradientOpacity(3, constant_1)
volume_property_3_0.SetComponentWeight(0, 1)
volume_property_3_0.SetComponentWeight(1, 1)
volume_property_3_0.SetComponentWeight(2, 1)
volume_property_3_0.SetComponentWeight(3, 1)
volume_mapper_3_0 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_3_0.SetSampleDistance(0.25)
volume_mapper_3_0.SetNumberOfThreads(1)
volume_mapper_3_0.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_3_0.SetCroppingRegionFlags(253440)
volume_mapper_3_0.CroppingOn()
volume_mapper_3_0.SetInputConnection(iac3.GetOutputPort())
volume_mapper_3_0.SetBlendModeToMaximumIntensity()
volume_3_0 = vtkVolume()
volume_3_0.SetMapper(volume_mapper_3_0)
volume_3_0.SetProperty(volume_property_3_0)
volume_3_0.AddPosition(90, 0, 0)

# [3][1] — Composite
volume_property_3_1 = vtkVolumeProperty()
volume_property_3_1.IndependentComponentsOn()
volume_property_3_1.SetColor(0, red)
volume_property_3_1.SetColor(1, green)
volume_property_3_1.SetColor(2, blue)
volume_property_3_1.SetColor(3, yellow)
volume_property_3_1.SetScalarOpacity(0, ramp_point_2)
volume_property_3_1.SetScalarOpacity(1, ramp_point_2)
volume_property_3_1.SetScalarOpacity(2, ramp_point_2)
volume_property_3_1.SetScalarOpacity(3, ramp_point_2)
volume_property_3_1.SetGradientOpacity(0, constant_1)
volume_property_3_1.SetGradientOpacity(1, constant_1)
volume_property_3_1.SetGradientOpacity(2, constant_1)
volume_property_3_1.SetGradientOpacity(3, constant_1)
volume_property_3_1.SetComponentWeight(0, 1)
volume_property_3_1.SetComponentWeight(1, 1)
volume_property_3_1.SetComponentWeight(2, 1)
volume_property_3_1.SetComponentWeight(3, 1)
volume_mapper_3_1 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_3_1.SetSampleDistance(0.25)
volume_mapper_3_1.SetNumberOfThreads(1)
volume_mapper_3_1.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_3_1.SetCroppingRegionFlags(253440)
volume_mapper_3_1.CroppingOn()
volume_mapper_3_1.SetInputConnection(iac3.GetOutputPort())
volume_mapper_3_1.SetBlendModeToComposite()
volume_3_1 = vtkVolume()
volume_3_1.SetMapper(volume_mapper_3_1)
volume_3_1.SetProperty(volume_property_3_1)
volume_3_1.AddPosition(90, 30, 0)

# [3][2] — Composite + Shade
volume_property_3_2 = vtkVolumeProperty()
volume_property_3_2.IndependentComponentsOn()
volume_property_3_2.SetColor(0, red)
volume_property_3_2.SetColor(1, green)
volume_property_3_2.SetColor(2, blue)
volume_property_3_2.SetColor(3, yellow)
volume_property_3_2.SetScalarOpacity(0, surface)
volume_property_3_2.SetScalarOpacity(1, surface)
volume_property_3_2.SetScalarOpacity(2, surface)
volume_property_3_2.SetScalarOpacity(3, surface)
volume_property_3_2.SetGradientOpacity(0, constant_1)
volume_property_3_2.SetGradientOpacity(1, constant_1)
volume_property_3_2.SetGradientOpacity(2, constant_1)
volume_property_3_2.SetGradientOpacity(3, constant_1)
volume_property_3_2.SetComponentWeight(0, 1)
volume_property_3_2.SetComponentWeight(1, 1)
volume_property_3_2.SetComponentWeight(2, 1)
volume_property_3_2.SetComponentWeight(3, 1)
volume_property_3_2.ShadeOn()
volume_mapper_3_2 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_3_2.SetSampleDistance(0.25)
volume_mapper_3_2.SetNumberOfThreads(1)
volume_mapper_3_2.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_3_2.SetCroppingRegionFlags(253440)
volume_mapper_3_2.CroppingOn()
volume_mapper_3_2.SetInputConnection(iac3.GetOutputPort())
volume_mapper_3_2.SetBlendModeToComposite()
volume_3_2 = vtkVolume()
volume_3_2.SetMapper(volume_mapper_3_2)
volume_3_2.SetProperty(volume_property_3_2)
volume_3_2.AddPosition(90, 60, 0)

# [3][3] — Composite + GO
volume_property_3_3 = vtkVolumeProperty()
volume_property_3_3.IndependentComponentsOn()
volume_property_3_3.SetColor(0, red)
volume_property_3_3.SetColor(1, green)
volume_property_3_3.SetColor(2, blue)
volume_property_3_3.SetColor(3, yellow)
volume_property_3_3.SetScalarOpacity(0, ramp_1)
volume_property_3_3.SetScalarOpacity(1, ramp_point_2)
volume_property_3_3.SetScalarOpacity(2, ramp_1)
volume_property_3_3.SetScalarOpacity(3, ramp_point_2)
volume_property_3_3.SetGradientOpacity(0, gop)
volume_property_3_3.SetGradientOpacity(1, constant_1)
volume_property_3_3.SetGradientOpacity(2, gop)
volume_property_3_3.SetGradientOpacity(3, constant_1)
volume_property_3_3.SetComponentWeight(0, 1)
volume_property_3_3.SetComponentWeight(1, 1)
volume_property_3_3.SetComponentWeight(2, 1)
volume_property_3_3.SetComponentWeight(3, 1)
volume_mapper_3_3 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_3_3.SetSampleDistance(0.25)
volume_mapper_3_3.SetNumberOfThreads(1)
volume_mapper_3_3.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_3_3.SetCroppingRegionFlags(253440)
volume_mapper_3_3.CroppingOn()
volume_mapper_3_3.SetInputConnection(iac3.GetOutputPort())
volume_mapper_3_3.SetBlendModeToComposite()
volume_3_3 = vtkVolume()
volume_3_3.SetMapper(volume_mapper_3_3)
volume_3_3.SetProperty(volume_property_3_3)
volume_3_3.AddPosition(90, 90, 0)

# [3][4] — Composite + GO + Shade
volume_property_3_4 = vtkVolumeProperty()
volume_property_3_4.IndependentComponentsOn()
volume_property_3_4.SetColor(0, red)
volume_property_3_4.SetColor(1, green)
volume_property_3_4.SetColor(2, blue)
volume_property_3_4.SetColor(3, yellow)
volume_property_3_4.SetScalarOpacity(0, surface)
volume_property_3_4.SetScalarOpacity(1, surface)
volume_property_3_4.SetScalarOpacity(2, surface)
volume_property_3_4.SetScalarOpacity(3, surface)
volume_property_3_4.SetGradientOpacity(0, gop)
volume_property_3_4.SetGradientOpacity(1, constant_1)
volume_property_3_4.SetGradientOpacity(2, gop)
volume_property_3_4.SetGradientOpacity(3, constant_1)
volume_property_3_4.SetComponentWeight(0, 1)
volume_property_3_4.SetComponentWeight(1, 1)
volume_property_3_4.SetComponentWeight(2, 1)
volume_property_3_4.SetComponentWeight(3, 1)
volume_property_3_4.ShadeOn(0)
volume_property_3_4.ShadeOn(1)
volume_property_3_4.ShadeOn(2)
volume_property_3_4.ShadeOn(3)
volume_mapper_3_4 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_3_4.SetSampleDistance(0.25)
volume_mapper_3_4.SetNumberOfThreads(1)
volume_mapper_3_4.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_3_4.SetCroppingRegionFlags(253440)
volume_mapper_3_4.CroppingOn()
volume_mapper_3_4.SetInputConnection(iac3.GetOutputPort())
volume_mapper_3_4.SetBlendModeToComposite()
volume_3_4 = vtkVolume()
volume_3_4.SetMapper(volume_mapper_3_4)
volume_3_4.SetProperty(volume_property_3_4)
volume_3_4.AddPosition(90, 120, 0)

# Row 4: four-component dependent (RGBA) data
# [4][0] — MIP
volume_property_4_0 = vtkVolumeProperty()
volume_property_4_0.IndependentComponentsOff()
volume_property_4_0.SetColor(rainbow)
volume_property_4_0.SetScalarOpacity(ramp_1)
volume_property_4_0.SetGradientOpacity(constant_1)
volume_mapper_4_0 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_4_0.SetSampleDistance(0.25)
volume_mapper_4_0.SetNumberOfThreads(1)
volume_mapper_4_0.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_4_0.SetCroppingRegionFlags(253440)
volume_mapper_4_0.CroppingOn()
volume_mapper_4_0.SetInputConnection(iac_rgba.GetOutputPort())
volume_mapper_4_0.SetBlendModeToMaximumIntensity()
volume_4_0 = vtkVolume()
volume_4_0.SetMapper(volume_mapper_4_0)
volume_4_0.SetProperty(volume_property_4_0)
volume_4_0.AddPosition(120, 0, 0)

# [4][1] — Composite
volume_property_4_1 = vtkVolumeProperty()
volume_property_4_1.IndependentComponentsOff()
volume_property_4_1.SetColor(rainbow)
volume_property_4_1.SetScalarOpacity(ramp_point_2)
volume_property_4_1.SetGradientOpacity(constant_1)
volume_mapper_4_1 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_4_1.SetSampleDistance(0.25)
volume_mapper_4_1.SetNumberOfThreads(1)
volume_mapper_4_1.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_4_1.SetCroppingRegionFlags(253440)
volume_mapper_4_1.CroppingOn()
volume_mapper_4_1.SetInputConnection(iac_rgba.GetOutputPort())
volume_mapper_4_1.SetBlendModeToComposite()
volume_4_1 = vtkVolume()
volume_4_1.SetMapper(volume_mapper_4_1)
volume_4_1.SetProperty(volume_property_4_1)
volume_4_1.AddPosition(120, 30, 0)

# [4][2] — Composite + Shade
volume_property_4_2 = vtkVolumeProperty()
volume_property_4_2.IndependentComponentsOff()
volume_property_4_2.SetColor(rainbow)
volume_property_4_2.SetScalarOpacity(surface)
volume_property_4_2.SetGradientOpacity(constant_1)
volume_property_4_2.ShadeOn()
volume_mapper_4_2 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_4_2.SetSampleDistance(0.25)
volume_mapper_4_2.SetNumberOfThreads(1)
volume_mapper_4_2.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_4_2.SetCroppingRegionFlags(253440)
volume_mapper_4_2.CroppingOn()
volume_mapper_4_2.SetInputConnection(iac_rgba.GetOutputPort())
volume_mapper_4_2.SetBlendModeToComposite()
volume_4_2 = vtkVolume()
volume_4_2.SetMapper(volume_mapper_4_2)
volume_4_2.SetProperty(volume_property_4_2)
volume_4_2.AddPosition(120, 60, 0)

# [4][3] — Composite + GO
volume_property_4_3 = vtkVolumeProperty()
volume_property_4_3.IndependentComponentsOff()
volume_property_4_3.SetColor(rainbow)
volume_property_4_3.SetScalarOpacity(ramp_point_2)
volume_property_4_3.SetGradientOpacity(gop)
volume_mapper_4_3 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_4_3.SetSampleDistance(0.25)
volume_mapper_4_3.SetNumberOfThreads(1)
volume_mapper_4_3.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_4_3.SetCroppingRegionFlags(253440)
volume_mapper_4_3.CroppingOn()
volume_mapper_4_3.SetInputConnection(iac_rgba.GetOutputPort())
volume_mapper_4_3.SetBlendModeToComposite()
volume_4_3 = vtkVolume()
volume_4_3.SetMapper(volume_mapper_4_3)
volume_4_3.SetProperty(volume_property_4_3)
volume_4_3.AddPosition(120, 90, 0)

# [4][4] — Composite + GO + Shade
volume_property_4_4 = vtkVolumeProperty()
volume_property_4_4.IndependentComponentsOff()
volume_property_4_4.SetColor(rainbow)
volume_property_4_4.SetScalarOpacity(surface)
volume_property_4_4.SetGradientOpacity(gop)
volume_property_4_4.ShadeOn(0)
volume_property_4_4.ShadeOn(1)
volume_property_4_4.ShadeOn(2)
volume_property_4_4.ShadeOn(3)
volume_mapper_4_4 = vtkFixedPointVolumeRayCastMapper()
volume_mapper_4_4.SetSampleDistance(0.25)
volume_mapper_4_4.SetNumberOfThreads(1)
volume_mapper_4_4.SetCroppingRegionPlanes(10, 20, 10, 20, 10, 20)
volume_mapper_4_4.SetCroppingRegionFlags(253440)
volume_mapper_4_4.CroppingOn()
volume_mapper_4_4.SetInputConnection(iac_rgba.GetOutputPort())
volume_mapper_4_4.SetBlendModeToComposite()
volume_4_4 = vtkVolume()
volume_4_4.SetMapper(volume_mapper_4_4)
volume_4_4.SetProperty(volume_property_4_4)
volume_4_4.AddPosition(120, 120, 0)

renderer.AddVolume(volume_0_0)
renderer.AddVolume(volume_0_1)
renderer.AddVolume(volume_0_2)
renderer.AddVolume(volume_0_3)
renderer.AddVolume(volume_0_4)
renderer.AddVolume(volume_1_0)
renderer.AddVolume(volume_1_1)
renderer.AddVolume(volume_1_2)
renderer.AddVolume(volume_1_3)
renderer.AddVolume(volume_1_4)
renderer.AddVolume(volume_2_0)
renderer.AddVolume(volume_2_1)
renderer.AddVolume(volume_2_2)
renderer.AddVolume(volume_2_3)
renderer.AddVolume(volume_2_4)
renderer.AddVolume(volume_3_0)
renderer.AddVolume(volume_3_1)
renderer.AddVolume(volume_3_2)
renderer.AddVolume(volume_3_3)
renderer.AddVolume(volume_3_4)
renderer.AddVolume(volume_4_0)
renderer.AddVolume(volume_4_1)
renderer.AddVolume(volume_4_2)
renderer.AddVolume(volume_4_3)
renderer.AddVolume(volume_4_4)

# Scene
renderer.GetCullers().InitTraversal()
culler = renderer.GetCullers().GetNextItem()
culler.SetSortingStyleToBackToFront()

renderer.ResetCamera()
renderer.GetActiveCamera().Dolly(1.3)
renderer.GetActiveCamera().Azimuth(15)
renderer.GetActiveCamera().Elevation(5)
renderer.ResetCameraClippingRange()

interactor.Initialize()
interactor.Start()
