#!/usr/bin/env python

# Demonstrate PBR edge tint rendering with varying roughness and edge colors using HDR IBL.

import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401

import os

from vtkmodules.vtkFiltersSources import vtkSphereSource
from vtkmodules.vtkIOImage import vtkHDRReader
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkPolyDataMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
    vtkSkybox,
    vtkTexture,
)

data_dir = os.environ.get("VPE_DATA_DIR", os.path.dirname(os.path.abspath(__file__)))

# HDR environment texture
reader = vtkHDRReader()
reader.SetFileName(os.path.join(data_dir, "spiaggia_di_mondello_1k.hdr"))
texture = vtkTexture()
texture.SetColorModeToDirectScalars()
texture.MipmapOn()
texture.InterpolateOn()
texture.SetInputConnection(reader.GetOutputPort())

# Skybox
skybox = vtkSkybox()
skybox.SetFloorRight(0.0, 0.0, 1.0)
skybox.SetProjectionToSphere()
skybox.SetTexture(texture)

# Sphere source
sphere = vtkSphereSource()
sphere.SetThetaResolution(75)
sphere.SetPhiResolution(75)

mapper = vtkPolyDataMapper()
mapper.SetInputConnection(sphere.GetOutputPort())

# Row 0: black edge tint, varying roughness
actor_r0_0 = vtkActor()
actor_r0_0.SetPosition(0, 0.0, 0.0)
actor_r0_0.SetMapper(mapper)
actor_r0_0.GetProperty().SetInterpolationToPBR()
actor_r0_0.GetProperty().SetMetallic(1.0)
actor_r0_0.GetProperty().SetEdgeTint(0.0, 0.0, 0.0)
actor_r0_0.GetProperty().SetRoughness(0.0)

actor_r0_1 = vtkActor()
actor_r0_1.SetPosition(1, 0.0, 0.0)
actor_r0_1.SetMapper(mapper)
actor_r0_1.GetProperty().SetInterpolationToPBR()
actor_r0_1.GetProperty().SetMetallic(1.0)
actor_r0_1.GetProperty().SetEdgeTint(0.0, 0.0, 0.0)
actor_r0_1.GetProperty().SetRoughness(0.2)

actor_r0_2 = vtkActor()
actor_r0_2.SetPosition(2, 0.0, 0.0)
actor_r0_2.SetMapper(mapper)
actor_r0_2.GetProperty().SetInterpolationToPBR()
actor_r0_2.GetProperty().SetMetallic(1.0)
actor_r0_2.GetProperty().SetEdgeTint(0.0, 0.0, 0.0)
actor_r0_2.GetProperty().SetRoughness(0.4)

actor_r0_3 = vtkActor()
actor_r0_3.SetPosition(3, 0.0, 0.0)
actor_r0_3.SetMapper(mapper)
actor_r0_3.GetProperty().SetInterpolationToPBR()
actor_r0_3.GetProperty().SetMetallic(1.0)
actor_r0_3.GetProperty().SetEdgeTint(0.0, 0.0, 0.0)
actor_r0_3.GetProperty().SetRoughness(0.6)

actor_r0_4 = vtkActor()
actor_r0_4.SetPosition(4, 0.0, 0.0)
actor_r0_4.SetMapper(mapper)
actor_r0_4.GetProperty().SetInterpolationToPBR()
actor_r0_4.GetProperty().SetMetallic(1.0)
actor_r0_4.GetProperty().SetEdgeTint(0.0, 0.0, 0.0)
actor_r0_4.GetProperty().SetRoughness(0.8)

actor_r0_5 = vtkActor()
actor_r0_5.SetPosition(5, 0.0, 0.0)
actor_r0_5.SetMapper(mapper)
actor_r0_5.GetProperty().SetInterpolationToPBR()
actor_r0_5.GetProperty().SetMetallic(1.0)
actor_r0_5.GetProperty().SetEdgeTint(0.0, 0.0, 0.0)
actor_r0_5.GetProperty().SetRoughness(1.0)

# Row 1: black color, white edge tint
actor_r1_0 = vtkActor()
actor_r1_0.SetPosition(0, 1.0, 0.0)
actor_r1_0.SetMapper(mapper)
actor_r1_0.GetProperty().SetInterpolationToPBR()
actor_r1_0.GetProperty().SetMetallic(1.0)
actor_r1_0.GetProperty().SetColor(0.0, 0.0, 0.0)
actor_r1_0.GetProperty().SetEdgeTint(1.0, 1.0, 1.0)
actor_r1_0.GetProperty().SetRoughness(0.0)

actor_r1_1 = vtkActor()
actor_r1_1.SetPosition(1, 1.0, 0.0)
actor_r1_1.SetMapper(mapper)
actor_r1_1.GetProperty().SetInterpolationToPBR()
actor_r1_1.GetProperty().SetMetallic(1.0)
actor_r1_1.GetProperty().SetColor(0.0, 0.0, 0.0)
actor_r1_1.GetProperty().SetEdgeTint(1.0, 1.0, 1.0)
actor_r1_1.GetProperty().SetRoughness(0.2)

actor_r1_2 = vtkActor()
actor_r1_2.SetPosition(2, 1.0, 0.0)
actor_r1_2.SetMapper(mapper)
actor_r1_2.GetProperty().SetInterpolationToPBR()
actor_r1_2.GetProperty().SetMetallic(1.0)
actor_r1_2.GetProperty().SetColor(0.0, 0.0, 0.0)
actor_r1_2.GetProperty().SetEdgeTint(1.0, 1.0, 1.0)
actor_r1_2.GetProperty().SetRoughness(0.4)

actor_r1_3 = vtkActor()
actor_r1_3.SetPosition(3, 1.0, 0.0)
actor_r1_3.SetMapper(mapper)
actor_r1_3.GetProperty().SetInterpolationToPBR()
actor_r1_3.GetProperty().SetMetallic(1.0)
actor_r1_3.GetProperty().SetColor(0.0, 0.0, 0.0)
actor_r1_3.GetProperty().SetEdgeTint(1.0, 1.0, 1.0)
actor_r1_3.GetProperty().SetRoughness(0.6)

actor_r1_4 = vtkActor()
actor_r1_4.SetPosition(4, 1.0, 0.0)
actor_r1_4.SetMapper(mapper)
actor_r1_4.GetProperty().SetInterpolationToPBR()
actor_r1_4.GetProperty().SetMetallic(1.0)
actor_r1_4.GetProperty().SetColor(0.0, 0.0, 0.0)
actor_r1_4.GetProperty().SetEdgeTint(1.0, 1.0, 1.0)
actor_r1_4.GetProperty().SetRoughness(0.8)

actor_r1_5 = vtkActor()
actor_r1_5.SetPosition(5, 1.0, 0.0)
actor_r1_5.SetMapper(mapper)
actor_r1_5.GetProperty().SetInterpolationToPBR()
actor_r1_5.GetProperty().SetMetallic(1.0)
actor_r1_5.GetProperty().SetColor(0.0, 0.0, 0.0)
actor_r1_5.GetProperty().SetEdgeTint(1.0, 1.0, 1.0)
actor_r1_5.GetProperty().SetRoughness(1.0)

# Row 2: blue color, red edge tint
actor_r2_0 = vtkActor()
actor_r2_0.SetPosition(0, 2.0, 0.0)
actor_r2_0.SetMapper(mapper)
actor_r2_0.GetProperty().SetInterpolationToPBR()
actor_r2_0.GetProperty().SetMetallic(1.0)
actor_r2_0.GetProperty().SetColor(0.0, 0.0, 1.0)
actor_r2_0.GetProperty().SetEdgeTint(1.0, 0.0, 0.0)
actor_r2_0.GetProperty().SetRoughness(0.0)

actor_r2_1 = vtkActor()
actor_r2_1.SetPosition(1, 2.0, 0.0)
actor_r2_1.SetMapper(mapper)
actor_r2_1.GetProperty().SetInterpolationToPBR()
actor_r2_1.GetProperty().SetMetallic(1.0)
actor_r2_1.GetProperty().SetColor(0.0, 0.0, 1.0)
actor_r2_1.GetProperty().SetEdgeTint(1.0, 0.0, 0.0)
actor_r2_1.GetProperty().SetRoughness(0.2)

actor_r2_2 = vtkActor()
actor_r2_2.SetPosition(2, 2.0, 0.0)
actor_r2_2.SetMapper(mapper)
actor_r2_2.GetProperty().SetInterpolationToPBR()
actor_r2_2.GetProperty().SetMetallic(1.0)
actor_r2_2.GetProperty().SetColor(0.0, 0.0, 1.0)
actor_r2_2.GetProperty().SetEdgeTint(1.0, 0.0, 0.0)
actor_r2_2.GetProperty().SetRoughness(0.4)

actor_r2_3 = vtkActor()
actor_r2_3.SetPosition(3, 2.0, 0.0)
actor_r2_3.SetMapper(mapper)
actor_r2_3.GetProperty().SetInterpolationToPBR()
actor_r2_3.GetProperty().SetMetallic(1.0)
actor_r2_3.GetProperty().SetColor(0.0, 0.0, 1.0)
actor_r2_3.GetProperty().SetEdgeTint(1.0, 0.0, 0.0)
actor_r2_3.GetProperty().SetRoughness(0.6)

actor_r2_4 = vtkActor()
actor_r2_4.SetPosition(4, 2.0, 0.0)
actor_r2_4.SetMapper(mapper)
actor_r2_4.GetProperty().SetInterpolationToPBR()
actor_r2_4.GetProperty().SetMetallic(1.0)
actor_r2_4.GetProperty().SetColor(0.0, 0.0, 1.0)
actor_r2_4.GetProperty().SetEdgeTint(1.0, 0.0, 0.0)
actor_r2_4.GetProperty().SetRoughness(0.8)

actor_r2_5 = vtkActor()
actor_r2_5.SetPosition(5, 2.0, 0.0)
actor_r2_5.SetMapper(mapper)
actor_r2_5.GetProperty().SetInterpolationToPBR()
actor_r2_5.GetProperty().SetMetallic(1.0)
actor_r2_5.GetProperty().SetColor(0.0, 0.0, 1.0)
actor_r2_5.GetProperty().SetEdgeTint(1.0, 0.0, 0.0)
actor_r2_5.GetProperty().SetRoughness(1.0)

# Row 3: red color, blue edge tint
actor_r3_0 = vtkActor()
actor_r3_0.SetPosition(0, 3.0, 0.0)
actor_r3_0.SetMapper(mapper)
actor_r3_0.GetProperty().SetInterpolationToPBR()
actor_r3_0.GetProperty().SetMetallic(1.0)
actor_r3_0.GetProperty().SetColor(1.0, 0.0, 0.0)
actor_r3_0.GetProperty().SetEdgeTint(0.0, 0.0, 1.0)
actor_r3_0.GetProperty().SetRoughness(0.0)

actor_r3_1 = vtkActor()
actor_r3_1.SetPosition(1, 3.0, 0.0)
actor_r3_1.SetMapper(mapper)
actor_r3_1.GetProperty().SetInterpolationToPBR()
actor_r3_1.GetProperty().SetMetallic(1.0)
actor_r3_1.GetProperty().SetColor(1.0, 0.0, 0.0)
actor_r3_1.GetProperty().SetEdgeTint(0.0, 0.0, 1.0)
actor_r3_1.GetProperty().SetRoughness(0.2)

actor_r3_2 = vtkActor()
actor_r3_2.SetPosition(2, 3.0, 0.0)
actor_r3_2.SetMapper(mapper)
actor_r3_2.GetProperty().SetInterpolationToPBR()
actor_r3_2.GetProperty().SetMetallic(1.0)
actor_r3_2.GetProperty().SetColor(1.0, 0.0, 0.0)
actor_r3_2.GetProperty().SetEdgeTint(0.0, 0.0, 1.0)
actor_r3_2.GetProperty().SetRoughness(0.4)

actor_r3_3 = vtkActor()
actor_r3_3.SetPosition(3, 3.0, 0.0)
actor_r3_3.SetMapper(mapper)
actor_r3_3.GetProperty().SetInterpolationToPBR()
actor_r3_3.GetProperty().SetMetallic(1.0)
actor_r3_3.GetProperty().SetColor(1.0, 0.0, 0.0)
actor_r3_3.GetProperty().SetEdgeTint(0.0, 0.0, 1.0)
actor_r3_3.GetProperty().SetRoughness(0.6)

actor_r3_4 = vtkActor()
actor_r3_4.SetPosition(4, 3.0, 0.0)
actor_r3_4.SetMapper(mapper)
actor_r3_4.GetProperty().SetInterpolationToPBR()
actor_r3_4.GetProperty().SetMetallic(1.0)
actor_r3_4.GetProperty().SetColor(1.0, 0.0, 0.0)
actor_r3_4.GetProperty().SetEdgeTint(0.0, 0.0, 1.0)
actor_r3_4.GetProperty().SetRoughness(0.8)

actor_r3_5 = vtkActor()
actor_r3_5.SetPosition(5, 3.0, 0.0)
actor_r3_5.SetMapper(mapper)
actor_r3_5.GetProperty().SetInterpolationToPBR()
actor_r3_5.GetProperty().SetMetallic(1.0)
actor_r3_5.GetProperty().SetColor(1.0, 0.0, 0.0)
actor_r3_5.GetProperty().SetEdgeTint(0.0, 0.0, 1.0)
actor_r3_5.GetProperty().SetRoughness(1.0)

# Row 4: black color, yellow edge tint
actor_r4_0 = vtkActor()
actor_r4_0.SetPosition(0, 4.0, 0.0)
actor_r4_0.SetMapper(mapper)
actor_r4_0.GetProperty().SetInterpolationToPBR()
actor_r4_0.GetProperty().SetMetallic(1.0)
actor_r4_0.GetProperty().SetColor(0.0, 0.0, 0.0)
actor_r4_0.GetProperty().SetEdgeTint(1.0, 1.0, 0.0)
actor_r4_0.GetProperty().SetRoughness(0.0)

actor_r4_1 = vtkActor()
actor_r4_1.SetPosition(1, 4.0, 0.0)
actor_r4_1.SetMapper(mapper)
actor_r4_1.GetProperty().SetInterpolationToPBR()
actor_r4_1.GetProperty().SetMetallic(1.0)
actor_r4_1.GetProperty().SetColor(0.0, 0.0, 0.0)
actor_r4_1.GetProperty().SetEdgeTint(1.0, 1.0, 0.0)
actor_r4_1.GetProperty().SetRoughness(0.2)

actor_r4_2 = vtkActor()
actor_r4_2.SetPosition(2, 4.0, 0.0)
actor_r4_2.SetMapper(mapper)
actor_r4_2.GetProperty().SetInterpolationToPBR()
actor_r4_2.GetProperty().SetMetallic(1.0)
actor_r4_2.GetProperty().SetColor(0.0, 0.0, 0.0)
actor_r4_2.GetProperty().SetEdgeTint(1.0, 1.0, 0.0)
actor_r4_2.GetProperty().SetRoughness(0.4)

actor_r4_3 = vtkActor()
actor_r4_3.SetPosition(3, 4.0, 0.0)
actor_r4_3.SetMapper(mapper)
actor_r4_3.GetProperty().SetInterpolationToPBR()
actor_r4_3.GetProperty().SetMetallic(1.0)
actor_r4_3.GetProperty().SetColor(0.0, 0.0, 0.0)
actor_r4_3.GetProperty().SetEdgeTint(1.0, 1.0, 0.0)
actor_r4_3.GetProperty().SetRoughness(0.6)

actor_r4_4 = vtkActor()
actor_r4_4.SetPosition(4, 4.0, 0.0)
actor_r4_4.SetMapper(mapper)
actor_r4_4.GetProperty().SetInterpolationToPBR()
actor_r4_4.GetProperty().SetMetallic(1.0)
actor_r4_4.GetProperty().SetColor(0.0, 0.0, 0.0)
actor_r4_4.GetProperty().SetEdgeTint(1.0, 1.0, 0.0)
actor_r4_4.GetProperty().SetRoughness(0.8)

actor_r4_5 = vtkActor()
actor_r4_5.SetPosition(5, 4.0, 0.0)
actor_r4_5.SetMapper(mapper)
actor_r4_5.GetProperty().SetInterpolationToPBR()
actor_r4_5.GetProperty().SetMetallic(1.0)
actor_r4_5.GetProperty().SetColor(0.0, 0.0, 0.0)
actor_r4_5.GetProperty().SetEdgeTint(1.0, 1.0, 0.0)
actor_r4_5.GetProperty().SetRoughness(1.0)

# Renderer with IBL
renderer = vtkRenderer()
renderer.UseSphericalHarmonicsOff()
renderer.GetEnvMapIrradiance().SetIrradianceStep(0.3)
renderer.UseImageBasedLightingOn()
renderer.SetEnvironmentTexture(texture)
renderer.AddActor(skybox)
renderer.AddActor(actor_r0_0)
renderer.AddActor(actor_r0_1)
renderer.AddActor(actor_r0_2)
renderer.AddActor(actor_r0_3)
renderer.AddActor(actor_r0_4)
renderer.AddActor(actor_r0_5)
renderer.AddActor(actor_r1_0)
renderer.AddActor(actor_r1_1)
renderer.AddActor(actor_r1_2)
renderer.AddActor(actor_r1_3)
renderer.AddActor(actor_r1_4)
renderer.AddActor(actor_r1_5)
renderer.AddActor(actor_r2_0)
renderer.AddActor(actor_r2_1)
renderer.AddActor(actor_r2_2)
renderer.AddActor(actor_r2_3)
renderer.AddActor(actor_r2_4)
renderer.AddActor(actor_r2_5)
renderer.AddActor(actor_r3_0)
renderer.AddActor(actor_r3_1)
renderer.AddActor(actor_r3_2)
renderer.AddActor(actor_r3_3)
renderer.AddActor(actor_r3_4)
renderer.AddActor(actor_r3_5)
renderer.AddActor(actor_r4_0)
renderer.AddActor(actor_r4_1)
renderer.AddActor(actor_r4_2)
renderer.AddActor(actor_r4_3)
renderer.AddActor(actor_r4_4)
renderer.AddActor(actor_r4_5)

render_window = vtkRenderWindow()
render_window.SetSize(600, 600)
render_window.AddRenderer(renderer)
render_window.SetWindowName("pbr edge tint opengl")

interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)

interactor.Initialize()
interactor.Start()
