#!/usr/bin/env python

# Demonstrate PBR clear coat materials with varying coat roughness and strength using a skybox.

import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401

import os

from vtkmodules.vtkFiltersSources import vtkSphereSource
from vtkmodules.vtkIOImage import vtkJPEGReader
from vtkmodules.vtkImagingCore import vtkImageFlip
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkPolyDataMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
    vtkSkybox,
    vtkTexture,
)

data_dir = os.environ.get("VPE_DATA_DIR", os.path.dirname(os.path.abspath(__file__)))

# Cubemap environment texture
cubemap = vtkTexture()
cubemap.CubeMapOn()

jpg_px = vtkJPEGReader()
jpg_px.SetFileName(os.path.join(data_dir, "skybox", "posx.jpg"))
flip_px = vtkImageFlip()
flip_px.SetInputConnection(jpg_px.GetOutputPort())
flip_px.SetFilteredAxis(1)
cubemap.SetInputConnection(0, flip_px.GetOutputPort())

jpg_nx = vtkJPEGReader()
jpg_nx.SetFileName(os.path.join(data_dir, "skybox", "negx.jpg"))
flip_nx = vtkImageFlip()
flip_nx.SetInputConnection(jpg_nx.GetOutputPort())
flip_nx.SetFilteredAxis(1)
cubemap.SetInputConnection(1, flip_nx.GetOutputPort())

jpg_py = vtkJPEGReader()
jpg_py.SetFileName(os.path.join(data_dir, "skybox", "posy.jpg"))
flip_py = vtkImageFlip()
flip_py.SetInputConnection(jpg_py.GetOutputPort())
flip_py.SetFilteredAxis(1)
cubemap.SetInputConnection(2, flip_py.GetOutputPort())

jpg_ny = vtkJPEGReader()
jpg_ny.SetFileName(os.path.join(data_dir, "skybox", "negy.jpg"))
flip_ny = vtkImageFlip()
flip_ny.SetInputConnection(jpg_ny.GetOutputPort())
flip_ny.SetFilteredAxis(1)
cubemap.SetInputConnection(3, flip_ny.GetOutputPort())

jpg_pz = vtkJPEGReader()
jpg_pz.SetFileName(os.path.join(data_dir, "skybox", "posz.jpg"))
flip_pz = vtkImageFlip()
flip_pz.SetInputConnection(jpg_pz.GetOutputPort())
flip_pz.SetFilteredAxis(1)
cubemap.SetInputConnection(4, flip_pz.GetOutputPort())

jpg_nz = vtkJPEGReader()
jpg_nz.SetFileName(os.path.join(data_dir, "skybox", "negz.jpg"))
flip_nz = vtkImageFlip()
flip_nz.SetInputConnection(jpg_nz.GetOutputPort())
flip_nz.SetFilteredAxis(1)
cubemap.SetInputConnection(5, flip_nz.GetOutputPort())

# Sphere source
sphere = vtkSphereSource()
sphere.SetThetaResolution(75)
sphere.SetPhiResolution(75)

mapper = vtkPolyDataMapper()
mapper.SetInputConnection(sphere.GetOutputPort())

# Row 0: copper metallic, coat strength=1, varying coat roughness, roughness=0.1
actor_r0_0 = vtkActor()
actor_r0_0.SetPosition(0, 0.0, 0.0)
actor_r0_0.SetMapper(mapper)
actor_r0_0.GetProperty().SetInterpolationToPBR()
actor_r0_0.GetProperty().SetColor(0.72, 0.45, 0.2)
actor_r0_0.GetProperty().SetMetallic(1.0)
actor_r0_0.GetProperty().SetRoughness(0.1)
actor_r0_0.GetProperty().SetCoatStrength(1.0)
actor_r0_0.GetProperty().SetCoatRoughness(0.0)

actor_r0_1 = vtkActor()
actor_r0_1.SetPosition(1, 0.0, 0.0)
actor_r0_1.SetMapper(mapper)
actor_r0_1.GetProperty().SetInterpolationToPBR()
actor_r0_1.GetProperty().SetColor(0.72, 0.45, 0.2)
actor_r0_1.GetProperty().SetMetallic(1.0)
actor_r0_1.GetProperty().SetRoughness(0.1)
actor_r0_1.GetProperty().SetCoatStrength(1.0)
actor_r0_1.GetProperty().SetCoatRoughness(0.2)

actor_r0_2 = vtkActor()
actor_r0_2.SetPosition(2, 0.0, 0.0)
actor_r0_2.SetMapper(mapper)
actor_r0_2.GetProperty().SetInterpolationToPBR()
actor_r0_2.GetProperty().SetColor(0.72, 0.45, 0.2)
actor_r0_2.GetProperty().SetMetallic(1.0)
actor_r0_2.GetProperty().SetRoughness(0.1)
actor_r0_2.GetProperty().SetCoatStrength(1.0)
actor_r0_2.GetProperty().SetCoatRoughness(0.4)

actor_r0_3 = vtkActor()
actor_r0_3.SetPosition(3, 0.0, 0.0)
actor_r0_3.SetMapper(mapper)
actor_r0_3.GetProperty().SetInterpolationToPBR()
actor_r0_3.GetProperty().SetColor(0.72, 0.45, 0.2)
actor_r0_3.GetProperty().SetMetallic(1.0)
actor_r0_3.GetProperty().SetRoughness(0.1)
actor_r0_3.GetProperty().SetCoatStrength(1.0)
actor_r0_3.GetProperty().SetCoatRoughness(0.6)

actor_r0_4 = vtkActor()
actor_r0_4.SetPosition(4, 0.0, 0.0)
actor_r0_4.SetMapper(mapper)
actor_r0_4.GetProperty().SetInterpolationToPBR()
actor_r0_4.GetProperty().SetColor(0.72, 0.45, 0.2)
actor_r0_4.GetProperty().SetMetallic(1.0)
actor_r0_4.GetProperty().SetRoughness(0.1)
actor_r0_4.GetProperty().SetCoatStrength(1.0)
actor_r0_4.GetProperty().SetCoatRoughness(0.8)

actor_r0_5 = vtkActor()
actor_r0_5.SetPosition(5, 0.0, 0.0)
actor_r0_5.SetMapper(mapper)
actor_r0_5.GetProperty().SetInterpolationToPBR()
actor_r0_5.GetProperty().SetColor(0.72, 0.45, 0.2)
actor_r0_5.GetProperty().SetMetallic(1.0)
actor_r0_5.GetProperty().SetRoughness(0.1)
actor_r0_5.GetProperty().SetCoatStrength(1.0)
actor_r0_5.GetProperty().SetCoatRoughness(1.0)

# Row 1: copper metallic, coat strength=1, varying coat roughness, roughness=1.0
actor_r1_0 = vtkActor()
actor_r1_0.SetPosition(0, 1.0, 0.0)
actor_r1_0.SetMapper(mapper)
actor_r1_0.GetProperty().SetInterpolationToPBR()
actor_r1_0.GetProperty().SetColor(0.72, 0.45, 0.2)
actor_r1_0.GetProperty().SetMetallic(1.0)
actor_r1_0.GetProperty().SetRoughness(1.0)
actor_r1_0.GetProperty().SetCoatStrength(1.0)
actor_r1_0.GetProperty().SetCoatRoughness(0.0)

actor_r1_1 = vtkActor()
actor_r1_1.SetPosition(1, 1.0, 0.0)
actor_r1_1.SetMapper(mapper)
actor_r1_1.GetProperty().SetInterpolationToPBR()
actor_r1_1.GetProperty().SetColor(0.72, 0.45, 0.2)
actor_r1_1.GetProperty().SetMetallic(1.0)
actor_r1_1.GetProperty().SetRoughness(1.0)
actor_r1_1.GetProperty().SetCoatStrength(1.0)
actor_r1_1.GetProperty().SetCoatRoughness(0.2)

actor_r1_2 = vtkActor()
actor_r1_2.SetPosition(2, 1.0, 0.0)
actor_r1_2.SetMapper(mapper)
actor_r1_2.GetProperty().SetInterpolationToPBR()
actor_r1_2.GetProperty().SetColor(0.72, 0.45, 0.2)
actor_r1_2.GetProperty().SetMetallic(1.0)
actor_r1_2.GetProperty().SetRoughness(1.0)
actor_r1_2.GetProperty().SetCoatStrength(1.0)
actor_r1_2.GetProperty().SetCoatRoughness(0.4)

actor_r1_3 = vtkActor()
actor_r1_3.SetPosition(3, 1.0, 0.0)
actor_r1_3.SetMapper(mapper)
actor_r1_3.GetProperty().SetInterpolationToPBR()
actor_r1_3.GetProperty().SetColor(0.72, 0.45, 0.2)
actor_r1_3.GetProperty().SetMetallic(1.0)
actor_r1_3.GetProperty().SetRoughness(1.0)
actor_r1_3.GetProperty().SetCoatStrength(1.0)
actor_r1_3.GetProperty().SetCoatRoughness(0.6)

actor_r1_4 = vtkActor()
actor_r1_4.SetPosition(4, 1.0, 0.0)
actor_r1_4.SetMapper(mapper)
actor_r1_4.GetProperty().SetInterpolationToPBR()
actor_r1_4.GetProperty().SetColor(0.72, 0.45, 0.2)
actor_r1_4.GetProperty().SetMetallic(1.0)
actor_r1_4.GetProperty().SetRoughness(1.0)
actor_r1_4.GetProperty().SetCoatStrength(1.0)
actor_r1_4.GetProperty().SetCoatRoughness(0.8)

actor_r1_5 = vtkActor()
actor_r1_5.SetPosition(5, 1.0, 0.0)
actor_r1_5.SetMapper(mapper)
actor_r1_5.GetProperty().SetInterpolationToPBR()
actor_r1_5.GetProperty().SetColor(0.72, 0.45, 0.2)
actor_r1_5.GetProperty().SetMetallic(1.0)
actor_r1_5.GetProperty().SetRoughness(1.0)
actor_r1_5.GetProperty().SetCoatStrength(1.0)
actor_r1_5.GetProperty().SetCoatRoughness(1.0)

# Row 2: metallic, red coat color, varying coat strength
actor_r2_0 = vtkActor()
actor_r2_0.SetPosition(0, 2.0, 0.0)
actor_r2_0.SetMapper(mapper)
actor_r2_0.GetProperty().SetInterpolationToPBR()
actor_r2_0.GetProperty().SetMetallic(1.0)
actor_r2_0.GetProperty().SetRoughness(0.1)
actor_r2_0.GetProperty().SetCoatColor(1.0, 0.0, 0.0)
actor_r2_0.GetProperty().SetCoatRoughness(0.1)
actor_r2_0.GetProperty().SetCoatStrength(0.0)

actor_r2_1 = vtkActor()
actor_r2_1.SetPosition(1, 2.0, 0.0)
actor_r2_1.SetMapper(mapper)
actor_r2_1.GetProperty().SetInterpolationToPBR()
actor_r2_1.GetProperty().SetMetallic(1.0)
actor_r2_1.GetProperty().SetRoughness(0.1)
actor_r2_1.GetProperty().SetCoatColor(1.0, 0.0, 0.0)
actor_r2_1.GetProperty().SetCoatRoughness(0.1)
actor_r2_1.GetProperty().SetCoatStrength(0.2)

actor_r2_2 = vtkActor()
actor_r2_2.SetPosition(2, 2.0, 0.0)
actor_r2_2.SetMapper(mapper)
actor_r2_2.GetProperty().SetInterpolationToPBR()
actor_r2_2.GetProperty().SetMetallic(1.0)
actor_r2_2.GetProperty().SetRoughness(0.1)
actor_r2_2.GetProperty().SetCoatColor(1.0, 0.0, 0.0)
actor_r2_2.GetProperty().SetCoatRoughness(0.1)
actor_r2_2.GetProperty().SetCoatStrength(0.4)

actor_r2_3 = vtkActor()
actor_r2_3.SetPosition(3, 2.0, 0.0)
actor_r2_3.SetMapper(mapper)
actor_r2_3.GetProperty().SetInterpolationToPBR()
actor_r2_3.GetProperty().SetMetallic(1.0)
actor_r2_3.GetProperty().SetRoughness(0.1)
actor_r2_3.GetProperty().SetCoatColor(1.0, 0.0, 0.0)
actor_r2_3.GetProperty().SetCoatRoughness(0.1)
actor_r2_3.GetProperty().SetCoatStrength(0.6)

actor_r2_4 = vtkActor()
actor_r2_4.SetPosition(4, 2.0, 0.0)
actor_r2_4.SetMapper(mapper)
actor_r2_4.GetProperty().SetInterpolationToPBR()
actor_r2_4.GetProperty().SetMetallic(1.0)
actor_r2_4.GetProperty().SetRoughness(0.1)
actor_r2_4.GetProperty().SetCoatColor(1.0, 0.0, 0.0)
actor_r2_4.GetProperty().SetCoatRoughness(0.1)
actor_r2_4.GetProperty().SetCoatStrength(0.8)

actor_r2_5 = vtkActor()
actor_r2_5.SetPosition(5, 2.0, 0.0)
actor_r2_5.SetMapper(mapper)
actor_r2_5.GetProperty().SetInterpolationToPBR()
actor_r2_5.GetProperty().SetMetallic(1.0)
actor_r2_5.GetProperty().SetRoughness(0.1)
actor_r2_5.GetProperty().SetCoatColor(1.0, 0.0, 0.0)
actor_r2_5.GetProperty().SetCoatRoughness(0.1)
actor_r2_5.GetProperty().SetCoatStrength(1.0)

# Row 3: red coat color, coat roughness=1.0, varying coat strength
actor_r3_0 = vtkActor()
actor_r3_0.SetPosition(0, 3.0, 0.0)
actor_r3_0.SetMapper(mapper)
actor_r3_0.GetProperty().SetInterpolationToPBR()
actor_r3_0.GetProperty().SetRoughness(0.1)
actor_r3_0.GetProperty().SetCoatColor(1.0, 0.0, 0.0)
actor_r3_0.GetProperty().SetCoatRoughness(1.0)
actor_r3_0.GetProperty().SetCoatStrength(0.0)

actor_r3_1 = vtkActor()
actor_r3_1.SetPosition(1, 3.0, 0.0)
actor_r3_1.SetMapper(mapper)
actor_r3_1.GetProperty().SetInterpolationToPBR()
actor_r3_1.GetProperty().SetRoughness(0.1)
actor_r3_1.GetProperty().SetCoatColor(1.0, 0.0, 0.0)
actor_r3_1.GetProperty().SetCoatRoughness(1.0)
actor_r3_1.GetProperty().SetCoatStrength(0.2)

actor_r3_2 = vtkActor()
actor_r3_2.SetPosition(2, 3.0, 0.0)
actor_r3_2.SetMapper(mapper)
actor_r3_2.GetProperty().SetInterpolationToPBR()
actor_r3_2.GetProperty().SetRoughness(0.1)
actor_r3_2.GetProperty().SetCoatColor(1.0, 0.0, 0.0)
actor_r3_2.GetProperty().SetCoatRoughness(1.0)
actor_r3_2.GetProperty().SetCoatStrength(0.4)

actor_r3_3 = vtkActor()
actor_r3_3.SetPosition(3, 3.0, 0.0)
actor_r3_3.SetMapper(mapper)
actor_r3_3.GetProperty().SetInterpolationToPBR()
actor_r3_3.GetProperty().SetRoughness(0.1)
actor_r3_3.GetProperty().SetCoatColor(1.0, 0.0, 0.0)
actor_r3_3.GetProperty().SetCoatRoughness(1.0)
actor_r3_3.GetProperty().SetCoatStrength(0.6)

actor_r3_4 = vtkActor()
actor_r3_4.SetPosition(4, 3.0, 0.0)
actor_r3_4.SetMapper(mapper)
actor_r3_4.GetProperty().SetInterpolationToPBR()
actor_r3_4.GetProperty().SetRoughness(0.1)
actor_r3_4.GetProperty().SetCoatColor(1.0, 0.0, 0.0)
actor_r3_4.GetProperty().SetCoatRoughness(1.0)
actor_r3_4.GetProperty().SetCoatStrength(0.8)

actor_r3_5 = vtkActor()
actor_r3_5.SetPosition(5, 3.0, 0.0)
actor_r3_5.SetMapper(mapper)
actor_r3_5.GetProperty().SetInterpolationToPBR()
actor_r3_5.GetProperty().SetRoughness(0.1)
actor_r3_5.GetProperty().SetCoatColor(1.0, 0.0, 0.0)
actor_r3_5.GetProperty().SetCoatRoughness(1.0)
actor_r3_5.GetProperty().SetCoatStrength(1.0)

# Row 4: green dielectric, varying base IOR
actor_r4_0 = vtkActor()
actor_r4_0.SetPosition(0, 4.0, 0.0)
actor_r4_0.SetMapper(mapper)
actor_r4_0.GetProperty().SetInterpolationToPBR()
actor_r4_0.GetProperty().SetColor(0.0, 0.5, 0.30)
actor_r4_0.GetProperty().SetBaseIOR(1.0)

actor_r4_1 = vtkActor()
actor_r4_1.SetPosition(1, 4.0, 0.0)
actor_r4_1.SetMapper(mapper)
actor_r4_1.GetProperty().SetInterpolationToPBR()
actor_r4_1.GetProperty().SetColor(0.0, 0.5, 0.30)
actor_r4_1.GetProperty().SetBaseIOR(1.3333333333333333)

actor_r4_2 = vtkActor()
actor_r4_2.SetPosition(2, 4.0, 0.0)
actor_r4_2.SetMapper(mapper)
actor_r4_2.GetProperty().SetInterpolationToPBR()
actor_r4_2.GetProperty().SetColor(0.0, 0.5, 0.30)
actor_r4_2.GetProperty().SetBaseIOR(1.6666666666666667)

actor_r4_3 = vtkActor()
actor_r4_3.SetPosition(3, 4.0, 0.0)
actor_r4_3.SetMapper(mapper)
actor_r4_3.GetProperty().SetInterpolationToPBR()
actor_r4_3.GetProperty().SetColor(0.0, 0.5, 0.30)
actor_r4_3.GetProperty().SetBaseIOR(2.0)

actor_r4_4 = vtkActor()
actor_r4_4.SetPosition(4, 4.0, 0.0)
actor_r4_4.SetMapper(mapper)
actor_r4_4.GetProperty().SetInterpolationToPBR()
actor_r4_4.GetProperty().SetColor(0.0, 0.5, 0.30)
actor_r4_4.GetProperty().SetBaseIOR(2.3333333333333335)

actor_r4_5 = vtkActor()
actor_r4_5.SetPosition(5, 4.0, 0.0)
actor_r4_5.SetMapper(mapper)
actor_r4_5.GetProperty().SetInterpolationToPBR()
actor_r4_5.GetProperty().SetColor(0.0, 0.5, 0.30)
actor_r4_5.GetProperty().SetBaseIOR(2.6666666666666665)

# Skybox
skybox = vtkSkybox()
skybox.SetTexture(cubemap)

# Renderer with IBL
renderer = vtkRenderer()
renderer.GetEnvMapIrradiance().SetIrradianceStep(0.3)
renderer.UseSphericalHarmonicsOff()
renderer.SetEnvironmentTexture(cubemap, True)
renderer.UseImageBasedLightingOn()
renderer.AddActor(actor_r0_0)
renderer.AddActor(actor_r0_1)
renderer.AddActor(actor_r0_2)
renderer.AddActor(actor_r0_3)
renderer.AddActor(actor_r0_4)
renderer.AddActor(actor_r0_5)
renderer.AddActor(actor_r1_0)
renderer.AddActor(actor_r1_1)
renderer.AddActor(actor_r1_2)
renderer.AddActor(actor_r1_3)
renderer.AddActor(actor_r1_4)
renderer.AddActor(actor_r1_5)
renderer.AddActor(actor_r2_0)
renderer.AddActor(actor_r2_1)
renderer.AddActor(actor_r2_2)
renderer.AddActor(actor_r2_3)
renderer.AddActor(actor_r2_4)
renderer.AddActor(actor_r2_5)
renderer.AddActor(actor_r3_0)
renderer.AddActor(actor_r3_1)
renderer.AddActor(actor_r3_2)
renderer.AddActor(actor_r3_3)
renderer.AddActor(actor_r3_4)
renderer.AddActor(actor_r3_5)
renderer.AddActor(actor_r4_0)
renderer.AddActor(actor_r4_1)
renderer.AddActor(actor_r4_2)
renderer.AddActor(actor_r4_3)
renderer.AddActor(actor_r4_4)
renderer.AddActor(actor_r4_5)
renderer.AddActor(skybox)

render_window = vtkRenderWindow()
render_window.SetSize(600, 600)
render_window.AddRenderer(renderer)
render_window.SetWindowName("pbr materials coat opengl")

interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)

interactor.Initialize()
interactor.Start()
