#!/usr/bin/env python

# Clip geometry using boolean textures and two implicit quadric functions.

# Factory overrides: importing these modules registers the OpenGL rendering
# and interaction style implementations for vtkRenderingCore factory classes.
import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401

# VTK pipeline classes used in this example
from vtkmodules.vtkCommonDataModel import vtkQuadric
from vtkmodules.vtkFiltersSources import vtkSphereSource
from vtkmodules.vtkFiltersTexture import vtkImplicitTextureCoords
from vtkmodules.vtkImagingHybrid import vtkBooleanTexture
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkDataSetMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
    vtkTexture,
)

# Colors (normalized RGB)
slate_gray_rgb = (0.439, 0.502, 0.565)
misty_rose_rgb = (1.0, 0.894, 0.882)

# Boolean texture region definitions
SOLID = [255, 255]
CLEAR = [255, 0]
EDGE = [0, 255]

# Quadrics: define two elliptical cylinders as the R and S implicit functions
quadric1 = vtkQuadric()
quadric1.SetCoefficients(1, 2, 0, 0, 0, 0, 0, 0, 0, -0.07)

quadric2 = vtkQuadric()
quadric2.SetCoefficients(2, 1, 0, 0, 0, 0, 0, 0, 0, -0.07)

# Source: a single sphere shared by all 16 actors
sphere = vtkSphereSource()
sphere.SetPhiResolution(21)
sphere.SetThetaResolution(21)

# ImplicitTextureCoords: generate 2D texture coordinates from the two quadrics
tcoords = vtkImplicitTextureCoords()
tcoords.SetInputConnection(sphere.GetOutputPort())
tcoords.SetRFunction(quadric1)
tcoords.SetSFunction(quadric2)

# Mapper: shared by all 16 actors
mapper = vtkDataSetMapper()
mapper.SetInputConnection(tcoords.GetOutputPort())

# --- Case 0 ---
bool_tex_0 = vtkBooleanTexture()
bool_tex_0.SetXSize(64)
bool_tex_0.SetYSize(64)
bool_tex_0.SetThickness(0)
bool_tex_0.SetInIn(SOLID)
bool_tex_0.SetOutIn(SOLID)
bool_tex_0.SetInOut(SOLID)
bool_tex_0.SetOutOut(SOLID)
bool_tex_0.SetOnOn(SOLID)
bool_tex_0.SetOnIn(SOLID)
bool_tex_0.SetOnOut(SOLID)
bool_tex_0.SetInOn(SOLID)
bool_tex_0.SetOutOn(SOLID)
texture_0 = vtkTexture()
texture_0.SetInputConnection(bool_tex_0.GetOutputPort())
texture_0.InterpolateOff()
texture_0.RepeatOff()
actor_0 = vtkActor()
actor_0.SetMapper(mapper)
actor_0.SetTexture(texture_0)
actor_0.SetPosition(-4, 4, 0)
actor_0.SetScale(2.0, 2.0, 2.0)
actor_0.GetProperty().SetColor(misty_rose_rgb)

# --- Case 1 ---
bool_tex_1 = vtkBooleanTexture()
bool_tex_1.SetXSize(64)
bool_tex_1.SetYSize(64)
bool_tex_1.SetThickness(0)
bool_tex_1.SetInIn(CLEAR)
bool_tex_1.SetOutIn(SOLID)
bool_tex_1.SetInOut(SOLID)
bool_tex_1.SetOutOut(SOLID)
bool_tex_1.SetOnOn(EDGE)
bool_tex_1.SetOnIn(EDGE)
bool_tex_1.SetOnOut(SOLID)
bool_tex_1.SetInOn(EDGE)
bool_tex_1.SetOutOn(SOLID)
texture_1 = vtkTexture()
texture_1.SetInputConnection(bool_tex_1.GetOutputPort())
texture_1.InterpolateOff()
texture_1.RepeatOff()
actor_1 = vtkActor()
actor_1.SetMapper(mapper)
actor_1.SetTexture(texture_1)
actor_1.SetPosition(-2, 4, 0)
actor_1.SetScale(2.0, 2.0, 2.0)
actor_1.GetProperty().SetColor(misty_rose_rgb)

# --- Case 2 ---
bool_tex_2 = vtkBooleanTexture()
bool_tex_2.SetXSize(64)
bool_tex_2.SetYSize(64)
bool_tex_2.SetThickness(0)
bool_tex_2.SetInIn(SOLID)
bool_tex_2.SetOutIn(CLEAR)
bool_tex_2.SetInOut(SOLID)
bool_tex_2.SetOutOut(SOLID)
bool_tex_2.SetOnOn(EDGE)
bool_tex_2.SetOnIn(EDGE)
bool_tex_2.SetOnOut(SOLID)
bool_tex_2.SetInOn(SOLID)
bool_tex_2.SetOutOn(EDGE)
texture_2 = vtkTexture()
texture_2.SetInputConnection(bool_tex_2.GetOutputPort())
texture_2.InterpolateOff()
texture_2.RepeatOff()
actor_2 = vtkActor()
actor_2.SetMapper(mapper)
actor_2.SetTexture(texture_2)
actor_2.SetPosition(0, 4, 0)
actor_2.SetScale(2.0, 2.0, 2.0)
actor_2.GetProperty().SetColor(misty_rose_rgb)

# --- Case 3 ---
bool_tex_3 = vtkBooleanTexture()
bool_tex_3.SetXSize(64)
bool_tex_3.SetYSize(64)
bool_tex_3.SetThickness(0)
bool_tex_3.SetInIn(CLEAR)
bool_tex_3.SetOutIn(CLEAR)
bool_tex_3.SetInOut(SOLID)
bool_tex_3.SetOutOut(SOLID)
bool_tex_3.SetOnOn(EDGE)
bool_tex_3.SetOnIn(CLEAR)
bool_tex_3.SetOnOut(SOLID)
bool_tex_3.SetInOn(EDGE)
bool_tex_3.SetOutOn(EDGE)
texture_3 = vtkTexture()
texture_3.SetInputConnection(bool_tex_3.GetOutputPort())
texture_3.InterpolateOff()
texture_3.RepeatOff()
actor_3 = vtkActor()
actor_3.SetMapper(mapper)
actor_3.SetTexture(texture_3)
actor_3.SetPosition(2, 4, 0)
actor_3.SetScale(2.0, 2.0, 2.0)
actor_3.GetProperty().SetColor(misty_rose_rgb)

# --- Case 4 ---
bool_tex_4 = vtkBooleanTexture()
bool_tex_4.SetXSize(64)
bool_tex_4.SetYSize(64)
bool_tex_4.SetThickness(0)
bool_tex_4.SetInIn(SOLID)
bool_tex_4.SetOutIn(SOLID)
bool_tex_4.SetInOut(CLEAR)
bool_tex_4.SetOutOut(SOLID)
bool_tex_4.SetOnOn(EDGE)
bool_tex_4.SetOnIn(SOLID)
bool_tex_4.SetOnOut(EDGE)
bool_tex_4.SetInOn(EDGE)
bool_tex_4.SetOutOn(SOLID)
texture_4 = vtkTexture()
texture_4.SetInputConnection(bool_tex_4.GetOutputPort())
texture_4.InterpolateOff()
texture_4.RepeatOff()
actor_4 = vtkActor()
actor_4.SetMapper(mapper)
actor_4.SetTexture(texture_4)
actor_4.SetPosition(-4, 2, 0)
actor_4.SetScale(2.0, 2.0, 2.0)
actor_4.GetProperty().SetColor(misty_rose_rgb)

# --- Case 5 ---
bool_tex_5 = vtkBooleanTexture()
bool_tex_5.SetXSize(64)
bool_tex_5.SetYSize(64)
bool_tex_5.SetThickness(0)
bool_tex_5.SetInIn(CLEAR)
bool_tex_5.SetOutIn(SOLID)
bool_tex_5.SetInOut(CLEAR)
bool_tex_5.SetOutOut(SOLID)
bool_tex_5.SetOnOn(EDGE)
bool_tex_5.SetOnIn(EDGE)
bool_tex_5.SetOnOut(EDGE)
bool_tex_5.SetInOn(CLEAR)
bool_tex_5.SetOutOn(SOLID)
texture_5 = vtkTexture()
texture_5.SetInputConnection(bool_tex_5.GetOutputPort())
texture_5.InterpolateOff()
texture_5.RepeatOff()
actor_5 = vtkActor()
actor_5.SetMapper(mapper)
actor_5.SetTexture(texture_5)
actor_5.SetPosition(-2, 2, 0)
actor_5.SetScale(2.0, 2.0, 2.0)
actor_5.GetProperty().SetColor(misty_rose_rgb)

# --- Case 6 ---
bool_tex_6 = vtkBooleanTexture()
bool_tex_6.SetXSize(64)
bool_tex_6.SetYSize(64)
bool_tex_6.SetThickness(0)
bool_tex_6.SetInIn(SOLID)
bool_tex_6.SetOutIn(CLEAR)
bool_tex_6.SetInOut(CLEAR)
bool_tex_6.SetOutOut(SOLID)
bool_tex_6.SetOnOn(EDGE)
bool_tex_6.SetOnIn(EDGE)
bool_tex_6.SetOnOut(EDGE)
bool_tex_6.SetInOn(EDGE)
bool_tex_6.SetOutOn(EDGE)
texture_6 = vtkTexture()
texture_6.SetInputConnection(bool_tex_6.GetOutputPort())
texture_6.InterpolateOff()
texture_6.RepeatOff()
actor_6 = vtkActor()
actor_6.SetMapper(mapper)
actor_6.SetTexture(texture_6)
actor_6.SetPosition(0, 2, 0)
actor_6.SetScale(2.0, 2.0, 2.0)
actor_6.GetProperty().SetColor(misty_rose_rgb)

# --- Case 7 ---
bool_tex_7 = vtkBooleanTexture()
bool_tex_7.SetXSize(64)
bool_tex_7.SetYSize(64)
bool_tex_7.SetThickness(0)
bool_tex_7.SetInIn(CLEAR)
bool_tex_7.SetOutIn(CLEAR)
bool_tex_7.SetInOut(CLEAR)
bool_tex_7.SetOutOut(SOLID)
bool_tex_7.SetOnOn(EDGE)
bool_tex_7.SetOnIn(CLEAR)
bool_tex_7.SetOnOut(EDGE)
bool_tex_7.SetInOn(CLEAR)
bool_tex_7.SetOutOn(EDGE)
texture_7 = vtkTexture()
texture_7.SetInputConnection(bool_tex_7.GetOutputPort())
texture_7.InterpolateOff()
texture_7.RepeatOff()
actor_7 = vtkActor()
actor_7.SetMapper(mapper)
actor_7.SetTexture(texture_7)
actor_7.SetPosition(2, 2, 0)
actor_7.SetScale(2.0, 2.0, 2.0)
actor_7.GetProperty().SetColor(misty_rose_rgb)

# --- Case 8 ---
bool_tex_8 = vtkBooleanTexture()
bool_tex_8.SetXSize(64)
bool_tex_8.SetYSize(64)
bool_tex_8.SetThickness(0)
bool_tex_8.SetInIn(SOLID)
bool_tex_8.SetOutIn(SOLID)
bool_tex_8.SetInOut(SOLID)
bool_tex_8.SetOutOut(CLEAR)
bool_tex_8.SetOnOn(EDGE)
bool_tex_8.SetOnIn(SOLID)
bool_tex_8.SetOnOut(EDGE)
bool_tex_8.SetInOn(SOLID)
bool_tex_8.SetOutOn(EDGE)
texture_8 = vtkTexture()
texture_8.SetInputConnection(bool_tex_8.GetOutputPort())
texture_8.InterpolateOff()
texture_8.RepeatOff()
actor_8 = vtkActor()
actor_8.SetMapper(mapper)
actor_8.SetTexture(texture_8)
actor_8.SetPosition(-4, 0, 0)
actor_8.SetScale(2.0, 2.0, 2.0)
actor_8.GetProperty().SetColor(misty_rose_rgb)

# --- Case 9 ---
bool_tex_9 = vtkBooleanTexture()
bool_tex_9.SetXSize(64)
bool_tex_9.SetYSize(64)
bool_tex_9.SetThickness(0)
bool_tex_9.SetInIn(CLEAR)
bool_tex_9.SetOutIn(SOLID)
bool_tex_9.SetInOut(SOLID)
bool_tex_9.SetOutOut(CLEAR)
bool_tex_9.SetOnOn(EDGE)
bool_tex_9.SetOnIn(EDGE)
bool_tex_9.SetOnOut(EDGE)
bool_tex_9.SetInOn(EDGE)
bool_tex_9.SetOutOn(EDGE)
texture_9 = vtkTexture()
texture_9.SetInputConnection(bool_tex_9.GetOutputPort())
texture_9.InterpolateOff()
texture_9.RepeatOff()
actor_9 = vtkActor()
actor_9.SetMapper(mapper)
actor_9.SetTexture(texture_9)
actor_9.SetPosition(-2, 0, 0)
actor_9.SetScale(2.0, 2.0, 2.0)
actor_9.GetProperty().SetColor(misty_rose_rgb)

# --- Case 10 ---
bool_tex_10 = vtkBooleanTexture()
bool_tex_10.SetXSize(64)
bool_tex_10.SetYSize(64)
bool_tex_10.SetThickness(0)
bool_tex_10.SetInIn(SOLID)
bool_tex_10.SetOutIn(CLEAR)
bool_tex_10.SetInOut(SOLID)
bool_tex_10.SetOutOut(CLEAR)
bool_tex_10.SetOnOn(EDGE)
bool_tex_10.SetOnIn(EDGE)
bool_tex_10.SetOnOut(EDGE)
bool_tex_10.SetInOn(SOLID)
bool_tex_10.SetOutOn(CLEAR)
texture_10 = vtkTexture()
texture_10.SetInputConnection(bool_tex_10.GetOutputPort())
texture_10.InterpolateOff()
texture_10.RepeatOff()
actor_10 = vtkActor()
actor_10.SetMapper(mapper)
actor_10.SetTexture(texture_10)
actor_10.SetPosition(0, 0, 0)
actor_10.SetScale(2.0, 2.0, 2.0)
actor_10.GetProperty().SetColor(misty_rose_rgb)

# --- Case 11 ---
bool_tex_11 = vtkBooleanTexture()
bool_tex_11.SetXSize(64)
bool_tex_11.SetYSize(64)
bool_tex_11.SetThickness(0)
bool_tex_11.SetInIn(CLEAR)
bool_tex_11.SetOutIn(CLEAR)
bool_tex_11.SetInOut(SOLID)
bool_tex_11.SetOutOut(CLEAR)
bool_tex_11.SetOnOn(EDGE)
bool_tex_11.SetOnIn(CLEAR)
bool_tex_11.SetOnOut(EDGE)
bool_tex_11.SetInOn(EDGE)
bool_tex_11.SetOutOn(CLEAR)
texture_11 = vtkTexture()
texture_11.SetInputConnection(bool_tex_11.GetOutputPort())
texture_11.InterpolateOff()
texture_11.RepeatOff()
actor_11 = vtkActor()
actor_11.SetMapper(mapper)
actor_11.SetTexture(texture_11)
actor_11.SetPosition(2, 0, 0)
actor_11.SetScale(2.0, 2.0, 2.0)
actor_11.GetProperty().SetColor(misty_rose_rgb)

# --- Case 12 ---
bool_tex_12 = vtkBooleanTexture()
bool_tex_12.SetXSize(64)
bool_tex_12.SetYSize(64)
bool_tex_12.SetThickness(0)
bool_tex_12.SetInIn(SOLID)
bool_tex_12.SetOutIn(SOLID)
bool_tex_12.SetInOut(CLEAR)
bool_tex_12.SetOutOut(CLEAR)
bool_tex_12.SetOnOn(EDGE)
bool_tex_12.SetOnIn(SOLID)
bool_tex_12.SetOnOut(CLEAR)
bool_tex_12.SetInOn(EDGE)
bool_tex_12.SetOutOn(EDGE)
texture_12 = vtkTexture()
texture_12.SetInputConnection(bool_tex_12.GetOutputPort())
texture_12.InterpolateOff()
texture_12.RepeatOff()
actor_12 = vtkActor()
actor_12.SetMapper(mapper)
actor_12.SetTexture(texture_12)
actor_12.SetPosition(-4, -2, 0)
actor_12.SetScale(2.0, 2.0, 2.0)
actor_12.GetProperty().SetColor(misty_rose_rgb)

# --- Case 13 ---
bool_tex_13 = vtkBooleanTexture()
bool_tex_13.SetXSize(64)
bool_tex_13.SetYSize(64)
bool_tex_13.SetThickness(0)
bool_tex_13.SetInIn(CLEAR)
bool_tex_13.SetOutIn(SOLID)
bool_tex_13.SetInOut(CLEAR)
bool_tex_13.SetOutOut(CLEAR)
bool_tex_13.SetOnOn(EDGE)
bool_tex_13.SetOnIn(EDGE)
bool_tex_13.SetOnOut(CLEAR)
bool_tex_13.SetInOn(CLEAR)
bool_tex_13.SetOutOn(EDGE)
texture_13 = vtkTexture()
texture_13.SetInputConnection(bool_tex_13.GetOutputPort())
texture_13.InterpolateOff()
texture_13.RepeatOff()
actor_13 = vtkActor()
actor_13.SetMapper(mapper)
actor_13.SetTexture(texture_13)
actor_13.SetPosition(-2, -2, 0)
actor_13.SetScale(2.0, 2.0, 2.0)
actor_13.GetProperty().SetColor(misty_rose_rgb)

# --- Case 14 ---
bool_tex_14 = vtkBooleanTexture()
bool_tex_14.SetXSize(64)
bool_tex_14.SetYSize(64)
bool_tex_14.SetThickness(0)
bool_tex_14.SetInIn(SOLID)
bool_tex_14.SetOutIn(CLEAR)
bool_tex_14.SetInOut(CLEAR)
bool_tex_14.SetOutOut(CLEAR)
bool_tex_14.SetOnOn(EDGE)
bool_tex_14.SetOnIn(EDGE)
bool_tex_14.SetOnOut(CLEAR)
bool_tex_14.SetInOn(EDGE)
bool_tex_14.SetOutOn(CLEAR)
texture_14 = vtkTexture()
texture_14.SetInputConnection(bool_tex_14.GetOutputPort())
texture_14.InterpolateOff()
texture_14.RepeatOff()
actor_14 = vtkActor()
actor_14.SetMapper(mapper)
actor_14.SetTexture(texture_14)
actor_14.SetPosition(0, -2, 0)
actor_14.SetScale(2.0, 2.0, 2.0)
actor_14.GetProperty().SetColor(misty_rose_rgb)

# --- Case 15 ---
bool_tex_15 = vtkBooleanTexture()
bool_tex_15.SetXSize(64)
bool_tex_15.SetYSize(64)
bool_tex_15.SetThickness(0)
bool_tex_15.SetInIn(CLEAR)
bool_tex_15.SetOutIn(CLEAR)
bool_tex_15.SetInOut(CLEAR)
bool_tex_15.SetOutOut(CLEAR)
bool_tex_15.SetOnOn(CLEAR)
bool_tex_15.SetOnIn(CLEAR)
bool_tex_15.SetOnOut(CLEAR)
bool_tex_15.SetInOn(CLEAR)
bool_tex_15.SetOutOn(CLEAR)
texture_15 = vtkTexture()
texture_15.SetInputConnection(bool_tex_15.GetOutputPort())
texture_15.InterpolateOff()
texture_15.RepeatOff()
actor_15 = vtkActor()
actor_15.SetMapper(mapper)
actor_15.SetTexture(texture_15)
actor_15.SetPosition(2, -2, 0)
actor_15.SetScale(2.0, 2.0, 2.0)
actor_15.GetProperty().SetColor(misty_rose_rgb)

# Renderer: assemble the scene
renderer = vtkRenderer()
renderer.AddActor(actor_0)
renderer.AddActor(actor_1)
renderer.AddActor(actor_2)
renderer.AddActor(actor_3)
renderer.AddActor(actor_4)
renderer.AddActor(actor_5)
renderer.AddActor(actor_6)
renderer.AddActor(actor_7)
renderer.AddActor(actor_8)
renderer.AddActor(actor_9)
renderer.AddActor(actor_10)
renderer.AddActor(actor_11)
renderer.AddActor(actor_12)
renderer.AddActor(actor_13)
renderer.AddActor(actor_14)
renderer.AddActor(actor_15)
renderer.SetBackground(slate_gray_rgb)

# Window: display the rendered scene
render_window = vtkRenderWindow()
render_window.AddRenderer(renderer)
render_window.SetWindowName("texture cut quadric")
render_window.SetMultiSamples(0)
render_window.SetSize(640, 480)

# Interactor: handle mouse and keyboard events
render_window_interactor = vtkRenderWindowInteractor()
render_window_interactor.SetRenderWindow(render_window)

# Launch the interactive visualization
render_window_interactor.Initialize()
render_window_interactor.Start()
