#!/usr/bin/env python

# Demonstrate tone mapping render pass with 9 viewports showing different tone mapping modes.

import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401

import math

from vtkmodules.vtkFiltersSources import vtkSphereSource
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkLight,
    vtkPolyDataMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
)
from vtkmodules.vtkRenderingOpenGL2 import (
    vtkCameraPass,
    vtkLightsPass,
    vtkOpaquePass,
    vtkRenderPassCollection,
    vtkSequencePass,
    vtkToneMappingPass,
)

sphere = vtkSphereSource()
sphere.SetThetaResolution(20)
sphere.SetPhiResolution(20)

c = math.cos(math.pi * 2.0 / 3.0)
s = math.sin(math.pi * 2.0 / 3.0)
one_third = 1.0 / 3.0

# Mapper + actor 0
mapper_0 = vtkPolyDataMapper()
mapper_0.SetInputConnection(sphere.GetOutputPort())
actor_0 = vtkActor()
actor_0.SetMapper(mapper_0)
actor_0.GetProperty().SetInterpolationToPBR()

# Mapper + actor 1
mapper_1 = vtkPolyDataMapper()
mapper_1.SetInputConnection(sphere.GetOutputPort())
actor_1 = vtkActor()
actor_1.SetMapper(mapper_1)
actor_1.GetProperty().SetInterpolationToPBR()

# Mapper + actor 2
mapper_2 = vtkPolyDataMapper()
mapper_2.SetInputConnection(sphere.GetOutputPort())
actor_2 = vtkActor()
actor_2.SetMapper(mapper_2)
actor_2.GetProperty().SetInterpolationToPBR()

# Mapper + actor 3
mapper_3 = vtkPolyDataMapper()
mapper_3.SetInputConnection(sphere.GetOutputPort())
actor_3 = vtkActor()
actor_3.SetMapper(mapper_3)
actor_3.GetProperty().SetInterpolationToPBR()

# Mapper + actor 4
mapper_4 = vtkPolyDataMapper()
mapper_4.SetInputConnection(sphere.GetOutputPort())
actor_4 = vtkActor()
actor_4.SetMapper(mapper_4)
actor_4.GetProperty().SetInterpolationToPBR()

# Mapper + actor 5
mapper_5 = vtkPolyDataMapper()
mapper_5.SetInputConnection(sphere.GetOutputPort())
actor_5 = vtkActor()
actor_5.SetMapper(mapper_5)
actor_5.GetProperty().SetInterpolationToPBR()

# Mapper + actor 6
mapper_6 = vtkPolyDataMapper()
mapper_6.SetInputConnection(sphere.GetOutputPort())
actor_6 = vtkActor()
actor_6.SetMapper(mapper_6)
actor_6.GetProperty().SetInterpolationToPBR()

# Mapper + actor 7
mapper_7 = vtkPolyDataMapper()
mapper_7.SetInputConnection(sphere.GetOutputPort())
actor_7 = vtkActor()
actor_7.SetMapper(mapper_7)
actor_7.GetProperty().SetInterpolationToPBR()

# Mapper + actor 8
mapper_8 = vtkPolyDataMapper()
mapper_8.SetInputConnection(sphere.GetOutputPort())
actor_8 = vtkActor()
actor_8.SetMapper(mapper_8)
actor_8.GetProperty().SetInterpolationToPBR()

# Render pass pipeline 0: Clamp
camera_pass_0 = vtkCameraPass()
seq_0 = vtkSequencePass()
passes_0 = vtkRenderPassCollection()
passes_0.AddItem(vtkLightsPass())
passes_0.AddItem(vtkOpaquePass())
seq_0.SetPasses(passes_0)
camera_pass_0.SetDelegatePass(seq_0)
tone_pass_0 = vtkToneMappingPass()
tone_pass_0.SetToneMappingType(0)
tone_pass_0.SetDelegatePass(camera_pass_0)

# Render pass pipeline 1: Reinhard
camera_pass_1 = vtkCameraPass()
seq_1 = vtkSequencePass()
passes_1 = vtkRenderPassCollection()
passes_1.AddItem(vtkLightsPass())
passes_1.AddItem(vtkOpaquePass())
seq_1.SetPasses(passes_1)
camera_pass_1.SetDelegatePass(seq_1)
tone_pass_1 = vtkToneMappingPass()
tone_pass_1.SetToneMappingType(1)
tone_pass_1.SetDelegatePass(camera_pass_1)

# Render pass pipeline 2: Exponential (exposure 1.0)
camera_pass_2 = vtkCameraPass()
seq_2 = vtkSequencePass()
passes_2 = vtkRenderPassCollection()
passes_2.AddItem(vtkLightsPass())
passes_2.AddItem(vtkOpaquePass())
seq_2.SetPasses(passes_2)
camera_pass_2.SetDelegatePass(seq_2)
tone_pass_2 = vtkToneMappingPass()
tone_pass_2.SetToneMappingType(2)
tone_pass_2.SetExposure(1.0)
tone_pass_2.SetDelegatePass(camera_pass_2)

# Render pass pipeline 3: Exponential (exposure 2.0)
camera_pass_3 = vtkCameraPass()
seq_3 = vtkSequencePass()
passes_3 = vtkRenderPassCollection()
passes_3.AddItem(vtkLightsPass())
passes_3.AddItem(vtkOpaquePass())
seq_3.SetPasses(passes_3)
camera_pass_3.SetDelegatePass(seq_3)
tone_pass_3 = vtkToneMappingPass()
tone_pass_3.SetToneMappingType(2)
tone_pass_3.SetExposure(2.0)
tone_pass_3.SetDelegatePass(camera_pass_3)

# Render pass pipeline 4: GenericFilmic Uncharted2
camera_pass_4 = vtkCameraPass()
seq_4 = vtkSequencePass()
passes_4 = vtkRenderPassCollection()
passes_4.AddItem(vtkLightsPass())
passes_4.AddItem(vtkOpaquePass())
seq_4.SetPasses(passes_4)
camera_pass_4.SetDelegatePass(seq_4)
tone_pass_4 = vtkToneMappingPass()
tone_pass_4.SetToneMappingType(3)
tone_pass_4.SetGenericFilmicUncharted2Presets()
tone_pass_4.SetDelegatePass(camera_pass_4)

# Render pass pipeline 5: GenericFilmic Default
camera_pass_5 = vtkCameraPass()
seq_5 = vtkSequencePass()
passes_5 = vtkRenderPassCollection()
passes_5.AddItem(vtkLightsPass())
passes_5.AddItem(vtkOpaquePass())
seq_5.SetPasses(passes_5)
camera_pass_5.SetDelegatePass(seq_5)
tone_pass_5 = vtkToneMappingPass()
tone_pass_5.SetToneMappingType(3)
tone_pass_5.SetGenericFilmicDefaultPresets()
tone_pass_5.SetDelegatePass(camera_pass_5)

# Render pass pipeline 6: GenericFilmic no ACES
camera_pass_6 = vtkCameraPass()
seq_6 = vtkSequencePass()
passes_6 = vtkRenderPassCollection()
passes_6.AddItem(vtkLightsPass())
passes_6.AddItem(vtkOpaquePass())
seq_6.SetPasses(passes_6)
camera_pass_6.SetDelegatePass(seq_6)
tone_pass_6 = vtkToneMappingPass()
tone_pass_6.SetToneMappingType(3)
tone_pass_6.SetUseACES(False)
tone_pass_6.SetDelegatePass(camera_pass_6)

# Render pass pipeline 7: GenericFilmic Uncharted2 no ACES
camera_pass_7 = vtkCameraPass()
seq_7 = vtkSequencePass()
passes_7 = vtkRenderPassCollection()
passes_7.AddItem(vtkLightsPass())
passes_7.AddItem(vtkOpaquePass())
seq_7.SetPasses(passes_7)
camera_pass_7.SetDelegatePass(seq_7)
tone_pass_7 = vtkToneMappingPass()
tone_pass_7.SetToneMappingType(3)
tone_pass_7.SetGenericFilmicUncharted2Presets()
tone_pass_7.SetUseACES(False)
tone_pass_7.SetDelegatePass(camera_pass_7)

# Render pass pipeline 8: NeutralPBR
camera_pass_8 = vtkCameraPass()
seq_8 = vtkSequencePass()
passes_8 = vtkRenderPassCollection()
passes_8.AddItem(vtkLightsPass())
passes_8.AddItem(vtkOpaquePass())
seq_8.SetPasses(passes_8)
camera_pass_8.SetDelegatePass(seq_8)
tone_pass_8 = vtkToneMappingPass()
tone_pass_8.SetToneMappingType(4)
tone_pass_8.SetDelegatePass(camera_pass_8)

# Renderers
renderer_0 = vtkRenderer()
renderer_0.SetPass(tone_pass_0)
renderer_0.SetViewport(0, 0, one_third, one_third)
renderer_0.AddActor(actor_0)

renderer_1 = vtkRenderer()
renderer_1.SetPass(tone_pass_1)
renderer_1.SetViewport(one_third, 0, 2 * one_third, one_third)
renderer_1.AddActor(actor_1)

renderer_2 = vtkRenderer()
renderer_2.SetPass(tone_pass_2)
renderer_2.SetViewport(2 * one_third, 0, 1.0, one_third)
renderer_2.AddActor(actor_2)

renderer_3 = vtkRenderer()
renderer_3.SetPass(tone_pass_3)
renderer_3.SetViewport(0, one_third, one_third, 2 * one_third)
renderer_3.AddActor(actor_3)

renderer_4 = vtkRenderer()
renderer_4.SetPass(tone_pass_4)
renderer_4.SetViewport(one_third, one_third, 2 * one_third, 2 * one_third)
renderer_4.AddActor(actor_4)

renderer_5 = vtkRenderer()
renderer_5.SetPass(tone_pass_5)
renderer_5.SetViewport(2 * one_third, one_third, 1.0, 2 * one_third)
renderer_5.AddActor(actor_5)

renderer_6 = vtkRenderer()
renderer_6.SetPass(tone_pass_6)
renderer_6.SetViewport(0, 2 * one_third, one_third, 1.0)
renderer_6.AddActor(actor_6)

renderer_7 = vtkRenderer()
renderer_7.SetPass(tone_pass_7)
renderer_7.SetViewport(one_third, 2 * one_third, 2 * one_third, 1.0)
renderer_7.AddActor(actor_7)

renderer_8 = vtkRenderer()
renderer_8.SetPass(tone_pass_8)
renderer_8.SetViewport(2 * one_third, 2 * one_third, 1.0, 1.0)
renderer_8.AddActor(actor_8)

# Render window
render_window = vtkRenderWindow()
render_window.SetSize(900, 900)
render_window.AddRenderer(renderer_0)
render_window.AddRenderer(renderer_1)
render_window.AddRenderer(renderer_2)
render_window.AddRenderer(renderer_3)
render_window.AddRenderer(renderer_4)
render_window.AddRenderer(renderer_5)
render_window.AddRenderer(renderer_6)
render_window.AddRenderer(renderer_7)
render_window.AddRenderer(renderer_8)
render_window.SetWindowName("tone mapping pass")

# Interactor
interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)

# Scene — lights and camera for viewport 0
light_0_f = vtkLight()
light_0_f.SetPosition(0.0, 0.0, 1.0)
light_0_f.SetFocalPoint(0.0, 0.0, 0.0)
light_0_f.SetColor(1.0, 1.0, 1.0)
light_0_f.PositionalOn()
light_0_f.SwitchOn()
light_0_s1 = vtkLight()
light_0_s1.SetPosition(1.0, 0.0, 1.0)
light_0_s1.SetFocalPoint(0.0, 0.0, 0.0)
light_0_s1.SetColor(1.0, 1.0, 1.0)
light_0_s1.PositionalOn()
light_0_s1.SwitchOn()
light_0_s2 = vtkLight()
light_0_s2.SetPosition(c, s, 1.0)
light_0_s2.SetFocalPoint(0.0, 0.0, 0.0)
light_0_s2.SetColor(1.0, 1.0, 1.0)
light_0_s2.PositionalOn()
light_0_s2.SwitchOn()
light_0_s3 = vtkLight()
light_0_s3.SetPosition(c, -s, 1.0)
light_0_s3.SetFocalPoint(0.0, 0.0, 0.0)
light_0_s3.SetColor(1.0, 1.0, 1.0)
light_0_s3.PositionalOn()
light_0_s3.SwitchOn()
renderer_0.AddLight(light_0_f)
renderer_0.AddLight(light_0_s1)
renderer_0.AddLight(light_0_s2)
renderer_0.AddLight(light_0_s3)
renderer_0.ResetCamera()
renderer_0.GetActiveCamera().Zoom(1.3)
renderer_0.ResetCameraClippingRange()

# Scene — lights and camera for viewport 1
light_1_f = vtkLight()
light_1_f.SetPosition(0.0, 0.0, 1.0)
light_1_f.SetFocalPoint(0.0, 0.0, 0.0)
light_1_f.SetColor(1.0, 1.0, 1.0)
light_1_f.PositionalOn()
light_1_f.SwitchOn()
light_1_s1 = vtkLight()
light_1_s1.SetPosition(1.0, 0.0, 1.0)
light_1_s1.SetFocalPoint(0.0, 0.0, 0.0)
light_1_s1.SetColor(1.0, 1.0, 1.0)
light_1_s1.PositionalOn()
light_1_s1.SwitchOn()
light_1_s2 = vtkLight()
light_1_s2.SetPosition(c, s, 1.0)
light_1_s2.SetFocalPoint(0.0, 0.0, 0.0)
light_1_s2.SetColor(1.0, 1.0, 1.0)
light_1_s2.PositionalOn()
light_1_s2.SwitchOn()
light_1_s3 = vtkLight()
light_1_s3.SetPosition(c, -s, 1.0)
light_1_s3.SetFocalPoint(0.0, 0.0, 0.0)
light_1_s3.SetColor(1.0, 1.0, 1.0)
light_1_s3.PositionalOn()
light_1_s3.SwitchOn()
renderer_1.AddLight(light_1_f)
renderer_1.AddLight(light_1_s1)
renderer_1.AddLight(light_1_s2)
renderer_1.AddLight(light_1_s3)
renderer_1.ResetCamera()
renderer_1.GetActiveCamera().Zoom(1.3)
renderer_1.ResetCameraClippingRange()

# Scene — lights and camera for viewport 2
light_2_f = vtkLight()
light_2_f.SetPosition(0.0, 0.0, 1.0)
light_2_f.SetFocalPoint(0.0, 0.0, 0.0)
light_2_f.SetColor(1.0, 1.0, 1.0)
light_2_f.PositionalOn()
light_2_f.SwitchOn()
light_2_s1 = vtkLight()
light_2_s1.SetPosition(1.0, 0.0, 1.0)
light_2_s1.SetFocalPoint(0.0, 0.0, 0.0)
light_2_s1.SetColor(1.0, 1.0, 1.0)
light_2_s1.PositionalOn()
light_2_s1.SwitchOn()
light_2_s2 = vtkLight()
light_2_s2.SetPosition(c, s, 1.0)
light_2_s2.SetFocalPoint(0.0, 0.0, 0.0)
light_2_s2.SetColor(1.0, 1.0, 1.0)
light_2_s2.PositionalOn()
light_2_s2.SwitchOn()
light_2_s3 = vtkLight()
light_2_s3.SetPosition(c, -s, 1.0)
light_2_s3.SetFocalPoint(0.0, 0.0, 0.0)
light_2_s3.SetColor(1.0, 1.0, 1.0)
light_2_s3.PositionalOn()
light_2_s3.SwitchOn()
renderer_2.AddLight(light_2_f)
renderer_2.AddLight(light_2_s1)
renderer_2.AddLight(light_2_s2)
renderer_2.AddLight(light_2_s3)
renderer_2.ResetCamera()
renderer_2.GetActiveCamera().Zoom(1.3)
renderer_2.ResetCameraClippingRange()

# Scene — lights and camera for viewport 3
light_3_f = vtkLight()
light_3_f.SetPosition(0.0, 0.0, 1.0)
light_3_f.SetFocalPoint(0.0, 0.0, 0.0)
light_3_f.SetColor(1.0, 1.0, 1.0)
light_3_f.PositionalOn()
light_3_f.SwitchOn()
light_3_s1 = vtkLight()
light_3_s1.SetPosition(1.0, 0.0, 1.0)
light_3_s1.SetFocalPoint(0.0, 0.0, 0.0)
light_3_s1.SetColor(1.0, 1.0, 1.0)
light_3_s1.PositionalOn()
light_3_s1.SwitchOn()
light_3_s2 = vtkLight()
light_3_s2.SetPosition(c, s, 1.0)
light_3_s2.SetFocalPoint(0.0, 0.0, 0.0)
light_3_s2.SetColor(1.0, 1.0, 1.0)
light_3_s2.PositionalOn()
light_3_s2.SwitchOn()
light_3_s3 = vtkLight()
light_3_s3.SetPosition(c, -s, 1.0)
light_3_s3.SetFocalPoint(0.0, 0.0, 0.0)
light_3_s3.SetColor(1.0, 1.0, 1.0)
light_3_s3.PositionalOn()
light_3_s3.SwitchOn()
renderer_3.AddLight(light_3_f)
renderer_3.AddLight(light_3_s1)
renderer_3.AddLight(light_3_s2)
renderer_3.AddLight(light_3_s3)
renderer_3.ResetCamera()
renderer_3.GetActiveCamera().Zoom(1.3)
renderer_3.ResetCameraClippingRange()

# Scene — lights and camera for viewport 4
light_4_f = vtkLight()
light_4_f.SetPosition(0.0, 0.0, 1.0)
light_4_f.SetFocalPoint(0.0, 0.0, 0.0)
light_4_f.SetColor(1.0, 1.0, 1.0)
light_4_f.PositionalOn()
light_4_f.SwitchOn()
light_4_s1 = vtkLight()
light_4_s1.SetPosition(1.0, 0.0, 1.0)
light_4_s1.SetFocalPoint(0.0, 0.0, 0.0)
light_4_s1.SetColor(1.0, 1.0, 1.0)
light_4_s1.PositionalOn()
light_4_s1.SwitchOn()
light_4_s2 = vtkLight()
light_4_s2.SetPosition(c, s, 1.0)
light_4_s2.SetFocalPoint(0.0, 0.0, 0.0)
light_4_s2.SetColor(1.0, 1.0, 1.0)
light_4_s2.PositionalOn()
light_4_s2.SwitchOn()
light_4_s3 = vtkLight()
light_4_s3.SetPosition(c, -s, 1.0)
light_4_s3.SetFocalPoint(0.0, 0.0, 0.0)
light_4_s3.SetColor(1.0, 1.0, 1.0)
light_4_s3.PositionalOn()
light_4_s3.SwitchOn()
renderer_4.AddLight(light_4_f)
renderer_4.AddLight(light_4_s1)
renderer_4.AddLight(light_4_s2)
renderer_4.AddLight(light_4_s3)
renderer_4.ResetCamera()
renderer_4.GetActiveCamera().Zoom(1.3)
renderer_4.ResetCameraClippingRange()

# Scene — lights and camera for viewport 5
light_5_f = vtkLight()
light_5_f.SetPosition(0.0, 0.0, 1.0)
light_5_f.SetFocalPoint(0.0, 0.0, 0.0)
light_5_f.SetColor(1.0, 1.0, 1.0)
light_5_f.PositionalOn()
light_5_f.SwitchOn()
light_5_s1 = vtkLight()
light_5_s1.SetPosition(1.0, 0.0, 1.0)
light_5_s1.SetFocalPoint(0.0, 0.0, 0.0)
light_5_s1.SetColor(1.0, 1.0, 1.0)
light_5_s1.PositionalOn()
light_5_s1.SwitchOn()
light_5_s2 = vtkLight()
light_5_s2.SetPosition(c, s, 1.0)
light_5_s2.SetFocalPoint(0.0, 0.0, 0.0)
light_5_s2.SetColor(1.0, 1.0, 1.0)
light_5_s2.PositionalOn()
light_5_s2.SwitchOn()
light_5_s3 = vtkLight()
light_5_s3.SetPosition(c, -s, 1.0)
light_5_s3.SetFocalPoint(0.0, 0.0, 0.0)
light_5_s3.SetColor(1.0, 1.0, 1.0)
light_5_s3.PositionalOn()
light_5_s3.SwitchOn()
renderer_5.AddLight(light_5_f)
renderer_5.AddLight(light_5_s1)
renderer_5.AddLight(light_5_s2)
renderer_5.AddLight(light_5_s3)
renderer_5.ResetCamera()
renderer_5.GetActiveCamera().Zoom(1.3)
renderer_5.ResetCameraClippingRange()

# Scene — lights and camera for viewport 6
light_6_f = vtkLight()
light_6_f.SetPosition(0.0, 0.0, 1.0)
light_6_f.SetFocalPoint(0.0, 0.0, 0.0)
light_6_f.SetColor(1.0, 1.0, 1.0)
light_6_f.PositionalOn()
light_6_f.SwitchOn()
light_6_s1 = vtkLight()
light_6_s1.SetPosition(1.0, 0.0, 1.0)
light_6_s1.SetFocalPoint(0.0, 0.0, 0.0)
light_6_s1.SetColor(1.0, 1.0, 1.0)
light_6_s1.PositionalOn()
light_6_s1.SwitchOn()
light_6_s2 = vtkLight()
light_6_s2.SetPosition(c, s, 1.0)
light_6_s2.SetFocalPoint(0.0, 0.0, 0.0)
light_6_s2.SetColor(1.0, 1.0, 1.0)
light_6_s2.PositionalOn()
light_6_s2.SwitchOn()
light_6_s3 = vtkLight()
light_6_s3.SetPosition(c, -s, 1.0)
light_6_s3.SetFocalPoint(0.0, 0.0, 0.0)
light_6_s3.SetColor(1.0, 1.0, 1.0)
light_6_s3.PositionalOn()
light_6_s3.SwitchOn()
renderer_6.AddLight(light_6_f)
renderer_6.AddLight(light_6_s1)
renderer_6.AddLight(light_6_s2)
renderer_6.AddLight(light_6_s3)
renderer_6.ResetCamera()
renderer_6.GetActiveCamera().Zoom(1.3)
renderer_6.ResetCameraClippingRange()

# Scene — lights and camera for viewport 7
light_7_f = vtkLight()
light_7_f.SetPosition(0.0, 0.0, 1.0)
light_7_f.SetFocalPoint(0.0, 0.0, 0.0)
light_7_f.SetColor(1.0, 1.0, 1.0)
light_7_f.PositionalOn()
light_7_f.SwitchOn()
light_7_s1 = vtkLight()
light_7_s1.SetPosition(1.0, 0.0, 1.0)
light_7_s1.SetFocalPoint(0.0, 0.0, 0.0)
light_7_s1.SetColor(1.0, 1.0, 1.0)
light_7_s1.PositionalOn()
light_7_s1.SwitchOn()
light_7_s2 = vtkLight()
light_7_s2.SetPosition(c, s, 1.0)
light_7_s2.SetFocalPoint(0.0, 0.0, 0.0)
light_7_s2.SetColor(1.0, 1.0, 1.0)
light_7_s2.PositionalOn()
light_7_s2.SwitchOn()
light_7_s3 = vtkLight()
light_7_s3.SetPosition(c, -s, 1.0)
light_7_s3.SetFocalPoint(0.0, 0.0, 0.0)
light_7_s3.SetColor(1.0, 1.0, 1.0)
light_7_s3.PositionalOn()
light_7_s3.SwitchOn()
renderer_7.AddLight(light_7_f)
renderer_7.AddLight(light_7_s1)
renderer_7.AddLight(light_7_s2)
renderer_7.AddLight(light_7_s3)
renderer_7.ResetCamera()
renderer_7.GetActiveCamera().Zoom(1.3)
renderer_7.ResetCameraClippingRange()

# Scene — lights and camera for viewport 8
light_8_f = vtkLight()
light_8_f.SetPosition(0.0, 0.0, 1.0)
light_8_f.SetFocalPoint(0.0, 0.0, 0.0)
light_8_f.SetColor(1.0, 1.0, 1.0)
light_8_f.PositionalOn()
light_8_f.SwitchOn()
light_8_s1 = vtkLight()
light_8_s1.SetPosition(1.0, 0.0, 1.0)
light_8_s1.SetFocalPoint(0.0, 0.0, 0.0)
light_8_s1.SetColor(1.0, 1.0, 1.0)
light_8_s1.PositionalOn()
light_8_s1.SwitchOn()
light_8_s2 = vtkLight()
light_8_s2.SetPosition(c, s, 1.0)
light_8_s2.SetFocalPoint(0.0, 0.0, 0.0)
light_8_s2.SetColor(1.0, 1.0, 1.0)
light_8_s2.PositionalOn()
light_8_s2.SwitchOn()
light_8_s3 = vtkLight()
light_8_s3.SetPosition(c, -s, 1.0)
light_8_s3.SetFocalPoint(0.0, 0.0, 0.0)
light_8_s3.SetColor(1.0, 1.0, 1.0)
light_8_s3.PositionalOn()
light_8_s3.SwitchOn()
renderer_8.AddLight(light_8_f)
renderer_8.AddLight(light_8_s1)
renderer_8.AddLight(light_8_s2)
renderer_8.AddLight(light_8_s3)
renderer_8.ResetCamera()
renderer_8.GetActiveCamera().Zoom(1.3)
renderer_8.ResetCameraClippingRange()

interactor.Initialize()
interactor.Start()
