#!/usr/bin/env python

# Read an EnSight Gold case file using vtkGenericEnSightReader and display
# the geometry with scalar coloring.  A small EnSight Gold dataset (a quad
# surface with a scalar field) is generated if the files do not already exist.

import math
import os
from pathlib import Path

# Factory overrides: importing these modules registers the OpenGL rendering
# and interaction style implementations for vtkRenderingCore factory classes.
import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401

# VTK pipeline classes used in this example
from vtkmodules.vtkFiltersGeometry import vtkDataSetSurfaceFilter
from vtkmodules.vtkIOEnSight import vtkGenericEnSightReader
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkPolyDataMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
)

# Colors (normalized RGB)
slate_gray_rgb = (0.439, 0.502, 0.565)

# Data directory: defaults to the folder containing this script
data_dir = Path(os.environ.get("VPE_DATA_DIR", Path(__file__).parent))
case_path = data_dir / "sample.case"

# Generate a minimal EnSight Gold dataset if the files do not exist
if not case_path.exists():
    nx, ny = 10, 10
    n_nodes = nx * ny
    n_cells = (nx - 1) * (ny - 1)

    # Write the geometry file
    geo_path = data_dir / "sample.geo"
    with open(geo_path, "w") as f:
        f.write("EnSight Gold Geometry\n")
        f.write("Generated by ReadEnSight example\n")
        f.write("node id off\n")
        f.write("element id off\n")
        f.write("part\n")
        f.write("         1\n")
        f.write("quad surface\n")
        f.write("coordinates\n")
        f.write(f"{n_nodes:8d}\n")
        # x coordinates
        for j in range(ny):
            for i in range(nx):
                f.write(f"{i * 1.0:12.5e}\n")
        # y coordinates
        for j in range(ny):
            for i in range(nx):
                f.write(f"{j * 1.0:12.5e}\n")
        # z coordinates (sin ripple)
        for j in range(ny):
            for i in range(nx):
                z = math.sin(i * 0.7) * math.cos(j * 0.7) * 0.5
                f.write(f"{z:12.5e}\n")
        f.write("quad4\n")
        f.write(f"{n_cells:8d}\n")
        for j in range(ny - 1):
            for i in range(nx - 1):
                n0 = j * nx + i + 1
                n1 = n0 + 1
                n2 = n1 + nx
                n3 = n0 + nx
                f.write(f"{n0:8d}{n1:8d}{n2:8d}{n3:8d}\n")

    # Write the scalar file
    scalar_path = data_dir / "sample.scl"
    with open(scalar_path, "w") as f:
        f.write("Height\n")
        f.write("part\n")
        f.write("         1\n")
        f.write("coordinates\n")
        for j in range(ny):
            for i in range(nx):
                z = math.sin(i * 0.7) * math.cos(j * 0.7) * 0.5
                f.write(f"{z:12.5e}\n")

    # Write the case file
    with open(case_path, "w") as f:
        f.write("FORMAT\n")
        f.write("type: ensight gold\n")
        f.write("GEOMETRY\n")
        f.write("model: sample.geo\n")
        f.write("VARIABLE\n")
        f.write("scalar per node: Height sample.scl\n")

# Reader: load the EnSight case
reader = vtkGenericEnSightReader()
reader.SetCaseFileName(str(case_path))
reader.Update()

# Filter: extract surface geometry
surface = vtkDataSetSurfaceFilter()
surface.SetInputData(reader.GetOutput().GetBlock(0))

# Mapper: map polygon data to graphics primitives with scalar coloring
mapper = vtkPolyDataMapper()
mapper.SetInputConnection(surface.GetOutputPort())
mapper.SetScalarRange(reader.GetOutput().GetBlock(0).GetScalarRange())

# Actor: assign the mapped geometry
actor = vtkActor()
actor.SetMapper(mapper)

# Renderer: assemble the scene
renderer = vtkRenderer()
renderer.AddActor(actor)
renderer.SetBackground(slate_gray_rgb)
renderer.ResetCamera()

# Window: display the rendered scene
render_window = vtkRenderWindow()
render_window.AddRenderer(renderer)
render_window.SetSize(640, 480)
render_window.SetWindowName("ReadEnSight")

# Interactor: handle mouse and keyboard events
interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)

# Launch the interactive visualization
interactor.Initialize()
interactor.Start()
