#!/usr/bin/env python

# Demonstrate vtkLinearExtrusionFilter by reading US state outlines,
# extruding each state cell with random scale factors, and rendering
# with random colors.

import os

# Factory overrides
import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingFreeType  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401

from vtkmodules.vtkCommonCore import vtkMath
from vtkmodules.vtkFiltersCore import vtkTriangleFilter
from vtkmodules.vtkFiltersGeometry import vtkGeometryFilter
from vtkmodules.vtkFiltersModeling import vtkLinearExtrusionFilter
from vtkmodules.vtkIOLegacy import vtkPolyDataReader
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkPolyDataMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
)

data_dir = os.environ.get("VPE_DATA_DIR", os.path.dirname(os.path.abspath(__file__)))

# Read US state outlines
reader = vtkPolyDataReader()
reader.SetFileName(os.path.join(data_dir, "usa.vtk"))

vtk_math = vtkMath()

# Extract each state cell
geometry_filter_0 = vtkGeometryFilter()
geometry_filter_0.SetInputConnection(reader.GetOutputPort())
geometry_filter_0.CellClippingOn()
geometry_filter_0.SetCellMinimum(0)
geometry_filter_0.SetCellMaximum(0)

geometry_filter_1 = vtkGeometryFilter()
geometry_filter_1.SetInputConnection(reader.GetOutputPort())
geometry_filter_1.CellClippingOn()
geometry_filter_1.SetCellMinimum(1)
geometry_filter_1.SetCellMaximum(1)

geometry_filter_2 = vtkGeometryFilter()
geometry_filter_2.SetInputConnection(reader.GetOutputPort())
geometry_filter_2.CellClippingOn()
geometry_filter_2.SetCellMinimum(2)
geometry_filter_2.SetCellMaximum(2)

geometry_filter_3 = vtkGeometryFilter()
geometry_filter_3.SetInputConnection(reader.GetOutputPort())
geometry_filter_3.CellClippingOn()
geometry_filter_3.SetCellMinimum(3)
geometry_filter_3.SetCellMaximum(3)

geometry_filter_4 = vtkGeometryFilter()
geometry_filter_4.SetInputConnection(reader.GetOutputPort())
geometry_filter_4.CellClippingOn()
geometry_filter_4.SetCellMinimum(4)
geometry_filter_4.SetCellMaximum(4)

geometry_filter_5 = vtkGeometryFilter()
geometry_filter_5.SetInputConnection(reader.GetOutputPort())
geometry_filter_5.CellClippingOn()
geometry_filter_5.SetCellMinimum(5)
geometry_filter_5.SetCellMaximum(5)

geometry_filter_6 = vtkGeometryFilter()
geometry_filter_6.SetInputConnection(reader.GetOutputPort())
geometry_filter_6.CellClippingOn()
geometry_filter_6.SetCellMinimum(6)
geometry_filter_6.SetCellMaximum(6)

geometry_filter_7 = vtkGeometryFilter()
geometry_filter_7.SetInputConnection(reader.GetOutputPort())
geometry_filter_7.CellClippingOn()
geometry_filter_7.SetCellMinimum(7)
geometry_filter_7.SetCellMaximum(7)

geometry_filter_8 = vtkGeometryFilter()
geometry_filter_8.SetInputConnection(reader.GetOutputPort())
geometry_filter_8.CellClippingOn()
geometry_filter_8.SetCellMinimum(8)
geometry_filter_8.SetCellMaximum(8)

geometry_filter_9 = vtkGeometryFilter()
geometry_filter_9.SetInputConnection(reader.GetOutputPort())
geometry_filter_9.CellClippingOn()
geometry_filter_9.SetCellMinimum(9)
geometry_filter_9.SetCellMaximum(9)

geometry_filter_10 = vtkGeometryFilter()
geometry_filter_10.SetInputConnection(reader.GetOutputPort())
geometry_filter_10.CellClippingOn()
geometry_filter_10.SetCellMinimum(10)
geometry_filter_10.SetCellMaximum(10)

geometry_filter_11 = vtkGeometryFilter()
geometry_filter_11.SetInputConnection(reader.GetOutputPort())
geometry_filter_11.CellClippingOn()
geometry_filter_11.SetCellMinimum(11)
geometry_filter_11.SetCellMaximum(11)

geometry_filter_12 = vtkGeometryFilter()
geometry_filter_12.SetInputConnection(reader.GetOutputPort())
geometry_filter_12.CellClippingOn()
geometry_filter_12.SetCellMinimum(12)
geometry_filter_12.SetCellMaximum(12)

geometry_filter_13 = vtkGeometryFilter()
geometry_filter_13.SetInputConnection(reader.GetOutputPort())
geometry_filter_13.CellClippingOn()
geometry_filter_13.SetCellMinimum(13)
geometry_filter_13.SetCellMaximum(13)

geometry_filter_14 = vtkGeometryFilter()
geometry_filter_14.SetInputConnection(reader.GetOutputPort())
geometry_filter_14.CellClippingOn()
geometry_filter_14.SetCellMinimum(14)
geometry_filter_14.SetCellMaximum(14)

geometry_filter_15 = vtkGeometryFilter()
geometry_filter_15.SetInputConnection(reader.GetOutputPort())
geometry_filter_15.CellClippingOn()
geometry_filter_15.SetCellMinimum(15)
geometry_filter_15.SetCellMaximum(15)

geometry_filter_16 = vtkGeometryFilter()
geometry_filter_16.SetInputConnection(reader.GetOutputPort())
geometry_filter_16.CellClippingOn()
geometry_filter_16.SetCellMinimum(16)
geometry_filter_16.SetCellMaximum(16)

geometry_filter_17 = vtkGeometryFilter()
geometry_filter_17.SetInputConnection(reader.GetOutputPort())
geometry_filter_17.CellClippingOn()
geometry_filter_17.SetCellMinimum(17)
geometry_filter_17.SetCellMaximum(17)

geometry_filter_18 = vtkGeometryFilter()
geometry_filter_18.SetInputConnection(reader.GetOutputPort())
geometry_filter_18.CellClippingOn()
geometry_filter_18.SetCellMinimum(18)
geometry_filter_18.SetCellMaximum(18)

geometry_filter_19 = vtkGeometryFilter()
geometry_filter_19.SetInputConnection(reader.GetOutputPort())
geometry_filter_19.CellClippingOn()
geometry_filter_19.SetCellMinimum(19)
geometry_filter_19.SetCellMaximum(19)

geometry_filter_20 = vtkGeometryFilter()
geometry_filter_20.SetInputConnection(reader.GetOutputPort())
geometry_filter_20.CellClippingOn()
geometry_filter_20.SetCellMinimum(20)
geometry_filter_20.SetCellMaximum(20)

geometry_filter_21 = vtkGeometryFilter()
geometry_filter_21.SetInputConnection(reader.GetOutputPort())
geometry_filter_21.CellClippingOn()
geometry_filter_21.SetCellMinimum(21)
geometry_filter_21.SetCellMaximum(21)

geometry_filter_22 = vtkGeometryFilter()
geometry_filter_22.SetInputConnection(reader.GetOutputPort())
geometry_filter_22.CellClippingOn()
geometry_filter_22.SetCellMinimum(22)
geometry_filter_22.SetCellMaximum(22)

geometry_filter_23 = vtkGeometryFilter()
geometry_filter_23.SetInputConnection(reader.GetOutputPort())
geometry_filter_23.CellClippingOn()
geometry_filter_23.SetCellMinimum(23)
geometry_filter_23.SetCellMaximum(23)

geometry_filter_24 = vtkGeometryFilter()
geometry_filter_24.SetInputConnection(reader.GetOutputPort())
geometry_filter_24.CellClippingOn()
geometry_filter_24.SetCellMinimum(24)
geometry_filter_24.SetCellMaximum(24)

geometry_filter_25 = vtkGeometryFilter()
geometry_filter_25.SetInputConnection(reader.GetOutputPort())
geometry_filter_25.CellClippingOn()
geometry_filter_25.SetCellMinimum(25)
geometry_filter_25.SetCellMaximum(25)

geometry_filter_26 = vtkGeometryFilter()
geometry_filter_26.SetInputConnection(reader.GetOutputPort())
geometry_filter_26.CellClippingOn()
geometry_filter_26.SetCellMinimum(26)
geometry_filter_26.SetCellMaximum(26)

geometry_filter_27 = vtkGeometryFilter()
geometry_filter_27.SetInputConnection(reader.GetOutputPort())
geometry_filter_27.CellClippingOn()
geometry_filter_27.SetCellMinimum(27)
geometry_filter_27.SetCellMaximum(27)

geometry_filter_28 = vtkGeometryFilter()
geometry_filter_28.SetInputConnection(reader.GetOutputPort())
geometry_filter_28.CellClippingOn()
geometry_filter_28.SetCellMinimum(28)
geometry_filter_28.SetCellMaximum(28)

geometry_filter_29 = vtkGeometryFilter()
geometry_filter_29.SetInputConnection(reader.GetOutputPort())
geometry_filter_29.CellClippingOn()
geometry_filter_29.SetCellMinimum(29)
geometry_filter_29.SetCellMaximum(29)

geometry_filter_30 = vtkGeometryFilter()
geometry_filter_30.SetInputConnection(reader.GetOutputPort())
geometry_filter_30.CellClippingOn()
geometry_filter_30.SetCellMinimum(30)
geometry_filter_30.SetCellMaximum(30)

geometry_filter_31 = vtkGeometryFilter()
geometry_filter_31.SetInputConnection(reader.GetOutputPort())
geometry_filter_31.CellClippingOn()
geometry_filter_31.SetCellMinimum(31)
geometry_filter_31.SetCellMaximum(31)

geometry_filter_32 = vtkGeometryFilter()
geometry_filter_32.SetInputConnection(reader.GetOutputPort())
geometry_filter_32.CellClippingOn()
geometry_filter_32.SetCellMinimum(32)
geometry_filter_32.SetCellMaximum(32)

geometry_filter_33 = vtkGeometryFilter()
geometry_filter_33.SetInputConnection(reader.GetOutputPort())
geometry_filter_33.CellClippingOn()
geometry_filter_33.SetCellMinimum(33)
geometry_filter_33.SetCellMaximum(33)

geometry_filter_34 = vtkGeometryFilter()
geometry_filter_34.SetInputConnection(reader.GetOutputPort())
geometry_filter_34.CellClippingOn()
geometry_filter_34.SetCellMinimum(34)
geometry_filter_34.SetCellMaximum(34)

geometry_filter_35 = vtkGeometryFilter()
geometry_filter_35.SetInputConnection(reader.GetOutputPort())
geometry_filter_35.CellClippingOn()
geometry_filter_35.SetCellMinimum(35)
geometry_filter_35.SetCellMaximum(35)

geometry_filter_36 = vtkGeometryFilter()
geometry_filter_36.SetInputConnection(reader.GetOutputPort())
geometry_filter_36.CellClippingOn()
geometry_filter_36.SetCellMinimum(36)
geometry_filter_36.SetCellMaximum(36)

geometry_filter_37 = vtkGeometryFilter()
geometry_filter_37.SetInputConnection(reader.GetOutputPort())
geometry_filter_37.CellClippingOn()
geometry_filter_37.SetCellMinimum(37)
geometry_filter_37.SetCellMaximum(37)

geometry_filter_38 = vtkGeometryFilter()
geometry_filter_38.SetInputConnection(reader.GetOutputPort())
geometry_filter_38.CellClippingOn()
geometry_filter_38.SetCellMinimum(38)
geometry_filter_38.SetCellMaximum(38)

geometry_filter_39 = vtkGeometryFilter()
geometry_filter_39.SetInputConnection(reader.GetOutputPort())
geometry_filter_39.CellClippingOn()
geometry_filter_39.SetCellMinimum(39)
geometry_filter_39.SetCellMaximum(39)

geometry_filter_40 = vtkGeometryFilter()
geometry_filter_40.SetInputConnection(reader.GetOutputPort())
geometry_filter_40.CellClippingOn()
geometry_filter_40.SetCellMinimum(40)
geometry_filter_40.SetCellMaximum(40)

geometry_filter_41 = vtkGeometryFilter()
geometry_filter_41.SetInputConnection(reader.GetOutputPort())
geometry_filter_41.CellClippingOn()
geometry_filter_41.SetCellMinimum(41)
geometry_filter_41.SetCellMaximum(41)

geometry_filter_42 = vtkGeometryFilter()
geometry_filter_42.SetInputConnection(reader.GetOutputPort())
geometry_filter_42.CellClippingOn()
geometry_filter_42.SetCellMinimum(42)
geometry_filter_42.SetCellMaximum(42)

geometry_filter_43 = vtkGeometryFilter()
geometry_filter_43.SetInputConnection(reader.GetOutputPort())
geometry_filter_43.CellClippingOn()
geometry_filter_43.SetCellMinimum(43)
geometry_filter_43.SetCellMaximum(43)

geometry_filter_44 = vtkGeometryFilter()
geometry_filter_44.SetInputConnection(reader.GetOutputPort())
geometry_filter_44.CellClippingOn()
geometry_filter_44.SetCellMinimum(44)
geometry_filter_44.SetCellMaximum(44)

geometry_filter_45 = vtkGeometryFilter()
geometry_filter_45.SetInputConnection(reader.GetOutputPort())
geometry_filter_45.CellClippingOn()
geometry_filter_45.SetCellMinimum(45)
geometry_filter_45.SetCellMaximum(45)

geometry_filter_46 = vtkGeometryFilter()
geometry_filter_46.SetInputConnection(reader.GetOutputPort())
geometry_filter_46.CellClippingOn()
geometry_filter_46.SetCellMinimum(46)
geometry_filter_46.SetCellMaximum(46)

geometry_filter_47 = vtkGeometryFilter()
geometry_filter_47.SetInputConnection(reader.GetOutputPort())
geometry_filter_47.CellClippingOn()
geometry_filter_47.SetCellMinimum(47)
geometry_filter_47.SetCellMaximum(47)

geometry_filter_48 = vtkGeometryFilter()
geometry_filter_48.SetInputConnection(reader.GetOutputPort())
geometry_filter_48.CellClippingOn()
geometry_filter_48.SetCellMinimum(48)
geometry_filter_48.SetCellMaximum(48)

geometry_filter_49 = vtkGeometryFilter()
geometry_filter_49.SetInputConnection(reader.GetOutputPort())
geometry_filter_49.CellClippingOn()
geometry_filter_49.SetCellMinimum(49)
geometry_filter_49.SetCellMaximum(49)

geometry_filter_50 = vtkGeometryFilter()
geometry_filter_50.SetInputConnection(reader.GetOutputPort())
geometry_filter_50.CellClippingOn()
geometry_filter_50.SetCellMinimum(50)
geometry_filter_50.SetCellMaximum(50)

# Triangulate each state
triangle_filter_0 = vtkTriangleFilter()
triangle_filter_0.SetInputConnection(geometry_filter_0.GetOutputPort())

triangle_filter_1 = vtkTriangleFilter()
triangle_filter_1.SetInputConnection(geometry_filter_1.GetOutputPort())

triangle_filter_2 = vtkTriangleFilter()
triangle_filter_2.SetInputConnection(geometry_filter_2.GetOutputPort())

triangle_filter_3 = vtkTriangleFilter()
triangle_filter_3.SetInputConnection(geometry_filter_3.GetOutputPort())

triangle_filter_4 = vtkTriangleFilter()
triangle_filter_4.SetInputConnection(geometry_filter_4.GetOutputPort())

triangle_filter_5 = vtkTriangleFilter()
triangle_filter_5.SetInputConnection(geometry_filter_5.GetOutputPort())

triangle_filter_6 = vtkTriangleFilter()
triangle_filter_6.SetInputConnection(geometry_filter_6.GetOutputPort())

triangle_filter_7 = vtkTriangleFilter()
triangle_filter_7.SetInputConnection(geometry_filter_7.GetOutputPort())

triangle_filter_8 = vtkTriangleFilter()
triangle_filter_8.SetInputConnection(geometry_filter_8.GetOutputPort())

triangle_filter_9 = vtkTriangleFilter()
triangle_filter_9.SetInputConnection(geometry_filter_9.GetOutputPort())

triangle_filter_10 = vtkTriangleFilter()
triangle_filter_10.SetInputConnection(geometry_filter_10.GetOutputPort())

triangle_filter_11 = vtkTriangleFilter()
triangle_filter_11.SetInputConnection(geometry_filter_11.GetOutputPort())

triangle_filter_12 = vtkTriangleFilter()
triangle_filter_12.SetInputConnection(geometry_filter_12.GetOutputPort())

triangle_filter_13 = vtkTriangleFilter()
triangle_filter_13.SetInputConnection(geometry_filter_13.GetOutputPort())

triangle_filter_14 = vtkTriangleFilter()
triangle_filter_14.SetInputConnection(geometry_filter_14.GetOutputPort())

triangle_filter_15 = vtkTriangleFilter()
triangle_filter_15.SetInputConnection(geometry_filter_15.GetOutputPort())

triangle_filter_16 = vtkTriangleFilter()
triangle_filter_16.SetInputConnection(geometry_filter_16.GetOutputPort())

triangle_filter_17 = vtkTriangleFilter()
triangle_filter_17.SetInputConnection(geometry_filter_17.GetOutputPort())

triangle_filter_18 = vtkTriangleFilter()
triangle_filter_18.SetInputConnection(geometry_filter_18.GetOutputPort())

triangle_filter_19 = vtkTriangleFilter()
triangle_filter_19.SetInputConnection(geometry_filter_19.GetOutputPort())

triangle_filter_20 = vtkTriangleFilter()
triangle_filter_20.SetInputConnection(geometry_filter_20.GetOutputPort())

triangle_filter_21 = vtkTriangleFilter()
triangle_filter_21.SetInputConnection(geometry_filter_21.GetOutputPort())

triangle_filter_22 = vtkTriangleFilter()
triangle_filter_22.SetInputConnection(geometry_filter_22.GetOutputPort())

triangle_filter_23 = vtkTriangleFilter()
triangle_filter_23.SetInputConnection(geometry_filter_23.GetOutputPort())

triangle_filter_24 = vtkTriangleFilter()
triangle_filter_24.SetInputConnection(geometry_filter_24.GetOutputPort())

triangle_filter_25 = vtkTriangleFilter()
triangle_filter_25.SetInputConnection(geometry_filter_25.GetOutputPort())

triangle_filter_26 = vtkTriangleFilter()
triangle_filter_26.SetInputConnection(geometry_filter_26.GetOutputPort())

triangle_filter_27 = vtkTriangleFilter()
triangle_filter_27.SetInputConnection(geometry_filter_27.GetOutputPort())

triangle_filter_28 = vtkTriangleFilter()
triangle_filter_28.SetInputConnection(geometry_filter_28.GetOutputPort())

triangle_filter_29 = vtkTriangleFilter()
triangle_filter_29.SetInputConnection(geometry_filter_29.GetOutputPort())

triangle_filter_30 = vtkTriangleFilter()
triangle_filter_30.SetInputConnection(geometry_filter_30.GetOutputPort())

triangle_filter_31 = vtkTriangleFilter()
triangle_filter_31.SetInputConnection(geometry_filter_31.GetOutputPort())

triangle_filter_32 = vtkTriangleFilter()
triangle_filter_32.SetInputConnection(geometry_filter_32.GetOutputPort())

triangle_filter_33 = vtkTriangleFilter()
triangle_filter_33.SetInputConnection(geometry_filter_33.GetOutputPort())

triangle_filter_34 = vtkTriangleFilter()
triangle_filter_34.SetInputConnection(geometry_filter_34.GetOutputPort())

triangle_filter_35 = vtkTriangleFilter()
triangle_filter_35.SetInputConnection(geometry_filter_35.GetOutputPort())

triangle_filter_36 = vtkTriangleFilter()
triangle_filter_36.SetInputConnection(geometry_filter_36.GetOutputPort())

triangle_filter_37 = vtkTriangleFilter()
triangle_filter_37.SetInputConnection(geometry_filter_37.GetOutputPort())

triangle_filter_38 = vtkTriangleFilter()
triangle_filter_38.SetInputConnection(geometry_filter_38.GetOutputPort())

triangle_filter_39 = vtkTriangleFilter()
triangle_filter_39.SetInputConnection(geometry_filter_39.GetOutputPort())

triangle_filter_40 = vtkTriangleFilter()
triangle_filter_40.SetInputConnection(geometry_filter_40.GetOutputPort())

triangle_filter_41 = vtkTriangleFilter()
triangle_filter_41.SetInputConnection(geometry_filter_41.GetOutputPort())

triangle_filter_42 = vtkTriangleFilter()
triangle_filter_42.SetInputConnection(geometry_filter_42.GetOutputPort())

triangle_filter_43 = vtkTriangleFilter()
triangle_filter_43.SetInputConnection(geometry_filter_43.GetOutputPort())

triangle_filter_44 = vtkTriangleFilter()
triangle_filter_44.SetInputConnection(geometry_filter_44.GetOutputPort())

triangle_filter_45 = vtkTriangleFilter()
triangle_filter_45.SetInputConnection(geometry_filter_45.GetOutputPort())

triangle_filter_46 = vtkTriangleFilter()
triangle_filter_46.SetInputConnection(geometry_filter_46.GetOutputPort())

triangle_filter_47 = vtkTriangleFilter()
triangle_filter_47.SetInputConnection(geometry_filter_47.GetOutputPort())

triangle_filter_48 = vtkTriangleFilter()
triangle_filter_48.SetInputConnection(geometry_filter_48.GetOutputPort())

triangle_filter_49 = vtkTriangleFilter()
triangle_filter_49.SetInputConnection(geometry_filter_49.GetOutputPort())

triangle_filter_50 = vtkTriangleFilter()
triangle_filter_50.SetInputConnection(geometry_filter_50.GetOutputPort())

# Extrude each state with random height
extrude_0 = vtkLinearExtrusionFilter()
extrude_0.SetInputConnection(triangle_filter_0.GetOutputPort())
extrude_0.SetExtrusionType(1)
extrude_0.SetVector(0, 0, 1)
extrude_0.CappingOn()
extrude_0.SetScaleFactor(vtk_math.Random(1, 10))

extrude_1 = vtkLinearExtrusionFilter()
extrude_1.SetInputConnection(triangle_filter_1.GetOutputPort())
extrude_1.SetExtrusionType(1)
extrude_1.SetVector(0, 0, 1)
extrude_1.CappingOn()
extrude_1.SetScaleFactor(vtk_math.Random(1, 10))

extrude_2 = vtkLinearExtrusionFilter()
extrude_2.SetInputConnection(triangle_filter_2.GetOutputPort())
extrude_2.SetExtrusionType(1)
extrude_2.SetVector(0, 0, 1)
extrude_2.CappingOn()
extrude_2.SetScaleFactor(vtk_math.Random(1, 10))

extrude_3 = vtkLinearExtrusionFilter()
extrude_3.SetInputConnection(triangle_filter_3.GetOutputPort())
extrude_3.SetExtrusionType(1)
extrude_3.SetVector(0, 0, 1)
extrude_3.CappingOn()
extrude_3.SetScaleFactor(vtk_math.Random(1, 10))

extrude_4 = vtkLinearExtrusionFilter()
extrude_4.SetInputConnection(triangle_filter_4.GetOutputPort())
extrude_4.SetExtrusionType(1)
extrude_4.SetVector(0, 0, 1)
extrude_4.CappingOn()
extrude_4.SetScaleFactor(vtk_math.Random(1, 10))

extrude_5 = vtkLinearExtrusionFilter()
extrude_5.SetInputConnection(triangle_filter_5.GetOutputPort())
extrude_5.SetExtrusionType(1)
extrude_5.SetVector(0, 0, 1)
extrude_5.CappingOn()
extrude_5.SetScaleFactor(vtk_math.Random(1, 10))

extrude_6 = vtkLinearExtrusionFilter()
extrude_6.SetInputConnection(triangle_filter_6.GetOutputPort())
extrude_6.SetExtrusionType(1)
extrude_6.SetVector(0, 0, 1)
extrude_6.CappingOn()
extrude_6.SetScaleFactor(vtk_math.Random(1, 10))

extrude_7 = vtkLinearExtrusionFilter()
extrude_7.SetInputConnection(triangle_filter_7.GetOutputPort())
extrude_7.SetExtrusionType(1)
extrude_7.SetVector(0, 0, 1)
extrude_7.CappingOn()
extrude_7.SetScaleFactor(vtk_math.Random(1, 10))

extrude_8 = vtkLinearExtrusionFilter()
extrude_8.SetInputConnection(triangle_filter_8.GetOutputPort())
extrude_8.SetExtrusionType(1)
extrude_8.SetVector(0, 0, 1)
extrude_8.CappingOn()
extrude_8.SetScaleFactor(vtk_math.Random(1, 10))

extrude_9 = vtkLinearExtrusionFilter()
extrude_9.SetInputConnection(triangle_filter_9.GetOutputPort())
extrude_9.SetExtrusionType(1)
extrude_9.SetVector(0, 0, 1)
extrude_9.CappingOn()
extrude_9.SetScaleFactor(vtk_math.Random(1, 10))

extrude_10 = vtkLinearExtrusionFilter()
extrude_10.SetInputConnection(triangle_filter_10.GetOutputPort())
extrude_10.SetExtrusionType(1)
extrude_10.SetVector(0, 0, 1)
extrude_10.CappingOn()
extrude_10.SetScaleFactor(vtk_math.Random(1, 10))

extrude_11 = vtkLinearExtrusionFilter()
extrude_11.SetInputConnection(triangle_filter_11.GetOutputPort())
extrude_11.SetExtrusionType(1)
extrude_11.SetVector(0, 0, 1)
extrude_11.CappingOn()
extrude_11.SetScaleFactor(vtk_math.Random(1, 10))

extrude_12 = vtkLinearExtrusionFilter()
extrude_12.SetInputConnection(triangle_filter_12.GetOutputPort())
extrude_12.SetExtrusionType(1)
extrude_12.SetVector(0, 0, 1)
extrude_12.CappingOn()
extrude_12.SetScaleFactor(vtk_math.Random(1, 10))

extrude_13 = vtkLinearExtrusionFilter()
extrude_13.SetInputConnection(triangle_filter_13.GetOutputPort())
extrude_13.SetExtrusionType(1)
extrude_13.SetVector(0, 0, 1)
extrude_13.CappingOn()
extrude_13.SetScaleFactor(vtk_math.Random(1, 10))

extrude_14 = vtkLinearExtrusionFilter()
extrude_14.SetInputConnection(triangle_filter_14.GetOutputPort())
extrude_14.SetExtrusionType(1)
extrude_14.SetVector(0, 0, 1)
extrude_14.CappingOn()
extrude_14.SetScaleFactor(vtk_math.Random(1, 10))

extrude_15 = vtkLinearExtrusionFilter()
extrude_15.SetInputConnection(triangle_filter_15.GetOutputPort())
extrude_15.SetExtrusionType(1)
extrude_15.SetVector(0, 0, 1)
extrude_15.CappingOn()
extrude_15.SetScaleFactor(vtk_math.Random(1, 10))

extrude_16 = vtkLinearExtrusionFilter()
extrude_16.SetInputConnection(triangle_filter_16.GetOutputPort())
extrude_16.SetExtrusionType(1)
extrude_16.SetVector(0, 0, 1)
extrude_16.CappingOn()
extrude_16.SetScaleFactor(vtk_math.Random(1, 10))

extrude_17 = vtkLinearExtrusionFilter()
extrude_17.SetInputConnection(triangle_filter_17.GetOutputPort())
extrude_17.SetExtrusionType(1)
extrude_17.SetVector(0, 0, 1)
extrude_17.CappingOn()
extrude_17.SetScaleFactor(vtk_math.Random(1, 10))

extrude_18 = vtkLinearExtrusionFilter()
extrude_18.SetInputConnection(triangle_filter_18.GetOutputPort())
extrude_18.SetExtrusionType(1)
extrude_18.SetVector(0, 0, 1)
extrude_18.CappingOn()
extrude_18.SetScaleFactor(vtk_math.Random(1, 10))

extrude_19 = vtkLinearExtrusionFilter()
extrude_19.SetInputConnection(triangle_filter_19.GetOutputPort())
extrude_19.SetExtrusionType(1)
extrude_19.SetVector(0, 0, 1)
extrude_19.CappingOn()
extrude_19.SetScaleFactor(vtk_math.Random(1, 10))

extrude_20 = vtkLinearExtrusionFilter()
extrude_20.SetInputConnection(triangle_filter_20.GetOutputPort())
extrude_20.SetExtrusionType(1)
extrude_20.SetVector(0, 0, 1)
extrude_20.CappingOn()
extrude_20.SetScaleFactor(vtk_math.Random(1, 10))

extrude_21 = vtkLinearExtrusionFilter()
extrude_21.SetInputConnection(triangle_filter_21.GetOutputPort())
extrude_21.SetExtrusionType(1)
extrude_21.SetVector(0, 0, 1)
extrude_21.CappingOn()
extrude_21.SetScaleFactor(vtk_math.Random(1, 10))

extrude_22 = vtkLinearExtrusionFilter()
extrude_22.SetInputConnection(triangle_filter_22.GetOutputPort())
extrude_22.SetExtrusionType(1)
extrude_22.SetVector(0, 0, 1)
extrude_22.CappingOn()
extrude_22.SetScaleFactor(vtk_math.Random(1, 10))

extrude_23 = vtkLinearExtrusionFilter()
extrude_23.SetInputConnection(triangle_filter_23.GetOutputPort())
extrude_23.SetExtrusionType(1)
extrude_23.SetVector(0, 0, 1)
extrude_23.CappingOn()
extrude_23.SetScaleFactor(vtk_math.Random(1, 10))

extrude_24 = vtkLinearExtrusionFilter()
extrude_24.SetInputConnection(triangle_filter_24.GetOutputPort())
extrude_24.SetExtrusionType(1)
extrude_24.SetVector(0, 0, 1)
extrude_24.CappingOn()
extrude_24.SetScaleFactor(vtk_math.Random(1, 10))

extrude_25 = vtkLinearExtrusionFilter()
extrude_25.SetInputConnection(triangle_filter_25.GetOutputPort())
extrude_25.SetExtrusionType(1)
extrude_25.SetVector(0, 0, 1)
extrude_25.CappingOn()
extrude_25.SetScaleFactor(vtk_math.Random(1, 10))

extrude_26 = vtkLinearExtrusionFilter()
extrude_26.SetInputConnection(triangle_filter_26.GetOutputPort())
extrude_26.SetExtrusionType(1)
extrude_26.SetVector(0, 0, 1)
extrude_26.CappingOn()
extrude_26.SetScaleFactor(vtk_math.Random(1, 10))

extrude_27 = vtkLinearExtrusionFilter()
extrude_27.SetInputConnection(triangle_filter_27.GetOutputPort())
extrude_27.SetExtrusionType(1)
extrude_27.SetVector(0, 0, 1)
extrude_27.CappingOn()
extrude_27.SetScaleFactor(vtk_math.Random(1, 10))

extrude_28 = vtkLinearExtrusionFilter()
extrude_28.SetInputConnection(triangle_filter_28.GetOutputPort())
extrude_28.SetExtrusionType(1)
extrude_28.SetVector(0, 0, 1)
extrude_28.CappingOn()
extrude_28.SetScaleFactor(vtk_math.Random(1, 10))

extrude_29 = vtkLinearExtrusionFilter()
extrude_29.SetInputConnection(triangle_filter_29.GetOutputPort())
extrude_29.SetExtrusionType(1)
extrude_29.SetVector(0, 0, 1)
extrude_29.CappingOn()
extrude_29.SetScaleFactor(vtk_math.Random(1, 10))

extrude_30 = vtkLinearExtrusionFilter()
extrude_30.SetInputConnection(triangle_filter_30.GetOutputPort())
extrude_30.SetExtrusionType(1)
extrude_30.SetVector(0, 0, 1)
extrude_30.CappingOn()
extrude_30.SetScaleFactor(vtk_math.Random(1, 10))

extrude_31 = vtkLinearExtrusionFilter()
extrude_31.SetInputConnection(triangle_filter_31.GetOutputPort())
extrude_31.SetExtrusionType(1)
extrude_31.SetVector(0, 0, 1)
extrude_31.CappingOn()
extrude_31.SetScaleFactor(vtk_math.Random(1, 10))

extrude_32 = vtkLinearExtrusionFilter()
extrude_32.SetInputConnection(triangle_filter_32.GetOutputPort())
extrude_32.SetExtrusionType(1)
extrude_32.SetVector(0, 0, 1)
extrude_32.CappingOn()
extrude_32.SetScaleFactor(vtk_math.Random(1, 10))

extrude_33 = vtkLinearExtrusionFilter()
extrude_33.SetInputConnection(triangle_filter_33.GetOutputPort())
extrude_33.SetExtrusionType(1)
extrude_33.SetVector(0, 0, 1)
extrude_33.CappingOn()
extrude_33.SetScaleFactor(vtk_math.Random(1, 10))

extrude_34 = vtkLinearExtrusionFilter()
extrude_34.SetInputConnection(triangle_filter_34.GetOutputPort())
extrude_34.SetExtrusionType(1)
extrude_34.SetVector(0, 0, 1)
extrude_34.CappingOn()
extrude_34.SetScaleFactor(vtk_math.Random(1, 10))

extrude_35 = vtkLinearExtrusionFilter()
extrude_35.SetInputConnection(triangle_filter_35.GetOutputPort())
extrude_35.SetExtrusionType(1)
extrude_35.SetVector(0, 0, 1)
extrude_35.CappingOn()
extrude_35.SetScaleFactor(vtk_math.Random(1, 10))

extrude_36 = vtkLinearExtrusionFilter()
extrude_36.SetInputConnection(triangle_filter_36.GetOutputPort())
extrude_36.SetExtrusionType(1)
extrude_36.SetVector(0, 0, 1)
extrude_36.CappingOn()
extrude_36.SetScaleFactor(vtk_math.Random(1, 10))

extrude_37 = vtkLinearExtrusionFilter()
extrude_37.SetInputConnection(triangle_filter_37.GetOutputPort())
extrude_37.SetExtrusionType(1)
extrude_37.SetVector(0, 0, 1)
extrude_37.CappingOn()
extrude_37.SetScaleFactor(vtk_math.Random(1, 10))

extrude_38 = vtkLinearExtrusionFilter()
extrude_38.SetInputConnection(triangle_filter_38.GetOutputPort())
extrude_38.SetExtrusionType(1)
extrude_38.SetVector(0, 0, 1)
extrude_38.CappingOn()
extrude_38.SetScaleFactor(vtk_math.Random(1, 10))

extrude_39 = vtkLinearExtrusionFilter()
extrude_39.SetInputConnection(triangle_filter_39.GetOutputPort())
extrude_39.SetExtrusionType(1)
extrude_39.SetVector(0, 0, 1)
extrude_39.CappingOn()
extrude_39.SetScaleFactor(vtk_math.Random(1, 10))

extrude_40 = vtkLinearExtrusionFilter()
extrude_40.SetInputConnection(triangle_filter_40.GetOutputPort())
extrude_40.SetExtrusionType(1)
extrude_40.SetVector(0, 0, 1)
extrude_40.CappingOn()
extrude_40.SetScaleFactor(vtk_math.Random(1, 10))

extrude_41 = vtkLinearExtrusionFilter()
extrude_41.SetInputConnection(triangle_filter_41.GetOutputPort())
extrude_41.SetExtrusionType(1)
extrude_41.SetVector(0, 0, 1)
extrude_41.CappingOn()
extrude_41.SetScaleFactor(vtk_math.Random(1, 10))

extrude_42 = vtkLinearExtrusionFilter()
extrude_42.SetInputConnection(triangle_filter_42.GetOutputPort())
extrude_42.SetExtrusionType(1)
extrude_42.SetVector(0, 0, 1)
extrude_42.CappingOn()
extrude_42.SetScaleFactor(vtk_math.Random(1, 10))

extrude_43 = vtkLinearExtrusionFilter()
extrude_43.SetInputConnection(triangle_filter_43.GetOutputPort())
extrude_43.SetExtrusionType(1)
extrude_43.SetVector(0, 0, 1)
extrude_43.CappingOn()
extrude_43.SetScaleFactor(vtk_math.Random(1, 10))

extrude_44 = vtkLinearExtrusionFilter()
extrude_44.SetInputConnection(triangle_filter_44.GetOutputPort())
extrude_44.SetExtrusionType(1)
extrude_44.SetVector(0, 0, 1)
extrude_44.CappingOn()
extrude_44.SetScaleFactor(vtk_math.Random(1, 10))

extrude_45 = vtkLinearExtrusionFilter()
extrude_45.SetInputConnection(triangle_filter_45.GetOutputPort())
extrude_45.SetExtrusionType(1)
extrude_45.SetVector(0, 0, 1)
extrude_45.CappingOn()
extrude_45.SetScaleFactor(vtk_math.Random(1, 10))

extrude_46 = vtkLinearExtrusionFilter()
extrude_46.SetInputConnection(triangle_filter_46.GetOutputPort())
extrude_46.SetExtrusionType(1)
extrude_46.SetVector(0, 0, 1)
extrude_46.CappingOn()
extrude_46.SetScaleFactor(vtk_math.Random(1, 10))

extrude_47 = vtkLinearExtrusionFilter()
extrude_47.SetInputConnection(triangle_filter_47.GetOutputPort())
extrude_47.SetExtrusionType(1)
extrude_47.SetVector(0, 0, 1)
extrude_47.CappingOn()
extrude_47.SetScaleFactor(vtk_math.Random(1, 10))

extrude_48 = vtkLinearExtrusionFilter()
extrude_48.SetInputConnection(triangle_filter_48.GetOutputPort())
extrude_48.SetExtrusionType(1)
extrude_48.SetVector(0, 0, 1)
extrude_48.CappingOn()
extrude_48.SetScaleFactor(vtk_math.Random(1, 10))

extrude_49 = vtkLinearExtrusionFilter()
extrude_49.SetInputConnection(triangle_filter_49.GetOutputPort())
extrude_49.SetExtrusionType(1)
extrude_49.SetVector(0, 0, 1)
extrude_49.CappingOn()
extrude_49.SetScaleFactor(vtk_math.Random(1, 10))

extrude_50 = vtkLinearExtrusionFilter()
extrude_50.SetInputConnection(triangle_filter_50.GetOutputPort())
extrude_50.SetExtrusionType(1)
extrude_50.SetVector(0, 0, 1)
extrude_50.CappingOn()
extrude_50.SetScaleFactor(vtk_math.Random(1, 10))

# Mapper and actor pairs with random colors
mapper_0 = vtkPolyDataMapper()
mapper_0.SetInputConnection(extrude_0.GetOutputPort())
actor_0 = vtkActor()
actor_0.SetMapper(mapper_0)
actor_0.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_1 = vtkPolyDataMapper()
mapper_1.SetInputConnection(extrude_1.GetOutputPort())
actor_1 = vtkActor()
actor_1.SetMapper(mapper_1)
actor_1.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_2 = vtkPolyDataMapper()
mapper_2.SetInputConnection(extrude_2.GetOutputPort())
actor_2 = vtkActor()
actor_2.SetMapper(mapper_2)
actor_2.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_3 = vtkPolyDataMapper()
mapper_3.SetInputConnection(extrude_3.GetOutputPort())
actor_3 = vtkActor()
actor_3.SetMapper(mapper_3)
actor_3.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_4 = vtkPolyDataMapper()
mapper_4.SetInputConnection(extrude_4.GetOutputPort())
actor_4 = vtkActor()
actor_4.SetMapper(mapper_4)
actor_4.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_5 = vtkPolyDataMapper()
mapper_5.SetInputConnection(extrude_5.GetOutputPort())
actor_5 = vtkActor()
actor_5.SetMapper(mapper_5)
actor_5.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_6 = vtkPolyDataMapper()
mapper_6.SetInputConnection(extrude_6.GetOutputPort())
actor_6 = vtkActor()
actor_6.SetMapper(mapper_6)
actor_6.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_7 = vtkPolyDataMapper()
mapper_7.SetInputConnection(extrude_7.GetOutputPort())
actor_7 = vtkActor()
actor_7.SetMapper(mapper_7)
actor_7.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_8 = vtkPolyDataMapper()
mapper_8.SetInputConnection(extrude_8.GetOutputPort())
actor_8 = vtkActor()
actor_8.SetMapper(mapper_8)
actor_8.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_9 = vtkPolyDataMapper()
mapper_9.SetInputConnection(extrude_9.GetOutputPort())
actor_9 = vtkActor()
actor_9.SetMapper(mapper_9)
actor_9.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_10 = vtkPolyDataMapper()
mapper_10.SetInputConnection(extrude_10.GetOutputPort())
actor_10 = vtkActor()
actor_10.SetMapper(mapper_10)
actor_10.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_11 = vtkPolyDataMapper()
mapper_11.SetInputConnection(extrude_11.GetOutputPort())
actor_11 = vtkActor()
actor_11.SetMapper(mapper_11)
actor_11.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_12 = vtkPolyDataMapper()
mapper_12.SetInputConnection(extrude_12.GetOutputPort())
actor_12 = vtkActor()
actor_12.SetMapper(mapper_12)
actor_12.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_13 = vtkPolyDataMapper()
mapper_13.SetInputConnection(extrude_13.GetOutputPort())
actor_13 = vtkActor()
actor_13.SetMapper(mapper_13)
actor_13.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_14 = vtkPolyDataMapper()
mapper_14.SetInputConnection(extrude_14.GetOutputPort())
actor_14 = vtkActor()
actor_14.SetMapper(mapper_14)
actor_14.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_15 = vtkPolyDataMapper()
mapper_15.SetInputConnection(extrude_15.GetOutputPort())
actor_15 = vtkActor()
actor_15.SetMapper(mapper_15)
actor_15.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_16 = vtkPolyDataMapper()
mapper_16.SetInputConnection(extrude_16.GetOutputPort())
actor_16 = vtkActor()
actor_16.SetMapper(mapper_16)
actor_16.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_17 = vtkPolyDataMapper()
mapper_17.SetInputConnection(extrude_17.GetOutputPort())
actor_17 = vtkActor()
actor_17.SetMapper(mapper_17)
actor_17.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_18 = vtkPolyDataMapper()
mapper_18.SetInputConnection(extrude_18.GetOutputPort())
actor_18 = vtkActor()
actor_18.SetMapper(mapper_18)
actor_18.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_19 = vtkPolyDataMapper()
mapper_19.SetInputConnection(extrude_19.GetOutputPort())
actor_19 = vtkActor()
actor_19.SetMapper(mapper_19)
actor_19.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_20 = vtkPolyDataMapper()
mapper_20.SetInputConnection(extrude_20.GetOutputPort())
actor_20 = vtkActor()
actor_20.SetMapper(mapper_20)
actor_20.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_21 = vtkPolyDataMapper()
mapper_21.SetInputConnection(extrude_21.GetOutputPort())
actor_21 = vtkActor()
actor_21.SetMapper(mapper_21)
actor_21.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_22 = vtkPolyDataMapper()
mapper_22.SetInputConnection(extrude_22.GetOutputPort())
actor_22 = vtkActor()
actor_22.SetMapper(mapper_22)
actor_22.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_23 = vtkPolyDataMapper()
mapper_23.SetInputConnection(extrude_23.GetOutputPort())
actor_23 = vtkActor()
actor_23.SetMapper(mapper_23)
actor_23.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_24 = vtkPolyDataMapper()
mapper_24.SetInputConnection(extrude_24.GetOutputPort())
actor_24 = vtkActor()
actor_24.SetMapper(mapper_24)
actor_24.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_25 = vtkPolyDataMapper()
mapper_25.SetInputConnection(extrude_25.GetOutputPort())
actor_25 = vtkActor()
actor_25.SetMapper(mapper_25)
actor_25.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_26 = vtkPolyDataMapper()
mapper_26.SetInputConnection(extrude_26.GetOutputPort())
actor_26 = vtkActor()
actor_26.SetMapper(mapper_26)
actor_26.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_27 = vtkPolyDataMapper()
mapper_27.SetInputConnection(extrude_27.GetOutputPort())
actor_27 = vtkActor()
actor_27.SetMapper(mapper_27)
actor_27.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_28 = vtkPolyDataMapper()
mapper_28.SetInputConnection(extrude_28.GetOutputPort())
actor_28 = vtkActor()
actor_28.SetMapper(mapper_28)
actor_28.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_29 = vtkPolyDataMapper()
mapper_29.SetInputConnection(extrude_29.GetOutputPort())
actor_29 = vtkActor()
actor_29.SetMapper(mapper_29)
actor_29.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_30 = vtkPolyDataMapper()
mapper_30.SetInputConnection(extrude_30.GetOutputPort())
actor_30 = vtkActor()
actor_30.SetMapper(mapper_30)
actor_30.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_31 = vtkPolyDataMapper()
mapper_31.SetInputConnection(extrude_31.GetOutputPort())
actor_31 = vtkActor()
actor_31.SetMapper(mapper_31)
actor_31.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_32 = vtkPolyDataMapper()
mapper_32.SetInputConnection(extrude_32.GetOutputPort())
actor_32 = vtkActor()
actor_32.SetMapper(mapper_32)
actor_32.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_33 = vtkPolyDataMapper()
mapper_33.SetInputConnection(extrude_33.GetOutputPort())
actor_33 = vtkActor()
actor_33.SetMapper(mapper_33)
actor_33.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_34 = vtkPolyDataMapper()
mapper_34.SetInputConnection(extrude_34.GetOutputPort())
actor_34 = vtkActor()
actor_34.SetMapper(mapper_34)
actor_34.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_35 = vtkPolyDataMapper()
mapper_35.SetInputConnection(extrude_35.GetOutputPort())
actor_35 = vtkActor()
actor_35.SetMapper(mapper_35)
actor_35.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_36 = vtkPolyDataMapper()
mapper_36.SetInputConnection(extrude_36.GetOutputPort())
actor_36 = vtkActor()
actor_36.SetMapper(mapper_36)
actor_36.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_37 = vtkPolyDataMapper()
mapper_37.SetInputConnection(extrude_37.GetOutputPort())
actor_37 = vtkActor()
actor_37.SetMapper(mapper_37)
actor_37.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_38 = vtkPolyDataMapper()
mapper_38.SetInputConnection(extrude_38.GetOutputPort())
actor_38 = vtkActor()
actor_38.SetMapper(mapper_38)
actor_38.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_39 = vtkPolyDataMapper()
mapper_39.SetInputConnection(extrude_39.GetOutputPort())
actor_39 = vtkActor()
actor_39.SetMapper(mapper_39)
actor_39.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_40 = vtkPolyDataMapper()
mapper_40.SetInputConnection(extrude_40.GetOutputPort())
actor_40 = vtkActor()
actor_40.SetMapper(mapper_40)
actor_40.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_41 = vtkPolyDataMapper()
mapper_41.SetInputConnection(extrude_41.GetOutputPort())
actor_41 = vtkActor()
actor_41.SetMapper(mapper_41)
actor_41.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_42 = vtkPolyDataMapper()
mapper_42.SetInputConnection(extrude_42.GetOutputPort())
actor_42 = vtkActor()
actor_42.SetMapper(mapper_42)
actor_42.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_43 = vtkPolyDataMapper()
mapper_43.SetInputConnection(extrude_43.GetOutputPort())
actor_43 = vtkActor()
actor_43.SetMapper(mapper_43)
actor_43.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_44 = vtkPolyDataMapper()
mapper_44.SetInputConnection(extrude_44.GetOutputPort())
actor_44 = vtkActor()
actor_44.SetMapper(mapper_44)
actor_44.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_45 = vtkPolyDataMapper()
mapper_45.SetInputConnection(extrude_45.GetOutputPort())
actor_45 = vtkActor()
actor_45.SetMapper(mapper_45)
actor_45.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_46 = vtkPolyDataMapper()
mapper_46.SetInputConnection(extrude_46.GetOutputPort())
actor_46 = vtkActor()
actor_46.SetMapper(mapper_46)
actor_46.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_47 = vtkPolyDataMapper()
mapper_47.SetInputConnection(extrude_47.GetOutputPort())
actor_47 = vtkActor()
actor_47.SetMapper(mapper_47)
actor_47.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_48 = vtkPolyDataMapper()
mapper_48.SetInputConnection(extrude_48.GetOutputPort())
actor_48 = vtkActor()
actor_48.SetMapper(mapper_48)
actor_48.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_49 = vtkPolyDataMapper()
mapper_49.SetInputConnection(extrude_49.GetOutputPort())
actor_49 = vtkActor()
actor_49.SetMapper(mapper_49)
actor_49.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

mapper_50 = vtkPolyDataMapper()
mapper_50.SetInputConnection(extrude_50.GetOutputPort())
actor_50 = vtkActor()
actor_50.SetMapper(mapper_50)
actor_50.GetProperty().SetColor(vtk_math.Random(0, 1), vtk_math.Random(0, 1), vtk_math.Random(0, 1))

# Renderer
renderer = vtkRenderer()
renderer.AddActor(actor_0)
renderer.AddActor(actor_1)
renderer.AddActor(actor_2)
renderer.AddActor(actor_3)
renderer.AddActor(actor_4)
renderer.AddActor(actor_5)
renderer.AddActor(actor_6)
renderer.AddActor(actor_7)
renderer.AddActor(actor_8)
renderer.AddActor(actor_9)
renderer.AddActor(actor_10)
renderer.AddActor(actor_11)
renderer.AddActor(actor_12)
renderer.AddActor(actor_13)
renderer.AddActor(actor_14)
renderer.AddActor(actor_15)
renderer.AddActor(actor_16)
renderer.AddActor(actor_17)
renderer.AddActor(actor_18)
renderer.AddActor(actor_19)
renderer.AddActor(actor_20)
renderer.AddActor(actor_21)
renderer.AddActor(actor_22)
renderer.AddActor(actor_23)
renderer.AddActor(actor_24)
renderer.AddActor(actor_25)
renderer.AddActor(actor_26)
renderer.AddActor(actor_27)
renderer.AddActor(actor_28)
renderer.AddActor(actor_29)
renderer.AddActor(actor_30)
renderer.AddActor(actor_31)
renderer.AddActor(actor_32)
renderer.AddActor(actor_33)
renderer.AddActor(actor_34)
renderer.AddActor(actor_35)
renderer.AddActor(actor_36)
renderer.AddActor(actor_37)
renderer.AddActor(actor_38)
renderer.AddActor(actor_39)
renderer.AddActor(actor_40)
renderer.AddActor(actor_41)
renderer.AddActor(actor_42)
renderer.AddActor(actor_43)
renderer.AddActor(actor_44)
renderer.AddActor(actor_45)
renderer.AddActor(actor_46)
renderer.AddActor(actor_47)
renderer.AddActor(actor_48)
renderer.AddActor(actor_49)
renderer.AddActor(actor_50)
renderer.SetBackground(1, 1, 1)

# Window
render_window = vtkRenderWindow()
render_window.AddRenderer(renderer)
render_window.SetSize(500, 250)
render_window.SetWindowName("ele state")

# Scene
camera = renderer.GetActiveCamera()
camera.SetClippingRange(10.2299, 511.497)
camera.SetPosition(-119.669, -25.5502, 79.0198)
camera.SetFocalPoint(-115.96, 41.6709, 1.99546)
camera.SetViewUp(-0.0013035, 0.753456, 0.657497)

# Interactor
interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)

interactor.Initialize()
interactor.Start()
