#!/usr/bin/env python

# Demonstrate vtkGeometryFilter ghost cell handling across multiple
# mesh types with HIDDENCELL and DUPLICATECELL flags, with and
# without RemoveGhostInterfaces, arranged in a 5x4 viewport grid.

# Factory overrides
import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingFreeType  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401

from vtkmodules.vtkCommonCore import (
    vtkDoubleArray,
    vtkIntArray,
    vtkUnsignedCharArray,
)
from vtkmodules.vtkCommonDataModel import (
    vtkDataSetAttributes,
    vtkImageData,
    vtkRectilinearGrid,
)
from vtkmodules.vtkFiltersCore import (
    vtkAppendFilter,
    vtkUnstructuredGridToExplicitStructuredGrid,
)
from vtkmodules.vtkCommonExecutionModel import vtkImageToStructuredGrid
from vtkmodules.vtkFiltersGeometry import vtkGeometryFilter
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkDataSetMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
    vtkTextActor,
)

# Layout: 5 columns x 4 rows
col_width = 1.0 / 5
row_height = 1.0 / 4

# ========== Row 0: HIDDENCELL, RemoveGhostInterfaces=False ==========

# Row 0, Col 0: ImageData
image_r0c0 = vtkImageData()
image_r0c0.SetDimensions(3, 3, 3)
ghost_r0c0 = vtkUnsignedCharArray()
ghost_r0c0.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r0c0.SetNumberOfTuples(image_r0c0.GetNumberOfCells())
ghost_r0c0.SetValue(0, 0)
ghost_r0c0.SetValue(1, 0)
ghost_r0c0.SetValue(2, 0)
ghost_r0c0.SetValue(3, 0)
ghost_r0c0.SetValue(4, vtkDataSetAttributes.HIDDENCELL)
ghost_r0c0.SetValue(5, vtkDataSetAttributes.HIDDENCELL)
ghost_r0c0.SetValue(6, vtkDataSetAttributes.HIDDENCELL)
ghost_r0c0.SetValue(7, vtkDataSetAttributes.HIDDENCELL)
image_r0c0.GetCellData().AddArray(ghost_r0c0)
image_r0c0.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r0c0 = vtkGeometryFilter()
geom_r0c0.SetInputData(image_r0c0)
geom_r0c0.SetRemoveGhostInterfaces(False)

mapper_r0c0 = vtkDataSetMapper()
mapper_r0c0.SetInputConnection(geom_r0c0.GetOutputPort())
mapper_r0c0.SetScalarVisibility(False)

actor_r0c0 = vtkActor()
actor_r0c0.SetMapper(mapper_r0c0)
actor_r0c0.GetProperty().EdgeVisibilityOn()
actor_r0c0.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r0c0.GetProperty().SetLineWidth(4.0)
actor_r0c0.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r0c0 = vtkTextActor()
text_r0c0.SetInput("ImageData\nHIDDENCELL\nRemoveInterfaces=False")
text_r0c0.GetTextProperty().SetFontSize(14)
text_r0c0.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r0c0.SetPosition(5, 5)

# Row 0, Col 1: RectilinearGrid
image_r0c1 = vtkImageData()
image_r0c1.SetDimensions(3, 3, 3)
dims_r0c1 = image_r0c1.GetDimensions()
spacing_r0c1 = image_r0c1.GetSpacing()
origin_r0c1 = image_r0c1.GetOrigin()
x_coords_r0c1 = vtkDoubleArray()
x_coords_r0c1.SetNumberOfValues(dims_r0c1[0])
x_coords_r0c1.SetValue(0, origin_r0c1[0])
x_coords_r0c1.SetValue(1, origin_r0c1[0] + spacing_r0c1[0])
x_coords_r0c1.SetValue(2, origin_r0c1[0] + 2 * spacing_r0c1[0])
y_coords_r0c1 = vtkDoubleArray()
y_coords_r0c1.SetNumberOfValues(dims_r0c1[1])
y_coords_r0c1.SetValue(0, origin_r0c1[1])
y_coords_r0c1.SetValue(1, origin_r0c1[1] + spacing_r0c1[1])
y_coords_r0c1.SetValue(2, origin_r0c1[1] + 2 * spacing_r0c1[1])
z_coords_r0c1 = vtkDoubleArray()
z_coords_r0c1.SetNumberOfValues(dims_r0c1[2])
z_coords_r0c1.SetValue(0, origin_r0c1[2])
z_coords_r0c1.SetValue(1, origin_r0c1[2] + spacing_r0c1[2])
z_coords_r0c1.SetValue(2, origin_r0c1[2] + 2 * spacing_r0c1[2])
rgrid_r0c1 = vtkRectilinearGrid()
rgrid_r0c1.SetDimensions(dims_r0c1[0], dims_r0c1[1], dims_r0c1[2])
rgrid_r0c1.SetXCoordinates(x_coords_r0c1)
rgrid_r0c1.SetYCoordinates(y_coords_r0c1)
rgrid_r0c1.SetZCoordinates(z_coords_r0c1)
rgrid_r0c1.GetPointData().ShallowCopy(image_r0c1.GetPointData())
rgrid_r0c1.GetCellData().ShallowCopy(image_r0c1.GetCellData())
ghost_r0c1 = vtkUnsignedCharArray()
ghost_r0c1.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r0c1.SetNumberOfTuples(rgrid_r0c1.GetNumberOfCells())
ghost_r0c1.SetValue(0, 0)
ghost_r0c1.SetValue(1, 0)
ghost_r0c1.SetValue(2, 0)
ghost_r0c1.SetValue(3, 0)
ghost_r0c1.SetValue(4, vtkDataSetAttributes.HIDDENCELL)
ghost_r0c1.SetValue(5, vtkDataSetAttributes.HIDDENCELL)
ghost_r0c1.SetValue(6, vtkDataSetAttributes.HIDDENCELL)
ghost_r0c1.SetValue(7, vtkDataSetAttributes.HIDDENCELL)
rgrid_r0c1.GetCellData().AddArray(ghost_r0c1)
rgrid_r0c1.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r0c1 = vtkGeometryFilter()
geom_r0c1.SetInputData(rgrid_r0c1)
geom_r0c1.SetRemoveGhostInterfaces(False)

mapper_r0c1 = vtkDataSetMapper()
mapper_r0c1.SetInputConnection(geom_r0c1.GetOutputPort())
mapper_r0c1.SetScalarVisibility(False)

actor_r0c1 = vtkActor()
actor_r0c1.SetMapper(mapper_r0c1)
actor_r0c1.GetProperty().EdgeVisibilityOn()
actor_r0c1.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r0c1.GetProperty().SetLineWidth(4.0)
actor_r0c1.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r0c1 = vtkTextActor()
text_r0c1.SetInput("RectilinearGrid\nHIDDENCELL\nRemoveInterfaces=False")
text_r0c1.GetTextProperty().SetFontSize(14)
text_r0c1.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r0c1.SetPosition(5, 5)

# Row 0, Col 2: StructuredGrid
image_r0c2 = vtkImageData()
image_r0c2.SetDimensions(3, 3, 3)
img_to_sg_r0c2 = vtkImageToStructuredGrid()
img_to_sg_r0c2.SetInputData(image_r0c2)
img_to_sg_r0c2.Update()
sgrid_r0c2 = img_to_sg_r0c2.GetOutput()
ghost_r0c2 = vtkUnsignedCharArray()
ghost_r0c2.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r0c2.SetNumberOfTuples(sgrid_r0c2.GetNumberOfCells())
ghost_r0c2.SetValue(0, 0)
ghost_r0c2.SetValue(1, 0)
ghost_r0c2.SetValue(2, 0)
ghost_r0c2.SetValue(3, 0)
ghost_r0c2.SetValue(4, vtkDataSetAttributes.HIDDENCELL)
ghost_r0c2.SetValue(5, vtkDataSetAttributes.HIDDENCELL)
ghost_r0c2.SetValue(6, vtkDataSetAttributes.HIDDENCELL)
ghost_r0c2.SetValue(7, vtkDataSetAttributes.HIDDENCELL)
sgrid_r0c2.GetCellData().AddArray(ghost_r0c2)
sgrid_r0c2.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r0c2 = vtkGeometryFilter()
geom_r0c2.SetInputData(sgrid_r0c2)
geom_r0c2.SetRemoveGhostInterfaces(False)

mapper_r0c2 = vtkDataSetMapper()
mapper_r0c2.SetInputConnection(geom_r0c2.GetOutputPort())
mapper_r0c2.SetScalarVisibility(False)

actor_r0c2 = vtkActor()
actor_r0c2.SetMapper(mapper_r0c2)
actor_r0c2.GetProperty().EdgeVisibilityOn()
actor_r0c2.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r0c2.GetProperty().SetLineWidth(4.0)
actor_r0c2.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r0c2 = vtkTextActor()
text_r0c2.SetInput("StructuredGrid\nHIDDENCELL\nRemoveInterfaces=False")
text_r0c2.GetTextProperty().SetFontSize(14)
text_r0c2.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r0c2.SetPosition(5, 5)

# Row 0, Col 3: UnstructuredGrid
image_r0c3 = vtkImageData()
image_r0c3.SetDimensions(3, 3, 3)
append_r0c3 = vtkAppendFilter()
append_r0c3.AddInputData(image_r0c3)
append_r0c3.Update()
ugrid_r0c3 = append_r0c3.GetOutput()
ghost_r0c3 = vtkUnsignedCharArray()
ghost_r0c3.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r0c3.SetNumberOfTuples(ugrid_r0c3.GetNumberOfCells())
ghost_r0c3.SetValue(0, 0)
ghost_r0c3.SetValue(1, 0)
ghost_r0c3.SetValue(2, 0)
ghost_r0c3.SetValue(3, 0)
ghost_r0c3.SetValue(4, vtkDataSetAttributes.HIDDENCELL)
ghost_r0c3.SetValue(5, vtkDataSetAttributes.HIDDENCELL)
ghost_r0c3.SetValue(6, vtkDataSetAttributes.HIDDENCELL)
ghost_r0c3.SetValue(7, vtkDataSetAttributes.HIDDENCELL)
ugrid_r0c3.GetCellData().AddArray(ghost_r0c3)
ugrid_r0c3.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r0c3 = vtkGeometryFilter()
geom_r0c3.SetInputData(ugrid_r0c3)
geom_r0c3.SetRemoveGhostInterfaces(False)

mapper_r0c3 = vtkDataSetMapper()
mapper_r0c3.SetInputConnection(geom_r0c3.GetOutputPort())
mapper_r0c3.SetScalarVisibility(False)

actor_r0c3 = vtkActor()
actor_r0c3.SetMapper(mapper_r0c3)
actor_r0c3.GetProperty().EdgeVisibilityOn()
actor_r0c3.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r0c3.GetProperty().SetLineWidth(4.0)
actor_r0c3.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r0c3 = vtkTextActor()
text_r0c3.SetInput("UnstructuredGrid\nHIDDENCELL\nRemoveInterfaces=False")
text_r0c3.GetTextProperty().SetFontSize(14)
text_r0c3.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r0c3.SetPosition(5, 5)

# Row 0, Col 4: ExplicitStructuredGrid
image_r0c4 = vtkImageData()
image_r0c4.SetDimensions(3, 3, 3)
append_r0c4 = vtkAppendFilter()
append_r0c4.AddInputData(image_r0c4)
append_r0c4.Update()
ugrid_r0c4 = append_r0c4.GetOutput()
dims_r0c4 = image_r0c4.GetDimensions()
arr_i_r0c4 = vtkIntArray()
arr_i_r0c4.SetName("BLOCK_I")
arr_i_r0c4.SetNumberOfTuples(ugrid_r0c4.GetNumberOfCells())
arr_j_r0c4 = vtkIntArray()
arr_j_r0c4.SetName("BLOCK_J")
arr_j_r0c4.SetNumberOfTuples(ugrid_r0c4.GetNumberOfCells())
arr_k_r0c4 = vtkIntArray()
arr_k_r0c4.SetName("BLOCK_K")
arr_k_r0c4.SetNumberOfTuples(ugrid_r0c4.GetNumberOfCells())
cid_r0c4 = 0
for kk in range(dims_r0c4[2] - 1):
    for jj in range(dims_r0c4[1] - 1):
        for ii in range(dims_r0c4[0] - 1):
            arr_i_r0c4.SetValue(cid_r0c4, ii)
            arr_j_r0c4.SetValue(cid_r0c4, jj)
            arr_k_r0c4.SetValue(cid_r0c4, kk)
            cid_r0c4 += 1
ugrid_r0c4.GetCellData().AddArray(arr_i_r0c4)
ugrid_r0c4.GetCellData().AddArray(arr_j_r0c4)
ugrid_r0c4.GetCellData().AddArray(arr_k_r0c4)
ug_to_esg_r0c4 = vtkUnstructuredGridToExplicitStructuredGrid()
ug_to_esg_r0c4.SetInputData(ugrid_r0c4)
ug_to_esg_r0c4.SetInputArrayToProcess(0, 0, 0, 1, "BLOCK_I")
ug_to_esg_r0c4.SetInputArrayToProcess(1, 0, 0, 1, "BLOCK_J")
ug_to_esg_r0c4.SetInputArrayToProcess(2, 0, 0, 1, "BLOCK_K")
ug_to_esg_r0c4.Update()
esgrid_r0c4 = ug_to_esg_r0c4.GetOutput()
ghost_r0c4 = vtkUnsignedCharArray()
ghost_r0c4.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r0c4.SetNumberOfTuples(esgrid_r0c4.GetNumberOfCells())
ghost_r0c4.SetValue(0, 0)
ghost_r0c4.SetValue(1, 0)
ghost_r0c4.SetValue(2, 0)
ghost_r0c4.SetValue(3, 0)
ghost_r0c4.SetValue(4, vtkDataSetAttributes.HIDDENCELL)
ghost_r0c4.SetValue(5, vtkDataSetAttributes.HIDDENCELL)
ghost_r0c4.SetValue(6, vtkDataSetAttributes.HIDDENCELL)
ghost_r0c4.SetValue(7, vtkDataSetAttributes.HIDDENCELL)
esgrid_r0c4.GetCellData().AddArray(ghost_r0c4)
esgrid_r0c4.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r0c4 = vtkGeometryFilter()
geom_r0c4.SetInputData(esgrid_r0c4)
geom_r0c4.SetRemoveGhostInterfaces(False)

mapper_r0c4 = vtkDataSetMapper()
mapper_r0c4.SetInputConnection(geom_r0c4.GetOutputPort())
mapper_r0c4.SetScalarVisibility(False)

actor_r0c4 = vtkActor()
actor_r0c4.SetMapper(mapper_r0c4)
actor_r0c4.GetProperty().EdgeVisibilityOn()
actor_r0c4.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r0c4.GetProperty().SetLineWidth(4.0)
actor_r0c4.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r0c4 = vtkTextActor()
text_r0c4.SetInput("ExplicitStructuredGrid\nHIDDENCELL\nRemoveInterfaces=False")
text_r0c4.GetTextProperty().SetFontSize(14)
text_r0c4.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r0c4.SetPosition(5, 5)

# ========== Row 1: HIDDENCELL, RemoveGhostInterfaces=True ==========

# Row 1, Col 0: ImageData
image_r1c0 = vtkImageData()
image_r1c0.SetDimensions(3, 3, 3)
ghost_r1c0 = vtkUnsignedCharArray()
ghost_r1c0.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r1c0.SetNumberOfTuples(image_r1c0.GetNumberOfCells())
ghost_r1c0.SetValue(0, 0)
ghost_r1c0.SetValue(1, 0)
ghost_r1c0.SetValue(2, 0)
ghost_r1c0.SetValue(3, 0)
ghost_r1c0.SetValue(4, vtkDataSetAttributes.HIDDENCELL)
ghost_r1c0.SetValue(5, vtkDataSetAttributes.HIDDENCELL)
ghost_r1c0.SetValue(6, vtkDataSetAttributes.HIDDENCELL)
ghost_r1c0.SetValue(7, vtkDataSetAttributes.HIDDENCELL)
image_r1c0.GetCellData().AddArray(ghost_r1c0)
image_r1c0.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r1c0 = vtkGeometryFilter()
geom_r1c0.SetInputData(image_r1c0)
geom_r1c0.SetRemoveGhostInterfaces(True)

mapper_r1c0 = vtkDataSetMapper()
mapper_r1c0.SetInputConnection(geom_r1c0.GetOutputPort())
mapper_r1c0.SetScalarVisibility(False)

actor_r1c0 = vtkActor()
actor_r1c0.SetMapper(mapper_r1c0)
actor_r1c0.GetProperty().EdgeVisibilityOn()
actor_r1c0.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r1c0.GetProperty().SetLineWidth(4.0)
actor_r1c0.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r1c0 = vtkTextActor()
text_r1c0.SetInput("ImageData\nHIDDENCELL\nRemoveInterfaces=True")
text_r1c0.GetTextProperty().SetFontSize(14)
text_r1c0.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r1c0.SetPosition(5, 5)

# Row 1, Col 1: RectilinearGrid
image_r1c1 = vtkImageData()
image_r1c1.SetDimensions(3, 3, 3)
dims_r1c1 = image_r1c1.GetDimensions()
spacing_r1c1 = image_r1c1.GetSpacing()
origin_r1c1 = image_r1c1.GetOrigin()
x_coords_r1c1 = vtkDoubleArray()
x_coords_r1c1.SetNumberOfValues(dims_r1c1[0])
x_coords_r1c1.SetValue(0, origin_r1c1[0])
x_coords_r1c1.SetValue(1, origin_r1c1[0] + spacing_r1c1[0])
x_coords_r1c1.SetValue(2, origin_r1c1[0] + 2 * spacing_r1c1[0])
y_coords_r1c1 = vtkDoubleArray()
y_coords_r1c1.SetNumberOfValues(dims_r1c1[1])
y_coords_r1c1.SetValue(0, origin_r1c1[1])
y_coords_r1c1.SetValue(1, origin_r1c1[1] + spacing_r1c1[1])
y_coords_r1c1.SetValue(2, origin_r1c1[1] + 2 * spacing_r1c1[1])
z_coords_r1c1 = vtkDoubleArray()
z_coords_r1c1.SetNumberOfValues(dims_r1c1[2])
z_coords_r1c1.SetValue(0, origin_r1c1[2])
z_coords_r1c1.SetValue(1, origin_r1c1[2] + spacing_r1c1[2])
z_coords_r1c1.SetValue(2, origin_r1c1[2] + 2 * spacing_r1c1[2])
rgrid_r1c1 = vtkRectilinearGrid()
rgrid_r1c1.SetDimensions(dims_r1c1[0], dims_r1c1[1], dims_r1c1[2])
rgrid_r1c1.SetXCoordinates(x_coords_r1c1)
rgrid_r1c1.SetYCoordinates(y_coords_r1c1)
rgrid_r1c1.SetZCoordinates(z_coords_r1c1)
rgrid_r1c1.GetPointData().ShallowCopy(image_r1c1.GetPointData())
rgrid_r1c1.GetCellData().ShallowCopy(image_r1c1.GetCellData())
ghost_r1c1 = vtkUnsignedCharArray()
ghost_r1c1.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r1c1.SetNumberOfTuples(rgrid_r1c1.GetNumberOfCells())
ghost_r1c1.SetValue(0, 0)
ghost_r1c1.SetValue(1, 0)
ghost_r1c1.SetValue(2, 0)
ghost_r1c1.SetValue(3, 0)
ghost_r1c1.SetValue(4, vtkDataSetAttributes.HIDDENCELL)
ghost_r1c1.SetValue(5, vtkDataSetAttributes.HIDDENCELL)
ghost_r1c1.SetValue(6, vtkDataSetAttributes.HIDDENCELL)
ghost_r1c1.SetValue(7, vtkDataSetAttributes.HIDDENCELL)
rgrid_r1c1.GetCellData().AddArray(ghost_r1c1)
rgrid_r1c1.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r1c1 = vtkGeometryFilter()
geom_r1c1.SetInputData(rgrid_r1c1)
geom_r1c1.SetRemoveGhostInterfaces(True)

mapper_r1c1 = vtkDataSetMapper()
mapper_r1c1.SetInputConnection(geom_r1c1.GetOutputPort())
mapper_r1c1.SetScalarVisibility(False)

actor_r1c1 = vtkActor()
actor_r1c1.SetMapper(mapper_r1c1)
actor_r1c1.GetProperty().EdgeVisibilityOn()
actor_r1c1.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r1c1.GetProperty().SetLineWidth(4.0)
actor_r1c1.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r1c1 = vtkTextActor()
text_r1c1.SetInput("RectilinearGrid\nHIDDENCELL\nRemoveInterfaces=True")
text_r1c1.GetTextProperty().SetFontSize(14)
text_r1c1.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r1c1.SetPosition(5, 5)

# Row 1, Col 2: StructuredGrid
image_r1c2 = vtkImageData()
image_r1c2.SetDimensions(3, 3, 3)
img_to_sg_r1c2 = vtkImageToStructuredGrid()
img_to_sg_r1c2.SetInputData(image_r1c2)
img_to_sg_r1c2.Update()
sgrid_r1c2 = img_to_sg_r1c2.GetOutput()
ghost_r1c2 = vtkUnsignedCharArray()
ghost_r1c2.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r1c2.SetNumberOfTuples(sgrid_r1c2.GetNumberOfCells())
ghost_r1c2.SetValue(0, 0)
ghost_r1c2.SetValue(1, 0)
ghost_r1c2.SetValue(2, 0)
ghost_r1c2.SetValue(3, 0)
ghost_r1c2.SetValue(4, vtkDataSetAttributes.HIDDENCELL)
ghost_r1c2.SetValue(5, vtkDataSetAttributes.HIDDENCELL)
ghost_r1c2.SetValue(6, vtkDataSetAttributes.HIDDENCELL)
ghost_r1c2.SetValue(7, vtkDataSetAttributes.HIDDENCELL)
sgrid_r1c2.GetCellData().AddArray(ghost_r1c2)
sgrid_r1c2.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r1c2 = vtkGeometryFilter()
geom_r1c2.SetInputData(sgrid_r1c2)
geom_r1c2.SetRemoveGhostInterfaces(True)

mapper_r1c2 = vtkDataSetMapper()
mapper_r1c2.SetInputConnection(geom_r1c2.GetOutputPort())
mapper_r1c2.SetScalarVisibility(False)

actor_r1c2 = vtkActor()
actor_r1c2.SetMapper(mapper_r1c2)
actor_r1c2.GetProperty().EdgeVisibilityOn()
actor_r1c2.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r1c2.GetProperty().SetLineWidth(4.0)
actor_r1c2.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r1c2 = vtkTextActor()
text_r1c2.SetInput("StructuredGrid\nHIDDENCELL\nRemoveInterfaces=True")
text_r1c2.GetTextProperty().SetFontSize(14)
text_r1c2.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r1c2.SetPosition(5, 5)

# Row 1, Col 3: UnstructuredGrid
image_r1c3 = vtkImageData()
image_r1c3.SetDimensions(3, 3, 3)
append_r1c3 = vtkAppendFilter()
append_r1c3.AddInputData(image_r1c3)
append_r1c3.Update()
ugrid_r1c3 = append_r1c3.GetOutput()
ghost_r1c3 = vtkUnsignedCharArray()
ghost_r1c3.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r1c3.SetNumberOfTuples(ugrid_r1c3.GetNumberOfCells())
ghost_r1c3.SetValue(0, 0)
ghost_r1c3.SetValue(1, 0)
ghost_r1c3.SetValue(2, 0)
ghost_r1c3.SetValue(3, 0)
ghost_r1c3.SetValue(4, vtkDataSetAttributes.HIDDENCELL)
ghost_r1c3.SetValue(5, vtkDataSetAttributes.HIDDENCELL)
ghost_r1c3.SetValue(6, vtkDataSetAttributes.HIDDENCELL)
ghost_r1c3.SetValue(7, vtkDataSetAttributes.HIDDENCELL)
ugrid_r1c3.GetCellData().AddArray(ghost_r1c3)
ugrid_r1c3.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r1c3 = vtkGeometryFilter()
geom_r1c3.SetInputData(ugrid_r1c3)
geom_r1c3.SetRemoveGhostInterfaces(True)

mapper_r1c3 = vtkDataSetMapper()
mapper_r1c3.SetInputConnection(geom_r1c3.GetOutputPort())
mapper_r1c3.SetScalarVisibility(False)

actor_r1c3 = vtkActor()
actor_r1c3.SetMapper(mapper_r1c3)
actor_r1c3.GetProperty().EdgeVisibilityOn()
actor_r1c3.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r1c3.GetProperty().SetLineWidth(4.0)
actor_r1c3.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r1c3 = vtkTextActor()
text_r1c3.SetInput("UnstructuredGrid\nHIDDENCELL\nRemoveInterfaces=True")
text_r1c3.GetTextProperty().SetFontSize(14)
text_r1c3.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r1c3.SetPosition(5, 5)

# Row 1, Col 4: ExplicitStructuredGrid
image_r1c4 = vtkImageData()
image_r1c4.SetDimensions(3, 3, 3)
append_r1c4 = vtkAppendFilter()
append_r1c4.AddInputData(image_r1c4)
append_r1c4.Update()
ugrid_r1c4 = append_r1c4.GetOutput()
dims_r1c4 = image_r1c4.GetDimensions()
arr_i_r1c4 = vtkIntArray()
arr_i_r1c4.SetName("BLOCK_I")
arr_i_r1c4.SetNumberOfTuples(ugrid_r1c4.GetNumberOfCells())
arr_j_r1c4 = vtkIntArray()
arr_j_r1c4.SetName("BLOCK_J")
arr_j_r1c4.SetNumberOfTuples(ugrid_r1c4.GetNumberOfCells())
arr_k_r1c4 = vtkIntArray()
arr_k_r1c4.SetName("BLOCK_K")
arr_k_r1c4.SetNumberOfTuples(ugrid_r1c4.GetNumberOfCells())
cid_r1c4 = 0
for kk in range(dims_r1c4[2] - 1):
    for jj in range(dims_r1c4[1] - 1):
        for ii in range(dims_r1c4[0] - 1):
            arr_i_r1c4.SetValue(cid_r1c4, ii)
            arr_j_r1c4.SetValue(cid_r1c4, jj)
            arr_k_r1c4.SetValue(cid_r1c4, kk)
            cid_r1c4 += 1
ugrid_r1c4.GetCellData().AddArray(arr_i_r1c4)
ugrid_r1c4.GetCellData().AddArray(arr_j_r1c4)
ugrid_r1c4.GetCellData().AddArray(arr_k_r1c4)
ug_to_esg_r1c4 = vtkUnstructuredGridToExplicitStructuredGrid()
ug_to_esg_r1c4.SetInputData(ugrid_r1c4)
ug_to_esg_r1c4.SetInputArrayToProcess(0, 0, 0, 1, "BLOCK_I")
ug_to_esg_r1c4.SetInputArrayToProcess(1, 0, 0, 1, "BLOCK_J")
ug_to_esg_r1c4.SetInputArrayToProcess(2, 0, 0, 1, "BLOCK_K")
ug_to_esg_r1c4.Update()
esgrid_r1c4 = ug_to_esg_r1c4.GetOutput()
ghost_r1c4 = vtkUnsignedCharArray()
ghost_r1c4.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r1c4.SetNumberOfTuples(esgrid_r1c4.GetNumberOfCells())
ghost_r1c4.SetValue(0, 0)
ghost_r1c4.SetValue(1, 0)
ghost_r1c4.SetValue(2, 0)
ghost_r1c4.SetValue(3, 0)
ghost_r1c4.SetValue(4, vtkDataSetAttributes.HIDDENCELL)
ghost_r1c4.SetValue(5, vtkDataSetAttributes.HIDDENCELL)
ghost_r1c4.SetValue(6, vtkDataSetAttributes.HIDDENCELL)
ghost_r1c4.SetValue(7, vtkDataSetAttributes.HIDDENCELL)
esgrid_r1c4.GetCellData().AddArray(ghost_r1c4)
esgrid_r1c4.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r1c4 = vtkGeometryFilter()
geom_r1c4.SetInputData(esgrid_r1c4)
geom_r1c4.SetRemoveGhostInterfaces(True)

mapper_r1c4 = vtkDataSetMapper()
mapper_r1c4.SetInputConnection(geom_r1c4.GetOutputPort())
mapper_r1c4.SetScalarVisibility(False)

actor_r1c4 = vtkActor()
actor_r1c4.SetMapper(mapper_r1c4)
actor_r1c4.GetProperty().EdgeVisibilityOn()
actor_r1c4.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r1c4.GetProperty().SetLineWidth(4.0)
actor_r1c4.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r1c4 = vtkTextActor()
text_r1c4.SetInput("ExplicitStructuredGrid\nHIDDENCELL\nRemoveInterfaces=True")
text_r1c4.GetTextProperty().SetFontSize(14)
text_r1c4.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r1c4.SetPosition(5, 5)

# ========== Row 2: DUPLICATECELL, RemoveGhostInterfaces=False ==========

# Row 2, Col 0: ImageData
image_r2c0 = vtkImageData()
image_r2c0.SetDimensions(3, 3, 3)
ghost_r2c0 = vtkUnsignedCharArray()
ghost_r2c0.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r2c0.SetNumberOfTuples(image_r2c0.GetNumberOfCells())
ghost_r2c0.SetValue(0, 0)
ghost_r2c0.SetValue(1, 0)
ghost_r2c0.SetValue(2, 0)
ghost_r2c0.SetValue(3, 0)
ghost_r2c0.SetValue(4, vtkDataSetAttributes.DUPLICATECELL)
ghost_r2c0.SetValue(5, vtkDataSetAttributes.DUPLICATECELL)
ghost_r2c0.SetValue(6, vtkDataSetAttributes.DUPLICATECELL)
ghost_r2c0.SetValue(7, vtkDataSetAttributes.DUPLICATECELL)
image_r2c0.GetCellData().AddArray(ghost_r2c0)
image_r2c0.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r2c0 = vtkGeometryFilter()
geom_r2c0.SetInputData(image_r2c0)
geom_r2c0.SetRemoveGhostInterfaces(False)

mapper_r2c0 = vtkDataSetMapper()
mapper_r2c0.SetInputConnection(geom_r2c0.GetOutputPort())
mapper_r2c0.SetScalarVisibility(False)

actor_r2c0 = vtkActor()
actor_r2c0.SetMapper(mapper_r2c0)
actor_r2c0.GetProperty().EdgeVisibilityOn()
actor_r2c0.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r2c0.GetProperty().SetLineWidth(4.0)
actor_r2c0.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r2c0 = vtkTextActor()
text_r2c0.SetInput("ImageData\nDUPLICATECELL\nRemoveInterfaces=False")
text_r2c0.GetTextProperty().SetFontSize(14)
text_r2c0.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r2c0.SetPosition(5, 5)

# Row 2, Col 1: RectilinearGrid
image_r2c1 = vtkImageData()
image_r2c1.SetDimensions(3, 3, 3)
dims_r2c1 = image_r2c1.GetDimensions()
spacing_r2c1 = image_r2c1.GetSpacing()
origin_r2c1 = image_r2c1.GetOrigin()
x_coords_r2c1 = vtkDoubleArray()
x_coords_r2c1.SetNumberOfValues(dims_r2c1[0])
x_coords_r2c1.SetValue(0, origin_r2c1[0])
x_coords_r2c1.SetValue(1, origin_r2c1[0] + spacing_r2c1[0])
x_coords_r2c1.SetValue(2, origin_r2c1[0] + 2 * spacing_r2c1[0])
y_coords_r2c1 = vtkDoubleArray()
y_coords_r2c1.SetNumberOfValues(dims_r2c1[1])
y_coords_r2c1.SetValue(0, origin_r2c1[1])
y_coords_r2c1.SetValue(1, origin_r2c1[1] + spacing_r2c1[1])
y_coords_r2c1.SetValue(2, origin_r2c1[1] + 2 * spacing_r2c1[1])
z_coords_r2c1 = vtkDoubleArray()
z_coords_r2c1.SetNumberOfValues(dims_r2c1[2])
z_coords_r2c1.SetValue(0, origin_r2c1[2])
z_coords_r2c1.SetValue(1, origin_r2c1[2] + spacing_r2c1[2])
z_coords_r2c1.SetValue(2, origin_r2c1[2] + 2 * spacing_r2c1[2])
rgrid_r2c1 = vtkRectilinearGrid()
rgrid_r2c1.SetDimensions(dims_r2c1[0], dims_r2c1[1], dims_r2c1[2])
rgrid_r2c1.SetXCoordinates(x_coords_r2c1)
rgrid_r2c1.SetYCoordinates(y_coords_r2c1)
rgrid_r2c1.SetZCoordinates(z_coords_r2c1)
rgrid_r2c1.GetPointData().ShallowCopy(image_r2c1.GetPointData())
rgrid_r2c1.GetCellData().ShallowCopy(image_r2c1.GetCellData())
ghost_r2c1 = vtkUnsignedCharArray()
ghost_r2c1.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r2c1.SetNumberOfTuples(rgrid_r2c1.GetNumberOfCells())
ghost_r2c1.SetValue(0, 0)
ghost_r2c1.SetValue(1, 0)
ghost_r2c1.SetValue(2, 0)
ghost_r2c1.SetValue(3, 0)
ghost_r2c1.SetValue(4, vtkDataSetAttributes.DUPLICATECELL)
ghost_r2c1.SetValue(5, vtkDataSetAttributes.DUPLICATECELL)
ghost_r2c1.SetValue(6, vtkDataSetAttributes.DUPLICATECELL)
ghost_r2c1.SetValue(7, vtkDataSetAttributes.DUPLICATECELL)
rgrid_r2c1.GetCellData().AddArray(ghost_r2c1)
rgrid_r2c1.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r2c1 = vtkGeometryFilter()
geom_r2c1.SetInputData(rgrid_r2c1)
geom_r2c1.SetRemoveGhostInterfaces(False)

mapper_r2c1 = vtkDataSetMapper()
mapper_r2c1.SetInputConnection(geom_r2c1.GetOutputPort())
mapper_r2c1.SetScalarVisibility(False)

actor_r2c1 = vtkActor()
actor_r2c1.SetMapper(mapper_r2c1)
actor_r2c1.GetProperty().EdgeVisibilityOn()
actor_r2c1.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r2c1.GetProperty().SetLineWidth(4.0)
actor_r2c1.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r2c1 = vtkTextActor()
text_r2c1.SetInput("RectilinearGrid\nDUPLICATECELL\nRemoveInterfaces=False")
text_r2c1.GetTextProperty().SetFontSize(14)
text_r2c1.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r2c1.SetPosition(5, 5)

# Row 2, Col 2: StructuredGrid
image_r2c2 = vtkImageData()
image_r2c2.SetDimensions(3, 3, 3)
img_to_sg_r2c2 = vtkImageToStructuredGrid()
img_to_sg_r2c2.SetInputData(image_r2c2)
img_to_sg_r2c2.Update()
sgrid_r2c2 = img_to_sg_r2c2.GetOutput()
ghost_r2c2 = vtkUnsignedCharArray()
ghost_r2c2.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r2c2.SetNumberOfTuples(sgrid_r2c2.GetNumberOfCells())
ghost_r2c2.SetValue(0, 0)
ghost_r2c2.SetValue(1, 0)
ghost_r2c2.SetValue(2, 0)
ghost_r2c2.SetValue(3, 0)
ghost_r2c2.SetValue(4, vtkDataSetAttributes.DUPLICATECELL)
ghost_r2c2.SetValue(5, vtkDataSetAttributes.DUPLICATECELL)
ghost_r2c2.SetValue(6, vtkDataSetAttributes.DUPLICATECELL)
ghost_r2c2.SetValue(7, vtkDataSetAttributes.DUPLICATECELL)
sgrid_r2c2.GetCellData().AddArray(ghost_r2c2)
sgrid_r2c2.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r2c2 = vtkGeometryFilter()
geom_r2c2.SetInputData(sgrid_r2c2)
geom_r2c2.SetRemoveGhostInterfaces(False)

mapper_r2c2 = vtkDataSetMapper()
mapper_r2c2.SetInputConnection(geom_r2c2.GetOutputPort())
mapper_r2c2.SetScalarVisibility(False)

actor_r2c2 = vtkActor()
actor_r2c2.SetMapper(mapper_r2c2)
actor_r2c2.GetProperty().EdgeVisibilityOn()
actor_r2c2.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r2c2.GetProperty().SetLineWidth(4.0)
actor_r2c2.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r2c2 = vtkTextActor()
text_r2c2.SetInput("StructuredGrid\nDUPLICATECELL\nRemoveInterfaces=False")
text_r2c2.GetTextProperty().SetFontSize(14)
text_r2c2.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r2c2.SetPosition(5, 5)

# Row 2, Col 3: UnstructuredGrid
image_r2c3 = vtkImageData()
image_r2c3.SetDimensions(3, 3, 3)
append_r2c3 = vtkAppendFilter()
append_r2c3.AddInputData(image_r2c3)
append_r2c3.Update()
ugrid_r2c3 = append_r2c3.GetOutput()
ghost_r2c3 = vtkUnsignedCharArray()
ghost_r2c3.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r2c3.SetNumberOfTuples(ugrid_r2c3.GetNumberOfCells())
ghost_r2c3.SetValue(0, 0)
ghost_r2c3.SetValue(1, 0)
ghost_r2c3.SetValue(2, 0)
ghost_r2c3.SetValue(3, 0)
ghost_r2c3.SetValue(4, vtkDataSetAttributes.DUPLICATECELL)
ghost_r2c3.SetValue(5, vtkDataSetAttributes.DUPLICATECELL)
ghost_r2c3.SetValue(6, vtkDataSetAttributes.DUPLICATECELL)
ghost_r2c3.SetValue(7, vtkDataSetAttributes.DUPLICATECELL)
ugrid_r2c3.GetCellData().AddArray(ghost_r2c3)
ugrid_r2c3.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r2c3 = vtkGeometryFilter()
geom_r2c3.SetInputData(ugrid_r2c3)
geom_r2c3.SetRemoveGhostInterfaces(False)

mapper_r2c3 = vtkDataSetMapper()
mapper_r2c3.SetInputConnection(geom_r2c3.GetOutputPort())
mapper_r2c3.SetScalarVisibility(False)

actor_r2c3 = vtkActor()
actor_r2c3.SetMapper(mapper_r2c3)
actor_r2c3.GetProperty().EdgeVisibilityOn()
actor_r2c3.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r2c3.GetProperty().SetLineWidth(4.0)
actor_r2c3.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r2c3 = vtkTextActor()
text_r2c3.SetInput("UnstructuredGrid\nDUPLICATECELL\nRemoveInterfaces=False")
text_r2c3.GetTextProperty().SetFontSize(14)
text_r2c3.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r2c3.SetPosition(5, 5)

# Row 2, Col 4: ExplicitStructuredGrid
image_r2c4 = vtkImageData()
image_r2c4.SetDimensions(3, 3, 3)
append_r2c4 = vtkAppendFilter()
append_r2c4.AddInputData(image_r2c4)
append_r2c4.Update()
ugrid_r2c4 = append_r2c4.GetOutput()
dims_r2c4 = image_r2c4.GetDimensions()
arr_i_r2c4 = vtkIntArray()
arr_i_r2c4.SetName("BLOCK_I")
arr_i_r2c4.SetNumberOfTuples(ugrid_r2c4.GetNumberOfCells())
arr_j_r2c4 = vtkIntArray()
arr_j_r2c4.SetName("BLOCK_J")
arr_j_r2c4.SetNumberOfTuples(ugrid_r2c4.GetNumberOfCells())
arr_k_r2c4 = vtkIntArray()
arr_k_r2c4.SetName("BLOCK_K")
arr_k_r2c4.SetNumberOfTuples(ugrid_r2c4.GetNumberOfCells())
cid_r2c4 = 0
for kk in range(dims_r2c4[2] - 1):
    for jj in range(dims_r2c4[1] - 1):
        for ii in range(dims_r2c4[0] - 1):
            arr_i_r2c4.SetValue(cid_r2c4, ii)
            arr_j_r2c4.SetValue(cid_r2c4, jj)
            arr_k_r2c4.SetValue(cid_r2c4, kk)
            cid_r2c4 += 1
ugrid_r2c4.GetCellData().AddArray(arr_i_r2c4)
ugrid_r2c4.GetCellData().AddArray(arr_j_r2c4)
ugrid_r2c4.GetCellData().AddArray(arr_k_r2c4)
ug_to_esg_r2c4 = vtkUnstructuredGridToExplicitStructuredGrid()
ug_to_esg_r2c4.SetInputData(ugrid_r2c4)
ug_to_esg_r2c4.SetInputArrayToProcess(0, 0, 0, 1, "BLOCK_I")
ug_to_esg_r2c4.SetInputArrayToProcess(1, 0, 0, 1, "BLOCK_J")
ug_to_esg_r2c4.SetInputArrayToProcess(2, 0, 0, 1, "BLOCK_K")
ug_to_esg_r2c4.Update()
esgrid_r2c4 = ug_to_esg_r2c4.GetOutput()
ghost_r2c4 = vtkUnsignedCharArray()
ghost_r2c4.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r2c4.SetNumberOfTuples(esgrid_r2c4.GetNumberOfCells())
ghost_r2c4.SetValue(0, 0)
ghost_r2c4.SetValue(1, 0)
ghost_r2c4.SetValue(2, 0)
ghost_r2c4.SetValue(3, 0)
ghost_r2c4.SetValue(4, vtkDataSetAttributes.DUPLICATECELL)
ghost_r2c4.SetValue(5, vtkDataSetAttributes.DUPLICATECELL)
ghost_r2c4.SetValue(6, vtkDataSetAttributes.DUPLICATECELL)
ghost_r2c4.SetValue(7, vtkDataSetAttributes.DUPLICATECELL)
esgrid_r2c4.GetCellData().AddArray(ghost_r2c4)
esgrid_r2c4.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r2c4 = vtkGeometryFilter()
geom_r2c4.SetInputData(esgrid_r2c4)
geom_r2c4.SetRemoveGhostInterfaces(False)

mapper_r2c4 = vtkDataSetMapper()
mapper_r2c4.SetInputConnection(geom_r2c4.GetOutputPort())
mapper_r2c4.SetScalarVisibility(False)

actor_r2c4 = vtkActor()
actor_r2c4.SetMapper(mapper_r2c4)
actor_r2c4.GetProperty().EdgeVisibilityOn()
actor_r2c4.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r2c4.GetProperty().SetLineWidth(4.0)
actor_r2c4.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r2c4 = vtkTextActor()
text_r2c4.SetInput("ExplicitStructuredGrid\nDUPLICATECELL\nRemoveInterfaces=False")
text_r2c4.GetTextProperty().SetFontSize(14)
text_r2c4.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r2c4.SetPosition(5, 5)

# ========== Row 3: DUPLICATECELL, RemoveGhostInterfaces=True ==========

# Row 3, Col 0: ImageData
image_r3c0 = vtkImageData()
image_r3c0.SetDimensions(3, 3, 3)
ghost_r3c0 = vtkUnsignedCharArray()
ghost_r3c0.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r3c0.SetNumberOfTuples(image_r3c0.GetNumberOfCells())
ghost_r3c0.SetValue(0, 0)
ghost_r3c0.SetValue(1, 0)
ghost_r3c0.SetValue(2, 0)
ghost_r3c0.SetValue(3, 0)
ghost_r3c0.SetValue(4, vtkDataSetAttributes.DUPLICATECELL)
ghost_r3c0.SetValue(5, vtkDataSetAttributes.DUPLICATECELL)
ghost_r3c0.SetValue(6, vtkDataSetAttributes.DUPLICATECELL)
ghost_r3c0.SetValue(7, vtkDataSetAttributes.DUPLICATECELL)
image_r3c0.GetCellData().AddArray(ghost_r3c0)
image_r3c0.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r3c0 = vtkGeometryFilter()
geom_r3c0.SetInputData(image_r3c0)
geom_r3c0.SetRemoveGhostInterfaces(True)

mapper_r3c0 = vtkDataSetMapper()
mapper_r3c0.SetInputConnection(geom_r3c0.GetOutputPort())
mapper_r3c0.SetScalarVisibility(False)

actor_r3c0 = vtkActor()
actor_r3c0.SetMapper(mapper_r3c0)
actor_r3c0.GetProperty().EdgeVisibilityOn()
actor_r3c0.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r3c0.GetProperty().SetLineWidth(4.0)
actor_r3c0.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r3c0 = vtkTextActor()
text_r3c0.SetInput("ImageData\nDUPLICATECELL\nRemoveInterfaces=True")
text_r3c0.GetTextProperty().SetFontSize(14)
text_r3c0.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r3c0.SetPosition(5, 5)

# Row 3, Col 1: RectilinearGrid
image_r3c1 = vtkImageData()
image_r3c1.SetDimensions(3, 3, 3)
dims_r3c1 = image_r3c1.GetDimensions()
spacing_r3c1 = image_r3c1.GetSpacing()
origin_r3c1 = image_r3c1.GetOrigin()
x_coords_r3c1 = vtkDoubleArray()
x_coords_r3c1.SetNumberOfValues(dims_r3c1[0])
x_coords_r3c1.SetValue(0, origin_r3c1[0])
x_coords_r3c1.SetValue(1, origin_r3c1[0] + spacing_r3c1[0])
x_coords_r3c1.SetValue(2, origin_r3c1[0] + 2 * spacing_r3c1[0])
y_coords_r3c1 = vtkDoubleArray()
y_coords_r3c1.SetNumberOfValues(dims_r3c1[1])
y_coords_r3c1.SetValue(0, origin_r3c1[1])
y_coords_r3c1.SetValue(1, origin_r3c1[1] + spacing_r3c1[1])
y_coords_r3c1.SetValue(2, origin_r3c1[1] + 2 * spacing_r3c1[1])
z_coords_r3c1 = vtkDoubleArray()
z_coords_r3c1.SetNumberOfValues(dims_r3c1[2])
z_coords_r3c1.SetValue(0, origin_r3c1[2])
z_coords_r3c1.SetValue(1, origin_r3c1[2] + spacing_r3c1[2])
z_coords_r3c1.SetValue(2, origin_r3c1[2] + 2 * spacing_r3c1[2])
rgrid_r3c1 = vtkRectilinearGrid()
rgrid_r3c1.SetDimensions(dims_r3c1[0], dims_r3c1[1], dims_r3c1[2])
rgrid_r3c1.SetXCoordinates(x_coords_r3c1)
rgrid_r3c1.SetYCoordinates(y_coords_r3c1)
rgrid_r3c1.SetZCoordinates(z_coords_r3c1)
rgrid_r3c1.GetPointData().ShallowCopy(image_r3c1.GetPointData())
rgrid_r3c1.GetCellData().ShallowCopy(image_r3c1.GetCellData())
ghost_r3c1 = vtkUnsignedCharArray()
ghost_r3c1.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r3c1.SetNumberOfTuples(rgrid_r3c1.GetNumberOfCells())
ghost_r3c1.SetValue(0, 0)
ghost_r3c1.SetValue(1, 0)
ghost_r3c1.SetValue(2, 0)
ghost_r3c1.SetValue(3, 0)
ghost_r3c1.SetValue(4, vtkDataSetAttributes.DUPLICATECELL)
ghost_r3c1.SetValue(5, vtkDataSetAttributes.DUPLICATECELL)
ghost_r3c1.SetValue(6, vtkDataSetAttributes.DUPLICATECELL)
ghost_r3c1.SetValue(7, vtkDataSetAttributes.DUPLICATECELL)
rgrid_r3c1.GetCellData().AddArray(ghost_r3c1)
rgrid_r3c1.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r3c1 = vtkGeometryFilter()
geom_r3c1.SetInputData(rgrid_r3c1)
geom_r3c1.SetRemoveGhostInterfaces(True)

mapper_r3c1 = vtkDataSetMapper()
mapper_r3c1.SetInputConnection(geom_r3c1.GetOutputPort())
mapper_r3c1.SetScalarVisibility(False)

actor_r3c1 = vtkActor()
actor_r3c1.SetMapper(mapper_r3c1)
actor_r3c1.GetProperty().EdgeVisibilityOn()
actor_r3c1.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r3c1.GetProperty().SetLineWidth(4.0)
actor_r3c1.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r3c1 = vtkTextActor()
text_r3c1.SetInput("RectilinearGrid\nDUPLICATECELL\nRemoveInterfaces=True")
text_r3c1.GetTextProperty().SetFontSize(14)
text_r3c1.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r3c1.SetPosition(5, 5)

# Row 3, Col 2: StructuredGrid
image_r3c2 = vtkImageData()
image_r3c2.SetDimensions(3, 3, 3)
img_to_sg_r3c2 = vtkImageToStructuredGrid()
img_to_sg_r3c2.SetInputData(image_r3c2)
img_to_sg_r3c2.Update()
sgrid_r3c2 = img_to_sg_r3c2.GetOutput()
ghost_r3c2 = vtkUnsignedCharArray()
ghost_r3c2.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r3c2.SetNumberOfTuples(sgrid_r3c2.GetNumberOfCells())
ghost_r3c2.SetValue(0, 0)
ghost_r3c2.SetValue(1, 0)
ghost_r3c2.SetValue(2, 0)
ghost_r3c2.SetValue(3, 0)
ghost_r3c2.SetValue(4, vtkDataSetAttributes.DUPLICATECELL)
ghost_r3c2.SetValue(5, vtkDataSetAttributes.DUPLICATECELL)
ghost_r3c2.SetValue(6, vtkDataSetAttributes.DUPLICATECELL)
ghost_r3c2.SetValue(7, vtkDataSetAttributes.DUPLICATECELL)
sgrid_r3c2.GetCellData().AddArray(ghost_r3c2)
sgrid_r3c2.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r3c2 = vtkGeometryFilter()
geom_r3c2.SetInputData(sgrid_r3c2)
geom_r3c2.SetRemoveGhostInterfaces(True)

mapper_r3c2 = vtkDataSetMapper()
mapper_r3c2.SetInputConnection(geom_r3c2.GetOutputPort())
mapper_r3c2.SetScalarVisibility(False)

actor_r3c2 = vtkActor()
actor_r3c2.SetMapper(mapper_r3c2)
actor_r3c2.GetProperty().EdgeVisibilityOn()
actor_r3c2.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r3c2.GetProperty().SetLineWidth(4.0)
actor_r3c2.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r3c2 = vtkTextActor()
text_r3c2.SetInput("StructuredGrid\nDUPLICATECELL\nRemoveInterfaces=True")
text_r3c2.GetTextProperty().SetFontSize(14)
text_r3c2.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r3c2.SetPosition(5, 5)

# Row 3, Col 3: UnstructuredGrid
image_r3c3 = vtkImageData()
image_r3c3.SetDimensions(3, 3, 3)
append_r3c3 = vtkAppendFilter()
append_r3c3.AddInputData(image_r3c3)
append_r3c3.Update()
ugrid_r3c3 = append_r3c3.GetOutput()
ghost_r3c3 = vtkUnsignedCharArray()
ghost_r3c3.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r3c3.SetNumberOfTuples(ugrid_r3c3.GetNumberOfCells())
ghost_r3c3.SetValue(0, 0)
ghost_r3c3.SetValue(1, 0)
ghost_r3c3.SetValue(2, 0)
ghost_r3c3.SetValue(3, 0)
ghost_r3c3.SetValue(4, vtkDataSetAttributes.DUPLICATECELL)
ghost_r3c3.SetValue(5, vtkDataSetAttributes.DUPLICATECELL)
ghost_r3c3.SetValue(6, vtkDataSetAttributes.DUPLICATECELL)
ghost_r3c3.SetValue(7, vtkDataSetAttributes.DUPLICATECELL)
ugrid_r3c3.GetCellData().AddArray(ghost_r3c3)
ugrid_r3c3.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r3c3 = vtkGeometryFilter()
geom_r3c3.SetInputData(ugrid_r3c3)
geom_r3c3.SetRemoveGhostInterfaces(True)

mapper_r3c3 = vtkDataSetMapper()
mapper_r3c3.SetInputConnection(geom_r3c3.GetOutputPort())
mapper_r3c3.SetScalarVisibility(False)

actor_r3c3 = vtkActor()
actor_r3c3.SetMapper(mapper_r3c3)
actor_r3c3.GetProperty().EdgeVisibilityOn()
actor_r3c3.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r3c3.GetProperty().SetLineWidth(4.0)
actor_r3c3.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r3c3 = vtkTextActor()
text_r3c3.SetInput("UnstructuredGrid\nDUPLICATECELL\nRemoveInterfaces=True")
text_r3c3.GetTextProperty().SetFontSize(14)
text_r3c3.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r3c3.SetPosition(5, 5)

# Row 3, Col 4: ExplicitStructuredGrid
image_r3c4 = vtkImageData()
image_r3c4.SetDimensions(3, 3, 3)
append_r3c4 = vtkAppendFilter()
append_r3c4.AddInputData(image_r3c4)
append_r3c4.Update()
ugrid_r3c4 = append_r3c4.GetOutput()
dims_r3c4 = image_r3c4.GetDimensions()
arr_i_r3c4 = vtkIntArray()
arr_i_r3c4.SetName("BLOCK_I")
arr_i_r3c4.SetNumberOfTuples(ugrid_r3c4.GetNumberOfCells())
arr_j_r3c4 = vtkIntArray()
arr_j_r3c4.SetName("BLOCK_J")
arr_j_r3c4.SetNumberOfTuples(ugrid_r3c4.GetNumberOfCells())
arr_k_r3c4 = vtkIntArray()
arr_k_r3c4.SetName("BLOCK_K")
arr_k_r3c4.SetNumberOfTuples(ugrid_r3c4.GetNumberOfCells())
cid_r3c4 = 0
for kk in range(dims_r3c4[2] - 1):
    for jj in range(dims_r3c4[1] - 1):
        for ii in range(dims_r3c4[0] - 1):
            arr_i_r3c4.SetValue(cid_r3c4, ii)
            arr_j_r3c4.SetValue(cid_r3c4, jj)
            arr_k_r3c4.SetValue(cid_r3c4, kk)
            cid_r3c4 += 1
ugrid_r3c4.GetCellData().AddArray(arr_i_r3c4)
ugrid_r3c4.GetCellData().AddArray(arr_j_r3c4)
ugrid_r3c4.GetCellData().AddArray(arr_k_r3c4)
ug_to_esg_r3c4 = vtkUnstructuredGridToExplicitStructuredGrid()
ug_to_esg_r3c4.SetInputData(ugrid_r3c4)
ug_to_esg_r3c4.SetInputArrayToProcess(0, 0, 0, 1, "BLOCK_I")
ug_to_esg_r3c4.SetInputArrayToProcess(1, 0, 0, 1, "BLOCK_J")
ug_to_esg_r3c4.SetInputArrayToProcess(2, 0, 0, 1, "BLOCK_K")
ug_to_esg_r3c4.Update()
esgrid_r3c4 = ug_to_esg_r3c4.GetOutput()
ghost_r3c4 = vtkUnsignedCharArray()
ghost_r3c4.SetName(vtkDataSetAttributes.GhostArrayName())
ghost_r3c4.SetNumberOfTuples(esgrid_r3c4.GetNumberOfCells())
ghost_r3c4.SetValue(0, 0)
ghost_r3c4.SetValue(1, 0)
ghost_r3c4.SetValue(2, 0)
ghost_r3c4.SetValue(3, 0)
ghost_r3c4.SetValue(4, vtkDataSetAttributes.DUPLICATECELL)
ghost_r3c4.SetValue(5, vtkDataSetAttributes.DUPLICATECELL)
ghost_r3c4.SetValue(6, vtkDataSetAttributes.DUPLICATECELL)
ghost_r3c4.SetValue(7, vtkDataSetAttributes.DUPLICATECELL)
esgrid_r3c4.GetCellData().AddArray(ghost_r3c4)
esgrid_r3c4.GetCellData().SetActiveScalars(vtkDataSetAttributes.GhostArrayName())

geom_r3c4 = vtkGeometryFilter()
geom_r3c4.SetInputData(esgrid_r3c4)
geom_r3c4.SetRemoveGhostInterfaces(True)

mapper_r3c4 = vtkDataSetMapper()
mapper_r3c4.SetInputConnection(geom_r3c4.GetOutputPort())
mapper_r3c4.SetScalarVisibility(False)

actor_r3c4 = vtkActor()
actor_r3c4.SetMapper(mapper_r3c4)
actor_r3c4.GetProperty().EdgeVisibilityOn()
actor_r3c4.GetProperty().SetEdgeColor(0.0, 0.0, 0.0)
actor_r3c4.GetProperty().SetLineWidth(4.0)
actor_r3c4.GetProperty().SetColor(1.0, 1.0, 1.0)

text_r3c4 = vtkTextActor()
text_r3c4.SetInput("ExplicitStructuredGrid\nDUPLICATECELL\nRemoveInterfaces=True")
text_r3c4.GetTextProperty().SetFontSize(14)
text_r3c4.GetTextProperty().SetColor(1.0, 1.0, 1.0)
text_r3c4.SetPosition(5, 5)

# ========== Renderers ==========

renderer_r0c0 = vtkRenderer()
renderer_r0c0.SetViewport(0 * col_width, 0 * row_height, 1 * col_width, 1 * row_height)
renderer_r0c0.AddActor(actor_r0c0)
renderer_r0c0.AddViewProp(text_r0c0)
renderer_r0c0.SetBackground(0.1, 0.1, 0.1)

renderer_r0c1 = vtkRenderer()
renderer_r0c1.SetViewport(1 * col_width, 0 * row_height, 2 * col_width, 1 * row_height)
renderer_r0c1.AddActor(actor_r0c1)
renderer_r0c1.AddViewProp(text_r0c1)
renderer_r0c1.SetBackground(0.1, 0.1, 0.1)

renderer_r0c2 = vtkRenderer()
renderer_r0c2.SetViewport(2 * col_width, 0 * row_height, 3 * col_width, 1 * row_height)
renderer_r0c2.AddActor(actor_r0c2)
renderer_r0c2.AddViewProp(text_r0c2)
renderer_r0c2.SetBackground(0.1, 0.1, 0.1)

renderer_r0c3 = vtkRenderer()
renderer_r0c3.SetViewport(3 * col_width, 0 * row_height, 4 * col_width, 1 * row_height)
renderer_r0c3.AddActor(actor_r0c3)
renderer_r0c3.AddViewProp(text_r0c3)
renderer_r0c3.SetBackground(0.1, 0.1, 0.1)

renderer_r0c4 = vtkRenderer()
renderer_r0c4.SetViewport(4 * col_width, 0 * row_height, 5 * col_width, 1 * row_height)
renderer_r0c4.AddActor(actor_r0c4)
renderer_r0c4.AddViewProp(text_r0c4)
renderer_r0c4.SetBackground(0.1, 0.1, 0.1)

renderer_r1c0 = vtkRenderer()
renderer_r1c0.SetViewport(0 * col_width, 1 * row_height, 1 * col_width, 2 * row_height)
renderer_r1c0.AddActor(actor_r1c0)
renderer_r1c0.AddViewProp(text_r1c0)
renderer_r1c0.SetBackground(0.1, 0.1, 0.1)

renderer_r1c1 = vtkRenderer()
renderer_r1c1.SetViewport(1 * col_width, 1 * row_height, 2 * col_width, 2 * row_height)
renderer_r1c1.AddActor(actor_r1c1)
renderer_r1c1.AddViewProp(text_r1c1)
renderer_r1c1.SetBackground(0.1, 0.1, 0.1)

renderer_r1c2 = vtkRenderer()
renderer_r1c2.SetViewport(2 * col_width, 1 * row_height, 3 * col_width, 2 * row_height)
renderer_r1c2.AddActor(actor_r1c2)
renderer_r1c2.AddViewProp(text_r1c2)
renderer_r1c2.SetBackground(0.1, 0.1, 0.1)

renderer_r1c3 = vtkRenderer()
renderer_r1c3.SetViewport(3 * col_width, 1 * row_height, 4 * col_width, 2 * row_height)
renderer_r1c3.AddActor(actor_r1c3)
renderer_r1c3.AddViewProp(text_r1c3)
renderer_r1c3.SetBackground(0.1, 0.1, 0.1)

renderer_r1c4 = vtkRenderer()
renderer_r1c4.SetViewport(4 * col_width, 1 * row_height, 5 * col_width, 2 * row_height)
renderer_r1c4.AddActor(actor_r1c4)
renderer_r1c4.AddViewProp(text_r1c4)
renderer_r1c4.SetBackground(0.1, 0.1, 0.1)

renderer_r2c0 = vtkRenderer()
renderer_r2c0.SetViewport(0 * col_width, 2 * row_height, 1 * col_width, 3 * row_height)
renderer_r2c0.AddActor(actor_r2c0)
renderer_r2c0.AddViewProp(text_r2c0)
renderer_r2c0.SetBackground(0.1, 0.1, 0.1)

renderer_r2c1 = vtkRenderer()
renderer_r2c1.SetViewport(1 * col_width, 2 * row_height, 2 * col_width, 3 * row_height)
renderer_r2c1.AddActor(actor_r2c1)
renderer_r2c1.AddViewProp(text_r2c1)
renderer_r2c1.SetBackground(0.1, 0.1, 0.1)

renderer_r2c2 = vtkRenderer()
renderer_r2c2.SetViewport(2 * col_width, 2 * row_height, 3 * col_width, 3 * row_height)
renderer_r2c2.AddActor(actor_r2c2)
renderer_r2c2.AddViewProp(text_r2c2)
renderer_r2c2.SetBackground(0.1, 0.1, 0.1)

renderer_r2c3 = vtkRenderer()
renderer_r2c3.SetViewport(3 * col_width, 2 * row_height, 4 * col_width, 3 * row_height)
renderer_r2c3.AddActor(actor_r2c3)
renderer_r2c3.AddViewProp(text_r2c3)
renderer_r2c3.SetBackground(0.1, 0.1, 0.1)

renderer_r2c4 = vtkRenderer()
renderer_r2c4.SetViewport(4 * col_width, 2 * row_height, 5 * col_width, 3 * row_height)
renderer_r2c4.AddActor(actor_r2c4)
renderer_r2c4.AddViewProp(text_r2c4)
renderer_r2c4.SetBackground(0.1, 0.1, 0.1)

renderer_r3c0 = vtkRenderer()
renderer_r3c0.SetViewport(0 * col_width, 3 * row_height, 1 * col_width, 4 * row_height)
renderer_r3c0.AddActor(actor_r3c0)
renderer_r3c0.AddViewProp(text_r3c0)
renderer_r3c0.SetBackground(0.1, 0.1, 0.1)

renderer_r3c1 = vtkRenderer()
renderer_r3c1.SetViewport(1 * col_width, 3 * row_height, 2 * col_width, 4 * row_height)
renderer_r3c1.AddActor(actor_r3c1)
renderer_r3c1.AddViewProp(text_r3c1)
renderer_r3c1.SetBackground(0.1, 0.1, 0.1)

renderer_r3c2 = vtkRenderer()
renderer_r3c2.SetViewport(2 * col_width, 3 * row_height, 3 * col_width, 4 * row_height)
renderer_r3c2.AddActor(actor_r3c2)
renderer_r3c2.AddViewProp(text_r3c2)
renderer_r3c2.SetBackground(0.1, 0.1, 0.1)

renderer_r3c3 = vtkRenderer()
renderer_r3c3.SetViewport(3 * col_width, 3 * row_height, 4 * col_width, 4 * row_height)
renderer_r3c3.AddActor(actor_r3c3)
renderer_r3c3.AddViewProp(text_r3c3)
renderer_r3c3.SetBackground(0.1, 0.1, 0.1)

renderer_r3c4 = vtkRenderer()
renderer_r3c4.SetViewport(4 * col_width, 3 * row_height, 5 * col_width, 4 * row_height)
renderer_r3c4.AddActor(actor_r3c4)
renderer_r3c4.AddViewProp(text_r3c4)
renderer_r3c4.SetBackground(0.1, 0.1, 0.1)

# Window
render_window = vtkRenderWindow()
render_window.SetSize(1600, 1200)
render_window.SetWindowName("filter ghosts")
render_window.AddRenderer(renderer_r0c0)
render_window.AddRenderer(renderer_r0c1)
render_window.AddRenderer(renderer_r0c2)
render_window.AddRenderer(renderer_r0c3)
render_window.AddRenderer(renderer_r0c4)
render_window.AddRenderer(renderer_r1c0)
render_window.AddRenderer(renderer_r1c1)
render_window.AddRenderer(renderer_r1c2)
render_window.AddRenderer(renderer_r1c3)
render_window.AddRenderer(renderer_r1c4)
render_window.AddRenderer(renderer_r2c0)
render_window.AddRenderer(renderer_r2c1)
render_window.AddRenderer(renderer_r2c2)
render_window.AddRenderer(renderer_r2c3)
render_window.AddRenderer(renderer_r2c4)
render_window.AddRenderer(renderer_r3c0)
render_window.AddRenderer(renderer_r3c1)
render_window.AddRenderer(renderer_r3c2)
render_window.AddRenderer(renderer_r3c3)
render_window.AddRenderer(renderer_r3c4)

# Interactor
interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)

# Scene
camera_r0c0 = renderer_r0c0.GetActiveCamera()
camera_r0c0.SetPosition(1, 1, 1)
camera_r0c0.SetFocalPoint(0, 0, 0)
camera_r0c0.SetViewUp(0, 0, 1)
renderer_r0c0.ResetCamera()
camera_r0c0.Zoom(0.7)
renderer_r0c0.ResetCameraClippingRange()

camera_r0c1 = renderer_r0c1.GetActiveCamera()
camera_r0c1.SetPosition(1, 1, 1)
camera_r0c1.SetFocalPoint(0, 0, 0)
camera_r0c1.SetViewUp(0, 0, 1)
renderer_r0c1.ResetCamera()
camera_r0c1.Zoom(0.7)
renderer_r0c1.ResetCameraClippingRange()

camera_r0c2 = renderer_r0c2.GetActiveCamera()
camera_r0c2.SetPosition(1, 1, 1)
camera_r0c2.SetFocalPoint(0, 0, 0)
camera_r0c2.SetViewUp(0, 0, 1)
renderer_r0c2.ResetCamera()
camera_r0c2.Zoom(0.7)
renderer_r0c2.ResetCameraClippingRange()

camera_r0c3 = renderer_r0c3.GetActiveCamera()
camera_r0c3.SetPosition(1, 1, 1)
camera_r0c3.SetFocalPoint(0, 0, 0)
camera_r0c3.SetViewUp(0, 0, 1)
renderer_r0c3.ResetCamera()
camera_r0c3.Zoom(0.7)
renderer_r0c3.ResetCameraClippingRange()

camera_r0c4 = renderer_r0c4.GetActiveCamera()
camera_r0c4.SetPosition(1, 1, 1)
camera_r0c4.SetFocalPoint(0, 0, 0)
camera_r0c4.SetViewUp(0, 0, 1)
renderer_r0c4.ResetCamera()
camera_r0c4.Zoom(0.7)
renderer_r0c4.ResetCameraClippingRange()

camera_r1c0 = renderer_r1c0.GetActiveCamera()
camera_r1c0.SetPosition(1, 1, 1)
camera_r1c0.SetFocalPoint(0, 0, 0)
camera_r1c0.SetViewUp(0, 0, 1)
renderer_r1c0.ResetCamera()
camera_r1c0.Zoom(0.7)
renderer_r1c0.ResetCameraClippingRange()

camera_r1c1 = renderer_r1c1.GetActiveCamera()
camera_r1c1.SetPosition(1, 1, 1)
camera_r1c1.SetFocalPoint(0, 0, 0)
camera_r1c1.SetViewUp(0, 0, 1)
renderer_r1c1.ResetCamera()
camera_r1c1.Zoom(0.7)
renderer_r1c1.ResetCameraClippingRange()

camera_r1c2 = renderer_r1c2.GetActiveCamera()
camera_r1c2.SetPosition(1, 1, 1)
camera_r1c2.SetFocalPoint(0, 0, 0)
camera_r1c2.SetViewUp(0, 0, 1)
renderer_r1c2.ResetCamera()
camera_r1c2.Zoom(0.7)
renderer_r1c2.ResetCameraClippingRange()

camera_r1c3 = renderer_r1c3.GetActiveCamera()
camera_r1c3.SetPosition(1, 1, 1)
camera_r1c3.SetFocalPoint(0, 0, 0)
camera_r1c3.SetViewUp(0, 0, 1)
renderer_r1c3.ResetCamera()
camera_r1c3.Zoom(0.7)
renderer_r1c3.ResetCameraClippingRange()

camera_r1c4 = renderer_r1c4.GetActiveCamera()
camera_r1c4.SetPosition(1, 1, 1)
camera_r1c4.SetFocalPoint(0, 0, 0)
camera_r1c4.SetViewUp(0, 0, 1)
renderer_r1c4.ResetCamera()
camera_r1c4.Zoom(0.7)
renderer_r1c4.ResetCameraClippingRange()

camera_r2c0 = renderer_r2c0.GetActiveCamera()
camera_r2c0.SetPosition(1, 1, 1)
camera_r2c0.SetFocalPoint(0, 0, 0)
camera_r2c0.SetViewUp(0, 0, 1)
renderer_r2c0.ResetCamera()
camera_r2c0.Zoom(0.7)
renderer_r2c0.ResetCameraClippingRange()

camera_r2c1 = renderer_r2c1.GetActiveCamera()
camera_r2c1.SetPosition(1, 1, 1)
camera_r2c1.SetFocalPoint(0, 0, 0)
camera_r2c1.SetViewUp(0, 0, 1)
renderer_r2c1.ResetCamera()
camera_r2c1.Zoom(0.7)
renderer_r2c1.ResetCameraClippingRange()

camera_r2c2 = renderer_r2c2.GetActiveCamera()
camera_r2c2.SetPosition(1, 1, 1)
camera_r2c2.SetFocalPoint(0, 0, 0)
camera_r2c2.SetViewUp(0, 0, 1)
renderer_r2c2.ResetCamera()
camera_r2c2.Zoom(0.7)
renderer_r2c2.ResetCameraClippingRange()

camera_r2c3 = renderer_r2c3.GetActiveCamera()
camera_r2c3.SetPosition(1, 1, 1)
camera_r2c3.SetFocalPoint(0, 0, 0)
camera_r2c3.SetViewUp(0, 0, 1)
renderer_r2c3.ResetCamera()
camera_r2c3.Zoom(0.7)
renderer_r2c3.ResetCameraClippingRange()

camera_r2c4 = renderer_r2c4.GetActiveCamera()
camera_r2c4.SetPosition(1, 1, 1)
camera_r2c4.SetFocalPoint(0, 0, 0)
camera_r2c4.SetViewUp(0, 0, 1)
renderer_r2c4.ResetCamera()
camera_r2c4.Zoom(0.7)
renderer_r2c4.ResetCameraClippingRange()

camera_r3c0 = renderer_r3c0.GetActiveCamera()
camera_r3c0.SetPosition(1, 1, 1)
camera_r3c0.SetFocalPoint(0, 0, 0)
camera_r3c0.SetViewUp(0, 0, 1)
renderer_r3c0.ResetCamera()
camera_r3c0.Zoom(0.7)
renderer_r3c0.ResetCameraClippingRange()

camera_r3c1 = renderer_r3c1.GetActiveCamera()
camera_r3c1.SetPosition(1, 1, 1)
camera_r3c1.SetFocalPoint(0, 0, 0)
camera_r3c1.SetViewUp(0, 0, 1)
renderer_r3c1.ResetCamera()
camera_r3c1.Zoom(0.7)
renderer_r3c1.ResetCameraClippingRange()

camera_r3c2 = renderer_r3c2.GetActiveCamera()
camera_r3c2.SetPosition(1, 1, 1)
camera_r3c2.SetFocalPoint(0, 0, 0)
camera_r3c2.SetViewUp(0, 0, 1)
renderer_r3c2.ResetCamera()
camera_r3c2.Zoom(0.7)
renderer_r3c2.ResetCameraClippingRange()

camera_r3c3 = renderer_r3c3.GetActiveCamera()
camera_r3c3.SetPosition(1, 1, 1)
camera_r3c3.SetFocalPoint(0, 0, 0)
camera_r3c3.SetViewUp(0, 0, 1)
renderer_r3c3.ResetCamera()
camera_r3c3.Zoom(0.7)
renderer_r3c3.ResetCameraClippingRange()

camera_r3c4 = renderer_r3c4.GetActiveCamera()
camera_r3c4.SetPosition(1, 1, 1)
camera_r3c4.SetFocalPoint(0, 0, 0)
camera_r3c4.SetViewUp(0, 0, 1)
renderer_r3c4.ResetCamera()
camera_r3c4.Zoom(0.7)
renderer_r3c4.ResetCameraClippingRange()

interactor.Initialize()
interactor.Start()
