#!/usr/bin/env python

# Demonstrate vtkGlyphSource2D scaling by rendering all glyph types
# at four different fixed scale values in a grid layout.

# Factory overrides
import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingFreeType  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401

from vtkmodules.vtkCommonCore import vtkPoints
from vtkmodules.vtkCommonDataModel import vtkPolyData
from vtkmodules.vtkFiltersCore import vtkGlyph2D
from vtkmodules.vtkFiltersSources import vtkGlyphSource2D
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkPolyDataMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
)

# Row 0: VTK_NO_GLYPH (type 0)
points_0_0 = vtkPoints()
points_0_0.InsertNextPoint(3, 0, 0)
polydata_0_0 = vtkPolyData()
polydata_0_0.SetPoints(points_0_0)
glyph_source_0_0 = vtkGlyphSource2D()
glyph_source_0_0.SetGlyphType(0)
glyph_source_0_0.FilledOff()
glyph_source_0_0.SetResolution(25)
glyph_source_0_0.SetScale(0.5)
glyph_0_0 = vtkGlyph2D()
glyph_0_0.SetSourceConnection(glyph_source_0_0.GetOutputPort())
glyph_0_0.SetInputData(polydata_0_0)
glyph_0_0.Update()
mapper_0_0 = vtkPolyDataMapper()
mapper_0_0.SetInputConnection(glyph_0_0.GetOutputPort())
actor_0_0 = vtkActor()
actor_0_0.SetMapper(mapper_0_0)

points_0_1 = vtkPoints()
points_0_1.InsertNextPoint(6, 0, 0)
polydata_0_1 = vtkPolyData()
polydata_0_1.SetPoints(points_0_1)
glyph_source_0_1 = vtkGlyphSource2D()
glyph_source_0_1.SetGlyphType(0)
glyph_source_0_1.FilledOff()
glyph_source_0_1.SetResolution(25)
glyph_source_0_1.SetScale(1.0)
glyph_0_1 = vtkGlyph2D()
glyph_0_1.SetSourceConnection(glyph_source_0_1.GetOutputPort())
glyph_0_1.SetInputData(polydata_0_1)
glyph_0_1.Update()
mapper_0_1 = vtkPolyDataMapper()
mapper_0_1.SetInputConnection(glyph_0_1.GetOutputPort())
actor_0_1 = vtkActor()
actor_0_1.SetMapper(mapper_0_1)

points_0_2 = vtkPoints()
points_0_2.InsertNextPoint(9, 0, 0)
polydata_0_2 = vtkPolyData()
polydata_0_2.SetPoints(points_0_2)
glyph_source_0_2 = vtkGlyphSource2D()
glyph_source_0_2.SetGlyphType(0)
glyph_source_0_2.FilledOff()
glyph_source_0_2.SetResolution(25)
glyph_source_0_2.SetScale(1.5)
glyph_0_2 = vtkGlyph2D()
glyph_0_2.SetSourceConnection(glyph_source_0_2.GetOutputPort())
glyph_0_2.SetInputData(polydata_0_2)
glyph_0_2.Update()
mapper_0_2 = vtkPolyDataMapper()
mapper_0_2.SetInputConnection(glyph_0_2.GetOutputPort())
actor_0_2 = vtkActor()
actor_0_2.SetMapper(mapper_0_2)

points_0_3 = vtkPoints()
points_0_3.InsertNextPoint(12, 0, 0)
polydata_0_3 = vtkPolyData()
polydata_0_3.SetPoints(points_0_3)
glyph_source_0_3 = vtkGlyphSource2D()
glyph_source_0_3.SetGlyphType(0)
glyph_source_0_3.FilledOff()
glyph_source_0_3.SetResolution(25)
glyph_source_0_3.SetScale(2.0)
glyph_0_3 = vtkGlyph2D()
glyph_0_3.SetSourceConnection(glyph_source_0_3.GetOutputPort())
glyph_0_3.SetInputData(polydata_0_3)
glyph_0_3.Update()
mapper_0_3 = vtkPolyDataMapper()
mapper_0_3.SetInputConnection(glyph_0_3.GetOutputPort())
actor_0_3 = vtkActor()
actor_0_3.SetMapper(mapper_0_3)

# Row 1: VTK_VERTEX_GLYPH (type 1)
points_1_0 = vtkPoints()
points_1_0.InsertNextPoint(3, 3, 0)
polydata_1_0 = vtkPolyData()
polydata_1_0.SetPoints(points_1_0)
glyph_source_1_0 = vtkGlyphSource2D()
glyph_source_1_0.SetGlyphType(1)
glyph_source_1_0.FilledOff()
glyph_source_1_0.SetResolution(25)
glyph_source_1_0.SetScale(0.5)
glyph_1_0 = vtkGlyph2D()
glyph_1_0.SetSourceConnection(glyph_source_1_0.GetOutputPort())
glyph_1_0.SetInputData(polydata_1_0)
glyph_1_0.Update()
mapper_1_0 = vtkPolyDataMapper()
mapper_1_0.SetInputConnection(glyph_1_0.GetOutputPort())
actor_1_0 = vtkActor()
actor_1_0.SetMapper(mapper_1_0)

points_1_1 = vtkPoints()
points_1_1.InsertNextPoint(6, 3, 0)
polydata_1_1 = vtkPolyData()
polydata_1_1.SetPoints(points_1_1)
glyph_source_1_1 = vtkGlyphSource2D()
glyph_source_1_1.SetGlyphType(1)
glyph_source_1_1.FilledOff()
glyph_source_1_1.SetResolution(25)
glyph_source_1_1.SetScale(1.0)
glyph_1_1 = vtkGlyph2D()
glyph_1_1.SetSourceConnection(glyph_source_1_1.GetOutputPort())
glyph_1_1.SetInputData(polydata_1_1)
glyph_1_1.Update()
mapper_1_1 = vtkPolyDataMapper()
mapper_1_1.SetInputConnection(glyph_1_1.GetOutputPort())
actor_1_1 = vtkActor()
actor_1_1.SetMapper(mapper_1_1)

points_1_2 = vtkPoints()
points_1_2.InsertNextPoint(9, 3, 0)
polydata_1_2 = vtkPolyData()
polydata_1_2.SetPoints(points_1_2)
glyph_source_1_2 = vtkGlyphSource2D()
glyph_source_1_2.SetGlyphType(1)
glyph_source_1_2.FilledOff()
glyph_source_1_2.SetResolution(25)
glyph_source_1_2.SetScale(1.5)
glyph_1_2 = vtkGlyph2D()
glyph_1_2.SetSourceConnection(glyph_source_1_2.GetOutputPort())
glyph_1_2.SetInputData(polydata_1_2)
glyph_1_2.Update()
mapper_1_2 = vtkPolyDataMapper()
mapper_1_2.SetInputConnection(glyph_1_2.GetOutputPort())
actor_1_2 = vtkActor()
actor_1_2.SetMapper(mapper_1_2)

points_1_3 = vtkPoints()
points_1_3.InsertNextPoint(12, 3, 0)
polydata_1_3 = vtkPolyData()
polydata_1_3.SetPoints(points_1_3)
glyph_source_1_3 = vtkGlyphSource2D()
glyph_source_1_3.SetGlyphType(1)
glyph_source_1_3.FilledOff()
glyph_source_1_3.SetResolution(25)
glyph_source_1_3.SetScale(2.0)
glyph_1_3 = vtkGlyph2D()
glyph_1_3.SetSourceConnection(glyph_source_1_3.GetOutputPort())
glyph_1_3.SetInputData(polydata_1_3)
glyph_1_3.Update()
mapper_1_3 = vtkPolyDataMapper()
mapper_1_3.SetInputConnection(glyph_1_3.GetOutputPort())
actor_1_3 = vtkActor()
actor_1_3.SetMapper(mapper_1_3)

# Row 2: VTK_DASH_GLYPH (type 2)
points_2_0 = vtkPoints()
points_2_0.InsertNextPoint(3, 6, 0)
polydata_2_0 = vtkPolyData()
polydata_2_0.SetPoints(points_2_0)
glyph_source_2_0 = vtkGlyphSource2D()
glyph_source_2_0.SetGlyphType(2)
glyph_source_2_0.FilledOff()
glyph_source_2_0.SetResolution(25)
glyph_source_2_0.SetScale(0.5)
glyph_2_0 = vtkGlyph2D()
glyph_2_0.SetSourceConnection(glyph_source_2_0.GetOutputPort())
glyph_2_0.SetInputData(polydata_2_0)
glyph_2_0.Update()
mapper_2_0 = vtkPolyDataMapper()
mapper_2_0.SetInputConnection(glyph_2_0.GetOutputPort())
actor_2_0 = vtkActor()
actor_2_0.SetMapper(mapper_2_0)

points_2_1 = vtkPoints()
points_2_1.InsertNextPoint(6, 6, 0)
polydata_2_1 = vtkPolyData()
polydata_2_1.SetPoints(points_2_1)
glyph_source_2_1 = vtkGlyphSource2D()
glyph_source_2_1.SetGlyphType(2)
glyph_source_2_1.FilledOff()
glyph_source_2_1.SetResolution(25)
glyph_source_2_1.SetScale(1.0)
glyph_2_1 = vtkGlyph2D()
glyph_2_1.SetSourceConnection(glyph_source_2_1.GetOutputPort())
glyph_2_1.SetInputData(polydata_2_1)
glyph_2_1.Update()
mapper_2_1 = vtkPolyDataMapper()
mapper_2_1.SetInputConnection(glyph_2_1.GetOutputPort())
actor_2_1 = vtkActor()
actor_2_1.SetMapper(mapper_2_1)

points_2_2 = vtkPoints()
points_2_2.InsertNextPoint(9, 6, 0)
polydata_2_2 = vtkPolyData()
polydata_2_2.SetPoints(points_2_2)
glyph_source_2_2 = vtkGlyphSource2D()
glyph_source_2_2.SetGlyphType(2)
glyph_source_2_2.FilledOff()
glyph_source_2_2.SetResolution(25)
glyph_source_2_2.SetScale(1.5)
glyph_2_2 = vtkGlyph2D()
glyph_2_2.SetSourceConnection(glyph_source_2_2.GetOutputPort())
glyph_2_2.SetInputData(polydata_2_2)
glyph_2_2.Update()
mapper_2_2 = vtkPolyDataMapper()
mapper_2_2.SetInputConnection(glyph_2_2.GetOutputPort())
actor_2_2 = vtkActor()
actor_2_2.SetMapper(mapper_2_2)

points_2_3 = vtkPoints()
points_2_3.InsertNextPoint(12, 6, 0)
polydata_2_3 = vtkPolyData()
polydata_2_3.SetPoints(points_2_3)
glyph_source_2_3 = vtkGlyphSource2D()
glyph_source_2_3.SetGlyphType(2)
glyph_source_2_3.FilledOff()
glyph_source_2_3.SetResolution(25)
glyph_source_2_3.SetScale(2.0)
glyph_2_3 = vtkGlyph2D()
glyph_2_3.SetSourceConnection(glyph_source_2_3.GetOutputPort())
glyph_2_3.SetInputData(polydata_2_3)
glyph_2_3.Update()
mapper_2_3 = vtkPolyDataMapper()
mapper_2_3.SetInputConnection(glyph_2_3.GetOutputPort())
actor_2_3 = vtkActor()
actor_2_3.SetMapper(mapper_2_3)

# Row 3: VTK_CROSS_GLYPH (type 3)
points_3_0 = vtkPoints()
points_3_0.InsertNextPoint(3, 9, 0)
polydata_3_0 = vtkPolyData()
polydata_3_0.SetPoints(points_3_0)
glyph_source_3_0 = vtkGlyphSource2D()
glyph_source_3_0.SetGlyphType(3)
glyph_source_3_0.FilledOff()
glyph_source_3_0.SetResolution(25)
glyph_source_3_0.SetScale(0.5)
glyph_3_0 = vtkGlyph2D()
glyph_3_0.SetSourceConnection(glyph_source_3_0.GetOutputPort())
glyph_3_0.SetInputData(polydata_3_0)
glyph_3_0.Update()
mapper_3_0 = vtkPolyDataMapper()
mapper_3_0.SetInputConnection(glyph_3_0.GetOutputPort())
actor_3_0 = vtkActor()
actor_3_0.SetMapper(mapper_3_0)

points_3_1 = vtkPoints()
points_3_1.InsertNextPoint(6, 9, 0)
polydata_3_1 = vtkPolyData()
polydata_3_1.SetPoints(points_3_1)
glyph_source_3_1 = vtkGlyphSource2D()
glyph_source_3_1.SetGlyphType(3)
glyph_source_3_1.FilledOff()
glyph_source_3_1.SetResolution(25)
glyph_source_3_1.SetScale(1.0)
glyph_3_1 = vtkGlyph2D()
glyph_3_1.SetSourceConnection(glyph_source_3_1.GetOutputPort())
glyph_3_1.SetInputData(polydata_3_1)
glyph_3_1.Update()
mapper_3_1 = vtkPolyDataMapper()
mapper_3_1.SetInputConnection(glyph_3_1.GetOutputPort())
actor_3_1 = vtkActor()
actor_3_1.SetMapper(mapper_3_1)

points_3_2 = vtkPoints()
points_3_2.InsertNextPoint(9, 9, 0)
polydata_3_2 = vtkPolyData()
polydata_3_2.SetPoints(points_3_2)
glyph_source_3_2 = vtkGlyphSource2D()
glyph_source_3_2.SetGlyphType(3)
glyph_source_3_2.FilledOff()
glyph_source_3_2.SetResolution(25)
glyph_source_3_2.SetScale(1.5)
glyph_3_2 = vtkGlyph2D()
glyph_3_2.SetSourceConnection(glyph_source_3_2.GetOutputPort())
glyph_3_2.SetInputData(polydata_3_2)
glyph_3_2.Update()
mapper_3_2 = vtkPolyDataMapper()
mapper_3_2.SetInputConnection(glyph_3_2.GetOutputPort())
actor_3_2 = vtkActor()
actor_3_2.SetMapper(mapper_3_2)

points_3_3 = vtkPoints()
points_3_3.InsertNextPoint(12, 9, 0)
polydata_3_3 = vtkPolyData()
polydata_3_3.SetPoints(points_3_3)
glyph_source_3_3 = vtkGlyphSource2D()
glyph_source_3_3.SetGlyphType(3)
glyph_source_3_3.FilledOff()
glyph_source_3_3.SetResolution(25)
glyph_source_3_3.SetScale(2.0)
glyph_3_3 = vtkGlyph2D()
glyph_3_3.SetSourceConnection(glyph_source_3_3.GetOutputPort())
glyph_3_3.SetInputData(polydata_3_3)
glyph_3_3.Update()
mapper_3_3 = vtkPolyDataMapper()
mapper_3_3.SetInputConnection(glyph_3_3.GetOutputPort())
actor_3_3 = vtkActor()
actor_3_3.SetMapper(mapper_3_3)

# Row 4: VTK_THICKCROSS_GLYPH (type 4)
points_4_0 = vtkPoints()
points_4_0.InsertNextPoint(3, 12, 0)
polydata_4_0 = vtkPolyData()
polydata_4_0.SetPoints(points_4_0)
glyph_source_4_0 = vtkGlyphSource2D()
glyph_source_4_0.SetGlyphType(4)
glyph_source_4_0.FilledOff()
glyph_source_4_0.SetResolution(25)
glyph_source_4_0.SetScale(0.5)
glyph_4_0 = vtkGlyph2D()
glyph_4_0.SetSourceConnection(glyph_source_4_0.GetOutputPort())
glyph_4_0.SetInputData(polydata_4_0)
glyph_4_0.Update()
mapper_4_0 = vtkPolyDataMapper()
mapper_4_0.SetInputConnection(glyph_4_0.GetOutputPort())
actor_4_0 = vtkActor()
actor_4_0.SetMapper(mapper_4_0)

points_4_1 = vtkPoints()
points_4_1.InsertNextPoint(6, 12, 0)
polydata_4_1 = vtkPolyData()
polydata_4_1.SetPoints(points_4_1)
glyph_source_4_1 = vtkGlyphSource2D()
glyph_source_4_1.SetGlyphType(4)
glyph_source_4_1.FilledOff()
glyph_source_4_1.SetResolution(25)
glyph_source_4_1.SetScale(1.0)
glyph_4_1 = vtkGlyph2D()
glyph_4_1.SetSourceConnection(glyph_source_4_1.GetOutputPort())
glyph_4_1.SetInputData(polydata_4_1)
glyph_4_1.Update()
mapper_4_1 = vtkPolyDataMapper()
mapper_4_1.SetInputConnection(glyph_4_1.GetOutputPort())
actor_4_1 = vtkActor()
actor_4_1.SetMapper(mapper_4_1)

points_4_2 = vtkPoints()
points_4_2.InsertNextPoint(9, 12, 0)
polydata_4_2 = vtkPolyData()
polydata_4_2.SetPoints(points_4_2)
glyph_source_4_2 = vtkGlyphSource2D()
glyph_source_4_2.SetGlyphType(4)
glyph_source_4_2.FilledOff()
glyph_source_4_2.SetResolution(25)
glyph_source_4_2.SetScale(1.5)
glyph_4_2 = vtkGlyph2D()
glyph_4_2.SetSourceConnection(glyph_source_4_2.GetOutputPort())
glyph_4_2.SetInputData(polydata_4_2)
glyph_4_2.Update()
mapper_4_2 = vtkPolyDataMapper()
mapper_4_2.SetInputConnection(glyph_4_2.GetOutputPort())
actor_4_2 = vtkActor()
actor_4_2.SetMapper(mapper_4_2)

points_4_3 = vtkPoints()
points_4_3.InsertNextPoint(12, 12, 0)
polydata_4_3 = vtkPolyData()
polydata_4_3.SetPoints(points_4_3)
glyph_source_4_3 = vtkGlyphSource2D()
glyph_source_4_3.SetGlyphType(4)
glyph_source_4_3.FilledOff()
glyph_source_4_3.SetResolution(25)
glyph_source_4_3.SetScale(2.0)
glyph_4_3 = vtkGlyph2D()
glyph_4_3.SetSourceConnection(glyph_source_4_3.GetOutputPort())
glyph_4_3.SetInputData(polydata_4_3)
glyph_4_3.Update()
mapper_4_3 = vtkPolyDataMapper()
mapper_4_3.SetInputConnection(glyph_4_3.GetOutputPort())
actor_4_3 = vtkActor()
actor_4_3.SetMapper(mapper_4_3)

# Row 5: VTK_TRIANGLE_GLYPH (type 5)
points_5_0 = vtkPoints()
points_5_0.InsertNextPoint(3, 15, 0)
polydata_5_0 = vtkPolyData()
polydata_5_0.SetPoints(points_5_0)
glyph_source_5_0 = vtkGlyphSource2D()
glyph_source_5_0.SetGlyphType(5)
glyph_source_5_0.FilledOff()
glyph_source_5_0.SetResolution(25)
glyph_source_5_0.SetScale(0.5)
glyph_source_5_0.SetRotationAngle(90)
glyph_5_0 = vtkGlyph2D()
glyph_5_0.SetSourceConnection(glyph_source_5_0.GetOutputPort())
glyph_5_0.SetInputData(polydata_5_0)
glyph_5_0.Update()
mapper_5_0 = vtkPolyDataMapper()
mapper_5_0.SetInputConnection(glyph_5_0.GetOutputPort())
actor_5_0 = vtkActor()
actor_5_0.SetMapper(mapper_5_0)

points_5_1 = vtkPoints()
points_5_1.InsertNextPoint(6, 15, 0)
polydata_5_1 = vtkPolyData()
polydata_5_1.SetPoints(points_5_1)
glyph_source_5_1 = vtkGlyphSource2D()
glyph_source_5_1.SetGlyphType(5)
glyph_source_5_1.FilledOff()
glyph_source_5_1.SetResolution(25)
glyph_source_5_1.SetScale(1.0)
glyph_source_5_1.SetRotationAngle(90)
glyph_5_1 = vtkGlyph2D()
glyph_5_1.SetSourceConnection(glyph_source_5_1.GetOutputPort())
glyph_5_1.SetInputData(polydata_5_1)
glyph_5_1.Update()
mapper_5_1 = vtkPolyDataMapper()
mapper_5_1.SetInputConnection(glyph_5_1.GetOutputPort())
actor_5_1 = vtkActor()
actor_5_1.SetMapper(mapper_5_1)

points_5_2 = vtkPoints()
points_5_2.InsertNextPoint(9, 15, 0)
polydata_5_2 = vtkPolyData()
polydata_5_2.SetPoints(points_5_2)
glyph_source_5_2 = vtkGlyphSource2D()
glyph_source_5_2.SetGlyphType(5)
glyph_source_5_2.FilledOff()
glyph_source_5_2.SetResolution(25)
glyph_source_5_2.SetScale(1.5)
glyph_source_5_2.SetRotationAngle(90)
glyph_5_2 = vtkGlyph2D()
glyph_5_2.SetSourceConnection(glyph_source_5_2.GetOutputPort())
glyph_5_2.SetInputData(polydata_5_2)
glyph_5_2.Update()
mapper_5_2 = vtkPolyDataMapper()
mapper_5_2.SetInputConnection(glyph_5_2.GetOutputPort())
actor_5_2 = vtkActor()
actor_5_2.SetMapper(mapper_5_2)

points_5_3 = vtkPoints()
points_5_3.InsertNextPoint(12, 15, 0)
polydata_5_3 = vtkPolyData()
polydata_5_3.SetPoints(points_5_3)
glyph_source_5_3 = vtkGlyphSource2D()
glyph_source_5_3.SetGlyphType(5)
glyph_source_5_3.FilledOff()
glyph_source_5_3.SetResolution(25)
glyph_source_5_3.SetScale(2.0)
glyph_source_5_3.SetRotationAngle(90)
glyph_5_3 = vtkGlyph2D()
glyph_5_3.SetSourceConnection(glyph_source_5_3.GetOutputPort())
glyph_5_3.SetInputData(polydata_5_3)
glyph_5_3.Update()
mapper_5_3 = vtkPolyDataMapper()
mapper_5_3.SetInputConnection(glyph_5_3.GetOutputPort())
actor_5_3 = vtkActor()
actor_5_3.SetMapper(mapper_5_3)

# Row 6: VTK_SQUARE_GLYPH (type 6)
points_6_0 = vtkPoints()
points_6_0.InsertNextPoint(3, 18, 0)
polydata_6_0 = vtkPolyData()
polydata_6_0.SetPoints(points_6_0)
glyph_source_6_0 = vtkGlyphSource2D()
glyph_source_6_0.SetGlyphType(6)
glyph_source_6_0.FilledOff()
glyph_source_6_0.SetResolution(25)
glyph_source_6_0.SetScale(0.5)
glyph_6_0 = vtkGlyph2D()
glyph_6_0.SetSourceConnection(glyph_source_6_0.GetOutputPort())
glyph_6_0.SetInputData(polydata_6_0)
glyph_6_0.Update()
mapper_6_0 = vtkPolyDataMapper()
mapper_6_0.SetInputConnection(glyph_6_0.GetOutputPort())
actor_6_0 = vtkActor()
actor_6_0.SetMapper(mapper_6_0)

points_6_1 = vtkPoints()
points_6_1.InsertNextPoint(6, 18, 0)
polydata_6_1 = vtkPolyData()
polydata_6_1.SetPoints(points_6_1)
glyph_source_6_1 = vtkGlyphSource2D()
glyph_source_6_1.SetGlyphType(6)
glyph_source_6_1.FilledOff()
glyph_source_6_1.SetResolution(25)
glyph_source_6_1.SetScale(1.0)
glyph_6_1 = vtkGlyph2D()
glyph_6_1.SetSourceConnection(glyph_source_6_1.GetOutputPort())
glyph_6_1.SetInputData(polydata_6_1)
glyph_6_1.Update()
mapper_6_1 = vtkPolyDataMapper()
mapper_6_1.SetInputConnection(glyph_6_1.GetOutputPort())
actor_6_1 = vtkActor()
actor_6_1.SetMapper(mapper_6_1)

points_6_2 = vtkPoints()
points_6_2.InsertNextPoint(9, 18, 0)
polydata_6_2 = vtkPolyData()
polydata_6_2.SetPoints(points_6_2)
glyph_source_6_2 = vtkGlyphSource2D()
glyph_source_6_2.SetGlyphType(6)
glyph_source_6_2.FilledOff()
glyph_source_6_2.SetResolution(25)
glyph_source_6_2.SetScale(1.5)
glyph_6_2 = vtkGlyph2D()
glyph_6_2.SetSourceConnection(glyph_source_6_2.GetOutputPort())
glyph_6_2.SetInputData(polydata_6_2)
glyph_6_2.Update()
mapper_6_2 = vtkPolyDataMapper()
mapper_6_2.SetInputConnection(glyph_6_2.GetOutputPort())
actor_6_2 = vtkActor()
actor_6_2.SetMapper(mapper_6_2)

points_6_3 = vtkPoints()
points_6_3.InsertNextPoint(12, 18, 0)
polydata_6_3 = vtkPolyData()
polydata_6_3.SetPoints(points_6_3)
glyph_source_6_3 = vtkGlyphSource2D()
glyph_source_6_3.SetGlyphType(6)
glyph_source_6_3.FilledOff()
glyph_source_6_3.SetResolution(25)
glyph_source_6_3.SetScale(2.0)
glyph_6_3 = vtkGlyph2D()
glyph_6_3.SetSourceConnection(glyph_source_6_3.GetOutputPort())
glyph_6_3.SetInputData(polydata_6_3)
glyph_6_3.Update()
mapper_6_3 = vtkPolyDataMapper()
mapper_6_3.SetInputConnection(glyph_6_3.GetOutputPort())
actor_6_3 = vtkActor()
actor_6_3.SetMapper(mapper_6_3)

# Row 7: VTK_CIRCLE_GLYPH (type 7)
points_7_0 = vtkPoints()
points_7_0.InsertNextPoint(3, 21, 0)
polydata_7_0 = vtkPolyData()
polydata_7_0.SetPoints(points_7_0)
glyph_source_7_0 = vtkGlyphSource2D()
glyph_source_7_0.SetGlyphType(7)
glyph_source_7_0.FilledOff()
glyph_source_7_0.SetResolution(25)
glyph_source_7_0.SetScale(0.5)
glyph_7_0 = vtkGlyph2D()
glyph_7_0.SetSourceConnection(glyph_source_7_0.GetOutputPort())
glyph_7_0.SetInputData(polydata_7_0)
glyph_7_0.Update()
mapper_7_0 = vtkPolyDataMapper()
mapper_7_0.SetInputConnection(glyph_7_0.GetOutputPort())
actor_7_0 = vtkActor()
actor_7_0.SetMapper(mapper_7_0)

points_7_1 = vtkPoints()
points_7_1.InsertNextPoint(6, 21, 0)
polydata_7_1 = vtkPolyData()
polydata_7_1.SetPoints(points_7_1)
glyph_source_7_1 = vtkGlyphSource2D()
glyph_source_7_1.SetGlyphType(7)
glyph_source_7_1.FilledOff()
glyph_source_7_1.SetResolution(25)
glyph_source_7_1.SetScale(1.0)
glyph_7_1 = vtkGlyph2D()
glyph_7_1.SetSourceConnection(glyph_source_7_1.GetOutputPort())
glyph_7_1.SetInputData(polydata_7_1)
glyph_7_1.Update()
mapper_7_1 = vtkPolyDataMapper()
mapper_7_1.SetInputConnection(glyph_7_1.GetOutputPort())
actor_7_1 = vtkActor()
actor_7_1.SetMapper(mapper_7_1)

points_7_2 = vtkPoints()
points_7_2.InsertNextPoint(9, 21, 0)
polydata_7_2 = vtkPolyData()
polydata_7_2.SetPoints(points_7_2)
glyph_source_7_2 = vtkGlyphSource2D()
glyph_source_7_2.SetGlyphType(7)
glyph_source_7_2.FilledOff()
glyph_source_7_2.SetResolution(25)
glyph_source_7_2.SetScale(1.5)
glyph_7_2 = vtkGlyph2D()
glyph_7_2.SetSourceConnection(glyph_source_7_2.GetOutputPort())
glyph_7_2.SetInputData(polydata_7_2)
glyph_7_2.Update()
mapper_7_2 = vtkPolyDataMapper()
mapper_7_2.SetInputConnection(glyph_7_2.GetOutputPort())
actor_7_2 = vtkActor()
actor_7_2.SetMapper(mapper_7_2)

points_7_3 = vtkPoints()
points_7_3.InsertNextPoint(12, 21, 0)
polydata_7_3 = vtkPolyData()
polydata_7_3.SetPoints(points_7_3)
glyph_source_7_3 = vtkGlyphSource2D()
glyph_source_7_3.SetGlyphType(7)
glyph_source_7_3.FilledOff()
glyph_source_7_3.SetResolution(25)
glyph_source_7_3.SetScale(2.0)
glyph_7_3 = vtkGlyph2D()
glyph_7_3.SetSourceConnection(glyph_source_7_3.GetOutputPort())
glyph_7_3.SetInputData(polydata_7_3)
glyph_7_3.Update()
mapper_7_3 = vtkPolyDataMapper()
mapper_7_3.SetInputConnection(glyph_7_3.GetOutputPort())
actor_7_3 = vtkActor()
actor_7_3.SetMapper(mapper_7_3)

# Row 8: VTK_DIAMOND_GLYPH (type 8)
points_8_0 = vtkPoints()
points_8_0.InsertNextPoint(3, 24, 0)
polydata_8_0 = vtkPolyData()
polydata_8_0.SetPoints(points_8_0)
glyph_source_8_0 = vtkGlyphSource2D()
glyph_source_8_0.SetGlyphType(8)
glyph_source_8_0.FilledOff()
glyph_source_8_0.SetResolution(25)
glyph_source_8_0.SetScale(0.5)
glyph_8_0 = vtkGlyph2D()
glyph_8_0.SetSourceConnection(glyph_source_8_0.GetOutputPort())
glyph_8_0.SetInputData(polydata_8_0)
glyph_8_0.Update()
mapper_8_0 = vtkPolyDataMapper()
mapper_8_0.SetInputConnection(glyph_8_0.GetOutputPort())
actor_8_0 = vtkActor()
actor_8_0.SetMapper(mapper_8_0)

points_8_1 = vtkPoints()
points_8_1.InsertNextPoint(6, 24, 0)
polydata_8_1 = vtkPolyData()
polydata_8_1.SetPoints(points_8_1)
glyph_source_8_1 = vtkGlyphSource2D()
glyph_source_8_1.SetGlyphType(8)
glyph_source_8_1.FilledOff()
glyph_source_8_1.SetResolution(25)
glyph_source_8_1.SetScale(1.0)
glyph_8_1 = vtkGlyph2D()
glyph_8_1.SetSourceConnection(glyph_source_8_1.GetOutputPort())
glyph_8_1.SetInputData(polydata_8_1)
glyph_8_1.Update()
mapper_8_1 = vtkPolyDataMapper()
mapper_8_1.SetInputConnection(glyph_8_1.GetOutputPort())
actor_8_1 = vtkActor()
actor_8_1.SetMapper(mapper_8_1)

points_8_2 = vtkPoints()
points_8_2.InsertNextPoint(9, 24, 0)
polydata_8_2 = vtkPolyData()
polydata_8_2.SetPoints(points_8_2)
glyph_source_8_2 = vtkGlyphSource2D()
glyph_source_8_2.SetGlyphType(8)
glyph_source_8_2.FilledOff()
glyph_source_8_2.SetResolution(25)
glyph_source_8_2.SetScale(1.5)
glyph_8_2 = vtkGlyph2D()
glyph_8_2.SetSourceConnection(glyph_source_8_2.GetOutputPort())
glyph_8_2.SetInputData(polydata_8_2)
glyph_8_2.Update()
mapper_8_2 = vtkPolyDataMapper()
mapper_8_2.SetInputConnection(glyph_8_2.GetOutputPort())
actor_8_2 = vtkActor()
actor_8_2.SetMapper(mapper_8_2)

points_8_3 = vtkPoints()
points_8_3.InsertNextPoint(12, 24, 0)
polydata_8_3 = vtkPolyData()
polydata_8_3.SetPoints(points_8_3)
glyph_source_8_3 = vtkGlyphSource2D()
glyph_source_8_3.SetGlyphType(8)
glyph_source_8_3.FilledOff()
glyph_source_8_3.SetResolution(25)
glyph_source_8_3.SetScale(2.0)
glyph_8_3 = vtkGlyph2D()
glyph_8_3.SetSourceConnection(glyph_source_8_3.GetOutputPort())
glyph_8_3.SetInputData(polydata_8_3)
glyph_8_3.Update()
mapper_8_3 = vtkPolyDataMapper()
mapper_8_3.SetInputConnection(glyph_8_3.GetOutputPort())
actor_8_3 = vtkActor()
actor_8_3.SetMapper(mapper_8_3)

# Row 9: VTK_ARROW_GLYPH (type 9)
points_9_0 = vtkPoints()
points_9_0.InsertNextPoint(3, 27, 0)
polydata_9_0 = vtkPolyData()
polydata_9_0.SetPoints(points_9_0)
glyph_source_9_0 = vtkGlyphSource2D()
glyph_source_9_0.SetGlyphType(9)
glyph_source_9_0.FilledOff()
glyph_source_9_0.SetResolution(25)
glyph_source_9_0.SetScale(0.5)
glyph_9_0 = vtkGlyph2D()
glyph_9_0.SetSourceConnection(glyph_source_9_0.GetOutputPort())
glyph_9_0.SetInputData(polydata_9_0)
glyph_9_0.Update()
mapper_9_0 = vtkPolyDataMapper()
mapper_9_0.SetInputConnection(glyph_9_0.GetOutputPort())
actor_9_0 = vtkActor()
actor_9_0.SetMapper(mapper_9_0)

points_9_1 = vtkPoints()
points_9_1.InsertNextPoint(6, 27, 0)
polydata_9_1 = vtkPolyData()
polydata_9_1.SetPoints(points_9_1)
glyph_source_9_1 = vtkGlyphSource2D()
glyph_source_9_1.SetGlyphType(9)
glyph_source_9_1.FilledOff()
glyph_source_9_1.SetResolution(25)
glyph_source_9_1.SetScale(1.0)
glyph_9_1 = vtkGlyph2D()
glyph_9_1.SetSourceConnection(glyph_source_9_1.GetOutputPort())
glyph_9_1.SetInputData(polydata_9_1)
glyph_9_1.Update()
mapper_9_1 = vtkPolyDataMapper()
mapper_9_1.SetInputConnection(glyph_9_1.GetOutputPort())
actor_9_1 = vtkActor()
actor_9_1.SetMapper(mapper_9_1)

points_9_2 = vtkPoints()
points_9_2.InsertNextPoint(9, 27, 0)
polydata_9_2 = vtkPolyData()
polydata_9_2.SetPoints(points_9_2)
glyph_source_9_2 = vtkGlyphSource2D()
glyph_source_9_2.SetGlyphType(9)
glyph_source_9_2.FilledOff()
glyph_source_9_2.SetResolution(25)
glyph_source_9_2.SetScale(1.5)
glyph_9_2 = vtkGlyph2D()
glyph_9_2.SetSourceConnection(glyph_source_9_2.GetOutputPort())
glyph_9_2.SetInputData(polydata_9_2)
glyph_9_2.Update()
mapper_9_2 = vtkPolyDataMapper()
mapper_9_2.SetInputConnection(glyph_9_2.GetOutputPort())
actor_9_2 = vtkActor()
actor_9_2.SetMapper(mapper_9_2)

points_9_3 = vtkPoints()
points_9_3.InsertNextPoint(12, 27, 0)
polydata_9_3 = vtkPolyData()
polydata_9_3.SetPoints(points_9_3)
glyph_source_9_3 = vtkGlyphSource2D()
glyph_source_9_3.SetGlyphType(9)
glyph_source_9_3.FilledOff()
glyph_source_9_3.SetResolution(25)
glyph_source_9_3.SetScale(2.0)
glyph_9_3 = vtkGlyph2D()
glyph_9_3.SetSourceConnection(glyph_source_9_3.GetOutputPort())
glyph_9_3.SetInputData(polydata_9_3)
glyph_9_3.Update()
mapper_9_3 = vtkPolyDataMapper()
mapper_9_3.SetInputConnection(glyph_9_3.GetOutputPort())
actor_9_3 = vtkActor()
actor_9_3.SetMapper(mapper_9_3)

# Row 10: VTK_THICKARROW_GLYPH (type 10)
points_10_0 = vtkPoints()
points_10_0.InsertNextPoint(3, 30, 0)
polydata_10_0 = vtkPolyData()
polydata_10_0.SetPoints(points_10_0)
glyph_source_10_0 = vtkGlyphSource2D()
glyph_source_10_0.SetGlyphType(10)
glyph_source_10_0.FilledOff()
glyph_source_10_0.SetResolution(25)
glyph_source_10_0.SetScale(0.5)
glyph_10_0 = vtkGlyph2D()
glyph_10_0.SetSourceConnection(glyph_source_10_0.GetOutputPort())
glyph_10_0.SetInputData(polydata_10_0)
glyph_10_0.Update()
mapper_10_0 = vtkPolyDataMapper()
mapper_10_0.SetInputConnection(glyph_10_0.GetOutputPort())
actor_10_0 = vtkActor()
actor_10_0.SetMapper(mapper_10_0)

points_10_1 = vtkPoints()
points_10_1.InsertNextPoint(6, 30, 0)
polydata_10_1 = vtkPolyData()
polydata_10_1.SetPoints(points_10_1)
glyph_source_10_1 = vtkGlyphSource2D()
glyph_source_10_1.SetGlyphType(10)
glyph_source_10_1.FilledOff()
glyph_source_10_1.SetResolution(25)
glyph_source_10_1.SetScale(1.0)
glyph_10_1 = vtkGlyph2D()
glyph_10_1.SetSourceConnection(glyph_source_10_1.GetOutputPort())
glyph_10_1.SetInputData(polydata_10_1)
glyph_10_1.Update()
mapper_10_1 = vtkPolyDataMapper()
mapper_10_1.SetInputConnection(glyph_10_1.GetOutputPort())
actor_10_1 = vtkActor()
actor_10_1.SetMapper(mapper_10_1)

points_10_2 = vtkPoints()
points_10_2.InsertNextPoint(9, 30, 0)
polydata_10_2 = vtkPolyData()
polydata_10_2.SetPoints(points_10_2)
glyph_source_10_2 = vtkGlyphSource2D()
glyph_source_10_2.SetGlyphType(10)
glyph_source_10_2.FilledOff()
glyph_source_10_2.SetResolution(25)
glyph_source_10_2.SetScale(1.5)
glyph_10_2 = vtkGlyph2D()
glyph_10_2.SetSourceConnection(glyph_source_10_2.GetOutputPort())
glyph_10_2.SetInputData(polydata_10_2)
glyph_10_2.Update()
mapper_10_2 = vtkPolyDataMapper()
mapper_10_2.SetInputConnection(glyph_10_2.GetOutputPort())
actor_10_2 = vtkActor()
actor_10_2.SetMapper(mapper_10_2)

points_10_3 = vtkPoints()
points_10_3.InsertNextPoint(12, 30, 0)
polydata_10_3 = vtkPolyData()
polydata_10_3.SetPoints(points_10_3)
glyph_source_10_3 = vtkGlyphSource2D()
glyph_source_10_3.SetGlyphType(10)
glyph_source_10_3.FilledOff()
glyph_source_10_3.SetResolution(25)
glyph_source_10_3.SetScale(2.0)
glyph_10_3 = vtkGlyph2D()
glyph_10_3.SetSourceConnection(glyph_source_10_3.GetOutputPort())
glyph_10_3.SetInputData(polydata_10_3)
glyph_10_3.Update()
mapper_10_3 = vtkPolyDataMapper()
mapper_10_3.SetInputConnection(glyph_10_3.GetOutputPort())
actor_10_3 = vtkActor()
actor_10_3.SetMapper(mapper_10_3)

# Row 11: VTK_HOOKEDARROW_GLYPH (type 11)
points_11_0 = vtkPoints()
points_11_0.InsertNextPoint(3, 33, 0)
polydata_11_0 = vtkPolyData()
polydata_11_0.SetPoints(points_11_0)
glyph_source_11_0 = vtkGlyphSource2D()
glyph_source_11_0.SetGlyphType(11)
glyph_source_11_0.FilledOff()
glyph_source_11_0.SetResolution(25)
glyph_source_11_0.SetScale(0.5)
glyph_11_0 = vtkGlyph2D()
glyph_11_0.SetSourceConnection(glyph_source_11_0.GetOutputPort())
glyph_11_0.SetInputData(polydata_11_0)
glyph_11_0.Update()
mapper_11_0 = vtkPolyDataMapper()
mapper_11_0.SetInputConnection(glyph_11_0.GetOutputPort())
actor_11_0 = vtkActor()
actor_11_0.SetMapper(mapper_11_0)

points_11_1 = vtkPoints()
points_11_1.InsertNextPoint(6, 33, 0)
polydata_11_1 = vtkPolyData()
polydata_11_1.SetPoints(points_11_1)
glyph_source_11_1 = vtkGlyphSource2D()
glyph_source_11_1.SetGlyphType(11)
glyph_source_11_1.FilledOff()
glyph_source_11_1.SetResolution(25)
glyph_source_11_1.SetScale(1.0)
glyph_11_1 = vtkGlyph2D()
glyph_11_1.SetSourceConnection(glyph_source_11_1.GetOutputPort())
glyph_11_1.SetInputData(polydata_11_1)
glyph_11_1.Update()
mapper_11_1 = vtkPolyDataMapper()
mapper_11_1.SetInputConnection(glyph_11_1.GetOutputPort())
actor_11_1 = vtkActor()
actor_11_1.SetMapper(mapper_11_1)

points_11_2 = vtkPoints()
points_11_2.InsertNextPoint(9, 33, 0)
polydata_11_2 = vtkPolyData()
polydata_11_2.SetPoints(points_11_2)
glyph_source_11_2 = vtkGlyphSource2D()
glyph_source_11_2.SetGlyphType(11)
glyph_source_11_2.FilledOff()
glyph_source_11_2.SetResolution(25)
glyph_source_11_2.SetScale(1.5)
glyph_11_2 = vtkGlyph2D()
glyph_11_2.SetSourceConnection(glyph_source_11_2.GetOutputPort())
glyph_11_2.SetInputData(polydata_11_2)
glyph_11_2.Update()
mapper_11_2 = vtkPolyDataMapper()
mapper_11_2.SetInputConnection(glyph_11_2.GetOutputPort())
actor_11_2 = vtkActor()
actor_11_2.SetMapper(mapper_11_2)

points_11_3 = vtkPoints()
points_11_3.InsertNextPoint(12, 33, 0)
polydata_11_3 = vtkPolyData()
polydata_11_3.SetPoints(points_11_3)
glyph_source_11_3 = vtkGlyphSource2D()
glyph_source_11_3.SetGlyphType(11)
glyph_source_11_3.FilledOff()
glyph_source_11_3.SetResolution(25)
glyph_source_11_3.SetScale(2.0)
glyph_11_3 = vtkGlyph2D()
glyph_11_3.SetSourceConnection(glyph_source_11_3.GetOutputPort())
glyph_11_3.SetInputData(polydata_11_3)
glyph_11_3.Update()
mapper_11_3 = vtkPolyDataMapper()
mapper_11_3.SetInputConnection(glyph_11_3.GetOutputPort())
actor_11_3 = vtkActor()
actor_11_3.SetMapper(mapper_11_3)

# Row 12: VTK_EDGEARROW_GLYPH (type 12)
points_12_0 = vtkPoints()
points_12_0.InsertNextPoint(3, 36, 0)
polydata_12_0 = vtkPolyData()
polydata_12_0.SetPoints(points_12_0)
glyph_source_12_0 = vtkGlyphSource2D()
glyph_source_12_0.SetGlyphType(12)
glyph_source_12_0.FilledOff()
glyph_source_12_0.SetResolution(25)
glyph_source_12_0.SetScale(0.5)
glyph_12_0 = vtkGlyph2D()
glyph_12_0.SetSourceConnection(glyph_source_12_0.GetOutputPort())
glyph_12_0.SetInputData(polydata_12_0)
glyph_12_0.Update()
mapper_12_0 = vtkPolyDataMapper()
mapper_12_0.SetInputConnection(glyph_12_0.GetOutputPort())
actor_12_0 = vtkActor()
actor_12_0.SetMapper(mapper_12_0)

points_12_1 = vtkPoints()
points_12_1.InsertNextPoint(6, 36, 0)
polydata_12_1 = vtkPolyData()
polydata_12_1.SetPoints(points_12_1)
glyph_source_12_1 = vtkGlyphSource2D()
glyph_source_12_1.SetGlyphType(12)
glyph_source_12_1.FilledOff()
glyph_source_12_1.SetResolution(25)
glyph_source_12_1.SetScale(1.0)
glyph_12_1 = vtkGlyph2D()
glyph_12_1.SetSourceConnection(glyph_source_12_1.GetOutputPort())
glyph_12_1.SetInputData(polydata_12_1)
glyph_12_1.Update()
mapper_12_1 = vtkPolyDataMapper()
mapper_12_1.SetInputConnection(glyph_12_1.GetOutputPort())
actor_12_1 = vtkActor()
actor_12_1.SetMapper(mapper_12_1)

points_12_2 = vtkPoints()
points_12_2.InsertNextPoint(9, 36, 0)
polydata_12_2 = vtkPolyData()
polydata_12_2.SetPoints(points_12_2)
glyph_source_12_2 = vtkGlyphSource2D()
glyph_source_12_2.SetGlyphType(12)
glyph_source_12_2.FilledOff()
glyph_source_12_2.SetResolution(25)
glyph_source_12_2.SetScale(1.5)
glyph_12_2 = vtkGlyph2D()
glyph_12_2.SetSourceConnection(glyph_source_12_2.GetOutputPort())
glyph_12_2.SetInputData(polydata_12_2)
glyph_12_2.Update()
mapper_12_2 = vtkPolyDataMapper()
mapper_12_2.SetInputConnection(glyph_12_2.GetOutputPort())
actor_12_2 = vtkActor()
actor_12_2.SetMapper(mapper_12_2)

points_12_3 = vtkPoints()
points_12_3.InsertNextPoint(12, 36, 0)
polydata_12_3 = vtkPolyData()
polydata_12_3.SetPoints(points_12_3)
glyph_source_12_3 = vtkGlyphSource2D()
glyph_source_12_3.SetGlyphType(12)
glyph_source_12_3.FilledOff()
glyph_source_12_3.SetResolution(25)
glyph_source_12_3.SetScale(2.0)
glyph_12_3 = vtkGlyph2D()
glyph_12_3.SetSourceConnection(glyph_source_12_3.GetOutputPort())
glyph_12_3.SetInputData(polydata_12_3)
glyph_12_3.Update()
mapper_12_3 = vtkPolyDataMapper()
mapper_12_3.SetInputConnection(glyph_12_3.GetOutputPort())
actor_12_3 = vtkActor()
actor_12_3.SetMapper(mapper_12_3)

# Renderer
renderer = vtkRenderer()
renderer.AddActor(actor_0_0)
renderer.AddActor(actor_0_1)
renderer.AddActor(actor_0_2)
renderer.AddActor(actor_0_3)
renderer.AddActor(actor_1_0)
renderer.AddActor(actor_1_1)
renderer.AddActor(actor_1_2)
renderer.AddActor(actor_1_3)
renderer.AddActor(actor_2_0)
renderer.AddActor(actor_2_1)
renderer.AddActor(actor_2_2)
renderer.AddActor(actor_2_3)
renderer.AddActor(actor_3_0)
renderer.AddActor(actor_3_1)
renderer.AddActor(actor_3_2)
renderer.AddActor(actor_3_3)
renderer.AddActor(actor_4_0)
renderer.AddActor(actor_4_1)
renderer.AddActor(actor_4_2)
renderer.AddActor(actor_4_3)
renderer.AddActor(actor_5_0)
renderer.AddActor(actor_5_1)
renderer.AddActor(actor_5_2)
renderer.AddActor(actor_5_3)
renderer.AddActor(actor_6_0)
renderer.AddActor(actor_6_1)
renderer.AddActor(actor_6_2)
renderer.AddActor(actor_6_3)
renderer.AddActor(actor_7_0)
renderer.AddActor(actor_7_1)
renderer.AddActor(actor_7_2)
renderer.AddActor(actor_7_3)
renderer.AddActor(actor_8_0)
renderer.AddActor(actor_8_1)
renderer.AddActor(actor_8_2)
renderer.AddActor(actor_8_3)
renderer.AddActor(actor_9_0)
renderer.AddActor(actor_9_1)
renderer.AddActor(actor_9_2)
renderer.AddActor(actor_9_3)
renderer.AddActor(actor_10_0)
renderer.AddActor(actor_10_1)
renderer.AddActor(actor_10_2)
renderer.AddActor(actor_10_3)
renderer.AddActor(actor_11_0)
renderer.AddActor(actor_11_1)
renderer.AddActor(actor_11_2)
renderer.AddActor(actor_11_3)
renderer.AddActor(actor_12_0)
renderer.AddActor(actor_12_1)
renderer.AddActor(actor_12_2)
renderer.AddActor(actor_12_3)

# Window
render_window = vtkRenderWindow()
render_window.SetSize(400, 600)
render_window.AddRenderer(renderer)
render_window.SetWindowName("glyph scaling")

# Interactor
interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)

interactor.Initialize()
interactor.Start()
