#!/usr/bin/env python

# Display sixteen isoparametric (quadratic/higher-order) cell types in a
# 4 × 4 grid of viewports, each with its own renderer.  Each cell shows
# vertex-ordering labels and gold sphere glyphs at the vertices.
# Three-dimensional cells are rotated and sit on a translucent plinth.

# Factory overrides: importing these modules registers the OpenGL rendering,
# FreeType text rendering, and interaction style implementations.
import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingFreeType  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401
# VTK pipeline classes used in this example
from vtkmodules.vtkCommonCore import vtkPoints
from vtkmodules.vtkCommonDataModel import (
    vtkBiQuadraticQuad,
    vtkBiQuadraticQuadraticHexahedron,
    vtkBiQuadraticQuadraticWedge,
    vtkBiQuadraticTriangle,
    vtkCubicLine,
    vtkQuadraticEdge,
    vtkQuadraticHexahedron,
    vtkQuadraticLinearQuad,
    vtkQuadraticLinearWedge,
    vtkQuadraticPolygon,
    vtkQuadraticPyramid,
    vtkQuadraticQuad,
    vtkQuadraticTetra,
    vtkQuadraticTriangle,
    vtkQuadraticWedge,
    vtkTriQuadraticHexahedron,
    vtkUnstructuredGrid,
)
from vtkmodules.vtkCommonTransforms import vtkTransform
from vtkmodules.vtkFiltersGeneral import vtkTransformFilter
from vtkmodules.vtkFiltersSources import (
    vtkCubeSource,
    vtkSphereSource,
)
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkActor2D,
    vtkDataSetMapper,
    vtkGlyph3DMapper,
    vtkPolyDataMapper,
    vtkProperty,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
    vtkTextActor,
    vtkTextProperty,
)
from vtkmodules.vtkRenderingLabel import vtkLabeledDataMapper

# Colors (normalized RGB)
dark_salmon_rgb = (0.914, 0.588, 0.478)
seashell_rgb = (1.0, 0.961, 0.933)
gold_rgb = (1.0, 0.843, 0.0)
yellow_rgb = (1.0, 1.0, 0.0)
steel_blue_rgb = (0.275, 0.510, 0.706)
light_steel_blue_rgb = (0.690, 0.769, 0.871)
deep_pink_rgb = (1.0, 0.078, 0.576)
background_rgb = (0.690, 0.769, 0.871)

# ===========================================================================
# Sources: shared glyph source and 16 cell grids
# ===========================================================================
sphere_source = vtkSphereSource()
sphere_source.SetPhiResolution(21)
sphere_source.SetThetaResolution(21)
sphere_source.SetRadius(0.04)

# Cell 0: Quadratic Edge (wireframe, 2D)
qe_cell = vtkQuadraticEdge()
qe_pc = qe_cell.GetParametricCoords()
for i in range(qe_cell.GetNumberOfPoints()):
    qe_cell.GetPointIds().SetId(i, i)
    qe_cell.GetPoints().SetPoint(i, qe_pc[3 * i], qe_pc[3 * i + 1], qe_pc[3 * i + 2])
qe_grid = vtkUnstructuredGrid()
qe_grid.SetPoints(qe_cell.GetPoints())
qe_grid.InsertNextCell(qe_cell.GetCellType(), qe_cell.GetPointIds())
qe_bounds = qe_grid.GetBounds()
qe_new_pts = vtkPoints()
qe_new_pts.SetNumberOfPoints(qe_grid.GetNumberOfPoints())
for i in range(qe_grid.GetNumberOfPoints()):
    px, py, pz = qe_grid.GetPoint(i)
    qe_new_pts.SetPoint(i, px - (qe_bounds[0] + qe_bounds[1]) / 2.0,
                         py - (qe_bounds[2] + qe_bounds[3]) / 2.0,
                         pz - (qe_bounds[4] + qe_bounds[5]) / 2.0)
qe_grid.SetPoints(qe_new_pts)

# Cell 1: Quadratic Triangle (surface, 2D)
qt_cell = vtkQuadraticTriangle()
qt_pc = qt_cell.GetParametricCoords()
for i in range(qt_cell.GetNumberOfPoints()):
    qt_cell.GetPointIds().SetId(i, i)
    qt_cell.GetPoints().SetPoint(i, qt_pc[3 * i], qt_pc[3 * i + 1], qt_pc[3 * i + 2])
qt_grid = vtkUnstructuredGrid()
qt_grid.SetPoints(qt_cell.GetPoints())
qt_grid.InsertNextCell(qt_cell.GetCellType(), qt_cell.GetPointIds())
qt_bounds = qt_grid.GetBounds()
qt_new_pts = vtkPoints()
qt_new_pts.SetNumberOfPoints(qt_grid.GetNumberOfPoints())
for i in range(qt_grid.GetNumberOfPoints()):
    px, py, pz = qt_grid.GetPoint(i)
    qt_new_pts.SetPoint(i, px - (qt_bounds[0] + qt_bounds[1]) / 2.0,
                         py - (qt_bounds[2] + qt_bounds[3]) / 2.0,
                         pz - (qt_bounds[4] + qt_bounds[5]) / 2.0)
qt_grid.SetPoints(qt_new_pts)

# Cell 2: Quadratic Quad (surface, 2D)
qq_cell = vtkQuadraticQuad()
qq_pc = qq_cell.GetParametricCoords()
for i in range(qq_cell.GetNumberOfPoints()):
    qq_cell.GetPointIds().SetId(i, i)
    qq_cell.GetPoints().SetPoint(i, qq_pc[3 * i], qq_pc[3 * i + 1], qq_pc[3 * i + 2])
qq_grid = vtkUnstructuredGrid()
qq_grid.SetPoints(qq_cell.GetPoints())
qq_grid.InsertNextCell(qq_cell.GetCellType(), qq_cell.GetPointIds())
qq_bounds = qq_grid.GetBounds()
qq_new_pts = vtkPoints()
qq_new_pts.SetNumberOfPoints(qq_grid.GetNumberOfPoints())
for i in range(qq_grid.GetNumberOfPoints()):
    px, py, pz = qq_grid.GetPoint(i)
    qq_new_pts.SetPoint(i, px - (qq_bounds[0] + qq_bounds[1]) / 2.0,
                         py - (qq_bounds[2] + qq_bounds[3]) / 2.0,
                         pz - (qq_bounds[4] + qq_bounds[5]) / 2.0)
qq_grid.SetPoints(qq_new_pts)

# Cell 3: Quadratic Polygon (surface, 2D) — explicit points
qp_cell = vtkQuadraticPolygon()
qp_cell.GetPoints().SetNumberOfPoints(8)
qp_cell.GetPoints().SetPoint(0, 0.0, 0.0, 0.0)
qp_cell.GetPoints().SetPoint(1, 1.0, 0.0, 0.0)
qp_cell.GetPoints().SetPoint(2, 1.0, 1.0, 0.0)
qp_cell.GetPoints().SetPoint(3, 0.0, 1.0, 0.0)
qp_cell.GetPoints().SetPoint(4, 0.5, 0.0, 0.0)
qp_cell.GetPoints().SetPoint(5, 1.3, 0.5, 0.0)
qp_cell.GetPoints().SetPoint(6, 0.5, 1.0, 0.0)
qp_cell.GetPoints().SetPoint(7, 0.0, 0.5, 0.0)
qp_cell.GetPointIds().SetNumberOfIds(8)
for i in range(8):
    qp_cell.GetPointIds().SetId(i, i)
qp_grid = vtkUnstructuredGrid()
qp_grid.SetPoints(qp_cell.GetPoints())
qp_grid.InsertNextCell(qp_cell.GetCellType(), qp_cell.GetPointIds())
qp_bounds = qp_grid.GetBounds()
qp_new_pts = vtkPoints()
qp_new_pts.SetNumberOfPoints(qp_grid.GetNumberOfPoints())
for i in range(qp_grid.GetNumberOfPoints()):
    px, py, pz = qp_grid.GetPoint(i)
    qp_new_pts.SetPoint(i, px - (qp_bounds[0] + qp_bounds[1]) / 2.0,
                         py - (qp_bounds[2] + qp_bounds[3]) / 2.0,
                         pz - (qp_bounds[4] + qp_bounds[5]) / 2.0)
qp_grid.SetPoints(qp_new_pts)

# Cell 4: Quadratic Tetra (surface, 3D)
qtet_cell = vtkQuadraticTetra()
qtet_pc = qtet_cell.GetParametricCoords()
for i in range(qtet_cell.GetNumberOfPoints()):
    qtet_cell.GetPointIds().SetId(i, i)
    qtet_cell.GetPoints().SetPoint(i, qtet_pc[3 * i], qtet_pc[3 * i + 1], qtet_pc[3 * i + 2])
qtet_grid = vtkUnstructuredGrid()
qtet_grid.SetPoints(qtet_cell.GetPoints())
qtet_grid.InsertNextCell(qtet_cell.GetCellType(), qtet_cell.GetPointIds())
qtet_rot = vtkTransform()
qtet_rot.RotateX(-20)
qtet_rot.RotateY(20)
qtet_rtf = vtkTransformFilter()
qtet_rtf.SetTransform(qtet_rot)
qtet_rtf.SetInputData(qtet_grid)
qtet_rtf.Update()
qtet_grid.SetPoints(qtet_rtf.GetOutput().GetPoints())
qtet_bounds = qtet_grid.GetBounds()
qtet_new_pts = vtkPoints()
qtet_new_pts.SetNumberOfPoints(qtet_grid.GetNumberOfPoints())
for i in range(qtet_grid.GetNumberOfPoints()):
    px, py, pz = qtet_grid.GetPoint(i)
    qtet_new_pts.SetPoint(i, px - (qtet_bounds[0] + qtet_bounds[1]) / 2.0,
                           py - (qtet_bounds[2] + qtet_bounds[3]) / 2.0,
                           pz - (qtet_bounds[4] + qtet_bounds[5]) / 2.0)
qtet_grid.SetPoints(qtet_new_pts)

# Cell 5: Quadratic Hexahedron (surface, 3D)
qhex_cell = vtkQuadraticHexahedron()
qhex_pc = qhex_cell.GetParametricCoords()
for i in range(qhex_cell.GetNumberOfPoints()):
    qhex_cell.GetPointIds().SetId(i, i)
    qhex_cell.GetPoints().SetPoint(i, qhex_pc[3 * i], qhex_pc[3 * i + 1], qhex_pc[3 * i + 2])
qhex_grid = vtkUnstructuredGrid()
qhex_grid.SetPoints(qhex_cell.GetPoints())
qhex_grid.InsertNextCell(qhex_cell.GetCellType(), qhex_cell.GetPointIds())
qhex_rot = vtkTransform()
qhex_rot.RotateX(-20)
qhex_rot.RotateY(20)
qhex_rtf = vtkTransformFilter()
qhex_rtf.SetTransform(qhex_rot)
qhex_rtf.SetInputData(qhex_grid)
qhex_rtf.Update()
qhex_grid.SetPoints(qhex_rtf.GetOutput().GetPoints())
qhex_bounds = qhex_grid.GetBounds()
qhex_new_pts = vtkPoints()
qhex_new_pts.SetNumberOfPoints(qhex_grid.GetNumberOfPoints())
for i in range(qhex_grid.GetNumberOfPoints()):
    px, py, pz = qhex_grid.GetPoint(i)
    qhex_new_pts.SetPoint(i, px - (qhex_bounds[0] + qhex_bounds[1]) / 2.0,
                           py - (qhex_bounds[2] + qhex_bounds[3]) / 2.0,
                           pz - (qhex_bounds[4] + qhex_bounds[5]) / 2.0)
qhex_grid.SetPoints(qhex_new_pts)

# Cell 6: Quadratic Wedge (surface, 3D)
qw_cell = vtkQuadraticWedge()
qw_pc = qw_cell.GetParametricCoords()
for i in range(qw_cell.GetNumberOfPoints()):
    qw_cell.GetPointIds().SetId(i, i)
    qw_cell.GetPoints().SetPoint(i, qw_pc[3 * i], qw_pc[3 * i + 1], qw_pc[3 * i + 2])
qw_grid = vtkUnstructuredGrid()
qw_grid.SetPoints(qw_cell.GetPoints())
qw_grid.InsertNextCell(qw_cell.GetCellType(), qw_cell.GetPointIds())
qw_rot = vtkTransform()
qw_rot.RotateX(-20)
qw_rot.RotateY(20)
qw_rtf = vtkTransformFilter()
qw_rtf.SetTransform(qw_rot)
qw_rtf.SetInputData(qw_grid)
qw_rtf.Update()
qw_grid.SetPoints(qw_rtf.GetOutput().GetPoints())
qw_bounds = qw_grid.GetBounds()
qw_new_pts = vtkPoints()
qw_new_pts.SetNumberOfPoints(qw_grid.GetNumberOfPoints())
for i in range(qw_grid.GetNumberOfPoints()):
    px, py, pz = qw_grid.GetPoint(i)
    qw_new_pts.SetPoint(i, px - (qw_bounds[0] + qw_bounds[1]) / 2.0,
                         py - (qw_bounds[2] + qw_bounds[3]) / 2.0,
                         pz - (qw_bounds[4] + qw_bounds[5]) / 2.0)
qw_grid.SetPoints(qw_new_pts)

# Cell 7: Quadratic Pyramid (surface, 3D, pre-rotate X -90)
qpyr_cell = vtkQuadraticPyramid()
qpyr_pc = qpyr_cell.GetParametricCoords()
for i in range(qpyr_cell.GetNumberOfPoints()):
    qpyr_cell.GetPointIds().SetId(i, i)
    qpyr_cell.GetPoints().SetPoint(i, qpyr_pc[3 * i], qpyr_pc[3 * i + 1], qpyr_pc[3 * i + 2])
qpyr_grid = vtkUnstructuredGrid()
qpyr_grid.SetPoints(qpyr_cell.GetPoints())
qpyr_grid.InsertNextCell(qpyr_cell.GetCellType(), qpyr_cell.GetPointIds())
qpyr_pre_rot = vtkTransform()
qpyr_pre_rot.RotateX(-90)
qpyr_pre_rtf = vtkTransformFilter()
qpyr_pre_rtf.SetTransform(qpyr_pre_rot)
qpyr_pre_rtf.SetInputData(qpyr_grid)
qpyr_pre_rtf.Update()
qpyr_grid.SetPoints(qpyr_pre_rtf.GetOutput().GetPoints())
qpyr_rot = vtkTransform()
qpyr_rot.RotateX(-20)
qpyr_rot.RotateY(20)
qpyr_rtf = vtkTransformFilter()
qpyr_rtf.SetTransform(qpyr_rot)
qpyr_rtf.SetInputData(qpyr_grid)
qpyr_rtf.Update()
qpyr_grid.SetPoints(qpyr_rtf.GetOutput().GetPoints())
qpyr_bounds = qpyr_grid.GetBounds()
qpyr_new_pts = vtkPoints()
qpyr_new_pts.SetNumberOfPoints(qpyr_grid.GetNumberOfPoints())
for i in range(qpyr_grid.GetNumberOfPoints()):
    px, py, pz = qpyr_grid.GetPoint(i)
    qpyr_new_pts.SetPoint(i, px - (qpyr_bounds[0] + qpyr_bounds[1]) / 2.0,
                           py - (qpyr_bounds[2] + qpyr_bounds[3]) / 2.0,
                           pz - (qpyr_bounds[4] + qpyr_bounds[5]) / 2.0)
qpyr_grid.SetPoints(qpyr_new_pts)

# Cell 8: BiQuadratic Quad (surface, 2D)
bqq_cell = vtkBiQuadraticQuad()
bqq_pc = bqq_cell.GetParametricCoords()
for i in range(bqq_cell.GetNumberOfPoints()):
    bqq_cell.GetPointIds().SetId(i, i)
    bqq_cell.GetPoints().SetPoint(i, bqq_pc[3 * i], bqq_pc[3 * i + 1], bqq_pc[3 * i + 2])
bqq_grid = vtkUnstructuredGrid()
bqq_grid.SetPoints(bqq_cell.GetPoints())
bqq_grid.InsertNextCell(bqq_cell.GetCellType(), bqq_cell.GetPointIds())
bqq_bounds = bqq_grid.GetBounds()
bqq_new_pts = vtkPoints()
bqq_new_pts.SetNumberOfPoints(bqq_grid.GetNumberOfPoints())
for i in range(bqq_grid.GetNumberOfPoints()):
    px, py, pz = bqq_grid.GetPoint(i)
    bqq_new_pts.SetPoint(i, px - (bqq_bounds[0] + bqq_bounds[1]) / 2.0,
                          py - (bqq_bounds[2] + bqq_bounds[3]) / 2.0,
                          pz - (bqq_bounds[4] + bqq_bounds[5]) / 2.0)
bqq_grid.SetPoints(bqq_new_pts)

# Cell 9: TriQuadratic Hexahedron (surface, 3D)
tqh_cell = vtkTriQuadraticHexahedron()
tqh_pc = tqh_cell.GetParametricCoords()
for i in range(tqh_cell.GetNumberOfPoints()):
    tqh_cell.GetPointIds().SetId(i, i)
    tqh_cell.GetPoints().SetPoint(i, tqh_pc[3 * i], tqh_pc[3 * i + 1], tqh_pc[3 * i + 2])
tqh_grid = vtkUnstructuredGrid()
tqh_grid.SetPoints(tqh_cell.GetPoints())
tqh_grid.InsertNextCell(tqh_cell.GetCellType(), tqh_cell.GetPointIds())
tqh_rot = vtkTransform()
tqh_rot.RotateX(-20)
tqh_rot.RotateY(20)
tqh_rtf = vtkTransformFilter()
tqh_rtf.SetTransform(tqh_rot)
tqh_rtf.SetInputData(tqh_grid)
tqh_rtf.Update()
tqh_grid.SetPoints(tqh_rtf.GetOutput().GetPoints())
tqh_bounds = tqh_grid.GetBounds()
tqh_new_pts = vtkPoints()
tqh_new_pts.SetNumberOfPoints(tqh_grid.GetNumberOfPoints())
for i in range(tqh_grid.GetNumberOfPoints()):
    px, py, pz = tqh_grid.GetPoint(i)
    tqh_new_pts.SetPoint(i, px - (tqh_bounds[0] + tqh_bounds[1]) / 2.0,
                          py - (tqh_bounds[2] + tqh_bounds[3]) / 2.0,
                          pz - (tqh_bounds[4] + tqh_bounds[5]) / 2.0)
tqh_grid.SetPoints(tqh_new_pts)

# Cell 10: Quadratic Linear Quad (surface, 2D)
qlq_cell = vtkQuadraticLinearQuad()
qlq_pc = qlq_cell.GetParametricCoords()
for i in range(qlq_cell.GetNumberOfPoints()):
    qlq_cell.GetPointIds().SetId(i, i)
    qlq_cell.GetPoints().SetPoint(i, qlq_pc[3 * i], qlq_pc[3 * i + 1], qlq_pc[3 * i + 2])
qlq_grid = vtkUnstructuredGrid()
qlq_grid.SetPoints(qlq_cell.GetPoints())
qlq_grid.InsertNextCell(qlq_cell.GetCellType(), qlq_cell.GetPointIds())
qlq_bounds = qlq_grid.GetBounds()
qlq_new_pts = vtkPoints()
qlq_new_pts.SetNumberOfPoints(qlq_grid.GetNumberOfPoints())
for i in range(qlq_grid.GetNumberOfPoints()):
    px, py, pz = qlq_grid.GetPoint(i)
    qlq_new_pts.SetPoint(i, px - (qlq_bounds[0] + qlq_bounds[1]) / 2.0,
                          py - (qlq_bounds[2] + qlq_bounds[3]) / 2.0,
                          pz - (qlq_bounds[4] + qlq_bounds[5]) / 2.0)
qlq_grid.SetPoints(qlq_new_pts)

# Cell 11: Quadratic Linear Wedge (surface, 3D)
qlw_cell = vtkQuadraticLinearWedge()
qlw_pc = qlw_cell.GetParametricCoords()
for i in range(qlw_cell.GetNumberOfPoints()):
    qlw_cell.GetPointIds().SetId(i, i)
    qlw_cell.GetPoints().SetPoint(i, qlw_pc[3 * i], qlw_pc[3 * i + 1], qlw_pc[3 * i + 2])
qlw_grid = vtkUnstructuredGrid()
qlw_grid.SetPoints(qlw_cell.GetPoints())
qlw_grid.InsertNextCell(qlw_cell.GetCellType(), qlw_cell.GetPointIds())
qlw_rot = vtkTransform()
qlw_rot.RotateX(-20)
qlw_rot.RotateY(20)
qlw_rtf = vtkTransformFilter()
qlw_rtf.SetTransform(qlw_rot)
qlw_rtf.SetInputData(qlw_grid)
qlw_rtf.Update()
qlw_grid.SetPoints(qlw_rtf.GetOutput().GetPoints())
qlw_bounds = qlw_grid.GetBounds()
qlw_new_pts = vtkPoints()
qlw_new_pts.SetNumberOfPoints(qlw_grid.GetNumberOfPoints())
for i in range(qlw_grid.GetNumberOfPoints()):
    px, py, pz = qlw_grid.GetPoint(i)
    qlw_new_pts.SetPoint(i, px - (qlw_bounds[0] + qlw_bounds[1]) / 2.0,
                          py - (qlw_bounds[2] + qlw_bounds[3]) / 2.0,
                          pz - (qlw_bounds[4] + qlw_bounds[5]) / 2.0)
qlw_grid.SetPoints(qlw_new_pts)

# Cell 12: BiQuadratic Quadratic Wedge (surface, 3D)
bqqw_cell = vtkBiQuadraticQuadraticWedge()
bqqw_pc = bqqw_cell.GetParametricCoords()
for i in range(bqqw_cell.GetNumberOfPoints()):
    bqqw_cell.GetPointIds().SetId(i, i)
    bqqw_cell.GetPoints().SetPoint(i, bqqw_pc[3 * i], bqqw_pc[3 * i + 1], bqqw_pc[3 * i + 2])
bqqw_grid = vtkUnstructuredGrid()
bqqw_grid.SetPoints(bqqw_cell.GetPoints())
bqqw_grid.InsertNextCell(bqqw_cell.GetCellType(), bqqw_cell.GetPointIds())
bqqw_rot = vtkTransform()
bqqw_rot.RotateX(-20)
bqqw_rot.RotateY(20)
bqqw_rtf = vtkTransformFilter()
bqqw_rtf.SetTransform(bqqw_rot)
bqqw_rtf.SetInputData(bqqw_grid)
bqqw_rtf.Update()
bqqw_grid.SetPoints(bqqw_rtf.GetOutput().GetPoints())
bqqw_bounds = bqqw_grid.GetBounds()
bqqw_new_pts = vtkPoints()
bqqw_new_pts.SetNumberOfPoints(bqqw_grid.GetNumberOfPoints())
for i in range(bqqw_grid.GetNumberOfPoints()):
    px, py, pz = bqqw_grid.GetPoint(i)
    bqqw_new_pts.SetPoint(i, px - (bqqw_bounds[0] + bqqw_bounds[1]) / 2.0,
                           py - (bqqw_bounds[2] + bqqw_bounds[3]) / 2.0,
                           pz - (bqqw_bounds[4] + bqqw_bounds[5]) / 2.0)
bqqw_grid.SetPoints(bqqw_new_pts)

# Cell 13: BiQuadratic Quadratic Hexahedron (surface, 3D)
bqqh_cell = vtkBiQuadraticQuadraticHexahedron()
bqqh_pc = bqqh_cell.GetParametricCoords()
for i in range(bqqh_cell.GetNumberOfPoints()):
    bqqh_cell.GetPointIds().SetId(i, i)
    bqqh_cell.GetPoints().SetPoint(i, bqqh_pc[3 * i], bqqh_pc[3 * i + 1], bqqh_pc[3 * i + 2])
bqqh_grid = vtkUnstructuredGrid()
bqqh_grid.SetPoints(bqqh_cell.GetPoints())
bqqh_grid.InsertNextCell(bqqh_cell.GetCellType(), bqqh_cell.GetPointIds())
bqqh_rot = vtkTransform()
bqqh_rot.RotateX(-20)
bqqh_rot.RotateY(20)
bqqh_rtf = vtkTransformFilter()
bqqh_rtf.SetTransform(bqqh_rot)
bqqh_rtf.SetInputData(bqqh_grid)
bqqh_rtf.Update()
bqqh_grid.SetPoints(bqqh_rtf.GetOutput().GetPoints())
bqqh_bounds = bqqh_grid.GetBounds()
bqqh_new_pts = vtkPoints()
bqqh_new_pts.SetNumberOfPoints(bqqh_grid.GetNumberOfPoints())
for i in range(bqqh_grid.GetNumberOfPoints()):
    px, py, pz = bqqh_grid.GetPoint(i)
    bqqh_new_pts.SetPoint(i, px - (bqqh_bounds[0] + bqqh_bounds[1]) / 2.0,
                           py - (bqqh_bounds[2] + bqqh_bounds[3]) / 2.0,
                           pz - (bqqh_bounds[4] + bqqh_bounds[5]) / 2.0)
bqqh_grid.SetPoints(bqqh_new_pts)

# Cell 14: BiQuadratic Triangle (surface, 2D)
bqt_cell = vtkBiQuadraticTriangle()
bqt_pc = bqt_cell.GetParametricCoords()
for i in range(bqt_cell.GetNumberOfPoints()):
    bqt_cell.GetPointIds().SetId(i, i)
    bqt_cell.GetPoints().SetPoint(i, bqt_pc[3 * i], bqt_pc[3 * i + 1], bqt_pc[3 * i + 2])
bqt_grid = vtkUnstructuredGrid()
bqt_grid.SetPoints(bqt_cell.GetPoints())
bqt_grid.InsertNextCell(bqt_cell.GetCellType(), bqt_cell.GetPointIds())
bqt_bounds = bqt_grid.GetBounds()
bqt_new_pts = vtkPoints()
bqt_new_pts.SetNumberOfPoints(bqt_grid.GetNumberOfPoints())
for i in range(bqt_grid.GetNumberOfPoints()):
    px, py, pz = bqt_grid.GetPoint(i)
    bqt_new_pts.SetPoint(i, px - (bqt_bounds[0] + bqt_bounds[1]) / 2.0,
                          py - (bqt_bounds[2] + bqt_bounds[3]) / 2.0,
                          pz - (bqt_bounds[4] + bqt_bounds[5]) / 2.0)
bqt_grid.SetPoints(bqt_new_pts)

# Cell 15: Cubic Line (wireframe, 2D)
cl_cell = vtkCubicLine()
cl_pc = cl_cell.GetParametricCoords()
for i in range(cl_cell.GetNumberOfPoints()):
    cl_cell.GetPointIds().SetId(i, i)
    cl_cell.GetPoints().SetPoint(i, cl_pc[3 * i], cl_pc[3 * i + 1], cl_pc[3 * i + 2])
cl_grid = vtkUnstructuredGrid()
cl_grid.SetPoints(cl_cell.GetPoints())
cl_grid.InsertNextCell(cl_cell.GetCellType(), cl_cell.GetPointIds())
cl_bounds = cl_grid.GetBounds()
cl_new_pts = vtkPoints()
cl_new_pts.SetNumberOfPoints(cl_grid.GetNumberOfPoints())
for i in range(cl_grid.GetNumberOfPoints()):
    px, py, pz = cl_grid.GetPoint(i)
    cl_new_pts.SetPoint(i, px - (cl_bounds[0] + cl_bounds[1]) / 2.0,
                         py - (cl_bounds[2] + cl_bounds[3]) / 2.0,
                         pz - (cl_bounds[4] + cl_bounds[5]) / 2.0)
cl_grid.SetPoints(cl_new_pts)

# Plinth sources for 3D cells (4, 5, 6, 7, 9, 11, 12, 13)
qtet_plinth_bounds = qtet_grid.GetBounds()
qtet_plinth_dims = (qtet_plinth_bounds[1] - qtet_plinth_bounds[0],
                    qtet_plinth_bounds[3] - qtet_plinth_bounds[2],
                    qtet_plinth_bounds[5] - qtet_plinth_bounds[4])
qtet_plinth_thick = qtet_plinth_dims[2] * 0.01
qtet_plinth_source = vtkCubeSource()
qtet_plinth_source.SetCenter((qtet_plinth_bounds[1] + qtet_plinth_bounds[0]) / 2.0,
                              qtet_plinth_bounds[2] - qtet_plinth_thick / 2.0 - 0.05,
                              (qtet_plinth_bounds[5] + qtet_plinth_bounds[4]) / 2.0)
qtet_plinth_source.SetXLength(qtet_plinth_dims[0] + qtet_plinth_dims[0] * 0.5)
qtet_plinth_source.SetYLength(qtet_plinth_thick)
qtet_plinth_source.SetZLength(qtet_plinth_dims[2] + qtet_plinth_dims[2] * 0.5)

qhex_plinth_bounds = qhex_grid.GetBounds()
qhex_plinth_dims = (qhex_plinth_bounds[1] - qhex_plinth_bounds[0],
                    qhex_plinth_bounds[3] - qhex_plinth_bounds[2],
                    qhex_plinth_bounds[5] - qhex_plinth_bounds[4])
qhex_plinth_thick = qhex_plinth_dims[2] * 0.01
qhex_plinth_source = vtkCubeSource()
qhex_plinth_source.SetCenter((qhex_plinth_bounds[1] + qhex_plinth_bounds[0]) / 2.0,
                              qhex_plinth_bounds[2] - qhex_plinth_thick / 2.0 - 0.05,
                              (qhex_plinth_bounds[5] + qhex_plinth_bounds[4]) / 2.0)
qhex_plinth_source.SetXLength(qhex_plinth_dims[0] + qhex_plinth_dims[0] * 0.5)
qhex_plinth_source.SetYLength(qhex_plinth_thick)
qhex_plinth_source.SetZLength(qhex_plinth_dims[2] + qhex_plinth_dims[2] * 0.5)

qw_plinth_bounds = qw_grid.GetBounds()
qw_plinth_dims = (qw_plinth_bounds[1] - qw_plinth_bounds[0],
                  qw_plinth_bounds[3] - qw_plinth_bounds[2],
                  qw_plinth_bounds[5] - qw_plinth_bounds[4])
qw_plinth_thick = qw_plinth_dims[2] * 0.01
qw_plinth_source = vtkCubeSource()
qw_plinth_source.SetCenter((qw_plinth_bounds[1] + qw_plinth_bounds[0]) / 2.0,
                            qw_plinth_bounds[2] - qw_plinth_thick / 2.0 - 0.05,
                            (qw_plinth_bounds[5] + qw_plinth_bounds[4]) / 2.0)
qw_plinth_source.SetXLength(qw_plinth_dims[0] + qw_plinth_dims[0] * 0.5)
qw_plinth_source.SetYLength(qw_plinth_thick)
qw_plinth_source.SetZLength(qw_plinth_dims[2] + qw_plinth_dims[2] * 0.5)

qpyr_plinth_bounds = qpyr_grid.GetBounds()
qpyr_plinth_dims = (qpyr_plinth_bounds[1] - qpyr_plinth_bounds[0],
                    qpyr_plinth_bounds[3] - qpyr_plinth_bounds[2],
                    qpyr_plinth_bounds[5] - qpyr_plinth_bounds[4])
qpyr_plinth_thick = qpyr_plinth_dims[2] * 0.01
qpyr_plinth_source = vtkCubeSource()
qpyr_plinth_source.SetCenter((qpyr_plinth_bounds[1] + qpyr_plinth_bounds[0]) / 2.0,
                              qpyr_plinth_bounds[2] - qpyr_plinth_thick / 2.0 - 0.05,
                              (qpyr_plinth_bounds[5] + qpyr_plinth_bounds[4]) / 2.0)
qpyr_plinth_source.SetXLength(qpyr_plinth_dims[0] + qpyr_plinth_dims[0] * 0.5)
qpyr_plinth_source.SetYLength(qpyr_plinth_thick)
qpyr_plinth_source.SetZLength(qpyr_plinth_dims[2] + qpyr_plinth_dims[2] * 0.5)

tqh_plinth_bounds = tqh_grid.GetBounds()
tqh_plinth_dims = (tqh_plinth_bounds[1] - tqh_plinth_bounds[0],
                   tqh_plinth_bounds[3] - tqh_plinth_bounds[2],
                   tqh_plinth_bounds[5] - tqh_plinth_bounds[4])
tqh_plinth_thick = tqh_plinth_dims[2] * 0.01
tqh_plinth_source = vtkCubeSource()
tqh_plinth_source.SetCenter((tqh_plinth_bounds[1] + tqh_plinth_bounds[0]) / 2.0,
                             tqh_plinth_bounds[2] - tqh_plinth_thick / 2.0 - 0.05,
                             (tqh_plinth_bounds[5] + tqh_plinth_bounds[4]) / 2.0)
tqh_plinth_source.SetXLength(tqh_plinth_dims[0] + tqh_plinth_dims[0] * 0.5)
tqh_plinth_source.SetYLength(tqh_plinth_thick)
tqh_plinth_source.SetZLength(tqh_plinth_dims[2] + tqh_plinth_dims[2] * 0.5)

qlw_plinth_bounds = qlw_grid.GetBounds()
qlw_plinth_dims = (qlw_plinth_bounds[1] - qlw_plinth_bounds[0],
                   qlw_plinth_bounds[3] - qlw_plinth_bounds[2],
                   qlw_plinth_bounds[5] - qlw_plinth_bounds[4])
qlw_plinth_thick = qlw_plinth_dims[2] * 0.01
qlw_plinth_source = vtkCubeSource()
qlw_plinth_source.SetCenter((qlw_plinth_bounds[1] + qlw_plinth_bounds[0]) / 2.0,
                             qlw_plinth_bounds[2] - qlw_plinth_thick / 2.0 - 0.05,
                             (qlw_plinth_bounds[5] + qlw_plinth_bounds[4]) / 2.0)
qlw_plinth_source.SetXLength(qlw_plinth_dims[0] + qlw_plinth_dims[0] * 0.5)
qlw_plinth_source.SetYLength(qlw_plinth_thick)
qlw_plinth_source.SetZLength(qlw_plinth_dims[2] + qlw_plinth_dims[2] * 0.5)

bqqw_plinth_bounds = bqqw_grid.GetBounds()
bqqw_plinth_dims = (bqqw_plinth_bounds[1] - bqqw_plinth_bounds[0],
                    bqqw_plinth_bounds[3] - bqqw_plinth_bounds[2],
                    bqqw_plinth_bounds[5] - bqqw_plinth_bounds[4])
bqqw_plinth_thick = bqqw_plinth_dims[2] * 0.01
bqqw_plinth_source = vtkCubeSource()
bqqw_plinth_source.SetCenter((bqqw_plinth_bounds[1] + bqqw_plinth_bounds[0]) / 2.0,
                              bqqw_plinth_bounds[2] - bqqw_plinth_thick / 2.0 - 0.05,
                              (bqqw_plinth_bounds[5] + bqqw_plinth_bounds[4]) / 2.0)
bqqw_plinth_source.SetXLength(bqqw_plinth_dims[0] + bqqw_plinth_dims[0] * 0.5)
bqqw_plinth_source.SetYLength(bqqw_plinth_thick)
bqqw_plinth_source.SetZLength(bqqw_plinth_dims[2] + bqqw_plinth_dims[2] * 0.5)

bqqh_plinth_bounds = bqqh_grid.GetBounds()
bqqh_plinth_dims = (bqqh_plinth_bounds[1] - bqqh_plinth_bounds[0],
                    bqqh_plinth_bounds[3] - bqqh_plinth_bounds[2],
                    bqqh_plinth_bounds[5] - bqqh_plinth_bounds[4])
bqqh_plinth_thick = bqqh_plinth_dims[2] * 0.01
bqqh_plinth_source = vtkCubeSource()
bqqh_plinth_source.SetCenter((bqqh_plinth_bounds[1] + bqqh_plinth_bounds[0]) / 2.0,
                              bqqh_plinth_bounds[2] - bqqh_plinth_thick / 2.0 - 0.05,
                              (bqqh_plinth_bounds[5] + bqqh_plinth_bounds[4]) / 2.0)
bqqh_plinth_source.SetXLength(bqqh_plinth_dims[0] + bqqh_plinth_dims[0] * 0.5)
bqqh_plinth_source.SetYLength(bqqh_plinth_thick)
bqqh_plinth_source.SetZLength(bqqh_plinth_dims[2] + bqqh_plinth_dims[2] * 0.5)

# ===========================================================================
# Mappers and Actors
# ===========================================================================

# Cell 0: Quadratic Edge (wireframe, 2D)
qe_mapper = vtkDataSetMapper()
qe_mapper.SetInputData(qe_grid)
qe_property = vtkProperty()
qe_property.SetRepresentationToWireframe()
qe_property.SetLineWidth(2)
qe_property.SetOpacity(1)
qe_property.SetColor(0.0, 0.0, 0.0)
qe_actor = vtkActor()
qe_actor.SetMapper(qe_mapper)
qe_actor.SetProperty(qe_property)
qe_label_text_property = vtkTextProperty()
qe_label_text_property.BoldOn()
qe_label_text_property.ShadowOn()
qe_label_text_property.SetJustificationToCentered()
qe_label_text_property.SetColor(deep_pink_rgb)
qe_label_text_property.SetFontSize(14)
qe_label_mapper = vtkLabeledDataMapper()
qe_label_mapper.SetInputData(qe_grid)
qe_label_mapper.SetLabelTextProperty(qe_label_text_property)
qe_label_actor = vtkActor2D()
qe_label_actor.SetMapper(qe_label_mapper)
qe_glyph_mapper = vtkGlyph3DMapper()
qe_glyph_mapper.SetInputData(qe_grid)
qe_glyph_mapper.SetSourceConnection(sphere_source.GetOutputPort())
qe_glyph_mapper.ScalingOn()
qe_glyph_mapper.ScalarVisibilityOff()
qe_glyph_property = vtkProperty()
qe_glyph_property.SetAmbientColor(gold_rgb)
qe_glyph_property.SetDiffuseColor(yellow_rgb)
qe_glyph_property.SetSpecularColor(1.0, 1.0, 1.0)
qe_glyph_property.SetSpecular(0.5)
qe_glyph_property.SetDiffuse(0.7)
qe_glyph_property.SetAmbient(0.5)
qe_glyph_property.SetSpecularPower(20.0)
qe_glyph_property.SetOpacity(1.0)
qe_glyph_actor = vtkActor()
qe_glyph_actor.SetMapper(qe_glyph_mapper)
qe_glyph_actor.SetProperty(qe_glyph_property)
qe_text_actor = vtkTextActor()
qe_text_actor.SetInput("Quadratic Edge")
qe_text_actor.GetTextProperty().SetFontSize(12)
qe_text_actor.GetTextProperty().SetColor(0.0, 0.0, 0.0)
qe_text_actor.GetTextProperty().SetJustificationToCentered()
qe_text_actor.GetPositionCoordinate().SetCoordinateSystemToNormalizedViewport()
qe_text_actor.SetPosition(0.5, 0.01)

# Cell 1: Quadratic Triangle (surface, 2D)
qt_mapper = vtkDataSetMapper()
qt_mapper.SetInputData(qt_grid)
qt_property = vtkProperty()
qt_property.SetAmbientColor(dark_salmon_rgb)
qt_property.SetDiffuseColor(seashell_rgb)
qt_property.SetSpecularColor(1.0, 1.0, 1.0)
qt_property.SetSpecular(0.5)
qt_property.SetDiffuse(0.7)
qt_property.SetAmbient(0.5)
qt_property.SetSpecularPower(20.0)
qt_property.SetOpacity(0.9)
qt_property.EdgeVisibilityOn()
qt_property.SetLineWidth(3)
qt_actor = vtkActor()
qt_actor.SetMapper(qt_mapper)
qt_actor.SetProperty(qt_property)
qt_label_text_property = vtkTextProperty()
qt_label_text_property.BoldOn()
qt_label_text_property.ShadowOn()
qt_label_text_property.SetJustificationToCentered()
qt_label_text_property.SetColor(deep_pink_rgb)
qt_label_text_property.SetFontSize(14)
qt_label_mapper = vtkLabeledDataMapper()
qt_label_mapper.SetInputData(qt_grid)
qt_label_mapper.SetLabelTextProperty(qt_label_text_property)
qt_label_actor = vtkActor2D()
qt_label_actor.SetMapper(qt_label_mapper)
qt_glyph_mapper = vtkGlyph3DMapper()
qt_glyph_mapper.SetInputData(qt_grid)
qt_glyph_mapper.SetSourceConnection(sphere_source.GetOutputPort())
qt_glyph_mapper.ScalingOn()
qt_glyph_mapper.ScalarVisibilityOff()
qt_glyph_property = vtkProperty()
qt_glyph_property.SetAmbientColor(gold_rgb)
qt_glyph_property.SetDiffuseColor(yellow_rgb)
qt_glyph_property.SetSpecularColor(1.0, 1.0, 1.0)
qt_glyph_property.SetSpecular(0.5)
qt_glyph_property.SetDiffuse(0.7)
qt_glyph_property.SetAmbient(0.5)
qt_glyph_property.SetSpecularPower(20.0)
qt_glyph_property.SetOpacity(1.0)
qt_glyph_actor = vtkActor()
qt_glyph_actor.SetMapper(qt_glyph_mapper)
qt_glyph_actor.SetProperty(qt_glyph_property)
qt_text_actor = vtkTextActor()
qt_text_actor.SetInput("Quadratic Triangle")
qt_text_actor.GetTextProperty().SetFontSize(12)
qt_text_actor.GetTextProperty().SetColor(0.0, 0.0, 0.0)
qt_text_actor.GetTextProperty().SetJustificationToCentered()
qt_text_actor.GetPositionCoordinate().SetCoordinateSystemToNormalizedViewport()
qt_text_actor.SetPosition(0.5, 0.01)

# Cell 2: Quadratic Quad (surface, 2D)
qq_mapper = vtkDataSetMapper()
qq_mapper.SetInputData(qq_grid)
qq_property = vtkProperty()
qq_property.SetAmbientColor(dark_salmon_rgb)
qq_property.SetDiffuseColor(seashell_rgb)
qq_property.SetSpecularColor(1.0, 1.0, 1.0)
qq_property.SetSpecular(0.5)
qq_property.SetDiffuse(0.7)
qq_property.SetAmbient(0.5)
qq_property.SetSpecularPower(20.0)
qq_property.SetOpacity(0.9)
qq_property.EdgeVisibilityOn()
qq_property.SetLineWidth(3)
qq_actor = vtkActor()
qq_actor.SetMapper(qq_mapper)
qq_actor.SetProperty(qq_property)
qq_label_text_property = vtkTextProperty()
qq_label_text_property.BoldOn()
qq_label_text_property.ShadowOn()
qq_label_text_property.SetJustificationToCentered()
qq_label_text_property.SetColor(deep_pink_rgb)
qq_label_text_property.SetFontSize(14)
qq_label_mapper = vtkLabeledDataMapper()
qq_label_mapper.SetInputData(qq_grid)
qq_label_mapper.SetLabelTextProperty(qq_label_text_property)
qq_label_actor = vtkActor2D()
qq_label_actor.SetMapper(qq_label_mapper)
qq_glyph_mapper = vtkGlyph3DMapper()
qq_glyph_mapper.SetInputData(qq_grid)
qq_glyph_mapper.SetSourceConnection(sphere_source.GetOutputPort())
qq_glyph_mapper.ScalingOn()
qq_glyph_mapper.ScalarVisibilityOff()
qq_glyph_property = vtkProperty()
qq_glyph_property.SetAmbientColor(gold_rgb)
qq_glyph_property.SetDiffuseColor(yellow_rgb)
qq_glyph_property.SetSpecularColor(1.0, 1.0, 1.0)
qq_glyph_property.SetSpecular(0.5)
qq_glyph_property.SetDiffuse(0.7)
qq_glyph_property.SetAmbient(0.5)
qq_glyph_property.SetSpecularPower(20.0)
qq_glyph_property.SetOpacity(1.0)
qq_glyph_actor = vtkActor()
qq_glyph_actor.SetMapper(qq_glyph_mapper)
qq_glyph_actor.SetProperty(qq_glyph_property)
qq_text_actor = vtkTextActor()
qq_text_actor.SetInput("Quadratic Quad")
qq_text_actor.GetTextProperty().SetFontSize(12)
qq_text_actor.GetTextProperty().SetColor(0.0, 0.0, 0.0)
qq_text_actor.GetTextProperty().SetJustificationToCentered()
qq_text_actor.GetPositionCoordinate().SetCoordinateSystemToNormalizedViewport()
qq_text_actor.SetPosition(0.5, 0.01)

# Cell 3: Quadratic Polygon (surface, 2D)
qp_mapper = vtkDataSetMapper()
qp_mapper.SetInputData(qp_grid)
qp_property = vtkProperty()
qp_property.SetAmbientColor(dark_salmon_rgb)
qp_property.SetDiffuseColor(seashell_rgb)
qp_property.SetSpecularColor(1.0, 1.0, 1.0)
qp_property.SetSpecular(0.5)
qp_property.SetDiffuse(0.7)
qp_property.SetAmbient(0.5)
qp_property.SetSpecularPower(20.0)
qp_property.SetOpacity(0.9)
qp_property.EdgeVisibilityOn()
qp_property.SetLineWidth(3)
qp_actor = vtkActor()
qp_actor.SetMapper(qp_mapper)
qp_actor.SetProperty(qp_property)
qp_label_text_property = vtkTextProperty()
qp_label_text_property.BoldOn()
qp_label_text_property.ShadowOn()
qp_label_text_property.SetJustificationToCentered()
qp_label_text_property.SetColor(deep_pink_rgb)
qp_label_text_property.SetFontSize(14)
qp_label_mapper = vtkLabeledDataMapper()
qp_label_mapper.SetInputData(qp_grid)
qp_label_mapper.SetLabelTextProperty(qp_label_text_property)
qp_label_actor = vtkActor2D()
qp_label_actor.SetMapper(qp_label_mapper)
qp_glyph_mapper = vtkGlyph3DMapper()
qp_glyph_mapper.SetInputData(qp_grid)
qp_glyph_mapper.SetSourceConnection(sphere_source.GetOutputPort())
qp_glyph_mapper.ScalingOn()
qp_glyph_mapper.ScalarVisibilityOff()
qp_glyph_property = vtkProperty()
qp_glyph_property.SetAmbientColor(gold_rgb)
qp_glyph_property.SetDiffuseColor(yellow_rgb)
qp_glyph_property.SetSpecularColor(1.0, 1.0, 1.0)
qp_glyph_property.SetSpecular(0.5)
qp_glyph_property.SetDiffuse(0.7)
qp_glyph_property.SetAmbient(0.5)
qp_glyph_property.SetSpecularPower(20.0)
qp_glyph_property.SetOpacity(1.0)
qp_glyph_actor = vtkActor()
qp_glyph_actor.SetMapper(qp_glyph_mapper)
qp_glyph_actor.SetProperty(qp_glyph_property)
qp_text_actor = vtkTextActor()
qp_text_actor.SetInput("Quadratic Polygon")
qp_text_actor.GetTextProperty().SetFontSize(12)
qp_text_actor.GetTextProperty().SetColor(0.0, 0.0, 0.0)
qp_text_actor.GetTextProperty().SetJustificationToCentered()
qp_text_actor.GetPositionCoordinate().SetCoordinateSystemToNormalizedViewport()
qp_text_actor.SetPosition(0.5, 0.01)

# Cell 4: Quadratic Tetra (surface, 3D)
qtet_mapper = vtkDataSetMapper()
qtet_mapper.SetInputData(qtet_grid)
qtet_property = vtkProperty()
qtet_property.SetAmbientColor(dark_salmon_rgb)
qtet_property.SetDiffuseColor(seashell_rgb)
qtet_property.SetSpecularColor(1.0, 1.0, 1.0)
qtet_property.SetSpecular(0.5)
qtet_property.SetDiffuse(0.7)
qtet_property.SetAmbient(0.5)
qtet_property.SetSpecularPower(20.0)
qtet_property.SetOpacity(0.9)
qtet_property.EdgeVisibilityOn()
qtet_property.SetLineWidth(3)
qtet_actor = vtkActor()
qtet_actor.SetMapper(qtet_mapper)
qtet_actor.SetProperty(qtet_property)
qtet_label_text_property = vtkTextProperty()
qtet_label_text_property.BoldOn()
qtet_label_text_property.ShadowOn()
qtet_label_text_property.SetJustificationToCentered()
qtet_label_text_property.SetColor(deep_pink_rgb)
qtet_label_text_property.SetFontSize(14)
qtet_label_mapper = vtkLabeledDataMapper()
qtet_label_mapper.SetInputData(qtet_grid)
qtet_label_mapper.SetLabelTextProperty(qtet_label_text_property)
qtet_label_actor = vtkActor2D()
qtet_label_actor.SetMapper(qtet_label_mapper)
qtet_glyph_mapper = vtkGlyph3DMapper()
qtet_glyph_mapper.SetInputData(qtet_grid)
qtet_glyph_mapper.SetSourceConnection(sphere_source.GetOutputPort())
qtet_glyph_mapper.ScalingOn()
qtet_glyph_mapper.ScalarVisibilityOff()
qtet_glyph_property = vtkProperty()
qtet_glyph_property.SetAmbientColor(gold_rgb)
qtet_glyph_property.SetDiffuseColor(yellow_rgb)
qtet_glyph_property.SetSpecularColor(1.0, 1.0, 1.0)
qtet_glyph_property.SetSpecular(0.5)
qtet_glyph_property.SetDiffuse(0.7)
qtet_glyph_property.SetAmbient(0.5)
qtet_glyph_property.SetSpecularPower(20.0)
qtet_glyph_property.SetOpacity(1.0)
qtet_glyph_actor = vtkActor()
qtet_glyph_actor.SetMapper(qtet_glyph_mapper)
qtet_glyph_actor.SetProperty(qtet_glyph_property)
qtet_plinth_mapper = vtkPolyDataMapper()
qtet_plinth_mapper.SetInputConnection(qtet_plinth_source.GetOutputPort())
qtet_plinth_property = vtkProperty()
qtet_plinth_property.SetAmbientColor(steel_blue_rgb)
qtet_plinth_property.SetDiffuseColor(light_steel_blue_rgb)
qtet_plinth_property.SetSpecularColor(1.0, 1.0, 1.0)
qtet_plinth_property.SetSpecular(0.5)
qtet_plinth_property.SetDiffuse(0.7)
qtet_plinth_property.SetAmbient(0.5)
qtet_plinth_property.SetSpecularPower(20.0)
qtet_plinth_property.SetOpacity(0.8)
qtet_plinth_property.EdgeVisibilityOn()
qtet_plinth_property.SetLineWidth(1)
qtet_plinth_actor = vtkActor()
qtet_plinth_actor.SetMapper(qtet_plinth_mapper)
qtet_plinth_actor.SetProperty(qtet_plinth_property)
qtet_text_actor = vtkTextActor()
qtet_text_actor.SetInput("Quadratic Tetra")
qtet_text_actor.GetTextProperty().SetFontSize(12)
qtet_text_actor.GetTextProperty().SetColor(0.0, 0.0, 0.0)
qtet_text_actor.GetTextProperty().SetJustificationToCentered()
qtet_text_actor.GetPositionCoordinate().SetCoordinateSystemToNormalizedViewport()
qtet_text_actor.SetPosition(0.5, 0.01)

# Cell 5: Quadratic Hexahedron (surface, 3D)
qhex_mapper = vtkDataSetMapper()
qhex_mapper.SetInputData(qhex_grid)
qhex_property = vtkProperty()
qhex_property.SetAmbientColor(dark_salmon_rgb)
qhex_property.SetDiffuseColor(seashell_rgb)
qhex_property.SetSpecularColor(1.0, 1.0, 1.0)
qhex_property.SetSpecular(0.5)
qhex_property.SetDiffuse(0.7)
qhex_property.SetAmbient(0.5)
qhex_property.SetSpecularPower(20.0)
qhex_property.SetOpacity(0.9)
qhex_property.EdgeVisibilityOn()
qhex_property.SetLineWidth(3)
qhex_actor = vtkActor()
qhex_actor.SetMapper(qhex_mapper)
qhex_actor.SetProperty(qhex_property)
qhex_label_text_property = vtkTextProperty()
qhex_label_text_property.BoldOn()
qhex_label_text_property.ShadowOn()
qhex_label_text_property.SetJustificationToCentered()
qhex_label_text_property.SetColor(deep_pink_rgb)
qhex_label_text_property.SetFontSize(14)
qhex_label_mapper = vtkLabeledDataMapper()
qhex_label_mapper.SetInputData(qhex_grid)
qhex_label_mapper.SetLabelTextProperty(qhex_label_text_property)
qhex_label_actor = vtkActor2D()
qhex_label_actor.SetMapper(qhex_label_mapper)
qhex_glyph_mapper = vtkGlyph3DMapper()
qhex_glyph_mapper.SetInputData(qhex_grid)
qhex_glyph_mapper.SetSourceConnection(sphere_source.GetOutputPort())
qhex_glyph_mapper.ScalingOn()
qhex_glyph_mapper.ScalarVisibilityOff()
qhex_glyph_property = vtkProperty()
qhex_glyph_property.SetAmbientColor(gold_rgb)
qhex_glyph_property.SetDiffuseColor(yellow_rgb)
qhex_glyph_property.SetSpecularColor(1.0, 1.0, 1.0)
qhex_glyph_property.SetSpecular(0.5)
qhex_glyph_property.SetDiffuse(0.7)
qhex_glyph_property.SetAmbient(0.5)
qhex_glyph_property.SetSpecularPower(20.0)
qhex_glyph_property.SetOpacity(1.0)
qhex_glyph_actor = vtkActor()
qhex_glyph_actor.SetMapper(qhex_glyph_mapper)
qhex_glyph_actor.SetProperty(qhex_glyph_property)
qhex_plinth_mapper = vtkPolyDataMapper()
qhex_plinth_mapper.SetInputConnection(qhex_plinth_source.GetOutputPort())
qhex_plinth_property = vtkProperty()
qhex_plinth_property.SetAmbientColor(steel_blue_rgb)
qhex_plinth_property.SetDiffuseColor(light_steel_blue_rgb)
qhex_plinth_property.SetSpecularColor(1.0, 1.0, 1.0)
qhex_plinth_property.SetSpecular(0.5)
qhex_plinth_property.SetDiffuse(0.7)
qhex_plinth_property.SetAmbient(0.5)
qhex_plinth_property.SetSpecularPower(20.0)
qhex_plinth_property.SetOpacity(0.8)
qhex_plinth_property.EdgeVisibilityOn()
qhex_plinth_property.SetLineWidth(1)
qhex_plinth_actor = vtkActor()
qhex_plinth_actor.SetMapper(qhex_plinth_mapper)
qhex_plinth_actor.SetProperty(qhex_plinth_property)
qhex_text_actor = vtkTextActor()
qhex_text_actor.SetInput("Quadratic Hexahedron")
qhex_text_actor.GetTextProperty().SetFontSize(12)
qhex_text_actor.GetTextProperty().SetColor(0.0, 0.0, 0.0)
qhex_text_actor.GetTextProperty().SetJustificationToCentered()
qhex_text_actor.GetPositionCoordinate().SetCoordinateSystemToNormalizedViewport()
qhex_text_actor.SetPosition(0.5, 0.01)

# Cell 6: Quadratic Wedge (surface, 3D)
qw_mapper = vtkDataSetMapper()
qw_mapper.SetInputData(qw_grid)
qw_property = vtkProperty()
qw_property.SetAmbientColor(dark_salmon_rgb)
qw_property.SetDiffuseColor(seashell_rgb)
qw_property.SetSpecularColor(1.0, 1.0, 1.0)
qw_property.SetSpecular(0.5)
qw_property.SetDiffuse(0.7)
qw_property.SetAmbient(0.5)
qw_property.SetSpecularPower(20.0)
qw_property.SetOpacity(0.9)
qw_property.EdgeVisibilityOn()
qw_property.SetLineWidth(3)
qw_actor = vtkActor()
qw_actor.SetMapper(qw_mapper)
qw_actor.SetProperty(qw_property)
qw_label_text_property = vtkTextProperty()
qw_label_text_property.BoldOn()
qw_label_text_property.ShadowOn()
qw_label_text_property.SetJustificationToCentered()
qw_label_text_property.SetColor(deep_pink_rgb)
qw_label_text_property.SetFontSize(14)
qw_label_mapper = vtkLabeledDataMapper()
qw_label_mapper.SetInputData(qw_grid)
qw_label_mapper.SetLabelTextProperty(qw_label_text_property)
qw_label_actor = vtkActor2D()
qw_label_actor.SetMapper(qw_label_mapper)
qw_glyph_mapper = vtkGlyph3DMapper()
qw_glyph_mapper.SetInputData(qw_grid)
qw_glyph_mapper.SetSourceConnection(sphere_source.GetOutputPort())
qw_glyph_mapper.ScalingOn()
qw_glyph_mapper.ScalarVisibilityOff()
qw_glyph_property = vtkProperty()
qw_glyph_property.SetAmbientColor(gold_rgb)
qw_glyph_property.SetDiffuseColor(yellow_rgb)
qw_glyph_property.SetSpecularColor(1.0, 1.0, 1.0)
qw_glyph_property.SetSpecular(0.5)
qw_glyph_property.SetDiffuse(0.7)
qw_glyph_property.SetAmbient(0.5)
qw_glyph_property.SetSpecularPower(20.0)
qw_glyph_property.SetOpacity(1.0)
qw_glyph_actor = vtkActor()
qw_glyph_actor.SetMapper(qw_glyph_mapper)
qw_glyph_actor.SetProperty(qw_glyph_property)
qw_plinth_mapper = vtkPolyDataMapper()
qw_plinth_mapper.SetInputConnection(qw_plinth_source.GetOutputPort())
qw_plinth_property = vtkProperty()
qw_plinth_property.SetAmbientColor(steel_blue_rgb)
qw_plinth_property.SetDiffuseColor(light_steel_blue_rgb)
qw_plinth_property.SetSpecularColor(1.0, 1.0, 1.0)
qw_plinth_property.SetSpecular(0.5)
qw_plinth_property.SetDiffuse(0.7)
qw_plinth_property.SetAmbient(0.5)
qw_plinth_property.SetSpecularPower(20.0)
qw_plinth_property.SetOpacity(0.8)
qw_plinth_property.EdgeVisibilityOn()
qw_plinth_property.SetLineWidth(1)
qw_plinth_actor = vtkActor()
qw_plinth_actor.SetMapper(qw_plinth_mapper)
qw_plinth_actor.SetProperty(qw_plinth_property)
qw_text_actor = vtkTextActor()
qw_text_actor.SetInput("Quadratic Wedge")
qw_text_actor.GetTextProperty().SetFontSize(12)
qw_text_actor.GetTextProperty().SetColor(0.0, 0.0, 0.0)
qw_text_actor.GetTextProperty().SetJustificationToCentered()
qw_text_actor.GetPositionCoordinate().SetCoordinateSystemToNormalizedViewport()
qw_text_actor.SetPosition(0.5, 0.01)

# Cell 7: Quadratic Pyramid (surface, 3D)
qpyr_mapper = vtkDataSetMapper()
qpyr_mapper.SetInputData(qpyr_grid)
qpyr_property = vtkProperty()
qpyr_property.SetAmbientColor(dark_salmon_rgb)
qpyr_property.SetDiffuseColor(seashell_rgb)
qpyr_property.SetSpecularColor(1.0, 1.0, 1.0)
qpyr_property.SetSpecular(0.5)
qpyr_property.SetDiffuse(0.7)
qpyr_property.SetAmbient(0.5)
qpyr_property.SetSpecularPower(20.0)
qpyr_property.SetOpacity(0.9)
qpyr_property.EdgeVisibilityOn()
qpyr_property.SetLineWidth(3)
qpyr_actor = vtkActor()
qpyr_actor.SetMapper(qpyr_mapper)
qpyr_actor.SetProperty(qpyr_property)
qpyr_label_text_property = vtkTextProperty()
qpyr_label_text_property.BoldOn()
qpyr_label_text_property.ShadowOn()
qpyr_label_text_property.SetJustificationToCentered()
qpyr_label_text_property.SetColor(deep_pink_rgb)
qpyr_label_text_property.SetFontSize(14)
qpyr_label_mapper = vtkLabeledDataMapper()
qpyr_label_mapper.SetInputData(qpyr_grid)
qpyr_label_mapper.SetLabelTextProperty(qpyr_label_text_property)
qpyr_label_actor = vtkActor2D()
qpyr_label_actor.SetMapper(qpyr_label_mapper)
qpyr_glyph_mapper = vtkGlyph3DMapper()
qpyr_glyph_mapper.SetInputData(qpyr_grid)
qpyr_glyph_mapper.SetSourceConnection(sphere_source.GetOutputPort())
qpyr_glyph_mapper.ScalingOn()
qpyr_glyph_mapper.ScalarVisibilityOff()
qpyr_glyph_property = vtkProperty()
qpyr_glyph_property.SetAmbientColor(gold_rgb)
qpyr_glyph_property.SetDiffuseColor(yellow_rgb)
qpyr_glyph_property.SetSpecularColor(1.0, 1.0, 1.0)
qpyr_glyph_property.SetSpecular(0.5)
qpyr_glyph_property.SetDiffuse(0.7)
qpyr_glyph_property.SetAmbient(0.5)
qpyr_glyph_property.SetSpecularPower(20.0)
qpyr_glyph_property.SetOpacity(1.0)
qpyr_glyph_actor = vtkActor()
qpyr_glyph_actor.SetMapper(qpyr_glyph_mapper)
qpyr_glyph_actor.SetProperty(qpyr_glyph_property)
qpyr_plinth_mapper = vtkPolyDataMapper()
qpyr_plinth_mapper.SetInputConnection(qpyr_plinth_source.GetOutputPort())
qpyr_plinth_property = vtkProperty()
qpyr_plinth_property.SetAmbientColor(steel_blue_rgb)
qpyr_plinth_property.SetDiffuseColor(light_steel_blue_rgb)
qpyr_plinth_property.SetSpecularColor(1.0, 1.0, 1.0)
qpyr_plinth_property.SetSpecular(0.5)
qpyr_plinth_property.SetDiffuse(0.7)
qpyr_plinth_property.SetAmbient(0.5)
qpyr_plinth_property.SetSpecularPower(20.0)
qpyr_plinth_property.SetOpacity(0.8)
qpyr_plinth_property.EdgeVisibilityOn()
qpyr_plinth_property.SetLineWidth(1)
qpyr_plinth_actor = vtkActor()
qpyr_plinth_actor.SetMapper(qpyr_plinth_mapper)
qpyr_plinth_actor.SetProperty(qpyr_plinth_property)
qpyr_text_actor = vtkTextActor()
qpyr_text_actor.SetInput("Quadratic Pyramid")
qpyr_text_actor.GetTextProperty().SetFontSize(12)
qpyr_text_actor.GetTextProperty().SetColor(0.0, 0.0, 0.0)
qpyr_text_actor.GetTextProperty().SetJustificationToCentered()
qpyr_text_actor.GetPositionCoordinate().SetCoordinateSystemToNormalizedViewport()
qpyr_text_actor.SetPosition(0.5, 0.01)

# Cell 8: BiQuadratic Quad (surface, 2D)
bqq_mapper = vtkDataSetMapper()
bqq_mapper.SetInputData(bqq_grid)
bqq_property = vtkProperty()
bqq_property.SetAmbientColor(dark_salmon_rgb)
bqq_property.SetDiffuseColor(seashell_rgb)
bqq_property.SetSpecularColor(1.0, 1.0, 1.0)
bqq_property.SetSpecular(0.5)
bqq_property.SetDiffuse(0.7)
bqq_property.SetAmbient(0.5)
bqq_property.SetSpecularPower(20.0)
bqq_property.SetOpacity(0.9)
bqq_property.EdgeVisibilityOn()
bqq_property.SetLineWidth(3)
bqq_actor = vtkActor()
bqq_actor.SetMapper(bqq_mapper)
bqq_actor.SetProperty(bqq_property)
bqq_label_text_property = vtkTextProperty()
bqq_label_text_property.BoldOn()
bqq_label_text_property.ShadowOn()
bqq_label_text_property.SetJustificationToCentered()
bqq_label_text_property.SetColor(deep_pink_rgb)
bqq_label_text_property.SetFontSize(14)
bqq_label_mapper = vtkLabeledDataMapper()
bqq_label_mapper.SetInputData(bqq_grid)
bqq_label_mapper.SetLabelTextProperty(bqq_label_text_property)
bqq_label_actor = vtkActor2D()
bqq_label_actor.SetMapper(bqq_label_mapper)
bqq_glyph_mapper = vtkGlyph3DMapper()
bqq_glyph_mapper.SetInputData(bqq_grid)
bqq_glyph_mapper.SetSourceConnection(sphere_source.GetOutputPort())
bqq_glyph_mapper.ScalingOn()
bqq_glyph_mapper.ScalarVisibilityOff()
bqq_glyph_property = vtkProperty()
bqq_glyph_property.SetAmbientColor(gold_rgb)
bqq_glyph_property.SetDiffuseColor(yellow_rgb)
bqq_glyph_property.SetSpecularColor(1.0, 1.0, 1.0)
bqq_glyph_property.SetSpecular(0.5)
bqq_glyph_property.SetDiffuse(0.7)
bqq_glyph_property.SetAmbient(0.5)
bqq_glyph_property.SetSpecularPower(20.0)
bqq_glyph_property.SetOpacity(1.0)
bqq_glyph_actor = vtkActor()
bqq_glyph_actor.SetMapper(bqq_glyph_mapper)
bqq_glyph_actor.SetProperty(bqq_glyph_property)
bqq_text_actor = vtkTextActor()
bqq_text_actor.SetInput("BiQuadratic Quad")
bqq_text_actor.GetTextProperty().SetFontSize(12)
bqq_text_actor.GetTextProperty().SetColor(0.0, 0.0, 0.0)
bqq_text_actor.GetTextProperty().SetJustificationToCentered()
bqq_text_actor.GetPositionCoordinate().SetCoordinateSystemToNormalizedViewport()
bqq_text_actor.SetPosition(0.5, 0.01)

# Cell 9: TriQuadratic Hexahedron (surface, 3D)
tqh_mapper = vtkDataSetMapper()
tqh_mapper.SetInputData(tqh_grid)
tqh_property = vtkProperty()
tqh_property.SetAmbientColor(dark_salmon_rgb)
tqh_property.SetDiffuseColor(seashell_rgb)
tqh_property.SetSpecularColor(1.0, 1.0, 1.0)
tqh_property.SetSpecular(0.5)
tqh_property.SetDiffuse(0.7)
tqh_property.SetAmbient(0.5)
tqh_property.SetSpecularPower(20.0)
tqh_property.SetOpacity(0.9)
tqh_property.EdgeVisibilityOn()
tqh_property.SetLineWidth(3)
tqh_actor = vtkActor()
tqh_actor.SetMapper(tqh_mapper)
tqh_actor.SetProperty(tqh_property)
tqh_label_text_property = vtkTextProperty()
tqh_label_text_property.BoldOn()
tqh_label_text_property.ShadowOn()
tqh_label_text_property.SetJustificationToCentered()
tqh_label_text_property.SetColor(deep_pink_rgb)
tqh_label_text_property.SetFontSize(14)
tqh_label_mapper = vtkLabeledDataMapper()
tqh_label_mapper.SetInputData(tqh_grid)
tqh_label_mapper.SetLabelTextProperty(tqh_label_text_property)
tqh_label_actor = vtkActor2D()
tqh_label_actor.SetMapper(tqh_label_mapper)
tqh_glyph_mapper = vtkGlyph3DMapper()
tqh_glyph_mapper.SetInputData(tqh_grid)
tqh_glyph_mapper.SetSourceConnection(sphere_source.GetOutputPort())
tqh_glyph_mapper.ScalingOn()
tqh_glyph_mapper.ScalarVisibilityOff()
tqh_glyph_property = vtkProperty()
tqh_glyph_property.SetAmbientColor(gold_rgb)
tqh_glyph_property.SetDiffuseColor(yellow_rgb)
tqh_glyph_property.SetSpecularColor(1.0, 1.0, 1.0)
tqh_glyph_property.SetSpecular(0.5)
tqh_glyph_property.SetDiffuse(0.7)
tqh_glyph_property.SetAmbient(0.5)
tqh_glyph_property.SetSpecularPower(20.0)
tqh_glyph_property.SetOpacity(1.0)
tqh_glyph_actor = vtkActor()
tqh_glyph_actor.SetMapper(tqh_glyph_mapper)
tqh_glyph_actor.SetProperty(tqh_glyph_property)
tqh_plinth_mapper = vtkPolyDataMapper()
tqh_plinth_mapper.SetInputConnection(tqh_plinth_source.GetOutputPort())
tqh_plinth_property = vtkProperty()
tqh_plinth_property.SetAmbientColor(steel_blue_rgb)
tqh_plinth_property.SetDiffuseColor(light_steel_blue_rgb)
tqh_plinth_property.SetSpecularColor(1.0, 1.0, 1.0)
tqh_plinth_property.SetSpecular(0.5)
tqh_plinth_property.SetDiffuse(0.7)
tqh_plinth_property.SetAmbient(0.5)
tqh_plinth_property.SetSpecularPower(20.0)
tqh_plinth_property.SetOpacity(0.8)
tqh_plinth_property.EdgeVisibilityOn()
tqh_plinth_property.SetLineWidth(1)
tqh_plinth_actor = vtkActor()
tqh_plinth_actor.SetMapper(tqh_plinth_mapper)
tqh_plinth_actor.SetProperty(tqh_plinth_property)
tqh_text_actor = vtkTextActor()
tqh_text_actor.SetInput("TriQuadratic Hexahedron")
tqh_text_actor.GetTextProperty().SetFontSize(12)
tqh_text_actor.GetTextProperty().SetColor(0.0, 0.0, 0.0)
tqh_text_actor.GetTextProperty().SetJustificationToCentered()
tqh_text_actor.GetPositionCoordinate().SetCoordinateSystemToNormalizedViewport()
tqh_text_actor.SetPosition(0.5, 0.01)

# Cell 10: Quadratic Linear Quad (surface, 2D)
qlq_mapper = vtkDataSetMapper()
qlq_mapper.SetInputData(qlq_grid)
qlq_property = vtkProperty()
qlq_property.SetAmbientColor(dark_salmon_rgb)
qlq_property.SetDiffuseColor(seashell_rgb)
qlq_property.SetSpecularColor(1.0, 1.0, 1.0)
qlq_property.SetSpecular(0.5)
qlq_property.SetDiffuse(0.7)
qlq_property.SetAmbient(0.5)
qlq_property.SetSpecularPower(20.0)
qlq_property.SetOpacity(0.9)
qlq_property.EdgeVisibilityOn()
qlq_property.SetLineWidth(3)
qlq_actor = vtkActor()
qlq_actor.SetMapper(qlq_mapper)
qlq_actor.SetProperty(qlq_property)
qlq_label_text_property = vtkTextProperty()
qlq_label_text_property.BoldOn()
qlq_label_text_property.ShadowOn()
qlq_label_text_property.SetJustificationToCentered()
qlq_label_text_property.SetColor(deep_pink_rgb)
qlq_label_text_property.SetFontSize(14)
qlq_label_mapper = vtkLabeledDataMapper()
qlq_label_mapper.SetInputData(qlq_grid)
qlq_label_mapper.SetLabelTextProperty(qlq_label_text_property)
qlq_label_actor = vtkActor2D()
qlq_label_actor.SetMapper(qlq_label_mapper)
qlq_glyph_mapper = vtkGlyph3DMapper()
qlq_glyph_mapper.SetInputData(qlq_grid)
qlq_glyph_mapper.SetSourceConnection(sphere_source.GetOutputPort())
qlq_glyph_mapper.ScalingOn()
qlq_glyph_mapper.ScalarVisibilityOff()
qlq_glyph_property = vtkProperty()
qlq_glyph_property.SetAmbientColor(gold_rgb)
qlq_glyph_property.SetDiffuseColor(yellow_rgb)
qlq_glyph_property.SetSpecularColor(1.0, 1.0, 1.0)
qlq_glyph_property.SetSpecular(0.5)
qlq_glyph_property.SetDiffuse(0.7)
qlq_glyph_property.SetAmbient(0.5)
qlq_glyph_property.SetSpecularPower(20.0)
qlq_glyph_property.SetOpacity(1.0)
qlq_glyph_actor = vtkActor()
qlq_glyph_actor.SetMapper(qlq_glyph_mapper)
qlq_glyph_actor.SetProperty(qlq_glyph_property)
qlq_text_actor = vtkTextActor()
qlq_text_actor.SetInput("Quadratic Linear Quad")
qlq_text_actor.GetTextProperty().SetFontSize(12)
qlq_text_actor.GetTextProperty().SetColor(0.0, 0.0, 0.0)
qlq_text_actor.GetTextProperty().SetJustificationToCentered()
qlq_text_actor.GetPositionCoordinate().SetCoordinateSystemToNormalizedViewport()
qlq_text_actor.SetPosition(0.5, 0.01)

# Cell 11: Quadratic Linear Wedge (surface, 3D)
qlw_mapper = vtkDataSetMapper()
qlw_mapper.SetInputData(qlw_grid)
qlw_property = vtkProperty()
qlw_property.SetAmbientColor(dark_salmon_rgb)
qlw_property.SetDiffuseColor(seashell_rgb)
qlw_property.SetSpecularColor(1.0, 1.0, 1.0)
qlw_property.SetSpecular(0.5)
qlw_property.SetDiffuse(0.7)
qlw_property.SetAmbient(0.5)
qlw_property.SetSpecularPower(20.0)
qlw_property.SetOpacity(0.9)
qlw_property.EdgeVisibilityOn()
qlw_property.SetLineWidth(3)
qlw_actor = vtkActor()
qlw_actor.SetMapper(qlw_mapper)
qlw_actor.SetProperty(qlw_property)
qlw_label_text_property = vtkTextProperty()
qlw_label_text_property.BoldOn()
qlw_label_text_property.ShadowOn()
qlw_label_text_property.SetJustificationToCentered()
qlw_label_text_property.SetColor(deep_pink_rgb)
qlw_label_text_property.SetFontSize(14)
qlw_label_mapper = vtkLabeledDataMapper()
qlw_label_mapper.SetInputData(qlw_grid)
qlw_label_mapper.SetLabelTextProperty(qlw_label_text_property)
qlw_label_actor = vtkActor2D()
qlw_label_actor.SetMapper(qlw_label_mapper)
qlw_glyph_mapper = vtkGlyph3DMapper()
qlw_glyph_mapper.SetInputData(qlw_grid)
qlw_glyph_mapper.SetSourceConnection(sphere_source.GetOutputPort())
qlw_glyph_mapper.ScalingOn()
qlw_glyph_mapper.ScalarVisibilityOff()
qlw_glyph_property = vtkProperty()
qlw_glyph_property.SetAmbientColor(gold_rgb)
qlw_glyph_property.SetDiffuseColor(yellow_rgb)
qlw_glyph_property.SetSpecularColor(1.0, 1.0, 1.0)
qlw_glyph_property.SetSpecular(0.5)
qlw_glyph_property.SetDiffuse(0.7)
qlw_glyph_property.SetAmbient(0.5)
qlw_glyph_property.SetSpecularPower(20.0)
qlw_glyph_property.SetOpacity(1.0)
qlw_glyph_actor = vtkActor()
qlw_glyph_actor.SetMapper(qlw_glyph_mapper)
qlw_glyph_actor.SetProperty(qlw_glyph_property)
qlw_plinth_mapper = vtkPolyDataMapper()
qlw_plinth_mapper.SetInputConnection(qlw_plinth_source.GetOutputPort())
qlw_plinth_property = vtkProperty()
qlw_plinth_property.SetAmbientColor(steel_blue_rgb)
qlw_plinth_property.SetDiffuseColor(light_steel_blue_rgb)
qlw_plinth_property.SetSpecularColor(1.0, 1.0, 1.0)
qlw_plinth_property.SetSpecular(0.5)
qlw_plinth_property.SetDiffuse(0.7)
qlw_plinth_property.SetAmbient(0.5)
qlw_plinth_property.SetSpecularPower(20.0)
qlw_plinth_property.SetOpacity(0.8)
qlw_plinth_property.EdgeVisibilityOn()
qlw_plinth_property.SetLineWidth(1)
qlw_plinth_actor = vtkActor()
qlw_plinth_actor.SetMapper(qlw_plinth_mapper)
qlw_plinth_actor.SetProperty(qlw_plinth_property)
qlw_text_actor = vtkTextActor()
qlw_text_actor.SetInput("Quadratic Linear Wedge")
qlw_text_actor.GetTextProperty().SetFontSize(12)
qlw_text_actor.GetTextProperty().SetColor(0.0, 0.0, 0.0)
qlw_text_actor.GetTextProperty().SetJustificationToCentered()
qlw_text_actor.GetPositionCoordinate().SetCoordinateSystemToNormalizedViewport()
qlw_text_actor.SetPosition(0.5, 0.01)

# Cell 12: BiQuadratic Quadratic Wedge (surface, 3D)
bqqw_mapper = vtkDataSetMapper()
bqqw_mapper.SetInputData(bqqw_grid)
bqqw_property = vtkProperty()
bqqw_property.SetAmbientColor(dark_salmon_rgb)
bqqw_property.SetDiffuseColor(seashell_rgb)
bqqw_property.SetSpecularColor(1.0, 1.0, 1.0)
bqqw_property.SetSpecular(0.5)
bqqw_property.SetDiffuse(0.7)
bqqw_property.SetAmbient(0.5)
bqqw_property.SetSpecularPower(20.0)
bqqw_property.SetOpacity(0.9)
bqqw_property.EdgeVisibilityOn()
bqqw_property.SetLineWidth(3)
bqqw_actor = vtkActor()
bqqw_actor.SetMapper(bqqw_mapper)
bqqw_actor.SetProperty(bqqw_property)
bqqw_label_text_property = vtkTextProperty()
bqqw_label_text_property.BoldOn()
bqqw_label_text_property.ShadowOn()
bqqw_label_text_property.SetJustificationToCentered()
bqqw_label_text_property.SetColor(deep_pink_rgb)
bqqw_label_text_property.SetFontSize(14)
bqqw_label_mapper = vtkLabeledDataMapper()
bqqw_label_mapper.SetInputData(bqqw_grid)
bqqw_label_mapper.SetLabelTextProperty(bqqw_label_text_property)
bqqw_label_actor = vtkActor2D()
bqqw_label_actor.SetMapper(bqqw_label_mapper)
bqqw_glyph_mapper = vtkGlyph3DMapper()
bqqw_glyph_mapper.SetInputData(bqqw_grid)
bqqw_glyph_mapper.SetSourceConnection(sphere_source.GetOutputPort())
bqqw_glyph_mapper.ScalingOn()
bqqw_glyph_mapper.ScalarVisibilityOff()
bqqw_glyph_property = vtkProperty()
bqqw_glyph_property.SetAmbientColor(gold_rgb)
bqqw_glyph_property.SetDiffuseColor(yellow_rgb)
bqqw_glyph_property.SetSpecularColor(1.0, 1.0, 1.0)
bqqw_glyph_property.SetSpecular(0.5)
bqqw_glyph_property.SetDiffuse(0.7)
bqqw_glyph_property.SetAmbient(0.5)
bqqw_glyph_property.SetSpecularPower(20.0)
bqqw_glyph_property.SetOpacity(1.0)
bqqw_glyph_actor = vtkActor()
bqqw_glyph_actor.SetMapper(bqqw_glyph_mapper)
bqqw_glyph_actor.SetProperty(bqqw_glyph_property)
bqqw_plinth_mapper = vtkPolyDataMapper()
bqqw_plinth_mapper.SetInputConnection(bqqw_plinth_source.GetOutputPort())
bqqw_plinth_property = vtkProperty()
bqqw_plinth_property.SetAmbientColor(steel_blue_rgb)
bqqw_plinth_property.SetDiffuseColor(light_steel_blue_rgb)
bqqw_plinth_property.SetSpecularColor(1.0, 1.0, 1.0)
bqqw_plinth_property.SetSpecular(0.5)
bqqw_plinth_property.SetDiffuse(0.7)
bqqw_plinth_property.SetAmbient(0.5)
bqqw_plinth_property.SetSpecularPower(20.0)
bqqw_plinth_property.SetOpacity(0.8)
bqqw_plinth_property.EdgeVisibilityOn()
bqqw_plinth_property.SetLineWidth(1)
bqqw_plinth_actor = vtkActor()
bqqw_plinth_actor.SetMapper(bqqw_plinth_mapper)
bqqw_plinth_actor.SetProperty(bqqw_plinth_property)
bqqw_text_actor = vtkTextActor()
bqqw_text_actor.SetInput("BiQuadratic Quadratic Wedge")
bqqw_text_actor.GetTextProperty().SetFontSize(12)
bqqw_text_actor.GetTextProperty().SetColor(0.0, 0.0, 0.0)
bqqw_text_actor.GetTextProperty().SetJustificationToCentered()
bqqw_text_actor.GetPositionCoordinate().SetCoordinateSystemToNormalizedViewport()
bqqw_text_actor.SetPosition(0.5, 0.01)

# Cell 13: BiQuadratic Quadratic Hexahedron (surface, 3D)
bqqh_mapper = vtkDataSetMapper()
bqqh_mapper.SetInputData(bqqh_grid)
bqqh_property = vtkProperty()
bqqh_property.SetAmbientColor(dark_salmon_rgb)
bqqh_property.SetDiffuseColor(seashell_rgb)
bqqh_property.SetSpecularColor(1.0, 1.0, 1.0)
bqqh_property.SetSpecular(0.5)
bqqh_property.SetDiffuse(0.7)
bqqh_property.SetAmbient(0.5)
bqqh_property.SetSpecularPower(20.0)
bqqh_property.SetOpacity(0.9)
bqqh_property.EdgeVisibilityOn()
bqqh_property.SetLineWidth(3)
bqqh_actor = vtkActor()
bqqh_actor.SetMapper(bqqh_mapper)
bqqh_actor.SetProperty(bqqh_property)
bqqh_label_text_property = vtkTextProperty()
bqqh_label_text_property.BoldOn()
bqqh_label_text_property.ShadowOn()
bqqh_label_text_property.SetJustificationToCentered()
bqqh_label_text_property.SetColor(deep_pink_rgb)
bqqh_label_text_property.SetFontSize(14)
bqqh_label_mapper = vtkLabeledDataMapper()
bqqh_label_mapper.SetInputData(bqqh_grid)
bqqh_label_mapper.SetLabelTextProperty(bqqh_label_text_property)
bqqh_label_actor = vtkActor2D()
bqqh_label_actor.SetMapper(bqqh_label_mapper)
bqqh_glyph_mapper = vtkGlyph3DMapper()
bqqh_glyph_mapper.SetInputData(bqqh_grid)
bqqh_glyph_mapper.SetSourceConnection(sphere_source.GetOutputPort())
bqqh_glyph_mapper.ScalingOn()
bqqh_glyph_mapper.ScalarVisibilityOff()
bqqh_glyph_property = vtkProperty()
bqqh_glyph_property.SetAmbientColor(gold_rgb)
bqqh_glyph_property.SetDiffuseColor(yellow_rgb)
bqqh_glyph_property.SetSpecularColor(1.0, 1.0, 1.0)
bqqh_glyph_property.SetSpecular(0.5)
bqqh_glyph_property.SetDiffuse(0.7)
bqqh_glyph_property.SetAmbient(0.5)
bqqh_glyph_property.SetSpecularPower(20.0)
bqqh_glyph_property.SetOpacity(1.0)
bqqh_glyph_actor = vtkActor()
bqqh_glyph_actor.SetMapper(bqqh_glyph_mapper)
bqqh_glyph_actor.SetProperty(bqqh_glyph_property)
bqqh_plinth_mapper = vtkPolyDataMapper()
bqqh_plinth_mapper.SetInputConnection(bqqh_plinth_source.GetOutputPort())
bqqh_plinth_property = vtkProperty()
bqqh_plinth_property.SetAmbientColor(steel_blue_rgb)
bqqh_plinth_property.SetDiffuseColor(light_steel_blue_rgb)
bqqh_plinth_property.SetSpecularColor(1.0, 1.0, 1.0)
bqqh_plinth_property.SetSpecular(0.5)
bqqh_plinth_property.SetDiffuse(0.7)
bqqh_plinth_property.SetAmbient(0.5)
bqqh_plinth_property.SetSpecularPower(20.0)
bqqh_plinth_property.SetOpacity(0.8)
bqqh_plinth_property.EdgeVisibilityOn()
bqqh_plinth_property.SetLineWidth(1)
bqqh_plinth_actor = vtkActor()
bqqh_plinth_actor.SetMapper(bqqh_plinth_mapper)
bqqh_plinth_actor.SetProperty(bqqh_plinth_property)
bqqh_text_actor = vtkTextActor()
bqqh_text_actor.SetInput("BiQuadratic Quadratic Hex")
bqqh_text_actor.GetTextProperty().SetFontSize(12)
bqqh_text_actor.GetTextProperty().SetColor(0.0, 0.0, 0.0)
bqqh_text_actor.GetTextProperty().SetJustificationToCentered()
bqqh_text_actor.GetPositionCoordinate().SetCoordinateSystemToNormalizedViewport()
bqqh_text_actor.SetPosition(0.5, 0.01)

# Cell 14: BiQuadratic Triangle (surface, 2D)
bqt_mapper = vtkDataSetMapper()
bqt_mapper.SetInputData(bqt_grid)
bqt_property = vtkProperty()
bqt_property.SetAmbientColor(dark_salmon_rgb)
bqt_property.SetDiffuseColor(seashell_rgb)
bqt_property.SetSpecularColor(1.0, 1.0, 1.0)
bqt_property.SetSpecular(0.5)
bqt_property.SetDiffuse(0.7)
bqt_property.SetAmbient(0.5)
bqt_property.SetSpecularPower(20.0)
bqt_property.SetOpacity(0.9)
bqt_property.EdgeVisibilityOn()
bqt_property.SetLineWidth(3)
bqt_actor = vtkActor()
bqt_actor.SetMapper(bqt_mapper)
bqt_actor.SetProperty(bqt_property)
bqt_label_text_property = vtkTextProperty()
bqt_label_text_property.BoldOn()
bqt_label_text_property.ShadowOn()
bqt_label_text_property.SetJustificationToCentered()
bqt_label_text_property.SetColor(deep_pink_rgb)
bqt_label_text_property.SetFontSize(14)
bqt_label_mapper = vtkLabeledDataMapper()
bqt_label_mapper.SetInputData(bqt_grid)
bqt_label_mapper.SetLabelTextProperty(bqt_label_text_property)
bqt_label_actor = vtkActor2D()
bqt_label_actor.SetMapper(bqt_label_mapper)
bqt_glyph_mapper = vtkGlyph3DMapper()
bqt_glyph_mapper.SetInputData(bqt_grid)
bqt_glyph_mapper.SetSourceConnection(sphere_source.GetOutputPort())
bqt_glyph_mapper.ScalingOn()
bqt_glyph_mapper.ScalarVisibilityOff()
bqt_glyph_property = vtkProperty()
bqt_glyph_property.SetAmbientColor(gold_rgb)
bqt_glyph_property.SetDiffuseColor(yellow_rgb)
bqt_glyph_property.SetSpecularColor(1.0, 1.0, 1.0)
bqt_glyph_property.SetSpecular(0.5)
bqt_glyph_property.SetDiffuse(0.7)
bqt_glyph_property.SetAmbient(0.5)
bqt_glyph_property.SetSpecularPower(20.0)
bqt_glyph_property.SetOpacity(1.0)
bqt_glyph_actor = vtkActor()
bqt_glyph_actor.SetMapper(bqt_glyph_mapper)
bqt_glyph_actor.SetProperty(bqt_glyph_property)
bqt_text_actor = vtkTextActor()
bqt_text_actor.SetInput("BiQuadratic Triangle")
bqt_text_actor.GetTextProperty().SetFontSize(12)
bqt_text_actor.GetTextProperty().SetColor(0.0, 0.0, 0.0)
bqt_text_actor.GetTextProperty().SetJustificationToCentered()
bqt_text_actor.GetPositionCoordinate().SetCoordinateSystemToNormalizedViewport()
bqt_text_actor.SetPosition(0.5, 0.01)

# Cell 15: Cubic Line (wireframe, 2D)
cl_mapper = vtkDataSetMapper()
cl_mapper.SetInputData(cl_grid)
cl_property = vtkProperty()
cl_property.SetRepresentationToWireframe()
cl_property.SetLineWidth(2)
cl_property.SetOpacity(1)
cl_property.SetColor(0.0, 0.0, 0.0)
cl_actor = vtkActor()
cl_actor.SetMapper(cl_mapper)
cl_actor.SetProperty(cl_property)
cl_label_text_property = vtkTextProperty()
cl_label_text_property.BoldOn()
cl_label_text_property.ShadowOn()
cl_label_text_property.SetJustificationToCentered()
cl_label_text_property.SetColor(deep_pink_rgb)
cl_label_text_property.SetFontSize(14)
cl_label_mapper = vtkLabeledDataMapper()
cl_label_mapper.SetInputData(cl_grid)
cl_label_mapper.SetLabelTextProperty(cl_label_text_property)
cl_label_actor = vtkActor2D()
cl_label_actor.SetMapper(cl_label_mapper)
cl_glyph_mapper = vtkGlyph3DMapper()
cl_glyph_mapper.SetInputData(cl_grid)
cl_glyph_mapper.SetSourceConnection(sphere_source.GetOutputPort())
cl_glyph_mapper.ScalingOn()
cl_glyph_mapper.ScalarVisibilityOff()
cl_glyph_property = vtkProperty()
cl_glyph_property.SetAmbientColor(gold_rgb)
cl_glyph_property.SetDiffuseColor(yellow_rgb)
cl_glyph_property.SetSpecularColor(1.0, 1.0, 1.0)
cl_glyph_property.SetSpecular(0.5)
cl_glyph_property.SetDiffuse(0.7)
cl_glyph_property.SetAmbient(0.5)
cl_glyph_property.SetSpecularPower(20.0)
cl_glyph_property.SetOpacity(1.0)
cl_glyph_actor = vtkActor()
cl_glyph_actor.SetMapper(cl_glyph_mapper)
cl_glyph_actor.SetProperty(cl_glyph_property)
cl_text_actor = vtkTextActor()
cl_text_actor.SetInput("Cubic Line")
cl_text_actor.GetTextProperty().SetFontSize(12)
cl_text_actor.GetTextProperty().SetColor(0.0, 0.0, 0.0)
cl_text_actor.GetTextProperty().SetJustificationToCentered()
cl_text_actor.GetPositionCoordinate().SetCoordinateSystemToNormalizedViewport()
cl_text_actor.SetPosition(0.5, 0.01)

# ===========================================================================
# Renderers: 16 renderers in a 4 × 4 grid
# ===========================================================================

# Row 0 (top): cells 0-3, y = 0.75–1.00
qe_renderer = vtkRenderer()
qe_renderer.AddActor(qe_actor)
qe_renderer.AddActor(qe_label_actor)
qe_renderer.AddActor(qe_glyph_actor)
qe_renderer.AddViewProp(qe_text_actor)
qe_renderer.SetBackground(background_rgb)
qe_renderer.SetViewport(0.00, 0.75, 0.25, 1.00)

qt_renderer = vtkRenderer()
qt_renderer.AddActor(qt_actor)
qt_renderer.AddActor(qt_label_actor)
qt_renderer.AddActor(qt_glyph_actor)
qt_renderer.AddViewProp(qt_text_actor)
qt_renderer.SetBackground(background_rgb)
qt_renderer.SetViewport(0.25, 0.75, 0.50, 1.00)

qq_renderer = vtkRenderer()
qq_renderer.AddActor(qq_actor)
qq_renderer.AddActor(qq_label_actor)
qq_renderer.AddActor(qq_glyph_actor)
qq_renderer.AddViewProp(qq_text_actor)
qq_renderer.SetBackground(background_rgb)
qq_renderer.SetViewport(0.50, 0.75, 0.75, 1.00)

qp_renderer = vtkRenderer()
qp_renderer.AddActor(qp_actor)
qp_renderer.AddActor(qp_label_actor)
qp_renderer.AddActor(qp_glyph_actor)
qp_renderer.AddViewProp(qp_text_actor)
qp_renderer.SetBackground(background_rgb)
qp_renderer.SetViewport(0.75, 0.75, 1.00, 1.00)

# Row 1: cells 4-7, y = 0.50–0.75
qtet_renderer = vtkRenderer()
qtet_renderer.AddActor(qtet_actor)
qtet_renderer.AddActor(qtet_label_actor)
qtet_renderer.AddActor(qtet_glyph_actor)
qtet_renderer.AddActor(qtet_plinth_actor)
qtet_renderer.AddViewProp(qtet_text_actor)
qtet_renderer.SetBackground(background_rgb)
qtet_renderer.SetViewport(0.00, 0.50, 0.25, 0.75)

qhex_renderer = vtkRenderer()
qhex_renderer.AddActor(qhex_actor)
qhex_renderer.AddActor(qhex_label_actor)
qhex_renderer.AddActor(qhex_glyph_actor)
qhex_renderer.AddActor(qhex_plinth_actor)
qhex_renderer.AddViewProp(qhex_text_actor)
qhex_renderer.SetBackground(background_rgb)
qhex_renderer.SetViewport(0.25, 0.50, 0.50, 0.75)

qw_renderer = vtkRenderer()
qw_renderer.AddActor(qw_actor)
qw_renderer.AddActor(qw_label_actor)
qw_renderer.AddActor(qw_glyph_actor)
qw_renderer.AddActor(qw_plinth_actor)
qw_renderer.AddViewProp(qw_text_actor)
qw_renderer.SetBackground(background_rgb)
qw_renderer.SetViewport(0.50, 0.50, 0.75, 0.75)

qpyr_renderer = vtkRenderer()
qpyr_renderer.AddActor(qpyr_actor)
qpyr_renderer.AddActor(qpyr_label_actor)
qpyr_renderer.AddActor(qpyr_glyph_actor)
qpyr_renderer.AddActor(qpyr_plinth_actor)
qpyr_renderer.AddViewProp(qpyr_text_actor)
qpyr_renderer.SetBackground(background_rgb)
qpyr_renderer.SetViewport(0.75, 0.50, 1.00, 0.75)

# Row 2: cells 8-11, y = 0.25–0.50
bqq_renderer = vtkRenderer()
bqq_renderer.AddActor(bqq_actor)
bqq_renderer.AddActor(bqq_label_actor)
bqq_renderer.AddActor(bqq_glyph_actor)
bqq_renderer.AddViewProp(bqq_text_actor)
bqq_renderer.SetBackground(background_rgb)
bqq_renderer.SetViewport(0.00, 0.25, 0.25, 0.50)

tqh_renderer = vtkRenderer()
tqh_renderer.AddActor(tqh_actor)
tqh_renderer.AddActor(tqh_label_actor)
tqh_renderer.AddActor(tqh_glyph_actor)
tqh_renderer.AddActor(tqh_plinth_actor)
tqh_renderer.AddViewProp(tqh_text_actor)
tqh_renderer.SetBackground(background_rgb)
tqh_renderer.SetViewport(0.25, 0.25, 0.50, 0.50)

qlq_renderer = vtkRenderer()
qlq_renderer.AddActor(qlq_actor)
qlq_renderer.AddActor(qlq_label_actor)
qlq_renderer.AddActor(qlq_glyph_actor)
qlq_renderer.AddViewProp(qlq_text_actor)
qlq_renderer.SetBackground(background_rgb)
qlq_renderer.SetViewport(0.50, 0.25, 0.75, 0.50)

qlw_renderer = vtkRenderer()
qlw_renderer.AddActor(qlw_actor)
qlw_renderer.AddActor(qlw_label_actor)
qlw_renderer.AddActor(qlw_glyph_actor)
qlw_renderer.AddActor(qlw_plinth_actor)
qlw_renderer.AddViewProp(qlw_text_actor)
qlw_renderer.SetBackground(background_rgb)
qlw_renderer.SetViewport(0.75, 0.25, 1.00, 0.50)

# Row 3 (bottom): cells 12-15, y = 0.00–0.25
bqqw_renderer = vtkRenderer()
bqqw_renderer.AddActor(bqqw_actor)
bqqw_renderer.AddActor(bqqw_label_actor)
bqqw_renderer.AddActor(bqqw_glyph_actor)
bqqw_renderer.AddActor(bqqw_plinth_actor)
bqqw_renderer.AddViewProp(bqqw_text_actor)
bqqw_renderer.SetBackground(background_rgb)
bqqw_renderer.SetViewport(0.00, 0.00, 0.25, 0.25)

bqqh_renderer = vtkRenderer()
bqqh_renderer.AddActor(bqqh_actor)
bqqh_renderer.AddActor(bqqh_label_actor)
bqqh_renderer.AddActor(bqqh_glyph_actor)
bqqh_renderer.AddActor(bqqh_plinth_actor)
bqqh_renderer.AddViewProp(bqqh_text_actor)
bqqh_renderer.SetBackground(background_rgb)
bqqh_renderer.SetViewport(0.25, 0.00, 0.50, 0.25)

bqt_renderer = vtkRenderer()
bqt_renderer.AddActor(bqt_actor)
bqt_renderer.AddActor(bqt_label_actor)
bqt_renderer.AddActor(bqt_glyph_actor)
bqt_renderer.AddViewProp(bqt_text_actor)
bqt_renderer.SetBackground(background_rgb)
bqt_renderer.SetViewport(0.50, 0.00, 0.75, 0.25)

cl_renderer = vtkRenderer()
cl_renderer.AddActor(cl_actor)
cl_renderer.AddActor(cl_label_actor)
cl_renderer.AddActor(cl_glyph_actor)
cl_renderer.AddViewProp(cl_text_actor)
cl_renderer.SetBackground(background_rgb)
cl_renderer.SetViewport(0.75, 0.00, 1.00, 0.25)

# ===========================================================================
# RenderWindow
# ===========================================================================
render_window = vtkRenderWindow()
render_window.AddRenderer(qe_renderer)
render_window.AddRenderer(qt_renderer)
render_window.AddRenderer(qq_renderer)
render_window.AddRenderer(qp_renderer)
render_window.AddRenderer(qtet_renderer)
render_window.AddRenderer(qhex_renderer)
render_window.AddRenderer(qw_renderer)
render_window.AddRenderer(qpyr_renderer)
render_window.AddRenderer(bqq_renderer)
render_window.AddRenderer(tqh_renderer)
render_window.AddRenderer(qlq_renderer)
render_window.AddRenderer(qlw_renderer)
render_window.AddRenderer(bqqw_renderer)
render_window.AddRenderer(bqqh_renderer)
render_window.AddRenderer(bqt_renderer)
render_window.AddRenderer(cl_renderer)
render_window.SetWindowName("isoparametric cells demo")
render_window.SetMultiSamples(0)
render_window.SetSize(1200, 1200)

# ===========================================================================
# Interactor
# ===========================================================================
render_window_interactor = vtkRenderWindowInteractor()
render_window_interactor.SetRenderWindow(render_window)

# ===========================================================================
# Scene: camera setup for all 16 renderers
# ===========================================================================
qe_renderer.ResetCamera()
qe_renderer.GetActiveCamera().Zoom(1.4)
qt_renderer.ResetCamera()
qt_renderer.GetActiveCamera().Zoom(1.4)
qq_renderer.ResetCamera()
qq_renderer.GetActiveCamera().Zoom(1.4)
qp_renderer.ResetCamera()
qp_renderer.GetActiveCamera().Zoom(1.4)
qtet_renderer.ResetCamera()
qtet_renderer.GetActiveCamera().Zoom(1.4)
qhex_renderer.ResetCamera()
qhex_renderer.GetActiveCamera().Zoom(1.4)
qw_renderer.ResetCamera()
qw_renderer.GetActiveCamera().Zoom(1.4)
qpyr_renderer.ResetCamera()
qpyr_renderer.GetActiveCamera().Zoom(1.4)
bqq_renderer.ResetCamera()
bqq_renderer.GetActiveCamera().Zoom(1.4)
tqh_renderer.ResetCamera()
tqh_renderer.GetActiveCamera().Zoom(1.4)
qlq_renderer.ResetCamera()
qlq_renderer.GetActiveCamera().Zoom(1.4)
qlw_renderer.ResetCamera()
qlw_renderer.GetActiveCamera().Zoom(1.4)
bqqw_renderer.ResetCamera()
bqqw_renderer.GetActiveCamera().Zoom(1.4)
bqqh_renderer.ResetCamera()
bqqh_renderer.GetActiveCamera().Zoom(1.4)
bqt_renderer.ResetCamera()
bqt_renderer.GetActiveCamera().Zoom(1.4)
cl_renderer.ResetCamera()
cl_renderer.GetActiveCamera().Zoom(1.4)

render_window_interactor.Initialize()
render_window_interactor.Start()
