#!/usr/bin/env python
# Demonstrate boolean texture mapping with quadric implicit functions on spheres.

import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401

from vtkmodules.vtkCommonDataModel import vtkQuadric
from vtkmodules.vtkFiltersSources import vtkSphereSource
from vtkmodules.vtkFiltersTexture import vtkImplicitTextureCoords
from vtkmodules.vtkImagingHybrid import vtkBooleanTexture
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkDataSetMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
    vtkTexture,
)

solid_texture = (255, 255)
clear_texture = (255, 0)
edge_texture = (0, 255)

# Define two elliptical cylinders.
quadric_1 = vtkQuadric()
quadric_1.SetCoefficients(1, 2, 0, 0, 0, 0, 0, 0, 0, -0.07)
quadric_2 = vtkQuadric()
quadric_2.SetCoefficients(2, 1, 0, 0, 0, 0, 0, 0, 0, -0.07)

# Create a sphere source.
sphere_source = vtkSphereSource()
sphere_source.SetPhiResolution(50)
sphere_source.SetThetaResolution(50)

# Create texture coordinates.
tcoords = vtkImplicitTextureCoords()
tcoords.SetInputConnection(sphere_source.GetOutputPort())
tcoords.SetRFunction(quadric_1)
tcoords.SetSFunction(quadric_2)

# Boolean textures for each case.
bool_tex_0 = vtkBooleanTexture()
bool_tex_0.SetXSize(256)
bool_tex_0.SetYSize(256)
bool_tex_0.SetThickness(1)
bool_tex_0.SetInIn(solid_texture)
bool_tex_0.SetOutIn(solid_texture)
bool_tex_0.SetInOut(solid_texture)
bool_tex_0.SetOutOut(solid_texture)
bool_tex_0.SetOnOn(solid_texture)
bool_tex_0.SetOnIn(solid_texture)
bool_tex_0.SetOnOut(solid_texture)
bool_tex_0.SetInOn(solid_texture)
bool_tex_0.SetOutOn(solid_texture)
bool_tex_0.Update()

bool_tex_1 = vtkBooleanTexture()
bool_tex_1.SetXSize(256)
bool_tex_1.SetYSize(256)
bool_tex_1.SetThickness(1)
bool_tex_1.SetInIn(clear_texture)
bool_tex_1.SetOutIn(solid_texture)
bool_tex_1.SetInOut(solid_texture)
bool_tex_1.SetOutOut(solid_texture)
bool_tex_1.SetOnOn(edge_texture)
bool_tex_1.SetOnIn(edge_texture)
bool_tex_1.SetOnOut(solid_texture)
bool_tex_1.SetInOn(edge_texture)
bool_tex_1.SetOutOn(solid_texture)
bool_tex_1.Update()

bool_tex_2 = vtkBooleanTexture()
bool_tex_2.SetXSize(256)
bool_tex_2.SetYSize(256)
bool_tex_2.SetThickness(1)
bool_tex_2.SetInIn(solid_texture)
bool_tex_2.SetOutIn(clear_texture)
bool_tex_2.SetInOut(solid_texture)
bool_tex_2.SetOutOut(solid_texture)
bool_tex_2.SetOnOn(edge_texture)
bool_tex_2.SetOnIn(edge_texture)
bool_tex_2.SetOnOut(solid_texture)
bool_tex_2.SetInOn(solid_texture)
bool_tex_2.SetOutOn(edge_texture)
bool_tex_2.Update()

bool_tex_3 = vtkBooleanTexture()
bool_tex_3.SetXSize(256)
bool_tex_3.SetYSize(256)
bool_tex_3.SetThickness(1)
bool_tex_3.SetInIn(clear_texture)
bool_tex_3.SetOutIn(clear_texture)
bool_tex_3.SetInOut(solid_texture)
bool_tex_3.SetOutOut(solid_texture)
bool_tex_3.SetOnOn(edge_texture)
bool_tex_3.SetOnIn(clear_texture)
bool_tex_3.SetOnOut(solid_texture)
bool_tex_3.SetInOn(edge_texture)
bool_tex_3.SetOutOn(edge_texture)
bool_tex_3.Update()

bool_tex_4 = vtkBooleanTexture()
bool_tex_4.SetXSize(256)
bool_tex_4.SetYSize(256)
bool_tex_4.SetThickness(1)
bool_tex_4.SetInIn(solid_texture)
bool_tex_4.SetOutIn(solid_texture)
bool_tex_4.SetInOut(clear_texture)
bool_tex_4.SetOutOut(solid_texture)
bool_tex_4.SetOnOn(edge_texture)
bool_tex_4.SetOnIn(solid_texture)
bool_tex_4.SetOnOut(edge_texture)
bool_tex_4.SetInOn(edge_texture)
bool_tex_4.SetOutOn(solid_texture)
bool_tex_4.Update()

bool_tex_5 = vtkBooleanTexture()
bool_tex_5.SetXSize(256)
bool_tex_5.SetYSize(256)
bool_tex_5.SetThickness(1)
bool_tex_5.SetInIn(clear_texture)
bool_tex_5.SetOutIn(solid_texture)
bool_tex_5.SetInOut(clear_texture)
bool_tex_5.SetOutOut(solid_texture)
bool_tex_5.SetOnOn(edge_texture)
bool_tex_5.SetOnIn(edge_texture)
bool_tex_5.SetOnOut(edge_texture)
bool_tex_5.SetInOn(clear_texture)
bool_tex_5.SetOutOn(solid_texture)
bool_tex_5.Update()

bool_tex_6 = vtkBooleanTexture()
bool_tex_6.SetXSize(256)
bool_tex_6.SetYSize(256)
bool_tex_6.SetThickness(1)
bool_tex_6.SetInIn(solid_texture)
bool_tex_6.SetOutIn(clear_texture)
bool_tex_6.SetInOut(clear_texture)
bool_tex_6.SetOutOut(solid_texture)
bool_tex_6.SetOnOn(edge_texture)
bool_tex_6.SetOnIn(edge_texture)
bool_tex_6.SetOnOut(edge_texture)
bool_tex_6.SetInOn(edge_texture)
bool_tex_6.SetOutOn(edge_texture)
bool_tex_6.Update()

bool_tex_7 = vtkBooleanTexture()
bool_tex_7.SetXSize(256)
bool_tex_7.SetYSize(256)
bool_tex_7.SetThickness(1)
bool_tex_7.SetInIn(clear_texture)
bool_tex_7.SetOutIn(clear_texture)
bool_tex_7.SetInOut(clear_texture)
bool_tex_7.SetOutOut(solid_texture)
bool_tex_7.SetOnOn(edge_texture)
bool_tex_7.SetOnIn(clear_texture)
bool_tex_7.SetOnOut(edge_texture)
bool_tex_7.SetInOn(clear_texture)
bool_tex_7.SetOutOn(edge_texture)
bool_tex_7.Update()

bool_tex_8 = vtkBooleanTexture()
bool_tex_8.SetXSize(256)
bool_tex_8.SetYSize(256)
bool_tex_8.SetThickness(1)
bool_tex_8.SetInIn(solid_texture)
bool_tex_8.SetOutIn(solid_texture)
bool_tex_8.SetInOut(solid_texture)
bool_tex_8.SetOutOut(clear_texture)
bool_tex_8.SetOnOn(edge_texture)
bool_tex_8.SetOnIn(solid_texture)
bool_tex_8.SetOnOut(edge_texture)
bool_tex_8.SetInOn(solid_texture)
bool_tex_8.SetOutOn(edge_texture)
bool_tex_8.Update()

bool_tex_9 = vtkBooleanTexture()
bool_tex_9.SetXSize(256)
bool_tex_9.SetYSize(256)
bool_tex_9.SetThickness(1)
bool_tex_9.SetInIn(clear_texture)
bool_tex_9.SetOutIn(solid_texture)
bool_tex_9.SetInOut(solid_texture)
bool_tex_9.SetOutOut(clear_texture)
bool_tex_9.SetOnOn(edge_texture)
bool_tex_9.SetOnIn(edge_texture)
bool_tex_9.SetOnOut(edge_texture)
bool_tex_9.SetInOn(edge_texture)
bool_tex_9.SetOutOn(edge_texture)
bool_tex_9.Update()

bool_tex_10 = vtkBooleanTexture()
bool_tex_10.SetXSize(256)
bool_tex_10.SetYSize(256)
bool_tex_10.SetThickness(1)
bool_tex_10.SetInIn(solid_texture)
bool_tex_10.SetOutIn(clear_texture)
bool_tex_10.SetInOut(solid_texture)
bool_tex_10.SetOutOut(clear_texture)
bool_tex_10.SetOnOn(edge_texture)
bool_tex_10.SetOnIn(edge_texture)
bool_tex_10.SetOnOut(edge_texture)
bool_tex_10.SetInOn(solid_texture)
bool_tex_10.SetOutOn(clear_texture)
bool_tex_10.Update()

bool_tex_11 = vtkBooleanTexture()
bool_tex_11.SetXSize(256)
bool_tex_11.SetYSize(256)
bool_tex_11.SetThickness(1)
bool_tex_11.SetInIn(clear_texture)
bool_tex_11.SetOutIn(clear_texture)
bool_tex_11.SetInOut(solid_texture)
bool_tex_11.SetOutOut(clear_texture)
bool_tex_11.SetOnOn(edge_texture)
bool_tex_11.SetOnIn(clear_texture)
bool_tex_11.SetOnOut(edge_texture)
bool_tex_11.SetInOn(edge_texture)
bool_tex_11.SetOutOn(clear_texture)
bool_tex_11.Update()

bool_tex_12 = vtkBooleanTexture()
bool_tex_12.SetXSize(256)
bool_tex_12.SetYSize(256)
bool_tex_12.SetThickness(1)
bool_tex_12.SetInIn(solid_texture)
bool_tex_12.SetOutIn(solid_texture)
bool_tex_12.SetInOut(clear_texture)
bool_tex_12.SetOutOut(clear_texture)
bool_tex_12.SetOnOn(edge_texture)
bool_tex_12.SetOnIn(solid_texture)
bool_tex_12.SetOnOut(clear_texture)
bool_tex_12.SetInOn(edge_texture)
bool_tex_12.SetOutOn(edge_texture)
bool_tex_12.Update()

bool_tex_13 = vtkBooleanTexture()
bool_tex_13.SetXSize(256)
bool_tex_13.SetYSize(256)
bool_tex_13.SetThickness(1)
bool_tex_13.SetInIn(clear_texture)
bool_tex_13.SetOutIn(solid_texture)
bool_tex_13.SetInOut(clear_texture)
bool_tex_13.SetOutOut(clear_texture)
bool_tex_13.SetOnOn(edge_texture)
bool_tex_13.SetOnIn(edge_texture)
bool_tex_13.SetOnOut(clear_texture)
bool_tex_13.SetInOn(clear_texture)
bool_tex_13.SetOutOn(edge_texture)
bool_tex_13.Update()

bool_tex_14 = vtkBooleanTexture()
bool_tex_14.SetXSize(256)
bool_tex_14.SetYSize(256)
bool_tex_14.SetThickness(1)
bool_tex_14.SetInIn(solid_texture)
bool_tex_14.SetOutIn(clear_texture)
bool_tex_14.SetInOut(clear_texture)
bool_tex_14.SetOutOut(clear_texture)
bool_tex_14.SetOnOn(edge_texture)
bool_tex_14.SetOnIn(edge_texture)
bool_tex_14.SetOnOut(clear_texture)
bool_tex_14.SetInOn(edge_texture)
bool_tex_14.SetOutOn(clear_texture)
bool_tex_14.Update()

bool_tex_15 = vtkBooleanTexture()
bool_tex_15.SetXSize(256)
bool_tex_15.SetYSize(256)
bool_tex_15.SetThickness(1)
bool_tex_15.SetInIn(clear_texture)
bool_tex_15.SetOutIn(clear_texture)
bool_tex_15.SetInOut(clear_texture)
bool_tex_15.SetOutOut(clear_texture)
bool_tex_15.SetOnOn(clear_texture)
bool_tex_15.SetOnIn(clear_texture)
bool_tex_15.SetOnOut(clear_texture)
bool_tex_15.SetInOn(clear_texture)
bool_tex_15.SetOutOn(clear_texture)
bool_tex_15.Update()

# Textures.
texture_0 = vtkTexture()
texture_0.SetInputData(bool_tex_0.GetOutput())
texture_0.InterpolateOff()
texture_0.RepeatOff()

texture_1 = vtkTexture()
texture_1.SetInputData(bool_tex_1.GetOutput())
texture_1.InterpolateOff()
texture_1.RepeatOff()

texture_2 = vtkTexture()
texture_2.SetInputData(bool_tex_2.GetOutput())
texture_2.InterpolateOff()
texture_2.RepeatOff()

texture_3 = vtkTexture()
texture_3.SetInputData(bool_tex_3.GetOutput())
texture_3.InterpolateOff()
texture_3.RepeatOff()

texture_4 = vtkTexture()
texture_4.SetInputData(bool_tex_4.GetOutput())
texture_4.InterpolateOff()
texture_4.RepeatOff()

texture_5 = vtkTexture()
texture_5.SetInputData(bool_tex_5.GetOutput())
texture_5.InterpolateOff()
texture_5.RepeatOff()

texture_6 = vtkTexture()
texture_6.SetInputData(bool_tex_6.GetOutput())
texture_6.InterpolateOff()
texture_6.RepeatOff()

texture_7 = vtkTexture()
texture_7.SetInputData(bool_tex_7.GetOutput())
texture_7.InterpolateOff()
texture_7.RepeatOff()

texture_8 = vtkTexture()
texture_8.SetInputData(bool_tex_8.GetOutput())
texture_8.InterpolateOff()
texture_8.RepeatOff()

texture_9 = vtkTexture()
texture_9.SetInputData(bool_tex_9.GetOutput())
texture_9.InterpolateOff()
texture_9.RepeatOff()

texture_10 = vtkTexture()
texture_10.SetInputData(bool_tex_10.GetOutput())
texture_10.InterpolateOff()
texture_10.RepeatOff()

texture_11 = vtkTexture()
texture_11.SetInputData(bool_tex_11.GetOutput())
texture_11.InterpolateOff()
texture_11.RepeatOff()

texture_12 = vtkTexture()
texture_12.SetInputData(bool_tex_12.GetOutput())
texture_12.InterpolateOff()
texture_12.RepeatOff()

texture_13 = vtkTexture()
texture_13.SetInputData(bool_tex_13.GetOutput())
texture_13.InterpolateOff()
texture_13.RepeatOff()

texture_14 = vtkTexture()
texture_14.SetInputData(bool_tex_14.GetOutput())
texture_14.InterpolateOff()
texture_14.RepeatOff()

texture_15 = vtkTexture()
texture_15.SetInputData(bool_tex_15.GetOutput())
texture_15.InterpolateOff()
texture_15.RepeatOff()

# Mapper (shared).
mapper = vtkDataSetMapper()
mapper.SetInputConnection(tcoords.GetOutputPort())

# Actors.
actor_0 = vtkActor()
actor_0.SetMapper(mapper)
actor_0.SetTexture(texture_0)
actor_0.SetPosition(-4, 4, 0)
actor_0.SetScale(2.0, 2.0, 2.0)

actor_1 = vtkActor()
actor_1.SetMapper(mapper)
actor_1.SetTexture(texture_1)
actor_1.SetPosition(-2, 4, 0)
actor_1.SetScale(2.0, 2.0, 2.0)

actor_2 = vtkActor()
actor_2.SetMapper(mapper)
actor_2.SetTexture(texture_2)
actor_2.SetPosition(0, 4, 0)
actor_2.SetScale(2.0, 2.0, 2.0)

actor_3 = vtkActor()
actor_3.SetMapper(mapper)
actor_3.SetTexture(texture_3)
actor_3.SetPosition(2, 4, 0)
actor_3.SetScale(2.0, 2.0, 2.0)

actor_4 = vtkActor()
actor_4.SetMapper(mapper)
actor_4.SetTexture(texture_4)
actor_4.SetPosition(-4, 2, 0)
actor_4.SetScale(2.0, 2.0, 2.0)

actor_5 = vtkActor()
actor_5.SetMapper(mapper)
actor_5.SetTexture(texture_5)
actor_5.SetPosition(-2, 2, 0)
actor_5.SetScale(2.0, 2.0, 2.0)

actor_6 = vtkActor()
actor_6.SetMapper(mapper)
actor_6.SetTexture(texture_6)
actor_6.SetPosition(0, 2, 0)
actor_6.SetScale(2.0, 2.0, 2.0)

actor_7 = vtkActor()
actor_7.SetMapper(mapper)
actor_7.SetTexture(texture_7)
actor_7.SetPosition(2, 2, 0)
actor_7.SetScale(2.0, 2.0, 2.0)

actor_8 = vtkActor()
actor_8.SetMapper(mapper)
actor_8.SetTexture(texture_8)
actor_8.SetPosition(-4, 0, 0)
actor_8.SetScale(2.0, 2.0, 2.0)

actor_9 = vtkActor()
actor_9.SetMapper(mapper)
actor_9.SetTexture(texture_9)
actor_9.SetPosition(-2, 0, 0)
actor_9.SetScale(2.0, 2.0, 2.0)

actor_10 = vtkActor()
actor_10.SetMapper(mapper)
actor_10.SetTexture(texture_10)
actor_10.SetPosition(0, 0, 0)
actor_10.SetScale(2.0, 2.0, 2.0)

actor_11 = vtkActor()
actor_11.SetMapper(mapper)
actor_11.SetTexture(texture_11)
actor_11.SetPosition(2, 0, 0)
actor_11.SetScale(2.0, 2.0, 2.0)

actor_12 = vtkActor()
actor_12.SetMapper(mapper)
actor_12.SetTexture(texture_12)
actor_12.SetPosition(-4, -2, 0)
actor_12.SetScale(2.0, 2.0, 2.0)

actor_13 = vtkActor()
actor_13.SetMapper(mapper)
actor_13.SetTexture(texture_13)
actor_13.SetPosition(-2, -2, 0)
actor_13.SetScale(2.0, 2.0, 2.0)

actor_14 = vtkActor()
actor_14.SetMapper(mapper)
actor_14.SetTexture(texture_14)
actor_14.SetPosition(0, -2, 0)
actor_14.SetScale(2.0, 2.0, 2.0)

actor_15 = vtkActor()
actor_15.SetMapper(mapper)
actor_15.SetTexture(texture_15)
actor_15.SetPosition(2, -2, 0)
actor_15.SetScale(2.0, 2.0, 2.0)

# Renderer.
renderer = vtkRenderer()
renderer.AddActor(actor_0)
renderer.AddActor(actor_1)
renderer.AddActor(actor_2)
renderer.AddActor(actor_3)
renderer.AddActor(actor_4)
renderer.AddActor(actor_5)
renderer.AddActor(actor_6)
renderer.AddActor(actor_7)
renderer.AddActor(actor_8)
renderer.AddActor(actor_9)
renderer.AddActor(actor_10)
renderer.AddActor(actor_11)
renderer.AddActor(actor_12)
renderer.AddActor(actor_13)
renderer.AddActor(actor_14)
renderer.AddActor(actor_15)
renderer.SetBackground(0.4392, 0.5020, 0.5647)

# Render window.
render_window = vtkRenderWindow()
render_window.SetSize(500, 500)
render_window.AddRenderer(renderer)
render_window.SetWindowName("quadric cut")

# Scene.
renderer.ResetCamera()
renderer.GetActiveCamera().Zoom(1.4)

interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)

interactor.Initialize()
interactor.Start()
