#!/usr/bin/env python
# Demonstrate structured grids of various dimensionalities (0D, 1D, 2D, 3D).

import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401

from vtkmodules.vtkCommonCore import vtkIdList, vtkPoints
from vtkmodules.vtkCommonDataModel import vtkGenericCell, vtkStructuredGrid
from vtkmodules.vtkFiltersGeometry import vtkStructuredGridGeometryFilter
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkPolyDataMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
)

cell = vtkGenericCell()
pt_ids = vtkIdList()

# 0D
zero_d_pts = vtkPoints()
zero_d_pts.SetNumberOfPoints(1)
zero_d_pts.SetPoint(0, 0, 0, 0)
zero_d_grid = vtkStructuredGrid()
zero_d_grid.SetDimensions(1, 1, 1)
zero_d_grid.SetPoints(zero_d_pts)
zero_d_grid.GetCell(0)
zero_d_grid.GetCell(0, cell)
zero_d_grid.GetCellPoints(0, pt_ids)
zero_d_geom = vtkStructuredGridGeometryFilter()
zero_d_geom.SetInputData(zero_d_grid)
zero_d_geom.SetExtent(0, 2, 0, 2, 0, 2)
zero_d_mapper = vtkPolyDataMapper()
zero_d_mapper.SetInputConnection(zero_d_geom.GetOutputPort())
zero_d_actor = vtkActor()
zero_d_actor.SetMapper(zero_d_mapper)
zero_d_actor.SetPosition(0, 0, 0)

# 1D - X
x_pts = vtkPoints()
x_pts.SetNumberOfPoints(2)
x_pts.SetPoint(0, 0, 0, 0)
x_pts.SetPoint(1, 1, 0, 0)
x_grid = vtkStructuredGrid()
x_grid.SetDimensions(2, 1, 1)
x_grid.SetPoints(x_pts)
x_grid.GetCell(0)
x_grid.GetCell(0, cell)
x_grid.GetCellPoints(0, pt_ids)
x_geom = vtkStructuredGridGeometryFilter()
x_geom.SetInputData(x_grid)
x_geom.SetExtent(0, 2, 0, 2, 0, 2)
x_mapper = vtkPolyDataMapper()
x_mapper.SetInputConnection(x_geom.GetOutputPort())
x_actor = vtkActor()
x_actor.SetMapper(x_mapper)
x_actor.SetPosition(2, 0, 0)

# 1D - Y
y_pts = vtkPoints()
y_pts.SetNumberOfPoints(2)
y_pts.SetPoint(0, 0, 0, 0)
y_pts.SetPoint(1, 0, 1, 0)
y_grid = vtkStructuredGrid()
y_grid.SetDimensions(1, 2, 1)
y_grid.SetPoints(y_pts)
y_grid.GetCell(0)
y_grid.GetCell(0, cell)
y_grid.GetCellPoints(0, pt_ids)
y_geom = vtkStructuredGridGeometryFilter()
y_geom.SetInputData(y_grid)
y_geom.SetExtent(0, 2, 0, 2, 0, 2)
y_mapper = vtkPolyDataMapper()
y_mapper.SetInputConnection(y_geom.GetOutputPort())
y_actor = vtkActor()
y_actor.SetMapper(y_mapper)
y_actor.SetPosition(4, 0, 0)

# 1D - Z
z_pts = vtkPoints()
z_pts.SetNumberOfPoints(2)
z_pts.SetPoint(0, 0, 0, 0)
z_pts.SetPoint(1, 0, 0, 1)
z_grid = vtkStructuredGrid()
z_grid.SetDimensions(1, 1, 2)
z_grid.SetPoints(z_pts)
z_grid.GetCell(0)
z_grid.GetCell(0, cell)
z_grid.GetCellPoints(0, pt_ids)
z_geom = vtkStructuredGridGeometryFilter()
z_geom.SetInputData(z_grid)
z_geom.SetExtent(0, 2, 0, 2, 0, 2)
z_mapper = vtkPolyDataMapper()
z_mapper.SetInputConnection(z_geom.GetOutputPort())
z_actor = vtkActor()
z_actor.SetMapper(z_mapper)
z_actor.SetPosition(6, 0, 0)

# 2D - XY
xy_pts = vtkPoints()
xy_pts.SetNumberOfPoints(4)
xy_pts.SetPoint(0, 0, 0, 0)
xy_pts.SetPoint(1, 1, 0, 0)
xy_pts.SetPoint(2, 0, 1, 0)
xy_pts.SetPoint(3, 1, 1, 0)
xy_grid = vtkStructuredGrid()
xy_grid.SetDimensions(2, 2, 1)
xy_grid.SetPoints(xy_pts)
xy_grid.GetCell(0)
xy_grid.GetCell(0, cell)
xy_grid.GetCellPoints(0, pt_ids)
xy_geom = vtkStructuredGridGeometryFilter()
xy_geom.SetInputData(xy_grid)
xy_geom.SetExtent(0, 2, 0, 2, 0, 2)
xy_mapper = vtkPolyDataMapper()
xy_mapper.SetInputConnection(xy_geom.GetOutputPort())
xy_actor = vtkActor()
xy_actor.SetMapper(xy_mapper)
xy_actor.SetPosition(0, 2, 0)

# 2D - YZ
yz_pts = vtkPoints()
yz_pts.SetNumberOfPoints(4)
yz_pts.SetPoint(0, 0, 0, 0)
yz_pts.SetPoint(1, 0, 1, 0)
yz_pts.SetPoint(2, 0, 0, 1)
yz_pts.SetPoint(3, 0, 1, 1)
yz_grid = vtkStructuredGrid()
yz_grid.SetDimensions(1, 2, 2)
yz_grid.SetPoints(yz_pts)
yz_grid.GetCell(0)
yz_grid.GetCell(0, cell)
yz_grid.GetCellPoints(0, pt_ids)
yz_geom = vtkStructuredGridGeometryFilter()
yz_geom.SetInputData(yz_grid)
yz_geom.SetExtent(0, 2, 0, 2, 0, 2)
yz_mapper = vtkPolyDataMapper()
yz_mapper.SetInputConnection(yz_geom.GetOutputPort())
yz_actor = vtkActor()
yz_actor.SetMapper(yz_mapper)
yz_actor.SetPosition(2, 2, 0)

# 2D - XZ
xz_pts = vtkPoints()
xz_pts.SetNumberOfPoints(4)
xz_pts.SetPoint(0, 0, 0, 0)
xz_pts.SetPoint(1, 1, 0, 0)
xz_pts.SetPoint(2, 0, 0, 1)
xz_pts.SetPoint(3, 1, 0, 1)
xz_grid = vtkStructuredGrid()
xz_grid.SetDimensions(2, 1, 2)
xz_grid.SetPoints(xz_pts)
xz_grid.GetCell(0)
xz_grid.GetCell(0, cell)
xz_grid.GetCellPoints(0, pt_ids)
xz_geom = vtkStructuredGridGeometryFilter()
xz_geom.SetInputData(xz_grid)
xz_geom.SetExtent(0, 2, 0, 2, 0, 2)
xz_mapper = vtkPolyDataMapper()
xz_mapper.SetInputConnection(xz_geom.GetOutputPort())
xz_actor = vtkActor()
xz_actor.SetMapper(xz_mapper)
xz_actor.SetPosition(4, 2, 0)

# 3D
xyz_pts = vtkPoints()
xyz_pts.SetNumberOfPoints(8)
xyz_pts.SetPoint(0, 0, 0, 0)
xyz_pts.SetPoint(1, 1, 0, 0)
xyz_pts.SetPoint(2, 0, 1, 0)
xyz_pts.SetPoint(3, 1, 1, 0)
xyz_pts.SetPoint(4, 0, 0, 1)
xyz_pts.SetPoint(5, 1, 0, 1)
xyz_pts.SetPoint(6, 0, 1, 1)
xyz_pts.SetPoint(7, 1, 1, 1)
xyz_grid = vtkStructuredGrid()
xyz_grid.SetDimensions(2, 2, 2)
xyz_grid.SetPoints(xyz_pts)
xyz_grid.GetCell(0)
xyz_grid.GetCell(0, cell)
xyz_grid.GetCellPoints(0, pt_ids)
xyz_geom = vtkStructuredGridGeometryFilter()
xyz_geom.SetInputData(xyz_grid)
xyz_geom.SetExtent(0, 2, 0, 2, 0, 2)
xyz_mapper = vtkPolyDataMapper()
xyz_mapper.SetInputConnection(xyz_geom.GetOutputPort())
xyz_actor = vtkActor()
xyz_actor.SetMapper(xyz_mapper)
xyz_actor.SetPosition(6, 2, 0)

renderer = vtkRenderer()
renderer.GetCullers().RemoveAllItems()
renderer.AddActor(zero_d_actor)
renderer.AddActor(x_actor)
renderer.AddActor(y_actor)
renderer.AddActor(z_actor)
renderer.AddActor(xy_actor)
renderer.AddActor(yz_actor)
renderer.AddActor(xz_actor)
renderer.AddActor(xyz_actor)

render_window = vtkRenderWindow()
render_window.SetSize(300, 150)
render_window.AddRenderer(renderer)
render_window.SetWindowName("structuredgrid")

cam = renderer.GetActiveCamera()
cam.SetClippingRange(2.27407, 14.9819)
cam.SetFocalPoint(3.1957, 1.74012, 0.176603)
cam.SetPosition(-0.380779, 6.13894, 5.59404)
cam.SetViewUp(0.137568, 0.811424, -0.568037)

interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)

interactor.Initialize()
interactor.Start()
