#!/usr/bin/env python

# Generate labeled blob volumes, extract discrete isosurfaces, and
# smooth them with vtkWindowedSincPolyDataFilter.

# Factory overrides: importing these modules registers the OpenGL rendering
# and interaction style implementations for vtkRenderingCore factory classes.
import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401
# VTK pipeline classes used in this example
from vtkmodules.vtkCommonCore import vtkLookupTable
from vtkmodules.vtkCommonDataModel import (
    vtkImageData,
    vtkSphere,
)
from vtkmodules.vtkFiltersCore import vtkWindowedSincPolyDataFilter
from vtkmodules.vtkFiltersGeneral import vtkDiscreteMarchingCubes
from vtkmodules.vtkImagingCore import vtkImageThreshold
from vtkmodules.vtkImagingHybrid import vtkSampleFunction
from vtkmodules.vtkImagingMath import vtkImageMathematics
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkPolyDataMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
)

# Colors (normalized RGB)
burlywood_background_rgb = (0.871, 0.722, 0.529)


# Datasets: sphere centers for 20 labeled blobs
n_labels = 20
radius = 8
sample_dims = (100, 100, 100)
model_bounds = (-50, 50, -50, 50, -50, 50)
threshold_value = radius * radius
centers = [
    (11, 21, 11), (-10, 4, 1), (14, 22, 16), (31, 22, -12),
    (-26, -26, -6), (-31, -13, 31), (-29, 8, 13), (-17, 28, -30),
    (-9, -32, 2), (16, -17, -26), (27, 13, 11), (-1, -26, 17),
    (3, 9, 15), (0, 7, -15), (23, 6, -32), (-10, 28, -31),
    (26, 5, 17), (-30, 22, -9), (-25, -32, 6), (-25, 0, -4),
]

# Source: build a labeled volume by compositing thresholded sphere samples
blob_image = vtkImageData()

sphere_0 = vtkSphere()
sphere_0.SetRadius(radius)
sphere_0.SetCenter(centers[0])
sampler_0 = vtkSampleFunction()
sampler_0.SetImplicitFunction(sphere_0)
sampler_0.SetOutputScalarTypeToFloat()
sampler_0.SetSampleDimensions(*sample_dims)
sampler_0.SetModelBounds(*model_bounds)
thres_0 = vtkImageThreshold()
thres_0.SetInputConnection(sampler_0.GetOutputPort())
thres_0.ThresholdByLower(threshold_value)
thres_0.ReplaceInOn()
thres_0.ReplaceOutOn()
thres_0.SetInValue(1)
thres_0.SetOutValue(0)
thres_0.Update()
blob_image.DeepCopy(thres_0.GetOutput())
max_0 = vtkImageMathematics()
max_0.SetInputData(0, blob_image)
max_0.SetInputData(1, thres_0.GetOutput())
max_0.SetOperationToMax()
max_0.Modified()
max_0.Update()
blob_image.DeepCopy(max_0.GetOutput())

sphere_1 = vtkSphere()
sphere_1.SetRadius(radius)
sphere_1.SetCenter(centers[1])
sampler_1 = vtkSampleFunction()
sampler_1.SetImplicitFunction(sphere_1)
sampler_1.SetOutputScalarTypeToFloat()
sampler_1.SetSampleDimensions(*sample_dims)
sampler_1.SetModelBounds(*model_bounds)
thres_1 = vtkImageThreshold()
thres_1.SetInputConnection(sampler_1.GetOutputPort())
thres_1.ThresholdByLower(threshold_value)
thres_1.ReplaceInOn()
thres_1.ReplaceOutOn()
thres_1.SetInValue(2)
thres_1.SetOutValue(0)
thres_1.Update()
max_1 = vtkImageMathematics()
max_1.SetInputData(0, blob_image)
max_1.SetInputData(1, thres_1.GetOutput())
max_1.SetOperationToMax()
max_1.Modified()
max_1.Update()
blob_image.DeepCopy(max_1.GetOutput())

sphere_2 = vtkSphere()
sphere_2.SetRadius(radius)
sphere_2.SetCenter(centers[2])
sampler_2 = vtkSampleFunction()
sampler_2.SetImplicitFunction(sphere_2)
sampler_2.SetOutputScalarTypeToFloat()
sampler_2.SetSampleDimensions(*sample_dims)
sampler_2.SetModelBounds(*model_bounds)
thres_2 = vtkImageThreshold()
thres_2.SetInputConnection(sampler_2.GetOutputPort())
thres_2.ThresholdByLower(threshold_value)
thres_2.ReplaceInOn()
thres_2.ReplaceOutOn()
thres_2.SetInValue(3)
thres_2.SetOutValue(0)
thres_2.Update()
max_2 = vtkImageMathematics()
max_2.SetInputData(0, blob_image)
max_2.SetInputData(1, thres_2.GetOutput())
max_2.SetOperationToMax()
max_2.Modified()
max_2.Update()
blob_image.DeepCopy(max_2.GetOutput())

sphere_3 = vtkSphere()
sphere_3.SetRadius(radius)
sphere_3.SetCenter(centers[3])
sampler_3 = vtkSampleFunction()
sampler_3.SetImplicitFunction(sphere_3)
sampler_3.SetOutputScalarTypeToFloat()
sampler_3.SetSampleDimensions(*sample_dims)
sampler_3.SetModelBounds(*model_bounds)
thres_3 = vtkImageThreshold()
thres_3.SetInputConnection(sampler_3.GetOutputPort())
thres_3.ThresholdByLower(threshold_value)
thres_3.ReplaceInOn()
thres_3.ReplaceOutOn()
thres_3.SetInValue(4)
thres_3.SetOutValue(0)
thres_3.Update()
max_3 = vtkImageMathematics()
max_3.SetInputData(0, blob_image)
max_3.SetInputData(1, thres_3.GetOutput())
max_3.SetOperationToMax()
max_3.Modified()
max_3.Update()
blob_image.DeepCopy(max_3.GetOutput())

sphere_4 = vtkSphere()
sphere_4.SetRadius(radius)
sphere_4.SetCenter(centers[4])
sampler_4 = vtkSampleFunction()
sampler_4.SetImplicitFunction(sphere_4)
sampler_4.SetOutputScalarTypeToFloat()
sampler_4.SetSampleDimensions(*sample_dims)
sampler_4.SetModelBounds(*model_bounds)
thres_4 = vtkImageThreshold()
thres_4.SetInputConnection(sampler_4.GetOutputPort())
thres_4.ThresholdByLower(threshold_value)
thres_4.ReplaceInOn()
thres_4.ReplaceOutOn()
thres_4.SetInValue(5)
thres_4.SetOutValue(0)
thres_4.Update()
max_4 = vtkImageMathematics()
max_4.SetInputData(0, blob_image)
max_4.SetInputData(1, thres_4.GetOutput())
max_4.SetOperationToMax()
max_4.Modified()
max_4.Update()
blob_image.DeepCopy(max_4.GetOutput())

sphere_5 = vtkSphere()
sphere_5.SetRadius(radius)
sphere_5.SetCenter(centers[5])
sampler_5 = vtkSampleFunction()
sampler_5.SetImplicitFunction(sphere_5)
sampler_5.SetOutputScalarTypeToFloat()
sampler_5.SetSampleDimensions(*sample_dims)
sampler_5.SetModelBounds(*model_bounds)
thres_5 = vtkImageThreshold()
thres_5.SetInputConnection(sampler_5.GetOutputPort())
thres_5.ThresholdByLower(threshold_value)
thres_5.ReplaceInOn()
thres_5.ReplaceOutOn()
thres_5.SetInValue(6)
thres_5.SetOutValue(0)
thres_5.Update()
max_5 = vtkImageMathematics()
max_5.SetInputData(0, blob_image)
max_5.SetInputData(1, thres_5.GetOutput())
max_5.SetOperationToMax()
max_5.Modified()
max_5.Update()
blob_image.DeepCopy(max_5.GetOutput())

sphere_6 = vtkSphere()
sphere_6.SetRadius(radius)
sphere_6.SetCenter(centers[6])
sampler_6 = vtkSampleFunction()
sampler_6.SetImplicitFunction(sphere_6)
sampler_6.SetOutputScalarTypeToFloat()
sampler_6.SetSampleDimensions(*sample_dims)
sampler_6.SetModelBounds(*model_bounds)
thres_6 = vtkImageThreshold()
thres_6.SetInputConnection(sampler_6.GetOutputPort())
thres_6.ThresholdByLower(threshold_value)
thres_6.ReplaceInOn()
thres_6.ReplaceOutOn()
thres_6.SetInValue(7)
thres_6.SetOutValue(0)
thres_6.Update()
max_6 = vtkImageMathematics()
max_6.SetInputData(0, blob_image)
max_6.SetInputData(1, thres_6.GetOutput())
max_6.SetOperationToMax()
max_6.Modified()
max_6.Update()
blob_image.DeepCopy(max_6.GetOutput())

sphere_7 = vtkSphere()
sphere_7.SetRadius(radius)
sphere_7.SetCenter(centers[7])
sampler_7 = vtkSampleFunction()
sampler_7.SetImplicitFunction(sphere_7)
sampler_7.SetOutputScalarTypeToFloat()
sampler_7.SetSampleDimensions(*sample_dims)
sampler_7.SetModelBounds(*model_bounds)
thres_7 = vtkImageThreshold()
thres_7.SetInputConnection(sampler_7.GetOutputPort())
thres_7.ThresholdByLower(threshold_value)
thres_7.ReplaceInOn()
thres_7.ReplaceOutOn()
thres_7.SetInValue(8)
thres_7.SetOutValue(0)
thres_7.Update()
max_7 = vtkImageMathematics()
max_7.SetInputData(0, blob_image)
max_7.SetInputData(1, thres_7.GetOutput())
max_7.SetOperationToMax()
max_7.Modified()
max_7.Update()
blob_image.DeepCopy(max_7.GetOutput())

sphere_8 = vtkSphere()
sphere_8.SetRadius(radius)
sphere_8.SetCenter(centers[8])
sampler_8 = vtkSampleFunction()
sampler_8.SetImplicitFunction(sphere_8)
sampler_8.SetOutputScalarTypeToFloat()
sampler_8.SetSampleDimensions(*sample_dims)
sampler_8.SetModelBounds(*model_bounds)
thres_8 = vtkImageThreshold()
thres_8.SetInputConnection(sampler_8.GetOutputPort())
thres_8.ThresholdByLower(threshold_value)
thres_8.ReplaceInOn()
thres_8.ReplaceOutOn()
thres_8.SetInValue(9)
thres_8.SetOutValue(0)
thres_8.Update()
max_8 = vtkImageMathematics()
max_8.SetInputData(0, blob_image)
max_8.SetInputData(1, thres_8.GetOutput())
max_8.SetOperationToMax()
max_8.Modified()
max_8.Update()
blob_image.DeepCopy(max_8.GetOutput())

sphere_9 = vtkSphere()
sphere_9.SetRadius(radius)
sphere_9.SetCenter(centers[9])
sampler_9 = vtkSampleFunction()
sampler_9.SetImplicitFunction(sphere_9)
sampler_9.SetOutputScalarTypeToFloat()
sampler_9.SetSampleDimensions(*sample_dims)
sampler_9.SetModelBounds(*model_bounds)
thres_9 = vtkImageThreshold()
thres_9.SetInputConnection(sampler_9.GetOutputPort())
thres_9.ThresholdByLower(threshold_value)
thres_9.ReplaceInOn()
thres_9.ReplaceOutOn()
thres_9.SetInValue(10)
thres_9.SetOutValue(0)
thres_9.Update()
max_9 = vtkImageMathematics()
max_9.SetInputData(0, blob_image)
max_9.SetInputData(1, thres_9.GetOutput())
max_9.SetOperationToMax()
max_9.Modified()
max_9.Update()
blob_image.DeepCopy(max_9.GetOutput())

sphere_10 = vtkSphere()
sphere_10.SetRadius(radius)
sphere_10.SetCenter(centers[10])
sampler_10 = vtkSampleFunction()
sampler_10.SetImplicitFunction(sphere_10)
sampler_10.SetOutputScalarTypeToFloat()
sampler_10.SetSampleDimensions(*sample_dims)
sampler_10.SetModelBounds(*model_bounds)
thres_10 = vtkImageThreshold()
thres_10.SetInputConnection(sampler_10.GetOutputPort())
thres_10.ThresholdByLower(threshold_value)
thres_10.ReplaceInOn()
thres_10.ReplaceOutOn()
thres_10.SetInValue(11)
thres_10.SetOutValue(0)
thres_10.Update()
max_10 = vtkImageMathematics()
max_10.SetInputData(0, blob_image)
max_10.SetInputData(1, thres_10.GetOutput())
max_10.SetOperationToMax()
max_10.Modified()
max_10.Update()
blob_image.DeepCopy(max_10.GetOutput())

sphere_11 = vtkSphere()
sphere_11.SetRadius(radius)
sphere_11.SetCenter(centers[11])
sampler_11 = vtkSampleFunction()
sampler_11.SetImplicitFunction(sphere_11)
sampler_11.SetOutputScalarTypeToFloat()
sampler_11.SetSampleDimensions(*sample_dims)
sampler_11.SetModelBounds(*model_bounds)
thres_11 = vtkImageThreshold()
thres_11.SetInputConnection(sampler_11.GetOutputPort())
thres_11.ThresholdByLower(threshold_value)
thres_11.ReplaceInOn()
thres_11.ReplaceOutOn()
thres_11.SetInValue(12)
thres_11.SetOutValue(0)
thres_11.Update()
max_11 = vtkImageMathematics()
max_11.SetInputData(0, blob_image)
max_11.SetInputData(1, thres_11.GetOutput())
max_11.SetOperationToMax()
max_11.Modified()
max_11.Update()
blob_image.DeepCopy(max_11.GetOutput())

sphere_12 = vtkSphere()
sphere_12.SetRadius(radius)
sphere_12.SetCenter(centers[12])
sampler_12 = vtkSampleFunction()
sampler_12.SetImplicitFunction(sphere_12)
sampler_12.SetOutputScalarTypeToFloat()
sampler_12.SetSampleDimensions(*sample_dims)
sampler_12.SetModelBounds(*model_bounds)
thres_12 = vtkImageThreshold()
thres_12.SetInputConnection(sampler_12.GetOutputPort())
thres_12.ThresholdByLower(threshold_value)
thres_12.ReplaceInOn()
thres_12.ReplaceOutOn()
thres_12.SetInValue(13)
thres_12.SetOutValue(0)
thres_12.Update()
max_12 = vtkImageMathematics()
max_12.SetInputData(0, blob_image)
max_12.SetInputData(1, thres_12.GetOutput())
max_12.SetOperationToMax()
max_12.Modified()
max_12.Update()
blob_image.DeepCopy(max_12.GetOutput())

sphere_13 = vtkSphere()
sphere_13.SetRadius(radius)
sphere_13.SetCenter(centers[13])
sampler_13 = vtkSampleFunction()
sampler_13.SetImplicitFunction(sphere_13)
sampler_13.SetOutputScalarTypeToFloat()
sampler_13.SetSampleDimensions(*sample_dims)
sampler_13.SetModelBounds(*model_bounds)
thres_13 = vtkImageThreshold()
thres_13.SetInputConnection(sampler_13.GetOutputPort())
thres_13.ThresholdByLower(threshold_value)
thres_13.ReplaceInOn()
thres_13.ReplaceOutOn()
thres_13.SetInValue(14)
thres_13.SetOutValue(0)
thres_13.Update()
max_13 = vtkImageMathematics()
max_13.SetInputData(0, blob_image)
max_13.SetInputData(1, thres_13.GetOutput())
max_13.SetOperationToMax()
max_13.Modified()
max_13.Update()
blob_image.DeepCopy(max_13.GetOutput())

sphere_14 = vtkSphere()
sphere_14.SetRadius(radius)
sphere_14.SetCenter(centers[14])
sampler_14 = vtkSampleFunction()
sampler_14.SetImplicitFunction(sphere_14)
sampler_14.SetOutputScalarTypeToFloat()
sampler_14.SetSampleDimensions(*sample_dims)
sampler_14.SetModelBounds(*model_bounds)
thres_14 = vtkImageThreshold()
thres_14.SetInputConnection(sampler_14.GetOutputPort())
thres_14.ThresholdByLower(threshold_value)
thres_14.ReplaceInOn()
thres_14.ReplaceOutOn()
thres_14.SetInValue(15)
thres_14.SetOutValue(0)
thres_14.Update()
max_14 = vtkImageMathematics()
max_14.SetInputData(0, blob_image)
max_14.SetInputData(1, thres_14.GetOutput())
max_14.SetOperationToMax()
max_14.Modified()
max_14.Update()
blob_image.DeepCopy(max_14.GetOutput())

sphere_15 = vtkSphere()
sphere_15.SetRadius(radius)
sphere_15.SetCenter(centers[15])
sampler_15 = vtkSampleFunction()
sampler_15.SetImplicitFunction(sphere_15)
sampler_15.SetOutputScalarTypeToFloat()
sampler_15.SetSampleDimensions(*sample_dims)
sampler_15.SetModelBounds(*model_bounds)
thres_15 = vtkImageThreshold()
thres_15.SetInputConnection(sampler_15.GetOutputPort())
thres_15.ThresholdByLower(threshold_value)
thres_15.ReplaceInOn()
thres_15.ReplaceOutOn()
thres_15.SetInValue(16)
thres_15.SetOutValue(0)
thres_15.Update()
max_15 = vtkImageMathematics()
max_15.SetInputData(0, blob_image)
max_15.SetInputData(1, thres_15.GetOutput())
max_15.SetOperationToMax()
max_15.Modified()
max_15.Update()
blob_image.DeepCopy(max_15.GetOutput())

sphere_16 = vtkSphere()
sphere_16.SetRadius(radius)
sphere_16.SetCenter(centers[16])
sampler_16 = vtkSampleFunction()
sampler_16.SetImplicitFunction(sphere_16)
sampler_16.SetOutputScalarTypeToFloat()
sampler_16.SetSampleDimensions(*sample_dims)
sampler_16.SetModelBounds(*model_bounds)
thres_16 = vtkImageThreshold()
thres_16.SetInputConnection(sampler_16.GetOutputPort())
thres_16.ThresholdByLower(threshold_value)
thres_16.ReplaceInOn()
thres_16.ReplaceOutOn()
thres_16.SetInValue(17)
thres_16.SetOutValue(0)
thres_16.Update()
max_16 = vtkImageMathematics()
max_16.SetInputData(0, blob_image)
max_16.SetInputData(1, thres_16.GetOutput())
max_16.SetOperationToMax()
max_16.Modified()
max_16.Update()
blob_image.DeepCopy(max_16.GetOutput())

sphere_17 = vtkSphere()
sphere_17.SetRadius(radius)
sphere_17.SetCenter(centers[17])
sampler_17 = vtkSampleFunction()
sampler_17.SetImplicitFunction(sphere_17)
sampler_17.SetOutputScalarTypeToFloat()
sampler_17.SetSampleDimensions(*sample_dims)
sampler_17.SetModelBounds(*model_bounds)
thres_17 = vtkImageThreshold()
thres_17.SetInputConnection(sampler_17.GetOutputPort())
thres_17.ThresholdByLower(threshold_value)
thres_17.ReplaceInOn()
thres_17.ReplaceOutOn()
thres_17.SetInValue(18)
thres_17.SetOutValue(0)
thres_17.Update()
max_17 = vtkImageMathematics()
max_17.SetInputData(0, blob_image)
max_17.SetInputData(1, thres_17.GetOutput())
max_17.SetOperationToMax()
max_17.Modified()
max_17.Update()
blob_image.DeepCopy(max_17.GetOutput())

sphere_18 = vtkSphere()
sphere_18.SetRadius(radius)
sphere_18.SetCenter(centers[18])
sampler_18 = vtkSampleFunction()
sampler_18.SetImplicitFunction(sphere_18)
sampler_18.SetOutputScalarTypeToFloat()
sampler_18.SetSampleDimensions(*sample_dims)
sampler_18.SetModelBounds(*model_bounds)
thres_18 = vtkImageThreshold()
thres_18.SetInputConnection(sampler_18.GetOutputPort())
thres_18.ThresholdByLower(threshold_value)
thres_18.ReplaceInOn()
thres_18.ReplaceOutOn()
thres_18.SetInValue(19)
thres_18.SetOutValue(0)
thres_18.Update()
max_18 = vtkImageMathematics()
max_18.SetInputData(0, blob_image)
max_18.SetInputData(1, thres_18.GetOutput())
max_18.SetOperationToMax()
max_18.Modified()
max_18.Update()
blob_image.DeepCopy(max_18.GetOutput())

sphere_19 = vtkSphere()
sphere_19.SetRadius(radius)
sphere_19.SetCenter(centers[19])
sampler_19 = vtkSampleFunction()
sampler_19.SetImplicitFunction(sphere_19)
sampler_19.SetOutputScalarTypeToFloat()
sampler_19.SetSampleDimensions(*sample_dims)
sampler_19.SetModelBounds(*model_bounds)
thres_19 = vtkImageThreshold()
thres_19.SetInputConnection(sampler_19.GetOutputPort())
thres_19.ThresholdByLower(threshold_value)
thres_19.ReplaceInOn()
thres_19.ReplaceOutOn()
thres_19.SetInValue(20)
thres_19.SetOutValue(0)
thres_19.Update()
max_19 = vtkImageMathematics()
max_19.SetInputData(0, blob_image)
max_19.SetInputData(1, thres_19.GetOutput())
max_19.SetOperationToMax()
max_19.Modified()
max_19.Update()
blob_image.DeepCopy(max_19.GetOutput())

# Filter: extract discrete isosurfaces
discrete = vtkDiscreteMarchingCubes()
discrete.SetInputData(blob_image)
discrete.GenerateValues(n_labels, 1, n_labels)

# Filter: smooth the discrete surfaces
smoother = vtkWindowedSincPolyDataFilter()
smoother.SetInputConnection(discrete.GetOutputPort())
smoother.SetNumberOfIterations(15)
smoother.BoundarySmoothingOff()
smoother.FeatureEdgeSmoothingOff()
smoother.SetFeatureAngle(120.0)
smoother.SetPassBand(0.001)
smoother.NonManifoldSmoothingOn()
smoother.NormalizeCoordinatesOn()
smoother.Update()

# Lookup table: per-label colors
lut = vtkLookupTable()
lut.SetNumberOfColors(n_labels)
lut.SetTableRange(0, n_labels - 1)
lut.SetScaleToLinear()
lut.Build()
lut.SetTableValue(0, 0.000, 0.000, 0.000, 1.0)
lut.SetTableValue(1, 0.805, 0.889, 0.798, 1.0)
lut.SetTableValue(2, 0.605, 0.738, 0.714, 1.0)
lut.SetTableValue(3, 0.827, 0.897, 0.843, 1.0)
lut.SetTableValue(4, 0.976, 0.895, 0.589, 1.0)
lut.SetTableValue(5, 0.462, 0.466, 0.639, 1.0)
lut.SetTableValue(6, 0.423, 0.580, 0.974, 1.0)
lut.SetTableValue(7, 0.443, 0.775, 0.820, 1.0)
lut.SetTableValue(8, 0.546, 0.947, 0.433, 1.0)
lut.SetTableValue(9, 0.612, 0.414, 0.720, 1.0)
lut.SetTableValue(10, 0.843, 0.542, 0.464, 1.0)
lut.SetTableValue(11, 0.939, 0.816, 0.803, 1.0)
lut.SetTableValue(12, 0.685, 0.466, 0.855, 1.0)
lut.SetTableValue(13, 0.730, 0.779, 0.841, 1.0)
lut.SetTableValue(14, 0.708, 0.767, 0.560, 1.0)
lut.SetTableValue(15, 0.910, 0.754, 0.412, 1.0)
lut.SetTableValue(16, 0.610, 0.947, 0.425, 1.0)
lut.SetTableValue(17, 0.937, 0.747, 0.852, 1.0)
lut.SetTableValue(18, 0.432, 0.900, 0.615, 1.0)
lut.SetTableValue(19, 0.478, 0.409, 0.757, 1.0)

# Mapper: color by label
mapper = vtkPolyDataMapper()
mapper.SetInputConnection(smoother.GetOutputPort())
mapper.SetLookupTable(lut)
mapper.SetScalarRange(0, lut.GetNumberOfColors())

# Actor: the smoothed discrete isosurfaces
actor = vtkActor()
actor.SetMapper(mapper)

# Renderer: assemble the scene
renderer = vtkRenderer()
renderer.AddActor(actor)
renderer.SetBackground(burlywood_background_rgb)

# Window: display the rendered scene
render_window = vtkRenderWindow()
render_window.AddRenderer(renderer)
render_window.SetWindowName("smooth discrete marching cubes")
render_window.SetMultiSamples(0)
render_window.SetSize(640, 480)

# Interactor: handle mouse and keyboard events
render_window_interactor = vtkRenderWindowInteractor()
render_window_interactor.SetRenderWindow(render_window)

# Launch the interactive visualization
render_window_interactor.Initialize()
render_window_interactor.Start()
