#!/usr/bin/env python

# Generate smoothed surface models from a labeled segmentation volume using
# vtkDiscreteFlyingEdges3D.  Each label produces a separate isosurface that
# is smoothed with a windowed sinc filter and displayed in a single scene.

import os
from pathlib import Path

# Factory overrides: importing these modules registers the OpenGL rendering
# and interaction style implementations for vtkRenderingCore factory classes.
import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401

# VTK pipeline classes used in this example
from vtkmodules.vtkCommonDataModel import (
    vtkDataObject,
    vtkDataSetAttributes,
)
from vtkmodules.vtkFiltersCore import (
    vtkMaskFields,
    vtkThreshold,
    vtkWindowedSincPolyDataFilter,
)
from vtkmodules.vtkFiltersGeneral import vtkDiscreteFlyingEdges3D
from vtkmodules.vtkFiltersGeometry import vtkGeometryFilter
from vtkmodules.vtkIOImage import vtkMetaImageReader
from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkPolyDataMapper,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
)

# Colors (normalized RGB)
dark_slate_blue_rgb = (0.282, 0.239, 0.545)

# Data directory: defaults to the folder containing this script
data_dir = Path(os.environ.get("VPE_DATA_DIR", Path(__file__).parent))

# Label range and smoothing parameters
start_label = 1
end_label = 29
smoothing_iterations = 15
pass_band = 0.001
feature_angle = 120.0

# Reader: load the labeled frog-tissue volume
reader = vtkMetaImageReader()
reader.SetFileName(str(data_dir / "Frog" / "frogtissue.mhd"))

# DiscreteFlyingEdges3D: generate isosurfaces for each label value
discrete_cubes = vtkDiscreteFlyingEdges3D()
discrete_cubes.SetInputConnection(reader.GetOutputPort())
discrete_cubes.GenerateValues(end_label - start_label + 1, start_label, end_label)

# Smoother: smooth the label surfaces while preserving boundaries
smoother = vtkWindowedSincPolyDataFilter()
smoother.SetInputConnection(discrete_cubes.GetOutputPort())
smoother.SetNumberOfIterations(smoothing_iterations)
smoother.BoundarySmoothingOff()
smoother.FeatureEdgeSmoothingOff()
smoother.SetFeatureAngle(feature_angle)
smoother.SetPassBand(pass_band)
smoother.NonManifoldSmoothingOn()
smoother.NormalizeCoordinatesOn()
smoother.Update()

# Renderer: assemble all label surfaces into one scene
renderer = vtkRenderer()
renderer.SetBackground(dark_slate_blue_rgb)

# ---- Label 1 ----
selector_1 = vtkThreshold()
selector_1.SetInputConnection(smoother.GetOutputPort())
selector_1.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_1.SetLowerThreshold(1)
selector_1.SetUpperThreshold(1)
scalars_off_1 = vtkMaskFields()
scalars_off_1.SetInputConnection(selector_1.GetOutputPort())
scalars_off_1.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_1.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_1 = vtkGeometryFilter()
geometry_1.SetInputConnection(scalars_off_1.GetOutputPort())
mapper_1 = vtkPolyDataMapper()
mapper_1.SetInputConnection(geometry_1.GetOutputPort())
mapper_1.ScalarVisibilityOff()
actor_1 = vtkActor()
actor_1.SetMapper(mapper_1)
actor_1.GetProperty().SetColor(1.0000, 0.7000, 0.0000)
renderer.AddActor(actor_1)

# ---- Label 2 ----
selector_2 = vtkThreshold()
selector_2.SetInputConnection(smoother.GetOutputPort())
selector_2.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_2.SetLowerThreshold(2)
selector_2.SetUpperThreshold(2)
scalars_off_2 = vtkMaskFields()
scalars_off_2.SetInputConnection(selector_2.GetOutputPort())
scalars_off_2.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_2.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_2 = vtkGeometryFilter()
geometry_2.SetInputConnection(scalars_off_2.GetOutputPort())
mapper_2 = vtkPolyDataMapper()
mapper_2.SetInputConnection(geometry_2.GetOutputPort())
mapper_2.ScalarVisibilityOff()
actor_2 = vtkActor()
actor_2.SetMapper(mapper_2)
actor_2.GetProperty().SetColor(0.9643, 0.6750, 0.0250)
renderer.AddActor(actor_2)

# ---- Label 3 ----
selector_3 = vtkThreshold()
selector_3.SetInputConnection(smoother.GetOutputPort())
selector_3.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_3.SetLowerThreshold(3)
selector_3.SetUpperThreshold(3)
scalars_off_3 = vtkMaskFields()
scalars_off_3.SetInputConnection(selector_3.GetOutputPort())
scalars_off_3.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_3.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_3 = vtkGeometryFilter()
geometry_3.SetInputConnection(scalars_off_3.GetOutputPort())
mapper_3 = vtkPolyDataMapper()
mapper_3.SetInputConnection(geometry_3.GetOutputPort())
mapper_3.ScalarVisibilityOff()
actor_3 = vtkActor()
actor_3.SetMapper(mapper_3)
actor_3.GetProperty().SetColor(0.9286, 0.6500, 0.0500)
renderer.AddActor(actor_3)

# ---- Label 4 ----
selector_4 = vtkThreshold()
selector_4.SetInputConnection(smoother.GetOutputPort())
selector_4.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_4.SetLowerThreshold(4)
selector_4.SetUpperThreshold(4)
scalars_off_4 = vtkMaskFields()
scalars_off_4.SetInputConnection(selector_4.GetOutputPort())
scalars_off_4.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_4.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_4 = vtkGeometryFilter()
geometry_4.SetInputConnection(scalars_off_4.GetOutputPort())
mapper_4 = vtkPolyDataMapper()
mapper_4.SetInputConnection(geometry_4.GetOutputPort())
mapper_4.ScalarVisibilityOff()
actor_4 = vtkActor()
actor_4.SetMapper(mapper_4)
actor_4.GetProperty().SetColor(0.8929, 0.6250, 0.0750)
renderer.AddActor(actor_4)

# ---- Label 5 ----
selector_5 = vtkThreshold()
selector_5.SetInputConnection(smoother.GetOutputPort())
selector_5.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_5.SetLowerThreshold(5)
selector_5.SetUpperThreshold(5)
scalars_off_5 = vtkMaskFields()
scalars_off_5.SetInputConnection(selector_5.GetOutputPort())
scalars_off_5.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_5.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_5 = vtkGeometryFilter()
geometry_5.SetInputConnection(scalars_off_5.GetOutputPort())
mapper_5 = vtkPolyDataMapper()
mapper_5.SetInputConnection(geometry_5.GetOutputPort())
mapper_5.ScalarVisibilityOff()
actor_5 = vtkActor()
actor_5.SetMapper(mapper_5)
actor_5.GetProperty().SetColor(0.8571, 0.6000, 0.1000)
renderer.AddActor(actor_5)

# ---- Label 6 ----
selector_6 = vtkThreshold()
selector_6.SetInputConnection(smoother.GetOutputPort())
selector_6.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_6.SetLowerThreshold(6)
selector_6.SetUpperThreshold(6)
scalars_off_6 = vtkMaskFields()
scalars_off_6.SetInputConnection(selector_6.GetOutputPort())
scalars_off_6.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_6.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_6 = vtkGeometryFilter()
geometry_6.SetInputConnection(scalars_off_6.GetOutputPort())
mapper_6 = vtkPolyDataMapper()
mapper_6.SetInputConnection(geometry_6.GetOutputPort())
mapper_6.ScalarVisibilityOff()
actor_6 = vtkActor()
actor_6.SetMapper(mapper_6)
actor_6.GetProperty().SetColor(0.8214, 0.5750, 0.1250)
renderer.AddActor(actor_6)

# ---- Label 7 ----
selector_7 = vtkThreshold()
selector_7.SetInputConnection(smoother.GetOutputPort())
selector_7.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_7.SetLowerThreshold(7)
selector_7.SetUpperThreshold(7)
scalars_off_7 = vtkMaskFields()
scalars_off_7.SetInputConnection(selector_7.GetOutputPort())
scalars_off_7.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_7.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_7 = vtkGeometryFilter()
geometry_7.SetInputConnection(scalars_off_7.GetOutputPort())
mapper_7 = vtkPolyDataMapper()
mapper_7.SetInputConnection(geometry_7.GetOutputPort())
mapper_7.ScalarVisibilityOff()
actor_7 = vtkActor()
actor_7.SetMapper(mapper_7)
actor_7.GetProperty().SetColor(0.7857, 0.5500, 0.1500)
renderer.AddActor(actor_7)

# ---- Label 8 ----
selector_8 = vtkThreshold()
selector_8.SetInputConnection(smoother.GetOutputPort())
selector_8.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_8.SetLowerThreshold(8)
selector_8.SetUpperThreshold(8)
scalars_off_8 = vtkMaskFields()
scalars_off_8.SetInputConnection(selector_8.GetOutputPort())
scalars_off_8.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_8.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_8 = vtkGeometryFilter()
geometry_8.SetInputConnection(scalars_off_8.GetOutputPort())
mapper_8 = vtkPolyDataMapper()
mapper_8.SetInputConnection(geometry_8.GetOutputPort())
mapper_8.ScalarVisibilityOff()
actor_8 = vtkActor()
actor_8.SetMapper(mapper_8)
actor_8.GetProperty().SetColor(0.7500, 0.5250, 0.1750)
renderer.AddActor(actor_8)

# ---- Label 9 ----
selector_9 = vtkThreshold()
selector_9.SetInputConnection(smoother.GetOutputPort())
selector_9.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_9.SetLowerThreshold(9)
selector_9.SetUpperThreshold(9)
scalars_off_9 = vtkMaskFields()
scalars_off_9.SetInputConnection(selector_9.GetOutputPort())
scalars_off_9.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_9.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_9 = vtkGeometryFilter()
geometry_9.SetInputConnection(scalars_off_9.GetOutputPort())
mapper_9 = vtkPolyDataMapper()
mapper_9.SetInputConnection(geometry_9.GetOutputPort())
mapper_9.ScalarVisibilityOff()
actor_9 = vtkActor()
actor_9.SetMapper(mapper_9)
actor_9.GetProperty().SetColor(0.7143, 0.5000, 0.2000)
renderer.AddActor(actor_9)

# ---- Label 10 ----
selector_10 = vtkThreshold()
selector_10.SetInputConnection(smoother.GetOutputPort())
selector_10.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_10.SetLowerThreshold(10)
selector_10.SetUpperThreshold(10)
scalars_off_10 = vtkMaskFields()
scalars_off_10.SetInputConnection(selector_10.GetOutputPort())
scalars_off_10.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_10.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_10 = vtkGeometryFilter()
geometry_10.SetInputConnection(scalars_off_10.GetOutputPort())
mapper_10 = vtkPolyDataMapper()
mapper_10.SetInputConnection(geometry_10.GetOutputPort())
mapper_10.ScalarVisibilityOff()
actor_10 = vtkActor()
actor_10.SetMapper(mapper_10)
actor_10.GetProperty().SetColor(0.6786, 0.4750, 0.2250)
renderer.AddActor(actor_10)

# ---- Label 11 ----
selector_11 = vtkThreshold()
selector_11.SetInputConnection(smoother.GetOutputPort())
selector_11.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_11.SetLowerThreshold(11)
selector_11.SetUpperThreshold(11)
scalars_off_11 = vtkMaskFields()
scalars_off_11.SetInputConnection(selector_11.GetOutputPort())
scalars_off_11.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_11.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_11 = vtkGeometryFilter()
geometry_11.SetInputConnection(scalars_off_11.GetOutputPort())
mapper_11 = vtkPolyDataMapper()
mapper_11.SetInputConnection(geometry_11.GetOutputPort())
mapper_11.ScalarVisibilityOff()
actor_11 = vtkActor()
actor_11.SetMapper(mapper_11)
actor_11.GetProperty().SetColor(0.6429, 0.4500, 0.2500)
renderer.AddActor(actor_11)

# ---- Label 12 ----
selector_12 = vtkThreshold()
selector_12.SetInputConnection(smoother.GetOutputPort())
selector_12.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_12.SetLowerThreshold(12)
selector_12.SetUpperThreshold(12)
scalars_off_12 = vtkMaskFields()
scalars_off_12.SetInputConnection(selector_12.GetOutputPort())
scalars_off_12.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_12.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_12 = vtkGeometryFilter()
geometry_12.SetInputConnection(scalars_off_12.GetOutputPort())
mapper_12 = vtkPolyDataMapper()
mapper_12.SetInputConnection(geometry_12.GetOutputPort())
mapper_12.ScalarVisibilityOff()
actor_12 = vtkActor()
actor_12.SetMapper(mapper_12)
actor_12.GetProperty().SetColor(0.6071, 0.4250, 0.2750)
renderer.AddActor(actor_12)

# ---- Label 13 ----
selector_13 = vtkThreshold()
selector_13.SetInputConnection(smoother.GetOutputPort())
selector_13.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_13.SetLowerThreshold(13)
selector_13.SetUpperThreshold(13)
scalars_off_13 = vtkMaskFields()
scalars_off_13.SetInputConnection(selector_13.GetOutputPort())
scalars_off_13.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_13.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_13 = vtkGeometryFilter()
geometry_13.SetInputConnection(scalars_off_13.GetOutputPort())
mapper_13 = vtkPolyDataMapper()
mapper_13.SetInputConnection(geometry_13.GetOutputPort())
mapper_13.ScalarVisibilityOff()
actor_13 = vtkActor()
actor_13.SetMapper(mapper_13)
actor_13.GetProperty().SetColor(0.5714, 0.4000, 0.3000)
renderer.AddActor(actor_13)

# ---- Label 14 ----
selector_14 = vtkThreshold()
selector_14.SetInputConnection(smoother.GetOutputPort())
selector_14.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_14.SetLowerThreshold(14)
selector_14.SetUpperThreshold(14)
scalars_off_14 = vtkMaskFields()
scalars_off_14.SetInputConnection(selector_14.GetOutputPort())
scalars_off_14.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_14.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_14 = vtkGeometryFilter()
geometry_14.SetInputConnection(scalars_off_14.GetOutputPort())
mapper_14 = vtkPolyDataMapper()
mapper_14.SetInputConnection(geometry_14.GetOutputPort())
mapper_14.ScalarVisibilityOff()
actor_14 = vtkActor()
actor_14.SetMapper(mapper_14)
actor_14.GetProperty().SetColor(0.5357, 0.3750, 0.3250)
renderer.AddActor(actor_14)

# ---- Label 15 ----
selector_15 = vtkThreshold()
selector_15.SetInputConnection(smoother.GetOutputPort())
selector_15.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_15.SetLowerThreshold(15)
selector_15.SetUpperThreshold(15)
scalars_off_15 = vtkMaskFields()
scalars_off_15.SetInputConnection(selector_15.GetOutputPort())
scalars_off_15.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_15.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_15 = vtkGeometryFilter()
geometry_15.SetInputConnection(scalars_off_15.GetOutputPort())
mapper_15 = vtkPolyDataMapper()
mapper_15.SetInputConnection(geometry_15.GetOutputPort())
mapper_15.ScalarVisibilityOff()
actor_15 = vtkActor()
actor_15.SetMapper(mapper_15)
actor_15.GetProperty().SetColor(0.5000, 0.3500, 0.3500)
renderer.AddActor(actor_15)

# ---- Label 16 ----
selector_16 = vtkThreshold()
selector_16.SetInputConnection(smoother.GetOutputPort())
selector_16.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_16.SetLowerThreshold(16)
selector_16.SetUpperThreshold(16)
scalars_off_16 = vtkMaskFields()
scalars_off_16.SetInputConnection(selector_16.GetOutputPort())
scalars_off_16.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_16.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_16 = vtkGeometryFilter()
geometry_16.SetInputConnection(scalars_off_16.GetOutputPort())
mapper_16 = vtkPolyDataMapper()
mapper_16.SetInputConnection(geometry_16.GetOutputPort())
mapper_16.ScalarVisibilityOff()
actor_16 = vtkActor()
actor_16.SetMapper(mapper_16)
actor_16.GetProperty().SetColor(0.5357, 0.3250, 0.3750)
renderer.AddActor(actor_16)

# ---- Label 17 ----
selector_17 = vtkThreshold()
selector_17.SetInputConnection(smoother.GetOutputPort())
selector_17.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_17.SetLowerThreshold(17)
selector_17.SetUpperThreshold(17)
scalars_off_17 = vtkMaskFields()
scalars_off_17.SetInputConnection(selector_17.GetOutputPort())
scalars_off_17.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_17.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_17 = vtkGeometryFilter()
geometry_17.SetInputConnection(scalars_off_17.GetOutputPort())
mapper_17 = vtkPolyDataMapper()
mapper_17.SetInputConnection(geometry_17.GetOutputPort())
mapper_17.ScalarVisibilityOff()
actor_17 = vtkActor()
actor_17.SetMapper(mapper_17)
actor_17.GetProperty().SetColor(0.5714, 0.3000, 0.4000)
renderer.AddActor(actor_17)

# ---- Label 20 ----
selector_20 = vtkThreshold()
selector_20.SetInputConnection(smoother.GetOutputPort())
selector_20.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_20.SetLowerThreshold(20)
selector_20.SetUpperThreshold(20)
scalars_off_20 = vtkMaskFields()
scalars_off_20.SetInputConnection(selector_20.GetOutputPort())
scalars_off_20.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_20.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_20 = vtkGeometryFilter()
geometry_20.SetInputConnection(scalars_off_20.GetOutputPort())
mapper_20 = vtkPolyDataMapper()
mapper_20.SetInputConnection(geometry_20.GetOutputPort())
mapper_20.ScalarVisibilityOff()
actor_20 = vtkActor()
actor_20.SetMapper(mapper_20)
actor_20.GetProperty().SetColor(0.6786, 0.2250, 0.4750)
renderer.AddActor(actor_20)

# ---- Label 21 ----
selector_21 = vtkThreshold()
selector_21.SetInputConnection(smoother.GetOutputPort())
selector_21.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_21.SetLowerThreshold(21)
selector_21.SetUpperThreshold(21)
scalars_off_21 = vtkMaskFields()
scalars_off_21.SetInputConnection(selector_21.GetOutputPort())
scalars_off_21.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_21.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_21 = vtkGeometryFilter()
geometry_21.SetInputConnection(scalars_off_21.GetOutputPort())
mapper_21 = vtkPolyDataMapper()
mapper_21.SetInputConnection(geometry_21.GetOutputPort())
mapper_21.ScalarVisibilityOff()
actor_21 = vtkActor()
actor_21.SetMapper(mapper_21)
actor_21.GetProperty().SetColor(0.7143, 0.2000, 0.5000)
renderer.AddActor(actor_21)

# ---- Label 23 ----
selector_23 = vtkThreshold()
selector_23.SetInputConnection(smoother.GetOutputPort())
selector_23.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_23.SetLowerThreshold(23)
selector_23.SetUpperThreshold(23)
scalars_off_23 = vtkMaskFields()
scalars_off_23.SetInputConnection(selector_23.GetOutputPort())
scalars_off_23.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_23.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_23 = vtkGeometryFilter()
geometry_23.SetInputConnection(scalars_off_23.GetOutputPort())
mapper_23 = vtkPolyDataMapper()
mapper_23.SetInputConnection(geometry_23.GetOutputPort())
mapper_23.ScalarVisibilityOff()
actor_23 = vtkActor()
actor_23.SetMapper(mapper_23)
actor_23.GetProperty().SetColor(0.7857, 0.1500, 0.5500)
renderer.AddActor(actor_23)

# ---- Label 24 ----
selector_24 = vtkThreshold()
selector_24.SetInputConnection(smoother.GetOutputPort())
selector_24.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_24.SetLowerThreshold(24)
selector_24.SetUpperThreshold(24)
scalars_off_24 = vtkMaskFields()
scalars_off_24.SetInputConnection(selector_24.GetOutputPort())
scalars_off_24.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_24.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_24 = vtkGeometryFilter()
geometry_24.SetInputConnection(scalars_off_24.GetOutputPort())
mapper_24 = vtkPolyDataMapper()
mapper_24.SetInputConnection(geometry_24.GetOutputPort())
mapper_24.ScalarVisibilityOff()
actor_24 = vtkActor()
actor_24.SetMapper(mapper_24)
actor_24.GetProperty().SetColor(0.8214, 0.1250, 0.5750)
renderer.AddActor(actor_24)

# ---- Label 25 ----
selector_25 = vtkThreshold()
selector_25.SetInputConnection(smoother.GetOutputPort())
selector_25.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_25.SetLowerThreshold(25)
selector_25.SetUpperThreshold(25)
scalars_off_25 = vtkMaskFields()
scalars_off_25.SetInputConnection(selector_25.GetOutputPort())
scalars_off_25.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_25.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_25 = vtkGeometryFilter()
geometry_25.SetInputConnection(scalars_off_25.GetOutputPort())
mapper_25 = vtkPolyDataMapper()
mapper_25.SetInputConnection(geometry_25.GetOutputPort())
mapper_25.ScalarVisibilityOff()
actor_25 = vtkActor()
actor_25.SetMapper(mapper_25)
actor_25.GetProperty().SetColor(0.8571, 0.1000, 0.6000)
renderer.AddActor(actor_25)

# ---- Label 26 ----
selector_26 = vtkThreshold()
selector_26.SetInputConnection(smoother.GetOutputPort())
selector_26.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_26.SetLowerThreshold(26)
selector_26.SetUpperThreshold(26)
scalars_off_26 = vtkMaskFields()
scalars_off_26.SetInputConnection(selector_26.GetOutputPort())
scalars_off_26.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_26.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_26 = vtkGeometryFilter()
geometry_26.SetInputConnection(scalars_off_26.GetOutputPort())
mapper_26 = vtkPolyDataMapper()
mapper_26.SetInputConnection(geometry_26.GetOutputPort())
mapper_26.ScalarVisibilityOff()
actor_26 = vtkActor()
actor_26.SetMapper(mapper_26)
actor_26.GetProperty().SetColor(0.8929, 0.0750, 0.6250)
renderer.AddActor(actor_26)

# ---- Label 27 ----
selector_27 = vtkThreshold()
selector_27.SetInputConnection(smoother.GetOutputPort())
selector_27.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_27.SetLowerThreshold(27)
selector_27.SetUpperThreshold(27)
scalars_off_27 = vtkMaskFields()
scalars_off_27.SetInputConnection(selector_27.GetOutputPort())
scalars_off_27.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_27.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_27 = vtkGeometryFilter()
geometry_27.SetInputConnection(scalars_off_27.GetOutputPort())
mapper_27 = vtkPolyDataMapper()
mapper_27.SetInputConnection(geometry_27.GetOutputPort())
mapper_27.ScalarVisibilityOff()
actor_27 = vtkActor()
actor_27.SetMapper(mapper_27)
actor_27.GetProperty().SetColor(0.9286, 0.0500, 0.6500)
renderer.AddActor(actor_27)

# ---- Label 29 ----
selector_29 = vtkThreshold()
selector_29.SetInputConnection(smoother.GetOutputPort())
selector_29.SetInputArrayToProcess(0, 0, 0, vtkDataObject.FIELD_ASSOCIATION_POINTS, vtkDataSetAttributes.SCALARS)
selector_29.SetLowerThreshold(29)
selector_29.SetUpperThreshold(29)
scalars_off_29 = vtkMaskFields()
scalars_off_29.SetInputConnection(selector_29.GetOutputPort())
scalars_off_29.CopyAttributeOff(vtkMaskFields.POINT_DATA, vtkDataSetAttributes.SCALARS)
scalars_off_29.CopyAttributeOff(vtkMaskFields.CELL_DATA, vtkDataSetAttributes.SCALARS)
geometry_29 = vtkGeometryFilter()
geometry_29.SetInputConnection(scalars_off_29.GetOutputPort())
mapper_29 = vtkPolyDataMapper()
mapper_29.SetInputConnection(geometry_29.GetOutputPort())
mapper_29.ScalarVisibilityOff()
actor_29 = vtkActor()
actor_29.SetMapper(mapper_29)
actor_29.GetProperty().SetColor(1.0000, 0.0000, 0.7000)
renderer.AddActor(actor_29)

# Window: display the rendered scene
render_window = vtkRenderWindow()
render_window.AddRenderer(renderer)
render_window.SetWindowName("generate models from labels")
render_window.SetMultiSamples(0)
render_window.SetSize(640, 480)

# Interactor: handle mouse and keyboard events
interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)

# Scene: position for a clear view of the frog anatomy
renderer.ResetCamera()
camera = renderer.GetActiveCamera()
camera.Elevation(-90)
camera.Azimuth(30)
renderer.ResetCamera()

render_window.Render()
interactor.Initialize()
interactor.Start()
