#!/usr/bin/env python

# Test vtkTextMapper with column-separated text, various fonts, and math text.

import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingFreeType  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401

from vtkmodules.vtkCommonCore import (
    VTK_ARIAL,
    VTK_COURIER,
    VTK_TEXT_BOTTOM,
    VTK_TEXT_CENTERED,
    VTK_TEXT_LEFT,
    VTK_TEXT_RIGHT,
    VTK_TEXT_TOP,
    VTK_TIMES,
)
from vtkmodules.vtkRenderingCore import (
    vtkActor2D,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
    vtkTextMapper,
)

# Entry 1: multiline math, Times, red, left-top
mapper_1 = vtkTextMapper()
mapper_1.SetInput("Sample multiline\ntext rendered\nwith mathText $\\sum_{i=0}^\\infty x_i$")
prop_1 = mapper_1.GetTextProperty()
prop_1.SetFontSize(16)
prop_1.SetColor(1.0, 0.0, 0.0)
prop_1.SetBackgroundColor(0.0, 1.0, 0.0)
prop_1.SetBackgroundOpacity(0.5)
prop_1.SetJustification(VTK_TEXT_LEFT)
prop_1.SetVerticalJustification(VTK_TEXT_TOP)
prop_1.SetCellOffset(0.0)
prop_1.SetLineOffset(0.0)
prop_1.SetLineSpacing(1.0)
prop_1.SetOrientation(0.0)
prop_1.SetFrame(False)
prop_1.SetFontFamily(VTK_TIMES)
actor_1 = vtkActor2D()
actor_1.SetMapper(mapper_1)
actor_1.SetPosition(10.0, 100.0)

# Entry 2: multiline math, Times, green, right-centered, framed
mapper_2 = vtkTextMapper()
mapper_2.SetInput("Sample multiline\ntext rendered\nwith mathText $\\sum_{i=0}^\\infty x_i$")
prop_2 = mapper_2.GetTextProperty()
prop_2.SetFontSize(16)
prop_2.SetColor(0.0, 1.0, 0.0)
prop_2.SetBackgroundColor(0.4, 0.5, 0.0)
prop_2.SetBackgroundOpacity(0.5)
prop_2.SetJustification(VTK_TEXT_RIGHT)
prop_2.SetVerticalJustification(VTK_TEXT_CENTERED)
prop_2.SetCellOffset(0.0)
prop_2.SetLineOffset(5.0)
prop_2.SetLineSpacing(1.0)
prop_2.SetOrientation(0.0)
prop_2.SetFrame(True)
prop_2.SetFontFamily(VTK_TIMES)
actor_2 = vtkActor2D()
actor_2.SetMapper(mapper_2)
actor_2.SetPosition(350.0, 60.0)

# Entry 3: columns with math, Courier, blue, centered, framed
mapper_3 = vtkTextMapper()
mapper_3.SetInput("Cell1 | Cell2 | $\\sum_{i=0}^\\infty x_i$\n12 | $\\sum_{i=0}^\\infty x_i$ | 2345")
prop_3 = mapper_3.GetTextProperty()
prop_3.SetFontSize(16)
prop_3.SetColor(0.0, 0.0, 1.0)
prop_3.SetBackgroundColor(0.2, 0.0, 0.5)
prop_3.SetBackgroundOpacity(0.5)
prop_3.SetJustification(VTK_TEXT_CENTERED)
prop_3.SetVerticalJustification(VTK_TEXT_CENTERED)
prop_3.SetCellOffset(0.0)
prop_3.SetLineOffset(5.0)
prop_3.SetLineSpacing(1.0)
prop_3.SetOrientation(0.0)
prop_3.SetFrame(True)
prop_3.SetFontFamily(VTK_COURIER)
actor_3 = vtkActor2D()
actor_3.SetMapper(mapper_3)
actor_3.SetPosition(500.0, 60.0)

# Entry 4: columns with math, Arial, orange, centered-bottom, framed, cell_offset=30
mapper_4 = vtkTextMapper()
mapper_4.SetInput("Cell1 | Cell2 | $\\sum_{i=0}^\\infty x_i$\n12 | $\\sum_{i=0}^\\infty x_i$ | 2345")
prop_4 = mapper_4.GetTextProperty()
prop_4.SetFontSize(16)
prop_4.SetColor(1.0, 0.2, 0.0)
prop_4.SetBackgroundColor(0.3, 0.1, 0.7)
prop_4.SetBackgroundOpacity(0.5)
prop_4.SetJustification(VTK_TEXT_CENTERED)
prop_4.SetVerticalJustification(VTK_TEXT_BOTTOM)
prop_4.SetCellOffset(30.0)
prop_4.SetLineOffset(10.0)
prop_4.SetLineSpacing(1.0)
prop_4.SetOrientation(0.0)
prop_4.SetFrame(True)
prop_4.SetFontFamily(VTK_ARIAL)
actor_4 = vtkActor2D()
actor_4.SetMapper(mapper_4)
actor_4.SetPosition(150.0, 150.0)

# Entry 5: columns with math, Arial, orange, centered-top, orientation=50, line_spacing=1.5
mapper_5 = vtkTextMapper()
mapper_5.SetInput("Cell1 | Cell2 | $\\sum_{i=0}^\\infty x_i$\n12 | $\\sum_{i=0}^\\infty x_i$ | 2345")
prop_5 = mapper_5.GetTextProperty()
prop_5.SetFontSize(16)
prop_5.SetColor(1.0, 0.2, 0.0)
prop_5.SetBackgroundColor(0.3, 0.1, 0.7)
prop_5.SetBackgroundOpacity(0.5)
prop_5.SetJustification(VTK_TEXT_CENTERED)
prop_5.SetVerticalJustification(VTK_TEXT_TOP)
prop_5.SetCellOffset(30.0)
prop_5.SetLineOffset(10.0)
prop_5.SetLineSpacing(1.5)
prop_5.SetOrientation(50.0)
prop_5.SetFrame(False)
prop_5.SetFontFamily(VTK_ARIAL)
actor_5 = vtkActor2D()
actor_5.SetMapper(mapper_5)
actor_5.SetPosition(400.0, 320.0)

# Entry 6: pipe-separated numbers, Arial, green-ish, centered, framed, cell_offset=41
mapper_6 = vtkTextMapper()
mapper_6.SetInput("1|2|3|4\n1|2|3")
prop_6 = mapper_6.GetTextProperty()
prop_6.SetFontSize(16)
prop_6.SetColor(0.3, 0.9, 0.5)
prop_6.SetBackgroundColor(0.0, 1.0, 0.0)
prop_6.SetBackgroundOpacity(0.5)
prop_6.SetJustification(VTK_TEXT_CENTERED)
prop_6.SetVerticalJustification(VTK_TEXT_CENTERED)
prop_6.SetCellOffset(41.0)
prop_6.SetLineOffset(0.0)
prop_6.SetLineSpacing(1.0)
prop_6.SetOrientation(0.0)
prop_6.SetFrame(True)
prop_6.SetFontFamily(VTK_ARIAL)
actor_6 = vtkActor2D()
actor_6.SetMapper(mapper_6)
actor_6.SetPosition(120.0, 350.0)

# Entry 7: empty pipes, Arial, yellow-green, centered
mapper_7 = vtkTextMapper()
mapper_7.SetInput("|||\n")
prop_7 = mapper_7.GetTextProperty()
prop_7.SetFontSize(16)
prop_7.SetColor(0.6, 0.8, 0.2)
prop_7.SetBackgroundColor(0.0, 1.0, 0.0)
prop_7.SetBackgroundOpacity(0.5)
prop_7.SetJustification(VTK_TEXT_CENTERED)
prop_7.SetVerticalJustification(VTK_TEXT_CENTERED)
prop_7.SetCellOffset(41.0)
prop_7.SetLineOffset(0.0)
prop_7.SetLineSpacing(1.0)
prop_7.SetOrientation(0.0)
prop_7.SetFrame(False)
prop_7.SetFontFamily(VTK_ARIAL)
actor_7 = vtkActor2D()
actor_7.SetMapper(mapper_7)
actor_7.SetPosition(120.0, 400.0)

# Entry 8: TEST with empty pipes and newlines, Arial, pink, framed, line_spacing=1.5
mapper_8 = vtkTextMapper()
mapper_8.SetInput("TEST|||\n\n\n")
prop_8 = mapper_8.GetTextProperty()
prop_8.SetFontSize(20)
prop_8.SetColor(1.0, 0.6, 0.6)
prop_8.SetBackgroundColor(0.0, 0.5, 0.0)
prop_8.SetBackgroundOpacity(0.5)
prop_8.SetJustification(VTK_TEXT_CENTERED)
prop_8.SetVerticalJustification(VTK_TEXT_CENTERED)
prop_8.SetCellOffset(20.0)
prop_8.SetLineOffset(0.0)
prop_8.SetLineSpacing(1.5)
prop_8.SetOrientation(0.0)
prop_8.SetFrame(True)
prop_8.SetFontFamily(VTK_ARIAL)
actor_8 = vtkActor2D()
actor_8.SetMapper(mapper_8)
actor_8.SetPosition(120.0, 500.0)

# Entry 9: TEST with pipes and trailing Test, Arial, teal, framed, cell_offset=41
mapper_9 = vtkTextMapper()
mapper_9.SetInput("TEST|||\n\n\n|Test")
prop_9 = mapper_9.GetTextProperty()
prop_9.SetFontSize(20)
prop_9.SetColor(0.2, 0.7, 0.4)
prop_9.SetBackgroundColor(0.0, 1.0, 0.0)
prop_9.SetBackgroundOpacity(0.5)
prop_9.SetJustification(VTK_TEXT_CENTERED)
prop_9.SetVerticalJustification(VTK_TEXT_CENTERED)
prop_9.SetCellOffset(41.0)
prop_9.SetLineOffset(0.0)
prop_9.SetLineSpacing(1.0)
prop_9.SetOrientation(0.0)
prop_9.SetFrame(True)
prop_9.SetFontFamily(VTK_ARIAL)
actor_9 = vtkActor2D()
actor_9.SetMapper(mapper_9)
actor_9.SetPosition(150.0, 550.0)

# Entry 10: pipe-separated numbers rotated 90, Arial, green-ish, framed, cell_offset=41
mapper_10 = vtkTextMapper()
mapper_10.SetInput("1|2|3|4\n1|2|3")
prop_10 = mapper_10.GetTextProperty()
prop_10.SetFontSize(16)
prop_10.SetColor(0.3, 0.9, 0.5)
prop_10.SetBackgroundColor(0.0, 1.0, 0.0)
prop_10.SetBackgroundOpacity(0.5)
prop_10.SetJustification(VTK_TEXT_CENTERED)
prop_10.SetVerticalJustification(VTK_TEXT_CENTERED)
prop_10.SetCellOffset(41.0)
prop_10.SetLineOffset(0.0)
prop_10.SetLineSpacing(1.0)
prop_10.SetOrientation(90.0)
prop_10.SetFrame(True)
prop_10.SetFontFamily(VTK_ARIAL)
actor_10 = vtkActor2D()
actor_10.SetMapper(mapper_10)
actor_10.SetPosition(260.0, 390.0)

# Entry 11: escaped pipes, Arial, blue
mapper_11 = vtkTextMapper()
mapper_11.SetInput("\\| Test FreeType escaped pipe \\pi \\|")
prop_11 = mapper_11.GetTextProperty()
prop_11.SetFontSize(16)
prop_11.SetColor(0.0, 0.0, 1.0)
prop_11.SetBackgroundColor(0.2, 1.0, 0.0)
prop_11.SetBackgroundOpacity(0.5)
prop_11.SetJustification(VTK_TEXT_CENTERED)
prop_11.SetVerticalJustification(VTK_TEXT_CENTERED)
prop_11.SetCellOffset(0.0)
prop_11.SetLineOffset(0.0)
prop_11.SetLineSpacing(1.0)
prop_11.SetOrientation(0.0)
prop_11.SetFrame(False)
prop_11.SetFontFamily(VTK_ARIAL)
actor_11 = vtkActor2D()
actor_11.SetMapper(mapper_11)
actor_11.SetPosition(450.0, 430.0)

# Entry 12: escaped pipes with math and column, Arial, red
mapper_12 = vtkTextMapper()
mapper_12.SetInput("\\| Test MathText escaped pipe $\\pi$ \\| | column")
prop_12 = mapper_12.GetTextProperty()
prop_12.SetFontSize(16)
prop_12.SetColor(1.0, 0.0, 0.0)
prop_12.SetBackgroundColor(0.0, 0.3, 0.2)
prop_12.SetBackgroundOpacity(0.5)
prop_12.SetJustification(VTK_TEXT_CENTERED)
prop_12.SetVerticalJustification(VTK_TEXT_CENTERED)
prop_12.SetCellOffset(0.0)
prop_12.SetLineOffset(0.0)
prop_12.SetLineSpacing(1.0)
prop_12.SetOrientation(0.0)
prop_12.SetFrame(False)
prop_12.SetFontFamily(VTK_ARIAL)
actor_12 = vtkActor2D()
actor_12.SetMapper(mapper_12)
actor_12.SetPosition(400.0, 510.0)

# Renderer
renderer = vtkRenderer()
renderer.SetBackground(0.1, 0.1, 0.1)
renderer.AddActor(actor_1)
renderer.AddActor(actor_2)
renderer.AddActor(actor_3)
renderer.AddActor(actor_4)
renderer.AddActor(actor_5)
renderer.AddActor(actor_6)
renderer.AddActor(actor_7)
renderer.AddActor(actor_8)
renderer.AddActor(actor_9)
renderer.AddActor(actor_10)
renderer.AddActor(actor_11)
renderer.AddActor(actor_12)

# Window
render_window = vtkRenderWindow()
render_window.AddRenderer(renderer)
render_window.SetWindowName("free type text mapper with columns")
render_window.SetMultiSamples(0)
render_window.SetSize(600, 600)

# Interactor
interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)

interactor.Initialize()
interactor.Start()
