#!/usr/bin/env python

# Test text actors rendered with opaque pass only (ForceOpaque for 3D actors).

import vtkmodules.vtkInteractionStyle  # noqa: F401
import vtkmodules.vtkRenderingFreeType  # noqa: F401
import vtkmodules.vtkRenderingOpenGL2  # noqa: F401

from vtkmodules.vtkRenderingCore import (
    vtkActor2D,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
    vtkRenderer,
    vtkTextActor,
    vtkTextMapper,
)
from vtkmodules.vtkRenderingCore import (
    vtkBillboardTextActor3D,
    vtkTextActor3D,
)
from vtkmodules.vtkRenderingOpenGL2 import vtkRenderStepsPass

width = 600
height = 600

# Disable everything but opaque and overlay
pass_obj = vtkRenderStepsPass()
pass_obj.SetTranslucentPass(None)
pass_obj.SetVolumetricPass(None)

dx = width / 5.0
dy = height / 13.0

# idx=0: t=0(TH,0.5) e=0(E0,0) b=0(B0,0.0)
ta_0 = vtkTextActor()
ta_0.SetInput("vtkTextActor: THE0B0")
ta_0.GetTextProperty().SetJustificationToCentered()
ta_0.GetTextProperty().SetVerticalJustificationToCentered()
ta_0.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta_0.GetTextProperty().SetOpacity(0.5)
ta_0.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta_0.GetTextProperty().SetFrameWidth(2)
ta_0.GetTextProperty().SetFrame(0)
ta_0.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta_0.GetTextProperty().SetBackgroundOpacity(0.0)
ta_0.SetPosition(dx * 1, dy * 1)

ta3d_0 = vtkTextActor3D()
ta3d_0.SetInput("vtkTextActor3D: THE0B0")
ta3d_0.GetTextProperty().SetJustificationToCentered()
ta3d_0.GetTextProperty().SetVerticalJustificationToCentered()
ta3d_0.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta3d_0.GetTextProperty().SetOpacity(0.5)
ta3d_0.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta3d_0.GetTextProperty().SetFrameWidth(2)
ta3d_0.GetTextProperty().SetFrame(0)
ta3d_0.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta3d_0.GetTextProperty().SetBackgroundOpacity(0.0)
ta3d_0.SetPosition(dx * 2, dy * 1.5, 0.0)
ta3d_0.SetForceOpaque(True)

tm_0 = vtkTextMapper()
tm_0.SetInput("vtkTextMapper: THE0B0")
tm_0.GetTextProperty().SetJustificationToCentered()
tm_0.GetTextProperty().SetVerticalJustificationToCentered()
tm_0.GetTextProperty().SetColor(0.0, 0.0, 1.0)
tm_0.GetTextProperty().SetOpacity(0.5)
tm_0.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
tm_0.GetTextProperty().SetFrameWidth(2)
tm_0.GetTextProperty().SetFrame(0)
tm_0.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
tm_0.GetTextProperty().SetBackgroundOpacity(0.0)
tm_actor_0 = vtkActor2D()
tm_actor_0.SetMapper(tm_0)
tm_actor_0.SetPosition(dx * 3, dy * 1)

bb_0 = vtkBillboardTextActor3D()
bb_0.SetInput("vtkBillboardTextActor3D: THE0B0")
bb_0.GetTextProperty().SetJustificationToCentered()
bb_0.GetTextProperty().SetVerticalJustificationToCentered()
bb_0.GetTextProperty().SetColor(0.0, 0.0, 1.0)
bb_0.GetTextProperty().SetOpacity(0.5)
bb_0.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
bb_0.GetTextProperty().SetFrameWidth(2)
bb_0.GetTextProperty().SetFrame(0)
bb_0.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
bb_0.GetTextProperty().SetBackgroundOpacity(0.0)
bb_0.SetPosition(dx * 4, dy * 1.5, 0.0)
bb_0.SetForceOpaque(True)

# idx=1: t=0(TH,0.5) e=0(E0,0) b=1(BH,0.5)
ta_1 = vtkTextActor()
ta_1.SetInput("vtkTextActor: THE0BH")
ta_1.GetTextProperty().SetJustificationToCentered()
ta_1.GetTextProperty().SetVerticalJustificationToCentered()
ta_1.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta_1.GetTextProperty().SetOpacity(0.5)
ta_1.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta_1.GetTextProperty().SetFrameWidth(2)
ta_1.GetTextProperty().SetFrame(0)
ta_1.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta_1.GetTextProperty().SetBackgroundOpacity(0.5)
ta_1.SetPosition(dx * 1, dy * 2)

ta3d_1 = vtkTextActor3D()
ta3d_1.SetInput("vtkTextActor3D: THE0BH")
ta3d_1.GetTextProperty().SetJustificationToCentered()
ta3d_1.GetTextProperty().SetVerticalJustificationToCentered()
ta3d_1.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta3d_1.GetTextProperty().SetOpacity(0.5)
ta3d_1.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta3d_1.GetTextProperty().SetFrameWidth(2)
ta3d_1.GetTextProperty().SetFrame(0)
ta3d_1.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta3d_1.GetTextProperty().SetBackgroundOpacity(0.5)
ta3d_1.SetPosition(dx * 2, dy * 2.5, 0.0)
ta3d_1.SetForceOpaque(True)

tm_1 = vtkTextMapper()
tm_1.SetInput("vtkTextMapper: THE0BH")
tm_1.GetTextProperty().SetJustificationToCentered()
tm_1.GetTextProperty().SetVerticalJustificationToCentered()
tm_1.GetTextProperty().SetColor(0.0, 0.0, 1.0)
tm_1.GetTextProperty().SetOpacity(0.5)
tm_1.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
tm_1.GetTextProperty().SetFrameWidth(2)
tm_1.GetTextProperty().SetFrame(0)
tm_1.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
tm_1.GetTextProperty().SetBackgroundOpacity(0.5)
tm_actor_1 = vtkActor2D()
tm_actor_1.SetMapper(tm_1)
tm_actor_1.SetPosition(dx * 3, dy * 2)

bb_1 = vtkBillboardTextActor3D()
bb_1.SetInput("vtkBillboardTextActor3D: THE0BH")
bb_1.GetTextProperty().SetJustificationToCentered()
bb_1.GetTextProperty().SetVerticalJustificationToCentered()
bb_1.GetTextProperty().SetColor(0.0, 0.0, 1.0)
bb_1.GetTextProperty().SetOpacity(0.5)
bb_1.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
bb_1.GetTextProperty().SetFrameWidth(2)
bb_1.GetTextProperty().SetFrame(0)
bb_1.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
bb_1.GetTextProperty().SetBackgroundOpacity(0.5)
bb_1.SetPosition(dx * 4, dy * 2.5, 0.0)
bb_1.SetForceOpaque(True)

# idx=2: t=0(TH,0.5) e=0(E0,0) b=2(BF,1.0)
ta_2 = vtkTextActor()
ta_2.SetInput("vtkTextActor: THE0BF")
ta_2.GetTextProperty().SetJustificationToCentered()
ta_2.GetTextProperty().SetVerticalJustificationToCentered()
ta_2.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta_2.GetTextProperty().SetOpacity(0.5)
ta_2.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta_2.GetTextProperty().SetFrameWidth(2)
ta_2.GetTextProperty().SetFrame(0)
ta_2.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta_2.GetTextProperty().SetBackgroundOpacity(1.0)
ta_2.SetPosition(dx * 1, dy * 3)

ta3d_2 = vtkTextActor3D()
ta3d_2.SetInput("vtkTextActor3D: THE0BF")
ta3d_2.GetTextProperty().SetJustificationToCentered()
ta3d_2.GetTextProperty().SetVerticalJustificationToCentered()
ta3d_2.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta3d_2.GetTextProperty().SetOpacity(0.5)
ta3d_2.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta3d_2.GetTextProperty().SetFrameWidth(2)
ta3d_2.GetTextProperty().SetFrame(0)
ta3d_2.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta3d_2.GetTextProperty().SetBackgroundOpacity(1.0)
ta3d_2.SetPosition(dx * 2, dy * 3.5, 0.0)
ta3d_2.SetForceOpaque(True)

tm_2 = vtkTextMapper()
tm_2.SetInput("vtkTextMapper: THE0BF")
tm_2.GetTextProperty().SetJustificationToCentered()
tm_2.GetTextProperty().SetVerticalJustificationToCentered()
tm_2.GetTextProperty().SetColor(0.0, 0.0, 1.0)
tm_2.GetTextProperty().SetOpacity(0.5)
tm_2.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
tm_2.GetTextProperty().SetFrameWidth(2)
tm_2.GetTextProperty().SetFrame(0)
tm_2.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
tm_2.GetTextProperty().SetBackgroundOpacity(1.0)
tm_actor_2 = vtkActor2D()
tm_actor_2.SetMapper(tm_2)
tm_actor_2.SetPosition(dx * 3, dy * 3)

bb_2 = vtkBillboardTextActor3D()
bb_2.SetInput("vtkBillboardTextActor3D: THE0BF")
bb_2.GetTextProperty().SetJustificationToCentered()
bb_2.GetTextProperty().SetVerticalJustificationToCentered()
bb_2.GetTextProperty().SetColor(0.0, 0.0, 1.0)
bb_2.GetTextProperty().SetOpacity(0.5)
bb_2.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
bb_2.GetTextProperty().SetFrameWidth(2)
bb_2.GetTextProperty().SetFrame(0)
bb_2.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
bb_2.GetTextProperty().SetBackgroundOpacity(1.0)
bb_2.SetPosition(dx * 4, dy * 3.5, 0.0)
bb_2.SetForceOpaque(True)

# idx=3: t=0(TH,0.5) e=1(E1,1) b=0(B0,0.0)
ta_3 = vtkTextActor()
ta_3.SetInput("vtkTextActor: THE1B0")
ta_3.GetTextProperty().SetJustificationToCentered()
ta_3.GetTextProperty().SetVerticalJustificationToCentered()
ta_3.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta_3.GetTextProperty().SetOpacity(0.5)
ta_3.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta_3.GetTextProperty().SetFrameWidth(2)
ta_3.GetTextProperty().SetFrame(1)
ta_3.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta_3.GetTextProperty().SetBackgroundOpacity(0.0)
ta_3.SetPosition(dx * 1, dy * 4)

ta3d_3 = vtkTextActor3D()
ta3d_3.SetInput("vtkTextActor3D: THE1B0")
ta3d_3.GetTextProperty().SetJustificationToCentered()
ta3d_3.GetTextProperty().SetVerticalJustificationToCentered()
ta3d_3.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta3d_3.GetTextProperty().SetOpacity(0.5)
ta3d_3.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta3d_3.GetTextProperty().SetFrameWidth(2)
ta3d_3.GetTextProperty().SetFrame(1)
ta3d_3.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta3d_3.GetTextProperty().SetBackgroundOpacity(0.0)
ta3d_3.SetPosition(dx * 2, dy * 4.5, 0.0)
ta3d_3.SetForceOpaque(True)

tm_3 = vtkTextMapper()
tm_3.SetInput("vtkTextMapper: THE1B0")
tm_3.GetTextProperty().SetJustificationToCentered()
tm_3.GetTextProperty().SetVerticalJustificationToCentered()
tm_3.GetTextProperty().SetColor(0.0, 0.0, 1.0)
tm_3.GetTextProperty().SetOpacity(0.5)
tm_3.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
tm_3.GetTextProperty().SetFrameWidth(2)
tm_3.GetTextProperty().SetFrame(1)
tm_3.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
tm_3.GetTextProperty().SetBackgroundOpacity(0.0)
tm_actor_3 = vtkActor2D()
tm_actor_3.SetMapper(tm_3)
tm_actor_3.SetPosition(dx * 3, dy * 4)

bb_3 = vtkBillboardTextActor3D()
bb_3.SetInput("vtkBillboardTextActor3D: THE1B0")
bb_3.GetTextProperty().SetJustificationToCentered()
bb_3.GetTextProperty().SetVerticalJustificationToCentered()
bb_3.GetTextProperty().SetColor(0.0, 0.0, 1.0)
bb_3.GetTextProperty().SetOpacity(0.5)
bb_3.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
bb_3.GetTextProperty().SetFrameWidth(2)
bb_3.GetTextProperty().SetFrame(1)
bb_3.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
bb_3.GetTextProperty().SetBackgroundOpacity(0.0)
bb_3.SetPosition(dx * 4, dy * 4.5, 0.0)
bb_3.SetForceOpaque(True)

# idx=4: t=0(TH,0.5) e=1(E1,1) b=1(BH,0.5)
ta_4 = vtkTextActor()
ta_4.SetInput("vtkTextActor: THE1BH")
ta_4.GetTextProperty().SetJustificationToCentered()
ta_4.GetTextProperty().SetVerticalJustificationToCentered()
ta_4.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta_4.GetTextProperty().SetOpacity(0.5)
ta_4.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta_4.GetTextProperty().SetFrameWidth(2)
ta_4.GetTextProperty().SetFrame(1)
ta_4.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta_4.GetTextProperty().SetBackgroundOpacity(0.5)
ta_4.SetPosition(dx * 1, dy * 5)

ta3d_4 = vtkTextActor3D()
ta3d_4.SetInput("vtkTextActor3D: THE1BH")
ta3d_4.GetTextProperty().SetJustificationToCentered()
ta3d_4.GetTextProperty().SetVerticalJustificationToCentered()
ta3d_4.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta3d_4.GetTextProperty().SetOpacity(0.5)
ta3d_4.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta3d_4.GetTextProperty().SetFrameWidth(2)
ta3d_4.GetTextProperty().SetFrame(1)
ta3d_4.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta3d_4.GetTextProperty().SetBackgroundOpacity(0.5)
ta3d_4.SetPosition(dx * 2, dy * 5.5, 0.0)
ta3d_4.SetForceOpaque(True)

tm_4 = vtkTextMapper()
tm_4.SetInput("vtkTextMapper: THE1BH")
tm_4.GetTextProperty().SetJustificationToCentered()
tm_4.GetTextProperty().SetVerticalJustificationToCentered()
tm_4.GetTextProperty().SetColor(0.0, 0.0, 1.0)
tm_4.GetTextProperty().SetOpacity(0.5)
tm_4.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
tm_4.GetTextProperty().SetFrameWidth(2)
tm_4.GetTextProperty().SetFrame(1)
tm_4.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
tm_4.GetTextProperty().SetBackgroundOpacity(0.5)
tm_actor_4 = vtkActor2D()
tm_actor_4.SetMapper(tm_4)
tm_actor_4.SetPosition(dx * 3, dy * 5)

bb_4 = vtkBillboardTextActor3D()
bb_4.SetInput("vtkBillboardTextActor3D: THE1BH")
bb_4.GetTextProperty().SetJustificationToCentered()
bb_4.GetTextProperty().SetVerticalJustificationToCentered()
bb_4.GetTextProperty().SetColor(0.0, 0.0, 1.0)
bb_4.GetTextProperty().SetOpacity(0.5)
bb_4.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
bb_4.GetTextProperty().SetFrameWidth(2)
bb_4.GetTextProperty().SetFrame(1)
bb_4.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
bb_4.GetTextProperty().SetBackgroundOpacity(0.5)
bb_4.SetPosition(dx * 4, dy * 5.5, 0.0)
bb_4.SetForceOpaque(True)

# idx=5: t=0(TH,0.5) e=1(E1,1) b=2(BF,1.0)
ta_5 = vtkTextActor()
ta_5.SetInput("vtkTextActor: THE1BF")
ta_5.GetTextProperty().SetJustificationToCentered()
ta_5.GetTextProperty().SetVerticalJustificationToCentered()
ta_5.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta_5.GetTextProperty().SetOpacity(0.5)
ta_5.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta_5.GetTextProperty().SetFrameWidth(2)
ta_5.GetTextProperty().SetFrame(1)
ta_5.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta_5.GetTextProperty().SetBackgroundOpacity(1.0)
ta_5.SetPosition(dx * 1, dy * 6)

ta3d_5 = vtkTextActor3D()
ta3d_5.SetInput("vtkTextActor3D: THE1BF")
ta3d_5.GetTextProperty().SetJustificationToCentered()
ta3d_5.GetTextProperty().SetVerticalJustificationToCentered()
ta3d_5.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta3d_5.GetTextProperty().SetOpacity(0.5)
ta3d_5.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta3d_5.GetTextProperty().SetFrameWidth(2)
ta3d_5.GetTextProperty().SetFrame(1)
ta3d_5.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta3d_5.GetTextProperty().SetBackgroundOpacity(1.0)
ta3d_5.SetPosition(dx * 2, dy * 6.5, 0.0)
ta3d_5.SetForceOpaque(True)

tm_5 = vtkTextMapper()
tm_5.SetInput("vtkTextMapper: THE1BF")
tm_5.GetTextProperty().SetJustificationToCentered()
tm_5.GetTextProperty().SetVerticalJustificationToCentered()
tm_5.GetTextProperty().SetColor(0.0, 0.0, 1.0)
tm_5.GetTextProperty().SetOpacity(0.5)
tm_5.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
tm_5.GetTextProperty().SetFrameWidth(2)
tm_5.GetTextProperty().SetFrame(1)
tm_5.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
tm_5.GetTextProperty().SetBackgroundOpacity(1.0)
tm_actor_5 = vtkActor2D()
tm_actor_5.SetMapper(tm_5)
tm_actor_5.SetPosition(dx * 3, dy * 6)

bb_5 = vtkBillboardTextActor3D()
bb_5.SetInput("vtkBillboardTextActor3D: THE1BF")
bb_5.GetTextProperty().SetJustificationToCentered()
bb_5.GetTextProperty().SetVerticalJustificationToCentered()
bb_5.GetTextProperty().SetColor(0.0, 0.0, 1.0)
bb_5.GetTextProperty().SetOpacity(0.5)
bb_5.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
bb_5.GetTextProperty().SetFrameWidth(2)
bb_5.GetTextProperty().SetFrame(1)
bb_5.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
bb_5.GetTextProperty().SetBackgroundOpacity(1.0)
bb_5.SetPosition(dx * 4, dy * 6.5, 0.0)
bb_5.SetForceOpaque(True)

# idx=6: t=1(TF,1.0) e=0(E0,0) b=0(B0,0.0)
ta_6 = vtkTextActor()
ta_6.SetInput("vtkTextActor: TFE0B0")
ta_6.GetTextProperty().SetJustificationToCentered()
ta_6.GetTextProperty().SetVerticalJustificationToCentered()
ta_6.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta_6.GetTextProperty().SetOpacity(1.0)
ta_6.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta_6.GetTextProperty().SetFrameWidth(2)
ta_6.GetTextProperty().SetFrame(0)
ta_6.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta_6.GetTextProperty().SetBackgroundOpacity(0.0)
ta_6.SetPosition(dx * 1, dy * 7)

ta3d_6 = vtkTextActor3D()
ta3d_6.SetInput("vtkTextActor3D: TFE0B0")
ta3d_6.GetTextProperty().SetJustificationToCentered()
ta3d_6.GetTextProperty().SetVerticalJustificationToCentered()
ta3d_6.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta3d_6.GetTextProperty().SetOpacity(1.0)
ta3d_6.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta3d_6.GetTextProperty().SetFrameWidth(2)
ta3d_6.GetTextProperty().SetFrame(0)
ta3d_6.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta3d_6.GetTextProperty().SetBackgroundOpacity(0.0)
ta3d_6.SetPosition(dx * 2, dy * 7.5, 0.0)
ta3d_6.SetForceOpaque(True)

tm_6 = vtkTextMapper()
tm_6.SetInput("vtkTextMapper: TFE0B0")
tm_6.GetTextProperty().SetJustificationToCentered()
tm_6.GetTextProperty().SetVerticalJustificationToCentered()
tm_6.GetTextProperty().SetColor(0.0, 0.0, 1.0)
tm_6.GetTextProperty().SetOpacity(1.0)
tm_6.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
tm_6.GetTextProperty().SetFrameWidth(2)
tm_6.GetTextProperty().SetFrame(0)
tm_6.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
tm_6.GetTextProperty().SetBackgroundOpacity(0.0)
tm_actor_6 = vtkActor2D()
tm_actor_6.SetMapper(tm_6)
tm_actor_6.SetPosition(dx * 3, dy * 7)

bb_6 = vtkBillboardTextActor3D()
bb_6.SetInput("vtkBillboardTextActor3D: TFE0B0")
bb_6.GetTextProperty().SetJustificationToCentered()
bb_6.GetTextProperty().SetVerticalJustificationToCentered()
bb_6.GetTextProperty().SetColor(0.0, 0.0, 1.0)
bb_6.GetTextProperty().SetOpacity(1.0)
bb_6.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
bb_6.GetTextProperty().SetFrameWidth(2)
bb_6.GetTextProperty().SetFrame(0)
bb_6.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
bb_6.GetTextProperty().SetBackgroundOpacity(0.0)
bb_6.SetPosition(dx * 4, dy * 7.5, 0.0)
bb_6.SetForceOpaque(True)

# idx=7: t=1(TF,1.0) e=0(E0,0) b=1(BH,0.5)
ta_7 = vtkTextActor()
ta_7.SetInput("vtkTextActor: TFE0BH")
ta_7.GetTextProperty().SetJustificationToCentered()
ta_7.GetTextProperty().SetVerticalJustificationToCentered()
ta_7.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta_7.GetTextProperty().SetOpacity(1.0)
ta_7.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta_7.GetTextProperty().SetFrameWidth(2)
ta_7.GetTextProperty().SetFrame(0)
ta_7.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta_7.GetTextProperty().SetBackgroundOpacity(0.5)
ta_7.SetPosition(dx * 1, dy * 8)

ta3d_7 = vtkTextActor3D()
ta3d_7.SetInput("vtkTextActor3D: TFE0BH")
ta3d_7.GetTextProperty().SetJustificationToCentered()
ta3d_7.GetTextProperty().SetVerticalJustificationToCentered()
ta3d_7.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta3d_7.GetTextProperty().SetOpacity(1.0)
ta3d_7.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta3d_7.GetTextProperty().SetFrameWidth(2)
ta3d_7.GetTextProperty().SetFrame(0)
ta3d_7.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta3d_7.GetTextProperty().SetBackgroundOpacity(0.5)
ta3d_7.SetPosition(dx * 2, dy * 8.5, 0.0)
ta3d_7.SetForceOpaque(True)

tm_7 = vtkTextMapper()
tm_7.SetInput("vtkTextMapper: TFE0BH")
tm_7.GetTextProperty().SetJustificationToCentered()
tm_7.GetTextProperty().SetVerticalJustificationToCentered()
tm_7.GetTextProperty().SetColor(0.0, 0.0, 1.0)
tm_7.GetTextProperty().SetOpacity(1.0)
tm_7.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
tm_7.GetTextProperty().SetFrameWidth(2)
tm_7.GetTextProperty().SetFrame(0)
tm_7.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
tm_7.GetTextProperty().SetBackgroundOpacity(0.5)
tm_actor_7 = vtkActor2D()
tm_actor_7.SetMapper(tm_7)
tm_actor_7.SetPosition(dx * 3, dy * 8)

bb_7 = vtkBillboardTextActor3D()
bb_7.SetInput("vtkBillboardTextActor3D: TFE0BH")
bb_7.GetTextProperty().SetJustificationToCentered()
bb_7.GetTextProperty().SetVerticalJustificationToCentered()
bb_7.GetTextProperty().SetColor(0.0, 0.0, 1.0)
bb_7.GetTextProperty().SetOpacity(1.0)
bb_7.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
bb_7.GetTextProperty().SetFrameWidth(2)
bb_7.GetTextProperty().SetFrame(0)
bb_7.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
bb_7.GetTextProperty().SetBackgroundOpacity(0.5)
bb_7.SetPosition(dx * 4, dy * 8.5, 0.0)
bb_7.SetForceOpaque(True)

# idx=8: t=1(TF,1.0) e=0(E0,0) b=2(BF,1.0)
ta_8 = vtkTextActor()
ta_8.SetInput("vtkTextActor: TFE0BF")
ta_8.GetTextProperty().SetJustificationToCentered()
ta_8.GetTextProperty().SetVerticalJustificationToCentered()
ta_8.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta_8.GetTextProperty().SetOpacity(1.0)
ta_8.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta_8.GetTextProperty().SetFrameWidth(2)
ta_8.GetTextProperty().SetFrame(0)
ta_8.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta_8.GetTextProperty().SetBackgroundOpacity(1.0)
ta_8.SetPosition(dx * 1, dy * 9)

ta3d_8 = vtkTextActor3D()
ta3d_8.SetInput("vtkTextActor3D: TFE0BF")
ta3d_8.GetTextProperty().SetJustificationToCentered()
ta3d_8.GetTextProperty().SetVerticalJustificationToCentered()
ta3d_8.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta3d_8.GetTextProperty().SetOpacity(1.0)
ta3d_8.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta3d_8.GetTextProperty().SetFrameWidth(2)
ta3d_8.GetTextProperty().SetFrame(0)
ta3d_8.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta3d_8.GetTextProperty().SetBackgroundOpacity(1.0)
ta3d_8.SetPosition(dx * 2, dy * 9.5, 0.0)
ta3d_8.SetForceOpaque(True)

tm_8 = vtkTextMapper()
tm_8.SetInput("vtkTextMapper: TFE0BF")
tm_8.GetTextProperty().SetJustificationToCentered()
tm_8.GetTextProperty().SetVerticalJustificationToCentered()
tm_8.GetTextProperty().SetColor(0.0, 0.0, 1.0)
tm_8.GetTextProperty().SetOpacity(1.0)
tm_8.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
tm_8.GetTextProperty().SetFrameWidth(2)
tm_8.GetTextProperty().SetFrame(0)
tm_8.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
tm_8.GetTextProperty().SetBackgroundOpacity(1.0)
tm_actor_8 = vtkActor2D()
tm_actor_8.SetMapper(tm_8)
tm_actor_8.SetPosition(dx * 3, dy * 9)

bb_8 = vtkBillboardTextActor3D()
bb_8.SetInput("vtkBillboardTextActor3D: TFE0BF")
bb_8.GetTextProperty().SetJustificationToCentered()
bb_8.GetTextProperty().SetVerticalJustificationToCentered()
bb_8.GetTextProperty().SetColor(0.0, 0.0, 1.0)
bb_8.GetTextProperty().SetOpacity(1.0)
bb_8.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
bb_8.GetTextProperty().SetFrameWidth(2)
bb_8.GetTextProperty().SetFrame(0)
bb_8.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
bb_8.GetTextProperty().SetBackgroundOpacity(1.0)
bb_8.SetPosition(dx * 4, dy * 9.5, 0.0)
bb_8.SetForceOpaque(True)

# idx=9: t=1(TF,1.0) e=1(E1,1) b=0(B0,0.0)
ta_9 = vtkTextActor()
ta_9.SetInput("vtkTextActor: TFE1B0")
ta_9.GetTextProperty().SetJustificationToCentered()
ta_9.GetTextProperty().SetVerticalJustificationToCentered()
ta_9.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta_9.GetTextProperty().SetOpacity(1.0)
ta_9.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta_9.GetTextProperty().SetFrameWidth(2)
ta_9.GetTextProperty().SetFrame(1)
ta_9.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta_9.GetTextProperty().SetBackgroundOpacity(0.0)
ta_9.SetPosition(dx * 1, dy * 10)

ta3d_9 = vtkTextActor3D()
ta3d_9.SetInput("vtkTextActor3D: TFE1B0")
ta3d_9.GetTextProperty().SetJustificationToCentered()
ta3d_9.GetTextProperty().SetVerticalJustificationToCentered()
ta3d_9.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta3d_9.GetTextProperty().SetOpacity(1.0)
ta3d_9.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta3d_9.GetTextProperty().SetFrameWidth(2)
ta3d_9.GetTextProperty().SetFrame(1)
ta3d_9.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta3d_9.GetTextProperty().SetBackgroundOpacity(0.0)
ta3d_9.SetPosition(dx * 2, dy * 10.5, 0.0)
ta3d_9.SetForceOpaque(True)

tm_9 = vtkTextMapper()
tm_9.SetInput("vtkTextMapper: TFE1B0")
tm_9.GetTextProperty().SetJustificationToCentered()
tm_9.GetTextProperty().SetVerticalJustificationToCentered()
tm_9.GetTextProperty().SetColor(0.0, 0.0, 1.0)
tm_9.GetTextProperty().SetOpacity(1.0)
tm_9.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
tm_9.GetTextProperty().SetFrameWidth(2)
tm_9.GetTextProperty().SetFrame(1)
tm_9.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
tm_9.GetTextProperty().SetBackgroundOpacity(0.0)
tm_actor_9 = vtkActor2D()
tm_actor_9.SetMapper(tm_9)
tm_actor_9.SetPosition(dx * 3, dy * 10)

bb_9 = vtkBillboardTextActor3D()
bb_9.SetInput("vtkBillboardTextActor3D: TFE1B0")
bb_9.GetTextProperty().SetJustificationToCentered()
bb_9.GetTextProperty().SetVerticalJustificationToCentered()
bb_9.GetTextProperty().SetColor(0.0, 0.0, 1.0)
bb_9.GetTextProperty().SetOpacity(1.0)
bb_9.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
bb_9.GetTextProperty().SetFrameWidth(2)
bb_9.GetTextProperty().SetFrame(1)
bb_9.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
bb_9.GetTextProperty().SetBackgroundOpacity(0.0)
bb_9.SetPosition(dx * 4, dy * 10.5, 0.0)
bb_9.SetForceOpaque(True)

# idx=10: t=1(TF,1.0) e=1(E1,1) b=1(BH,0.5)
ta_10 = vtkTextActor()
ta_10.SetInput("vtkTextActor: TFE1BH")
ta_10.GetTextProperty().SetJustificationToCentered()
ta_10.GetTextProperty().SetVerticalJustificationToCentered()
ta_10.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta_10.GetTextProperty().SetOpacity(1.0)
ta_10.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta_10.GetTextProperty().SetFrameWidth(2)
ta_10.GetTextProperty().SetFrame(1)
ta_10.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta_10.GetTextProperty().SetBackgroundOpacity(0.5)
ta_10.SetPosition(dx * 1, dy * 11)

ta3d_10 = vtkTextActor3D()
ta3d_10.SetInput("vtkTextActor3D: TFE1BH")
ta3d_10.GetTextProperty().SetJustificationToCentered()
ta3d_10.GetTextProperty().SetVerticalJustificationToCentered()
ta3d_10.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta3d_10.GetTextProperty().SetOpacity(1.0)
ta3d_10.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta3d_10.GetTextProperty().SetFrameWidth(2)
ta3d_10.GetTextProperty().SetFrame(1)
ta3d_10.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta3d_10.GetTextProperty().SetBackgroundOpacity(0.5)
ta3d_10.SetPosition(dx * 2, dy * 11.5, 0.0)
ta3d_10.SetForceOpaque(True)

tm_10 = vtkTextMapper()
tm_10.SetInput("vtkTextMapper: TFE1BH")
tm_10.GetTextProperty().SetJustificationToCentered()
tm_10.GetTextProperty().SetVerticalJustificationToCentered()
tm_10.GetTextProperty().SetColor(0.0, 0.0, 1.0)
tm_10.GetTextProperty().SetOpacity(1.0)
tm_10.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
tm_10.GetTextProperty().SetFrameWidth(2)
tm_10.GetTextProperty().SetFrame(1)
tm_10.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
tm_10.GetTextProperty().SetBackgroundOpacity(0.5)
tm_actor_10 = vtkActor2D()
tm_actor_10.SetMapper(tm_10)
tm_actor_10.SetPosition(dx * 3, dy * 11)

bb_10 = vtkBillboardTextActor3D()
bb_10.SetInput("vtkBillboardTextActor3D: TFE1BH")
bb_10.GetTextProperty().SetJustificationToCentered()
bb_10.GetTextProperty().SetVerticalJustificationToCentered()
bb_10.GetTextProperty().SetColor(0.0, 0.0, 1.0)
bb_10.GetTextProperty().SetOpacity(1.0)
bb_10.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
bb_10.GetTextProperty().SetFrameWidth(2)
bb_10.GetTextProperty().SetFrame(1)
bb_10.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
bb_10.GetTextProperty().SetBackgroundOpacity(0.5)
bb_10.SetPosition(dx * 4, dy * 11.5, 0.0)
bb_10.SetForceOpaque(True)

# idx=11: t=1(TF,1.0) e=1(E1,1) b=2(BF,1.0)
ta_11 = vtkTextActor()
ta_11.SetInput("vtkTextActor: TFE1BF")
ta_11.GetTextProperty().SetJustificationToCentered()
ta_11.GetTextProperty().SetVerticalJustificationToCentered()
ta_11.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta_11.GetTextProperty().SetOpacity(1.0)
ta_11.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta_11.GetTextProperty().SetFrameWidth(2)
ta_11.GetTextProperty().SetFrame(1)
ta_11.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta_11.GetTextProperty().SetBackgroundOpacity(1.0)
ta_11.SetPosition(dx * 1, dy * 12)

ta3d_11 = vtkTextActor3D()
ta3d_11.SetInput("vtkTextActor3D: TFE1BF")
ta3d_11.GetTextProperty().SetJustificationToCentered()
ta3d_11.GetTextProperty().SetVerticalJustificationToCentered()
ta3d_11.GetTextProperty().SetColor(0.0, 0.0, 1.0)
ta3d_11.GetTextProperty().SetOpacity(1.0)
ta3d_11.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
ta3d_11.GetTextProperty().SetFrameWidth(2)
ta3d_11.GetTextProperty().SetFrame(1)
ta3d_11.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
ta3d_11.GetTextProperty().SetBackgroundOpacity(1.0)
ta3d_11.SetPosition(dx * 2, dy * 12.5, 0.0)
ta3d_11.SetForceOpaque(True)

tm_11 = vtkTextMapper()
tm_11.SetInput("vtkTextMapper: TFE1BF")
tm_11.GetTextProperty().SetJustificationToCentered()
tm_11.GetTextProperty().SetVerticalJustificationToCentered()
tm_11.GetTextProperty().SetColor(0.0, 0.0, 1.0)
tm_11.GetTextProperty().SetOpacity(1.0)
tm_11.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
tm_11.GetTextProperty().SetFrameWidth(2)
tm_11.GetTextProperty().SetFrame(1)
tm_11.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
tm_11.GetTextProperty().SetBackgroundOpacity(1.0)
tm_actor_11 = vtkActor2D()
tm_actor_11.SetMapper(tm_11)
tm_actor_11.SetPosition(dx * 3, dy * 12)

bb_11 = vtkBillboardTextActor3D()
bb_11.SetInput("vtkBillboardTextActor3D: TFE1BF")
bb_11.GetTextProperty().SetJustificationToCentered()
bb_11.GetTextProperty().SetVerticalJustificationToCentered()
bb_11.GetTextProperty().SetColor(0.0, 0.0, 1.0)
bb_11.GetTextProperty().SetOpacity(1.0)
bb_11.GetTextProperty().SetFrameColor(0.0, 1.0, 0.0)
bb_11.GetTextProperty().SetFrameWidth(2)
bb_11.GetTextProperty().SetFrame(1)
bb_11.GetTextProperty().SetBackgroundColor(1.0, 0.0, 0.0)
bb_11.GetTextProperty().SetBackgroundOpacity(1.0)
bb_11.SetPosition(dx * 4, dy * 12.5, 0.0)
bb_11.SetForceOpaque(True)

# Renderer
renderer = vtkRenderer()
renderer.SetPass(pass_obj)
renderer.GradientBackgroundOn()
renderer.SetBackground(0.0, 0.0, 0.0)
renderer.SetBackground2(1.0, 1.0, 1.0)
renderer.AddViewProp(ta_0)
renderer.AddViewProp(ta3d_0)
renderer.AddViewProp(tm_actor_0)
renderer.AddViewProp(bb_0)
renderer.AddViewProp(ta_1)
renderer.AddViewProp(ta3d_1)
renderer.AddViewProp(tm_actor_1)
renderer.AddViewProp(bb_1)
renderer.AddViewProp(ta_2)
renderer.AddViewProp(ta3d_2)
renderer.AddViewProp(tm_actor_2)
renderer.AddViewProp(bb_2)
renderer.AddViewProp(ta_3)
renderer.AddViewProp(ta3d_3)
renderer.AddViewProp(tm_actor_3)
renderer.AddViewProp(bb_3)
renderer.AddViewProp(ta_4)
renderer.AddViewProp(ta3d_4)
renderer.AddViewProp(tm_actor_4)
renderer.AddViewProp(bb_4)
renderer.AddViewProp(ta_5)
renderer.AddViewProp(ta3d_5)
renderer.AddViewProp(tm_actor_5)
renderer.AddViewProp(bb_5)
renderer.AddViewProp(ta_6)
renderer.AddViewProp(ta3d_6)
renderer.AddViewProp(tm_actor_6)
renderer.AddViewProp(bb_6)
renderer.AddViewProp(ta_7)
renderer.AddViewProp(ta3d_7)
renderer.AddViewProp(tm_actor_7)
renderer.AddViewProp(bb_7)
renderer.AddViewProp(ta_8)
renderer.AddViewProp(ta3d_8)
renderer.AddViewProp(tm_actor_8)
renderer.AddViewProp(bb_8)
renderer.AddViewProp(ta_9)
renderer.AddViewProp(ta3d_9)
renderer.AddViewProp(tm_actor_9)
renderer.AddViewProp(bb_9)
renderer.AddViewProp(ta_10)
renderer.AddViewProp(ta3d_10)
renderer.AddViewProp(tm_actor_10)
renderer.AddViewProp(bb_10)
renderer.AddViewProp(ta_11)
renderer.AddViewProp(ta3d_11)
renderer.AddViewProp(tm_actor_11)
renderer.AddViewProp(bb_11)

# Window
render_window = vtkRenderWindow()
render_window.AddRenderer(renderer)
render_window.SetWindowName("text opaque pass")
render_window.SetMultiSamples(0)
render_window.SetSize(width, height)

# Interactor
interactor = vtkRenderWindowInteractor()
interactor.SetRenderWindow(render_window)

# Scene
renderer.GetActiveCamera().ParallelProjectionOn()
renderer.GetActiveCamera().SetPosition(width / 2, height / 2, 1.0)
renderer.GetActiveCamera().SetFocalPoint(width / 2, height / 2, 0.0)
renderer.GetActiveCamera().SetViewUp(0.0, 1.0, 0.0)
renderer.GetActiveCamera().SetParallelScale(height / 2)

interactor.Initialize()
interactor.Start()
